### ISSUE TITLE
Making time filters easier to use

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1]
Add some fanciness to the parsing of the input boxes so that multiple input format will work (just a date, date in american format etc)

**Comment by technoskald** [comment]
Perhaps something like [parsedatetime](https://github.com/bear/parsedatetime) would help with this.

**Comment by berggren** [comment]
Interesting, I'll take a look at that. Thanks!`

**Comment by mmaisel** [comment]
How about similar relative time selectors like Splunk or Kibana?

**Comment by berggren** [comment]
@mmaisel Yeah, I have been thinking of that too. I'll make sure to take a look at it when I'm strt working on this issue.

Thanks!

**Comment by berggren** [comment]
I think moment.js can be of help here.
http://momentjs.com/docs/#/parsing/string-formats/

**Comment by pettai** [comment]
Maybe this is more nice than useful, but how about a slider for increasing/decreasing the time window
(example on how the slider could look, http://flog.sunet.se/event/websso/authentication-flow/)

**Comment by berggren** [comment]
@pettai Yes, we actually had that in the beginning :) I will revisit this idea when I start working on a new filter view.

**Comment by hiddenillusion** [comment]
It'd also be convenient to be able to enter just a start date/time and not have to enter an end date/time. By default, it could just go from the start date/time to X amount of events (e.g. 500) or until the last `timestamp`.

Just sometimes a pain if I want to jump to a period of time but don't necessarily care when everything ends (or if I need to load the next page/500 events) to continue scrolling through the timeline.
