### ISSUE TITLE
Regular Expression in queries

### ISSUE THREAD

**Issue by ecapuano** [google/timesketch#1013]
Forgive me in advance if I am doing something obviously dumb here...

I am familiar with regex in Lucene against standard Elastic, but this syntax seems to have unexpected results for me in Timesketch queries.

Example of regex that _works as expected_, by filtering OUT messages with the word `Adobe` in them :
```
NOT message:/.*Adobe.*/
```
I can even perform multiple OR condition searches _without issue_:
```
NOT message:/.*(Adobe|Flash|Player).*/
```

But any method I try for filtering a **multi-word phrase does not yield expected results**:
```
NOT message:/.*Adobe\ Flash\ Player\ Update.*/
```
```
NOT message:/.*Adobe Flash Player Update.*/
```
```
NOT message:/.*"Adobe Flash Player Update".*/
```
```
NOT message:/.*Adobe\sFlash\sPlayer\sUpdate.*/
```
```
NOT message:/.*Adobe.Flash.Player.Update.*/
```

Is this a TimeSketch limitation? Elastic issue? `message` field issue? Layer 8 issue? 

Thanks in advance!

**Comment by berggren** [comment]
RegExp should work just as it does with standard Elastic. It is just a query string query in the end. Can you test with Kibana?

**Comment by kiddinn** [comment]
ths still an issue?

regular expressions should work fine. Closing this since there has not been any activity for a long time, re-open this if it's still an issue
