### ISSUE TITLE
Add more granular controls in field selection in the UI

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1035]
With #1029 in, can we get a bit more features into the UI:

1. Having the ability to select the ordering of fields
2. Current behavior is that as soon as you add a field to the UI a refresh of the site is made and the field made visible. If you want to add more than a single field you'll need to select one field at a time, wait for the refresh and then go back into the menu and select another one. Better would be the ability to select all fields you want to include and then a refresh of the UI is made.

**Comment by berggren** [comment]
This has been fixed in the new UI.
