### ISSUE TITLE
Add the ability to view saved aggregations in the UI

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1047]
The UI currently doesn't have any way to save and/or recover saved aggregations or insights.

The datastore and API support both storing and retrieving stored aggregations. This feature should be exposed in the UI since analyzers have the ability to store aggregations (that is when #1046 is completed)

**Comment by kiddinn** [comment]
Another FR that is closely related to this one is the ability to save aggregations in the UI

**Comment by berggren** [comment]
This has been implemented by pinning aggregations and showing them on the aggregation overview page.
