### ISSUE TITLE
Highlight comments

### ISSUE THREAD

**Issue by pettai** [google/timesketch#108]
![timesketch](https://cloud.githubusercontent.com/assets/3317462/9681931/2905e686-5302-11e5-9c88-ade837a9ffe8.png)

The "speech bubble" indicated that someone posted a comment(s), could be placed in the same column as the star(s), for better visibility. (And perhaps you want use the "toggle all" to select multiple events, and place the same comment (for instance a reference) on those)
It would also be nice if the comment(s) could be expandable (shown) in the collapsed timeline view, without having to expand the event and see all the data. ("expand only the comments in the main view")
Finally, make events with comment(s) a searchable filter criteria, so you easily can "catch up" on previous commented analyses.

**Comment by berggren** [comment]
Yeah, I like the idea of moving the speech bubble to the left along side the star. I will experiment with that. Also, showing expanded comments in the collapsed view is a really good idea, and pretty easy to do. Thanks, good ideas!

**Comment by berggren** [comment]
Moving the speach bubble made the UI a bit cluttered and not align etc. Keeping as is.
Showing the comments in the collapsed view is more difficult than I thought. We lazy load the comments when event is expanded.
