### ISSUE TITLE
Show sketch status / owner on the main page

### ISSUE THREAD

**Issue by pettai** [google/timesketch#109]
![timesketch2](https://cloud.githubusercontent.com/assets/3317462/9682826/8b07a8bc-530a-11e5-8ddb-e615c3f7720a.png)

**Comment by pettai** [comment]
More metadata like nr. of events, nr. of comments, nr of saved views etc. could also be of interest

**Comment by berggren** [comment]
@pettai Yes, this view need much more love! I'll make sure to put this on the milestone for the winter release.
