### ISSUE TITLE
Strip dates before parsing

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#1100]
If there are leading spaces in the date input fields Timesketch will error when trying to parse them.  The whitespace should probably be stripped before parsing.

**Comment by kiddinn** [comment]
is this in CSV/JSON importers?

**Comment by kiddinn** [comment]
@aarontp is this in CSV/JSON importers, or where did you come across this?

**Comment by kiddinn** [comment]
not heard anything in a while, will close this issue, please re-open it if this is still an issue (should not be if yiou use the timesketch importer to import the data)

**Comment by aarontp** [comment]
This is in the UI.  I just tested this again and I still see this behavior.

**Comment by jaegeral** [comment]
@marcobrotto  another one that you should be easily able to rule out, WDYT?
