### ISSUE TITLE
Cleanup in import folder

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1107]
ATM the timesketch-importer.sh only listens to new files being dropped and then runs tsctl to import files.

It does not cleanup after... so after a while if this method is used the data just keeps piling on and filling the disk

**Comment by berggren** [comment]
The issue is that the call is async, i.e. it will fire off the celery task. The script doesn't know when the file can be deleted. I opt to leave this to the server admin to clean up periodically separate from TS.
