### ISSUE TITLE
docker_timesketch_1 stuck on restarting

### ISSUE THREAD

**Issue by gmassawe** [google/timesketch#1112]
I am running docker on windows.  I get this error only on **docker_timesketch_1** the other containers are ok.
Error message:
`standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Comment by deralexxx** [comment]
Can you give more info which version of docker you are using etc?

(the abilities to help resolve that might be limited, as currently Windows docker hosts are not in scope to be supported) --> https://github.com/google/timesketch/tree/master/docker

Thx a lot

**Comment by berggren** [comment]
We have refactored the docker support, so this might work now. That being said, we don't support Docker on Windows currently. 

Please reopen this is it is still a problem.
