### ISSUE TITLE
Indexing a new timeline fails

### ISSUE THREAD

**Issue by binglot** [google/timesketch#1119]
After I've uploaded the timeline (and I tried 2 different plaso output files) and it starts indexing it, I receive the following error from Celery:

> [2020-02-28 05:26:41,086: INFO/MainProcess] Received task: timesketch.lib.tasks.run_plaso[3f88fe39-5ef8-45a6-9776-10d5a519bf28]  
> [2020-02-28 05:26:41,096: INFO/ForkPoolWorker-7] Index timeline [codelab] to index [0141e63036f94e5e8837caac7f745b52] (source: plaso)
> [2020-02-28 05:26:45,104: INFO/ForkPoolWorker-7] Task timesketch.lib.tasks.run_plaso[3f88fe39-5ef8-45a6-9776-10d5a519bf28] succeeded in 4.014234200003557s: '2020-02-28 05:26:44,150 [INFO] (MainProcess) PID:118 <data_location> Determined data location: /usr/share/plaso
> 2020-02-28 05:26:44,283 [INFO] (MainProcess) PID:118 <timesketch_out> Timeline name: codelab
> 2020-02-28 05:26:44,283 [INFO] (MainProcess) PID:118 <timesketch_out> Owner of the timeline: None
> Traceback (most recent call last):
>   File "/usr/bin/psort.py", line 85, in <module>
>     if not Main():
>   File "/usr/bin/psort.py", line 67, in Main
>     tool.ProcessStorage()
>   File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 568, in ProcessStorage
>     time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
>   File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 997, in ExportEvents
>     output_module.WriteHeader()
>   File "/usr/lib/python3/dist-packages/plaso/output/timesketch_out.py", line 111, in WriteHeader
>     self._CreateIndexIfNotExists(self._index_name, mappings)
>   File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 99, in...'

The web UI provides the following error:

> 2020-02-28 05:26:44,150 [INFO] (MainProcess) PID:118 <data_location> Determined data location: /usr/share/plaso
> 2020-02-28 05:26:44,283 [INFO] (MainProcess) PID:118 <timesketch_out> Timeline name: codelab
> 2020-02-28 05:26:44,283 [INFO] (MainProcess) PID:118 <timesketch_out> Owner of the timeline: None
> Traceback (most recent call last):
>   File "/usr/bin/psort.py", line 85, in <module>
>     if not Main():
>   File "/usr/bin/psort.py", line 67, in Main
>     tool.ProcessStorage()
>   File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 568, in ProcessStorage
>     time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
>   File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 997, in ExportEvents
>     output_module.WriteHeader()
>   File "/usr/lib/python3/dist-packages/plaso/output/timesketch_out.py", line 111, in WriteHeader
>     self._CreateIndexIfNotExists(self._index_name, mappings)
>   File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 99, in _CreateIndexIfNotExists
>     body={'mappings': mappings}, index=index_name)
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
>     return func(*args, params=params, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/indices.py", line 100, in create
>     "PUT", _make_path(index), params=params, body=body
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 358, in perform_request
>     timeout=timeout,
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
>     self._raise_error(response.status, raw_data)
>   File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
>     status_code, error_message, additional_info
> elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [plaso_event : {properties={timesketch_label={type=nested}}}]')

**Comment by n3x77** [comment]
I think this has something to do with the initial support of Elasticsearch 7. 
I get the same error message if im trying to use eleasticsearch 6.

Which version of elasticsearch do you use?

**Comment by kiddinn** [comment]
@berggren  can you take a look at this?

**Comment by deralexxx** [comment]
Can you run a log2timeline.py -v to show the version of the installed plaso-tools ?

I was running in the same issue and updating plaso to a version like https://github.com/log2timeline/plaso/releases/tag/20200121 helped.

Thx

**Comment by jaegeral** [comment]
@binglot any chance to verify that? (If you are inside a docker container, you can go there by: 
````
export CONTAINER_ID="$(sudo docker container list -f name=development_timesketch -q)"
docker exec -it $CONTAINER_ID /bin/bash
log2timeline.py --version
````

But maybe it would be a good idea to give that out by default if we have an exception when importing a plaso file?

**Comment by binglot** [comment]
Hey Alexander,

I'll try to reproduce it tomorrow and report back the results. Apologies
for the delay.

Thanks,
Bart

**Comment by binglot** [comment]
Hey Alex,

The delay from my side was related to the fact that I had to rebuild from scratch the development environment. Anyways... next time I'll reply quicker as I have it all set up now.

So, as I rebuilt the docker environment, I've come to the same place as before -- as soon as the Plaso file completes uploading, I get exactly the same error.

I check the version of log2timeline as per your recommendation, it's "20190916".

**Comment by binglot** [comment]
> I think this has something to do with the initial support of Elasticsearch 7.
> I get the same error message if im trying to use eleasticsearch 6.
> 
> Which version of elasticsearch do you use?

I've just built TS using Docker so it has Elasticsearch 7.

```
binglot@binglot:~/timesketch/docker/development$ sudo /usr/local/bin/docker-compose up -d
[...]
binglot@binglot:~/timesketch/docker/development$ grep -i elasticsearch *
docker-compose.yml:      - elasticsearch
docker-compose.yml:      - ELASTIC_ADDRESS=elasticsearch
docker-compose.yml:  elasticsearch:
docker-compose.yml:    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
```

**Comment by berggren** [comment]
> > I think this has something to do with the initial support of Elasticsearch 7.
> > I get the same error message if im trying to use eleasticsearch 6.
> > Which version of elasticsearch do you use?
> 
> I've just built TS using Docker so it has Elasticsearch 7.
> 
> ```
> binglot@binglot:~/timesketch/docker/development$ sudo /usr/local/bin/docker-compose up -d
> [...]
> binglot@binglot:~/timesketch/docker/development$ grep -i elasticsearch *
> docker-compose.yml:      - elasticsearch
> docker-compose.yml:      - ELASTIC_ADDRESS=elasticsearch
> docker-compose.yml:  elasticsearch:
> docker-compose.yml:    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
> ```

Hey @binglot did this fix it for you?

I updated all docker stuff in #1207 as part of a larger refactor and fixit for docker in TS. We now build base images automatically that is used.

Let me know.

**Comment by binglot** [comment]
Turns out that I was using an older version (from about 4 months ago) because I didn't realize that my fork of Timesketch was out of date. When I tried the latest version of Timesketch, these errors were gone.
