### ISSUE TITLE
Events not shown in new UI

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#1128]
Hi,

in the current version of timesketch 06032020 some events are not shown if only a low number of events match the search query. 

For example, I used the phishiy-domain analyzer and it tagged 35 events. If I try to look at this events now events will be shown within the ui only the counter is updated and shows 35 events matched.

**Comment by kiddinn** [comment]
what version are you running?

If you look at gunicorn logs, do you see any errors there?

**Comment by kiddinn** [comment]
@berggren I'm assigning this to you, since this is ui, although I suspect that there is something else in play here

**Comment by kiddinn** [comment]
have you tried the API Client, does that work, or same issue there?

**Comment by berggren** [comment]
This was indeed a bug. If a timeline was not in the 'ready' state it didn't show the results. This should have been fixed now. Please reopen if this is still an issue.
