### ISSUE TITLE
Detect tampered event logs analyzer

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1150]
Create an analyzer that iterates over Windows Event Log entries and attempts to detect if they were maliciously modified by applying the following rules:

- Check if entries for the same eventlog file have sequential record numbers and if any record numbers are missing (to detect if an entry was removed)
- Check if entries with sequential record numbers are chronologically ordered (to detect if the system time was changed)

**Comment by binglot** [comment]
I believe this was completed by @kiddinn .

**Comment by kiddinn** [comment]
Yes this should be done
