### ISSUE TITLE
Multiple pages not available in user interface

### ISSUE THREAD

**Issue by coenemichel** [google/timesketch#1155]
Hi, 

I installed Timesketch yesterday using the provided Docker instructions and doing the manual install as well. For both, I was able to access timesketch & upload a timeline, however, many of the other options were not present: 
- I could not edit my user profile (button was not there even)
- I'm able to create a story, but that's where it ends, no options are available to add data to a story, etc. only a title 
- The views tab is not available. 

Might be that I'm missing something, but I followed the installation steps from this github. 

Cheers

**Comment by MatthewClarkMay** [comment]
I am having similar issues - anyone have an idea?

**Comment by kiddinn** [comment]
is this still an issue?

(the user profile is `WAI` as in that has not yet been implemented in the new UI)

**Comment by berggren** [comment]
@coenemichel 

> * I'm able to create a story, but that's where it ends, no options are available to add data to a story, etc. only a title

The story is an interactive markdown editor with some extra features like inlining saved views.

> * The views tab is not available.

I guess you mean in the Story UI. You need to first create some saved views for the dropdown to appear.

Let us know how it goes.

**Comment by berggren** [comment]
Closing this as there has been no reply in a while. Feel free to reopen as needed.
