### ISSUE TITLE
Add description field for timelines

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#1161]
It would be nice to have a description field for each timeline, like there is for the sketch as a whole. This field could be used for storing the source of the timeline (for example. if the source is some kind of log data, you could put the exact query that produced the logs in the description field).

**Comment by jaegeral** [comment]
Did you look for more then what is now possible in https://demo.timesketch.org/sketch/1/manage/timelines (click on info)

```
Imported | Provider | Context | User | File on disk | File size | Original filename | Data label
-- | -- | -- | -- | -- | -- | -- | --
```

That will have the exact query and filename etc in it

**Comment by kiddinn** [comment]
This has been implemented with the data source model, which includes context and provider
