### ISSUE TITLE
UI: Add the ability to display saved aggregation in explore page

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1164]
With #1159 the ability to click parts of a chart and create a search in explore opens up the possibility to define an aggregation ID as well in the URL, eg: `https://<TS_HOST>/sketch/<SKETCH_ID>/explore?q=my_search_query&a=132` - would point to a saved aggregation with an aggregation id 132... so clicking a bar (or data point) on the chart would bring you to explore, displaying that filtered view and also display the aggregation that generated it.

**Comment by berggren** [comment]
Tracking in #1047
