### ISSUE TITLE
Add an archiving feature to sketches

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1180]
This feature takes a sketch and archives it. What that means is:

+ All stories are exported to a PDF
+ All views are exported as a CSV and then gzipped/compressed
+ Metadata about the sketch is saved to a file
+ All this data is then added to a ZIP container, so it ends up being a single file.
+ All comments are stored
+ All starred events are exported as a CSV and then compressed
+ A label is added to a sketch that is archived

Question whether we want any additional data stored.

Another question is whether the sketch and timelines in it should be deleted/removed after the archive takes place or not? (have that as an option)

What needs to happen:

- [x]  Add a HTML export functionality to stories
- [x]  Add a new API call in the backend that takes care of the archiving functionality, it should take as a parameter whether the sketch and timelines should be deleted after archiving
- [x]  Add labeling to sketches
- [x]  Add into the configuration files sketch labels that "prevent" deleting, could be used for adding labels to sketches that should not be deleted due to litigation holds for example.
- [x]  Add a feature in the UI that would also prevent deletion of sketches with these labels.

**Comment by kiddinn** [comment]
When a sketch is archived, few things happen:

+ an archive label is added to the sketch
+ the indices are marked in ES as closed (not deleted)
+ the same data is dumped as described above

The indices themselves are not deleted, just marked as closed in ES. This makes the sketch not readable nor writable, but the data is still there.

Then the sketch can be un-archived and then become functional again.

The UI then needs to read the archive label, mark the sketch somehow "grey" and then add the ability to un-archive a sketch within the ui itself.

**Comment by kiddinn** [comment]
Some of these features have already been implemented in #1181 

Few follow up PRs to add more functionality:  #1246,  #1248 and #1250 

Archiving support is in, at least in the API and API client. What is missing is the UI elements as well as enhancing some of the export capabilities.

**Comment by kiddinn** [comment]
ATM a sketch can be archived. What that means is:

1. All timelines in the sketch are archived
2. A check is made for all search indexes, if a search index is only inside an archived sketch the search index will also get archived, and therefore closed (in ES sense)
3. The sketch status is changed to `archived`

There is an option to export the sketch as well, but that is separate, and it will generate a ZIP file with the content of the sketch. This can be done irrelevant whether the sketch is archived or not (if it's archived it starts by un-archiving, then exporting and finally archiving again)

**Comment by kiddinn** [comment]
The export is no longer in a PDF format but instead in a HTML, therefore that original ask is not relevant anymore.

**Comment by kiddinn** [comment]
Expanding upon export support: #1251

**Comment by kiddinn** [comment]
And the UI support is in: #1256 

Just waiting on #1251 to be merged then this issue can be safely closed

**Comment by berggren** [comment]
All merged. This is complete. 🎉
