### ISSUE TITLE
Analyzers Pending 

### ISSUE THREAD

**Issue by rocket71** [google/timesketch#1185]
I recently installed Timesketch on Ubuntu.  After uploading a plaso file, I attempted to run analyzers but the are stuck on a Status of "pending".  It also appears to error when running the sigma analyzer.  This is likely due to it being a windows system vs linux.  Is it possible to add additional Sigma rules more applicable to the analyzer by adding yaml files to the directory?

Also, I see there are additional analyzers such as Psexec but unsure how to execute analyzers via cmd since not listed in the GUI. My apologies for such base questions, unsure where to make inquires.

**Comment by jaegeral** [comment]
Yes some sigma analyszers currently might have a problem, to help you further, can you post your error message?

**Comment by kiddinn** [comment]
what other analyzers are in a `pending` state?

Do you see any errors in the sever logs?

**Comment by kiddinn** [comment]
is this still an issue?

**Comment by kiddinn** [comment]
the sigma analyzer has been updated since this question, and it is still being worked on, not sure if this is still an issue, but I'm closing this down since I haven't heard anything in awhile and I believe this should no longer be an issue.

if it is still, then please re-open the issue.
