### ISSUE TITLE
setup.py fails to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1190]
When trying to build a dpkg source package on Ubuntu 20.04

```
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --buildsystem=pybuild --with=python3,systemd
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.8 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    from pip._internal.download import PipSession
ModuleNotFoundError: No module named 'pip._internal.download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    from pip.download import PipSession
ModuleNotFoundError: No module named 'pip.download'
E: pybuild pybuild:341: clean: plugin distutils failed with: exit code=1: python3.8 setup.py clean 
dh_auto_clean: error: pybuild --clean -i python{version} -p 3.8 returned exit code 13
make: *** [debian/rules:4: clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -S -sa failed
```

pip-python3 is installed
```
python3
>>> import pip.download
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pip.download'
>>> import pip
>>> pip.__version__
'20.0.2'
```

**Comment by garanews** [comment]
![image](https://user-images.githubusercontent.com/16938405/82316001-77c50480-99cc-11ea-9e0f-ac5e113b81d3.png)


then need to fix
`
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    'requirements.txt', session=PipSession(),
  File "setup.py", line 83, in <listcomp>
    install_requires=[str(req.req) for req in parse_requirements(
AttributeError: 'ParsedRequirement' object has no attribute 'req'
`

**Comment by joachimmetz** [comment]
@garanews thx for the suggestion but IMHO if something is named `pip._internal`, to me hints like a strong discouragement of using it external to pip module

**Comment by garanews** [comment]
Need to modify something because pip>20.0 breaks module: https://github.com/pypa/pip/issues/7645

Modified this:
` install_requires=[str(req.req) for req in parse_requirements(` 
` 'requirements.txt', session=PipSession(),` 
 ` )]`,` 

in this:

`    str(req.requirement)`
`    for req in parse_requirements("requirements.txt", session=PipSession(),)`
`],`

**Comment by garanews** [comment]
Hello,
we solved in this way: https://github.com/LDO-CERT/mans_to_es/blob/master/setup.py
Would you like a pr here in the same way to fix issue?

**Comment by joachimmetz** [comment]
Recommended way to use pip: https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program

**Comment by joachimmetz** [comment]
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirements-parsing

**Comment by joachimmetz** [comment]
@garanews I strongly recommend changing this in mans_to_es as well to use pkg_resources instead of PIP internal APIs

**Comment by joachimmetz** [comment]
Unfortunately this fails with older versions of pip (https://travis-ci.org/github/google/timesketch/jobs/691184377)

**Comment by joachimmetz** [comment]
Addressed in https://github.com/google/timesketch/pull/1225 and tests added in https://github.com/google/timesketch/pull/1220
