### ISSUE TITLE
Merge timelines

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1200]
When having many small timelines with similar data in a sketch it would be handy if one could merge them to a new index, name it and then purge the other timelines.

**Comment by jaegeral** [comment]
+1 for that, this would be awesome

**Comment by jaegeral** [comment]
To catch some caveats here in case someone else is taking it up.
It is not as easy as merging the indices
- [ ] db entries to be considered
- [ ] ACLs
- [ ] Views
- [ ] Aggregations

**Comment by jaegeral** [comment]
As far as I understand by changing the DB model and only having one index per sketch this is not needed anymore. The main source of that was to save indexes, right @berggren ? If so we can close this issue.

**Comment by kiddinn** [comment]
Agree, no need to keep this open anymore
