### ISSUE TITLE
Add mans support parser

### ISSUE THREAD

**Issue by garanews** [google/timesketch#1206]
Created #1205 that replaces the  #937 and uses mans_to_es as library instead of external tool.
Will follow new pr with documentation and docker support.
Regarding docker: there are 2 other pr waiting that we need:
#1195
#1174
We can create one pr that includes all we need (idna, python3-setuptools ,python3-wheel , build-essential to compile required dependencies ) or wait the merge  of those pr and create a pr with only build-essentials inside.
What do you think?

**Comment by kiddinn** [comment]
@berggren since you were working on the re-factoring of all things docker, can you respond here?

**Comment by garanews** [comment]
Another thing, what about upgrade some library? 
We had to tweak our dependencies in order to do not break yours:
numpy>=1.16.6
pandas>=0.24.2

Our code works with any issue with:
numpy==1.18.4
pandas==1.0.3

Is still necessary to support py2?

**Comment by kiddinn** [comment]
> Another thing, what about upgrade some library?
> We had to tweak our dependencies in order to do not break yours:
> numpy>=1.16.6
> pandas>=0.24.2
> 
> Our code works with any issue with:
> numpy==1.18.4
> pandas==1.0.3
> 

I'll update the requirements file

> Is still necessary to support py2?

no....

**Comment by berggren** [comment]
> @berggren since you were working on the re-factoring of all things docker, can you respond here?

Yeah, this has been fixed in #1207 as part of a larger refactor and fixit for docker in TS. We now build base images automatically that is used.
