### ISSUE TITLE
UI: Notification/Alert window

### ISSUE THREAD

**Issue by SecSamDev** [google/timesketch#1263]
It would be great if a analyzer notifies the user that it has finished, displaying additional information.
At this point, parsers only add more information to events, but it can help to have analyzer that look for patterns on multiple timelines and present the result.

I know an analyzer can create a story and populate it, but it would be better if it's in a different way.

I have implemented the functionality based on the stories: a modified model and view.

**Comment by kiddinn** [comment]
ok... so it seems like there are few points here, let's look at them...

```
It would be great if a analyzer notifies the user that it has finished, displaying additional information.
```

What sort of information do you have in mind?

```
At this point, parsers only add more information to events, but it can help to have analyzer that look for patterns on multiple timelines and present the result.
```

That is exactly what the analyzers are supposed to be able to do... add information to events, look for patterns in multiple timelines and to present the results... 

presenting teh results:
+ Adding information to events, such as tags, human_readable, etc
+ Adding saved views
+ Adding saved aggregations
+ Adding stories

```
I know an analyzer can create a story and populate it, but it would be better if it's in a different way.
```

What are you thinking about?

```
I have implemented the functionality based on the stories: a modified model and view.

```
What does a `modified model` here mean?

**Comment by SecSamDev** [comment]
I have created a new view called Alarms that shows a list of alarms created by analyzers (created a new Db Model, two new API routes, some extra views...). The alarms can only be created by the analyzers, and cant be modified, only deleted.

Las alertas le mostrarán a un analista comportamientos anómalos.
En un apartado distinto a donde se crean los informes (stories).

Por ejemplo: 
Sysmon Events 1 (Creation Process) buscando procesos que se ejecutan todas las horas para mantener la persistencia.

**Comment by kiddinn** [comment]
`I have created a new view called Alarms that shows a list of alarms created by analyzers `

Do you have a mock of this? Screenshots or something that shows how this looks like/

I'm just wondering what this will give us, besides what we've already got. Would be good to see some examples here.

**Comment by SecSamDev** [comment]
## Result of the analyzer

![tiomesketch-alerts](https://user-images.githubusercontent.com/38586018/84037394-d31c5e00-a99e-11ea-9646-44422a3b3d45.jpg)

## Analyzer
It only counts the number of events and notifies the user when finished with an alert.
![timesketch-code-analyzer](https://user-images.githubusercontent.com/38586018/84037535-03fc9300-a99f-11ea-970b-7443a274c890.jpg)

"Alert" could be confusing, better would be Execution History or something like that.

BTW: nice project structure. Easy to extend and make new analyzers and functionality.

**Comment by SecSamDev** [comment]
New screenshots:

![timesketch1](https://user-images.githubusercontent.com/38586018/84818973-9d6b1b00-b017-11ea-9888-ec3211466698.png)


![Captura de pantalla de 2020-06-16 21-22-06](https://user-images.githubusercontent.com/38586018/84819035-b247ae80-b017-11ea-9c43-481fef88f201.png)


![Captura de pantalla de 2020-06-16 21-21-57](https://user-images.githubusercontent.com/38586018/84819057-b83d8f80-b017-11ea-9a59-ab73a1a4139d.png)

**Comment by jaegeral** [comment]
@SecSamDev do you have a PR or something for that? I think this great stuff to display to users and is kind of related to https://github.com/google/timesketch/issues/1420

**Comment by jaegeral** [comment]
Auto closing that because lack of activity, feel free to re-open if new info is available
