### ISSUE TITLE
Delete Sketch from UI doesn't remove Sketch from DB

### ISSUE THREAD

**Issue by cshanahan** [google/timesketch#1269]
**TS Version**
Using Timesketch from Git master; installed on 2020-06-10

**STEPS TO REPRODUCE**
Run `tsctl runserver` and log into the app. Select an existing Sketch or create a new (test) Sketch. Select Delete from the UI drop-down option. Sketch appears to be deleted correctly and no errors are displayed. The Sketch is no longer available from the UI.
From CLI, run `tsctl list_sketches' and the Sketch that I deleted is still listed in the output.

**Comment by kiddinn** [comment]
The sketch does not get deleted from the DB, and should not, it gets set into a `delete` state, and that should preclude it from being listed in `list_sketches` function. I'll fix that.

**Comment by cshanahan** [comment]
> The sketch does not get deleted from the DB, and should not, it gets set into a `delete` state, and that should preclude it from being listed in `list_sketches` function.

That makes sense, thank you.
