### ISSUE TITLE
ES too_long_frame_exception if a sketch contains many timelines?

### ISSUE THREAD

**Issue by dov-csis** [google/timesketch#1274]
We get a `RequestError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')` starting at this line.

https://github.com/google/timesketch/blob/4d1fba42836a33a0cb09028c135e6b132fa71421/timesketch/api/v1/resources.py#L435

Increasing `http.max_initial_line_length` (its [default](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) is 4kb) would probably fix this though - but our ES provider does not allow changing this value.

We have 205 timelines associated to the given sketch.

Has anyone else seen this error? If our explanation above is correct, it might make sense to limit the maximal amount of timelines per sketch, what do you think?

**Comment by kiddinn** [comment]
We are going to setup an environment to reproduce this and fix the issue. This has to do with few checks we make, such as counts, etc, that generate a GET request to the Elastic REST API, and with X number of timelines the GET Request gets to be too large. We will need to check the size and then chunk up the requests to make this work.

**Comment by dov-csis** [comment]
Let us know - we can help with reproducing / double-checking the findings, and later with the fixes too. (We are on **20200507** at the moment though.)

**Comment by jaegeral** [comment]
Is that still an issue after our recent re-factoring of how we handle timelines in sketches?

**Comment by berggren** [comment]
This has been fixed in the new way we are indexing and handling timelines. Closing out.
