### ISSUE TITLE
Add an admin `bit` to TS

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1278]
Add an admin bit to the user database model. 

What this would do:

1. In SketchResource the bit would be checked, if set then a minimal set of information is returned for a sketch (unless the user also has read/write/delete permissions). This would be mainly just the ACL, the name and description of the sketch. No access to data.
2. In SketchListResource all sketches are returned, some with minimal details (one with only admin access)
3. In the archive API, an admin can archive any sketch.
4. An admin can add new users, etc... if that will be added to the API instead of only being open from tsctl as it is now.
5. In the future if dashboards are added, an admin bit would have a bit more overview than a regular user.

That is it, the admin bit is not giving any more access, no more access to data or anything, simply the ability to list up all available sketches and the ability to archive all sketches.

There need to be changes made in the UI and API client to make sure the UI/API don't crash when an admin visits a sketch they don't have access to. So that only the minimal set of information is returned and the tool does not crash since it expects more details.

**Comment by kiddinn** [comment]
this requires a schema change, adding a simple bit to the user schema

**Comment by berggren** [comment]
This has been implemented.
