### ISSUE TITLE
Problem indexing volatility memory dump

### ISSUE THREAD

**Issue by SecSamDev** [google/timesketch#1299]
I was trying to upload a json file with 54 elements but i don't see any changes in the elasticsearch index. Timesketch says: Indexing in progress... .
Each element has a field "process_mem_strings" that contains the output of the strings command of a process memory dump (50Mb).

I have checked the amount of documents and disk usage in the index and it seems like it is not indexing.
I also did not see any errors in the celery logs.

Maybe the celery task can't read a 50Mb json.

**Comment by kiddinn** [comment]
how did you upload this file?

What version of Timesketch do you have installed?

Does the JSON file (I assume it's json lines) have a `datetime` or a `timestamp` field? And a `timestamp_desc` and a `message`?

Are there error logs on the backend?

**Comment by SecSamDev** [comment]
File uploaded using UI.
It's a JSONL with all the mandatory fields.
And no errors on the backend.

**Comment by kiddinn** [comment]
ok.. so you are only able to upload a single line of the file, but not the entire file?

have you tried using the importer? timesketch-import-client (https://github.com/google/timesketch/blob/master/docs/UploadData.md#using-the-importer-cli-tool)

**Comment by SecSamDev** [comment]
The problem was with the timeout of the connection in "flush_queued_events". The default timeout is set to 10 seconds, and we are doing a bulk once every 1000 events. For my use case, were I'm indexing a small number of big documents, i needed to update the timeout to 60 seconds and add a retry.

```
    def flush_queued_events(self, retries=3):
        if self.import_events:
            try:
                self.client.bulk(body=self.import_events,request_timeout=60)
            except (ConnectionTimeout, socket.timeout) as e:
                if retries <= 0:
                    es_logger.error('Unable to add events, with error: {0!s}'.format(e))
                    raise e
                self.flush_queued_events(retries=(retries - 1))
```

**Comment by berggren** [comment]
Thanks @SecSamDev for the added details. Having events that big is not really the use-case for TS. It will be slow to download the full event etc.

I'm curious what use-case you have for this. That being said, I'm closing this issue from our side.
