### ISSUE TITLE
uploading plaso image from ubuntu shell

### ISSUE THREAD

**Issue by siftuser** [google/timesketch#1309]
I have both plaso & timesketch running on the same ubuntu box ... is there a way to upload the plaso file to timesketch running on same box than downloading & upload via gui ? thank you

**Comment by siftuser** [comment]
Also tried uploading via gui few times, but it does not complete beyond ~70% upload. Thank you

![Screenshot 2020-07-23 at 4 36 18 PM](https://user-images.githubusercontent.com/8371690/88267082-e131fe00-cd02-11ea-8353-f8bdcca0e69d.png)


host OS: ubuntu 18.04
timesketch is running via docker/e2e 
plaso size: 1.4gb
plaso ver 20200630

**Comment by jaegeral** [comment]
You can try 

````
tsctl import
````

To import, see: https://github.com/google/timesketch/blob/master/docs/Users-Guide.md#import for more info.

**Comment by siftuser** [comment]
Thank you @jaegeral! But I'm running timesketch as a docker instance ... so `tsctl` is not available on host os :(

**Comment by siftuser** [comment]
@jaegeral would you please help with this error ? 

```
tsctl import -f disk.plaso --username user1 -n disk1
Imported /data/disk.plaso to sketch: 5 (Sketch for: disk1)
```

But the gui shows following error:

```
Detailed information for disk1

Elasticsearch index: f0281e35e40d4b3bad6432623a6cd2b1
Original name: disk1
Added by: user1
Added: 2020-07-23 18:46
Error detail
2020-07-23 10:46:09,736 [INFO] (MainProcess) PID:304 <data_location> Determined data location: /usr/share/plaso
2020-07-23 10:46:09,982 [INFO] (MainProcess) PID:304 <timesketch_out> Timeline name: disk1
2020-07-23 10:46:09,982 [INFO] (MainProcess) PID:304 <timesketch_out> Owner of the timeline: None
```

**Comment by kiddinn** [comment]
have  you used the import client? you don't need to run that on the docker, like tsctl (see https://github.com/google/timesketch/blob/master/docs/UploadData.md)

```
$ timesketch_importer.py --sketch_id 5 disk.plaso
```

**Comment by siftuser** [comment]
Thank you @kiddinn ... no go :(

**CLI**
```
timesketch_importer --sketch_id 5 disk1.plaso 

[2020-07-23 13:45:58,412] timesketch_importer.importer_frontend/INFO Saving Credentials. <timesketch_importer/main>
[2020-07-23 13:45:58,412] timesketch_api.crypto_client/INFO File does not exist, creating it. <crypto/save_credentials>
[2020-07-23 13:45:58,479] timesketch_api.crypto_client/INFO Credentials saved to: /home/ubuntu/.timesketch.token <crypto/save_credentials>
[2020-07-23 13:45:58,546] timesketch_importer.importer_frontend/INFO Creating a client. <timesketch_importer/main>
[2020-07-23 13:45:58,952] timesketch_importer.importer_frontend/INFO Client created. <timesketch_importer/main>
[2020-07-23 13:45:58,952] timesketch_importer.importer_frontend/INFO Saving TS config. <timesketch_importer/main>
[2020-07-23 13:46:10,834] timesketch_importer.importer_frontend/INFO Uploading file. <timesketch_importer/main>
[2020-07-23 13:46:55,875] timesketch_importer.importer_frontend/INFO File got successfully uploaded to sketch: 5 <timesketch_importer/main>
```

**Error on the GUI**

```
Detailed information for disk1

Elasticsearch index: 92501890eaeb437db6d224aa91d84088
Original name: disk1
Added by: user1
Added: 2020-07-23 21:46
Error detail
2020-07-23 13:46:57,380 [INFO] (MainProcess) PID:320 <data_location> Determined data location: /usr/share/plaso
2020-07-23 13:46:57,632 [INFO] (MainProcess) PID:320 <timesketch_out> Timeline name: disk1
2020-07-23 13:46:57,632 [INFO] (MainProcess) PID:320 <timesketch_out> Owner of the timeline: None
```

**Comment by siftuser** [comment]
> Also tried uploading via gui few times, but it does not complete beyond ~70% upload. Thank you

If it helps, noticed this on the console, when the upload breaks in between 

```
timesketch_1     | [2020-07-23 16:45:45 +0000] [27] [CRITICAL] WORKER TIMEOUT (pid:33)
timesketch_1     | [2020-07-23 16:45:46 +0000] [47] [INFO] Booting worker with pid: 47
timesketch_1     | [2020-07-23 16:50:46 +0000] [27] [CRITICAL] WORKER TIMEOUT (pid:47)
timesketch_1     | [2020-07-23 16:50:47 +0000] [53] [INFO] Booting worker with pid: 53
```
![Screenshot 2020-07-23 at 4 36 18 PM](https://user-images.githubusercontent.com/8371690/88314974-45c37c00-cd48-11ea-92e5-3bf45a9e98fb.png)

**Comment by siftuser** [comment]
sorry for spamming. Is it same as https://github.com/google/timesketch/issues/1060 ?

**Comment by kiddinn** [comment]
ok, so looking at this

a) did you not try to upload the plaso file itself directly using the importer??

```
timesketch_importer --sketch_id 2 disk1.plaso
```
???

b) Secondly, you indicate that you run `psort` manually to produce the CSV file, so what parameters to `psort` did you use?

c) it seems like there isn't any timestamp data there, can you do a `head -2` on the CSV file to see what columns exist there? There looks to be a field called `time` there, but some of it has the wrong string format to be able to be parsed. Could there be some malformed time columns?

**Comment by siftuser** [comment]
> did you not try to upload the plaso file itself directly using the importer??
> 
> ```
> timesketch_importer --sketch_id 2 disk1.plaso
> ```

more than 1gb plaso file fails as listed [here](https://github.com/google/timesketch/issues/1309#issuecomment-662940734) 

`psort.py --output-time-zone UTC -o l2tcsv -w /plaso.csv /image.plaso "date > '2020-01-01' and date < '2020-04-01'"`

Above csv contains ~2M+ events. `timesketch_importer` uploads the csv file to TS docker instance. But shows only 1.5M events in the gui. Is there a param that restricts or caps at 1.5M events ? (tried more than once & same result)

**Comment by kiddinn** [comment]
> > did you not try to upload the plaso file itself directly using the importer??
> > ```
> > timesketch_importer --sketch_id 2 disk1.plaso
> > ```
> 
> more than 1gb plaso file fails as listed [here](https://github.com/google/timesketch/issues/1309#issuecomment-662940734)
> 
but this is using `tsctl` not the importer... so have you tried using the importer?

```
$ timesketch_importer --sketch_id 2 disk1.plaso
```


> `psort.py --output-time-zone UTC -o l2tcsv -w /plaso.csv /image.plaso "date > '2020-01-01' and date < '2020-04-01'"`
> 

Why are you using the `l2tcsv`? I would opt for you to skip that.


> Above csv contains ~2M+ events. `timesketch_importer` uploads the csv file to TS docker instance. But shows only 1.5M events in the gui. Is there a param that restricts or caps at 1.5M events ? (tried more than once & same result)


Wait, so the importer does work? That is it does import the file, I thought you said that the importer wasn't able to upload it and failed due to the parsing errors with `time` and `timezone`? 

And no, there isn't any cap at 1.5 m events. That is a bit odd though, and would need to be debugged a bit more. In the explorer if you select only that index and search for `*`, how many events are shown there?

**Comment by siftuser** [comment]
Thanks @kiddinn 

> have you tried using the importer?
> 
> ```
> $ timesketch_importer --sketch_id 2 disk1.plaso
> ```

Yes I did ... this is the result

`console`

```
[2020-08-12 10:24:06,219] timesketch_importer.importer_frontend/INFO Creating a client.
[2020-08-12 10:24:06,655] timesketch_importer.importer_frontend/INFO Client created.
[2020-08-12 10:24:06,655] timesketch_importer.importer_frontend/INFO Saving TS config.
[2020-08-12 10:24:06,655] timesketch_importer.importer_frontend/INFO Uploading file.
[2020-08-12 10:25:58,665] timesketch_importer.importer_frontend/INFO File got successfully uploaded to sketch: 2
```

`GUI`

```
Error detail
2020-08-12 10:26:00,987 [INFO] (MainProcess) PID:61 <data_location> Determined data location: /usr/share/plaso
2020-08-12 10:26:01,251 [INFO] (MainProcess) PID:61 <timesketch_out> Timeline name: 2plaso
2020-08-12 10:26:01,251 [INFO] (MainProcess) PID:61 <timesketch_out> Owner of the timeline: None
```

> Why are you using the l2tcsv? I would opt for you to skip that.
> Wait, so the importer does work? That is it does import the file, I thought you said that the importer wasn't able to upload it and failed due to the parsing errors with `time` and `timezone`?

`timesketch_importer` throws above error for `plaso file`. 
`timesketch_importer` works for csv file. By removing `l2tsv` option worked. The new csv file created was completely uploaded containing all records (2.5m+) 

more than 1gb plaso file fails as listed [here](https://github.com/google/timesketch/issues/1309#issuecomment-662940734)

**Comment by kiddinn** [comment]
ok... so the importer upload of the plaso file seems to actually work... there is something else that caused the plaso file to fail.

The error log you provided is not really an error log, these are just informational entries, which show that the actual plaso file got uploaded to the server.

There is something wrong OTOH on the backend, if the plaso upload fails, proper error logs that show the actual error should be presented, not the informational lines that are included (this is the second time I'm seeing this, so this needs to be fixed).

So there is some other reason for why the plaso file is failing, but since the logs don't really show it, it's hard to tell why. Can you take a look at your backend, to look at the celery logs to see if they provide any more details?

**Comment by siftuser** [comment]
Thanks @kiddinn 

Would you help, where to locate celery logs ? I tried /var/log of timesketch docker container

**Comment by kiddinn** [comment]
hi, how are you starting the celery worker? Is this on a dev instance? then it should be in STDOUT logs where you run the worker

otherwise it depends on your docker config

**Comment by siftuser** [comment]
running default git pulled docker container ([docker/e2e](https://github.com/google/timesketch/tree/master/docker/e2e))

**Comment by aleksf** [comment]
I am getting same issue with large plaso file (5GB) import into timesketch

Plaso version used to generate timeline: 20200717
Timesketch version: docker https://github.com/google/timesketch/tree/master/docker/e2e
Plaso version embedded in Timesketch: 20200430

Generated plaso file is parsed properly in the container where I am uploading it from:

```
pinfo.py XXX.plaso

************************** Plaso Storage Information ***************************
            Filename : XXX.plaso
      Format version : 20200523
        Storage type : session
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
bb70a021-538f-43d1-be28-549b1317b730 : 2020-09-05T07:06:53.305002Z
9b66e430-1958-4404-9371-952e0656cd7b : 2020-09-05T07:07:22.698865Z
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
 Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
              asl_log : 74
       binary_cookies : 428
    chrome_17_cookies : 257
    chrome_27_history : 3
    chrome_66_cookies : 643
         chrome_cache : 14223
   chrome_preferences : 53
             cups_ipp : 193
             filestat : 10648103
            fseventsd : 11122
       gdrive_synclog : 415368
google_analytics_utma : 22
google_analytics_utmb : 7
google_analytics_utmt : 8
google_analytics_utmz : 14
mac_document_versions : 17
         mac_keychain : 68
       mac_knowledgec : 38367
      mackeeper_cache : 482
              macwifi : 2634
        olecf_default : 1167
                 oxml : 1081
                   pe : 2
        plist_default : 8386
               syslog : 1527
                utmpx : 5
                Total : 11144254
--------------------------------------------------------------------------------

No events labels stored.

************************ Warnings generated per parser *************************
 Parser (plugin) name : Number of warnings
--------------------------------------------------------------------------------
          <No parser> : 5976
sqlite/mac_knowledgec : 2704
     sqlite/mac_notes : 2706
              asl_log : 5
              macwifi : 1
               sqlite : 79
       binary_cookies : 2
             cups_ipp : 18
   chrome_preferences : 6
       gdrive_synclog : 1038
--------------------------------------------------------------------------------
```

Upload with timesketch_importer, psort.py, tsctl does not return any errors:

**timesketch_importer -u secint --pwd-prompt --host http://timesketch --timeline_name XXX XXX.plaso**
`
[2020-09-08 01:51:06,408] timesketch_importer.importer_frontend/INFO Creating a client.
[2020-09-08 01:51:06,847] timesketch_importer.importer_frontend/INFO Client created.
[2020-09-08 01:51:06,847] timesketch_importer.importer_frontend/INFO Saving TS config.
[2020-09-08 01:51:06,881] timesketch_importer.importer_frontend/INFO Uploading file.
[2020-09-08 01:54:57,977] timesketch_importer.importer_frontend/INFO File got successfully uploaded to sketch: 3
`

Upload using test file from https://github.com/log2timeline/plaso/blob/master/test_data/pinfo_test.plaso works fine and produces timeline in timesketch.

**Comment by aleksf** [comment]
I believe, in my case I got to the bottom of the problem. Upload works fine, it's plaso version on timesketch side (20200430), which does not recognise file created with L2T version 20200717

`
2020-09-08 02:35:57,450 [WARNING] (MainProcess) PID:98 <psort_tool> Appending to an already existing storage file.
2020-09-08 02:35:57,460 [WARNING] (MainProcess) PID:98 <psort> Format of storage file: /tmp/a3f4ee1671734282a99966dff516c190 not supported
`

**Comment by aleksf** [comment]
As a temporary workaround I bumped up plaso version in timesketch container
```
pip3 install --upgrade plaso
```

**Comment by kiddinn** [comment]
I was just going to suggest that. We need a better way to surface issues with plaso version mismatch.

**Comment by kiddinn** [comment]
this ticket seems to be resolved, closing it down now.

We will need to do some other work to make sure the plaso version is up-to-date and supported.
