### ISSUE TITLE
MISP export of events

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1311]
MISP export of

- selected events
- all events with a defined label (starred)

There is already a MISP object template for time-sketch (which can be adjusted if needed):

https://www.misp-project.org/objects.html#_timesketch_timeline

The idea would be able to share a timeline via the MISP and benefit from the timeline view in MISP. This can be done easily if a first_seen/last_seen is set for each the timesketch_timeline object for each of the exported event. As a complementary step, a relationship can be added (https://www.misp-project.org/objects.html#_relationships) such as "followed-by" and "preceding-by" which are already used by the mactime import.

_Originally posted by @adulau in https://github.com/google/timesketch/issues/1106#issuecomment-667128534_

**Comment by jaegeral** [comment]
Moving it to a new issue to have the opportunity to discuss approach.

I gave it a try and mocked a small script, I do not have a MISP instance at hand to test and did not find any documentation.

Can you have a look at: https://github.com/jaegeral/timesketch/tree/misp_export

If you would run it:

``
timesketch/utils$ python3 misp_export.py
``

With 4 starred events from:
https://github.com/google/timesketch/blob/master/test_tools/test_events/sigma_events.jsonl

@adulau could you verify that this output would work for you? Then it should be easier to implement with proper API / UI

It would generate the following output (and it would be written to output.txt):

````
[
    {
        "datetime": "2015-07-24T19:01:01+00:00",
        "message": "A message",
        "timestamp": 123456789,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:02+00:00",
        "message": "Another message",
        "timestamp": 123456790,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:03+00:00",
        "message": "Yet more messages",
        "timestamp": 123456791,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:03+00:00",
        "message": "Install: zmap:amd64 (1.1.0-1) [Commandline: apt-get install zmap]",
        "timestamp": 123456791,
        "timestamp_desc": "foo"
    }
]

````


The raw output of the script (and including the data structure per event looks like the following:
```
4
{'_id': '8ixopnMBXeh3g6co_hwt', '_index': '3abfb7fabfb34b568a97ec097de6c28b', '_score': 1.1053605, '_source': {'datetime': '2015-07-24T19:01:01+00:00', 'label': ['__ts_star'], 'message': 'A message', 'timestamp': 123456789, 'timestamp_desc': 'Write time'}, '_type': '_doc', 'selected': False}
{'_id': '8yxopnMBXeh3g6co_hwt', '_index': '3abfb7fabfb34b568a97ec097de6c28b', '_score': 1.1053605, '_source': {'datetime': '2015-07-24T19:01:02+00:00', 'label': ['__ts_star'], 'message': 'Another message', 'timestamp': 123456790, 'timestamp_desc': 'Write time'}, '_type': '_doc', 'selected': False}
{'_id': '9CxopnMBXeh3g6co_hwt', '_index': '3abfb7fabfb34b568a97ec097de6c28b', '_score': 1.1053605, '_source': {'datetime': '2015-07-24T19:01:03+00:00', 'label': ['__ts_star'], 'message': 'Yet more messages', 'timestamp': 123456791, 'timestamp_desc': 'Write time'}, '_type': '_doc', 'selected': False}
{'_id': '9SxopnMBXeh3g6co_hwt', '_index': '3abfb7fabfb34b568a97ec097de6c28b', '_score': 1.1053605, '_source': {'datetime': '2015-07-24T19:01:03+00:00', 'label': ['__ts_star'], 'message': 'Install: zmap:amd64 (1.1.0-1) [Commandline: apt-get install zmap]', 'timestamp': 123456791, 'timestamp_desc': 'foo'}, '_type': '_doc', 'selected': False}



[
    {
        "datetime": "2015-07-24T19:01:01+00:00",
        "message": "A message",
        "timestamp": 123456789,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:02+00:00",
        "message": "Another message",
        "timestamp": 123456790,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:03+00:00",
        "message": "Yet more messages",
        "timestamp": 123456791,
        "timestamp_desc": "Write time"
    },
    {
        "datetime": "2015-07-24T19:01:03+00:00",
        "message": "Install: zmap:amd64 (1.1.0-1) [Commandline: apt-get install zmap]",
        "timestamp": 123456791,
        "timestamp_desc": "foo"
    }
]
```

**Comment by kiddinn** [comment]
in #1106 we'll implement an export function, I was thinking to just have a parameter to the API/UI that could indicate format, and misp could be one such format... so let's wait with adding this until that feature is ready and built-in.

once that feature is in, then we can just add a plugin or a new output definition that would provide the misp one. How does that sound?

**Comment by joachimmetz** [comment]
@jaegeral @kiddinn know that MISP is licensed APGL and this can be problematic setting up a test instance

**Comment by jaegeral** [comment]
If one would like to export Timesketch events and make them a misp object, could try to start with something:

````

from timesketch_api_client import client

ts = client.TimesketchApi(SERVER_LOCATION, USERNAME, PASSWORD)
sketch = ts.get_sketch(Sketch_id)
stared = sketch.search_by_label('__ts_star')
print(stared['meta']['es_total_count'])

````
stared is now containing all the events, so iterating, using the values you want to use and map them to misp-objects should be simple.

**Comment by jaegeral** [comment]
So given our discussions it should be fair to close this issue from our side.
