### ISSUE TITLE
psort filter date error

### ISSUE THREAD

**Issue by siftuser** [google/timesketch#1319]
Running `psort version 20200717` on ubuntu 18.04

`psort.py --output-time-zone UTC /image.plaso -o l2tcsv -w /plaso.csv "date < '2020-01-01' and date > '2020-08-01'"` 

throws error `psort.py: error: unrecognized arguments: date < '2020-01-01' and date > '2020-08-01'`

**Comment by joachimmetz** [comment]
@siftuser why are you reporting this to timesketch?

**Comment by siftuser** [comment]
apologies.  please ignore

**Comment by joachimmetz** [comment]
I can just move it to plaso

**Comment by joachimmetz** [comment]
darn that does not work cross-github org

**Comment by joachimmetz** [comment]
the answer is the order of arguments is the issue, try

```
psort.py --output-time-zone UTC -o l2tcsv -w /plaso.csv /image.plaso "date < '2020-01-01' and date > '2020-08-01'"
```
