### ISSUE TITLE
docker version - missing graph view

### ISSUE THREAD

**Issue by siftuser** [google/timesketch#1320]
Running docker/e2e version. But I dont see graph view or other features as mentioned in the [article](https://medium.com/timesketch/thinking-in-graphs-exploring-with-timesketch-84b79aecd8a6)  ... am I using incorrect docker version ? Thank you

![timesketch](https://user-images.githubusercontent.com/8371690/89540746-0ad54400-d830-11ea-9486-68ce1f788415.png)

**Comment by jaegeral** [comment]
Hi, the Graph view is currently not ported to the new UI unfortunately.

**Comment by kiddinn** [comment]
yes, ATM graph view is not visible in the new UI since we are re-working the entire graphing framework for Timesketch.

Once graphing is re-introduced we will add a view in the UI, closing this as of now, since this is WAI , at least for the moment
