### ISSUE TITLE
Issues with yarn build

### ISSUE THREAD

**Issue by binglot** [google/timesketch#1322]
When trying to run `docker exec -it $CONTAINER_ID yarn run --cwd=/usr/local/src/timesketch/timesketch/frontend build --mode development --watch` I received various errors. I tried a bunch of things and eventually resolved it so I can't remember the exact order but I think these were the commands I ran in the container that helped to resolve it.

```
$ tsdev.sh shell
# cd /usr/local/src/timesketch/timesketch/frontend
# yarn install
# yarn run serve
if get errors, run
# npm install
```

**Comment by berggren** [comment]
I bet this is because you need to initially need to run `yarn install` to install all packages and dependencies.

**Comment by berggren** [comment]
Closing this. Will be covered ion upcoming dev documentation,.
