### ISSUE TITLE
CSV exported from Timesketch can not be re-imported (Web importer)

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1323]
Right now if you export a sketch using **"Overview --> More --> Export"** you get a zip file with (besides other stuff) a csv e.g. starred_events.csv.

As I user I would expect that I can re-import the csv back to Timeskeztch, but I cannot.

I assume this is because the csv contains the columns:
``
tag
_id
_type
_index
``
Which are used from TS.

Imho we should eithe roffer within the CSV a file that can be re-imported or kill those TS internal things from the export.

**Comment by kiddinn** [comment]
does it not work using the timesketch importer?

I'm assuming you are only testing out the Web UI importer?

**Comment by kiddinn** [comment]
I might have to kill or at least rewrite the UI importer, since it's really not working well

**Comment by kiddinn** [comment]
The CSV that's produced is easily readable by other apps and libraries

**Comment by jaegeral** [comment]
Ok tested with the importer:

````
PYTHONPATH=. python3 timesketch_importer.py ~/dev/timesketch/test_tools/test_events/starred_events_problematic.csv
````

And worked nicely, only the if tags are empty they are imported as [ ] as one tag each.
