### ISSUE TITLE
Timesketch automated install & config script

### ISSUE THREAD

**Issue by blueteam0ps** [google/timesketch#1370]
Hi there,

I have created a new repo https://github.com/blueteam0ps/AllthingsTimeSketch. This contains a TS automatic install and configuration script. The script was tested on Ubuntu 18.04 LTS. Created this case so you can update the Github doco with a path as it will be a time saver for TS users.

**Comment by berggren** [comment]
Hey, thanks for this, and sorry for the late reply. We have since added contrib/deploy_timesketch.sh to make deployment easier using the Docker installation.

Thanks!
