### ISSUE TITLE
Problem with long lines in quotes in stories.

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1371]
When creating a story and adding a long line in quotes

```
Adding a long line....
```

The UI will show this as editable to begin with

![image](https://user-images.githubusercontent.com/8701947/93357034-659a8c00-f82f-11ea-8d0d-7bf9eca1912d.png)

But as soon as it gets rendered it will start to look like:

![image](https://user-images.githubusercontent.com/8701947/93357115-7e0aa680-f82f-11ea-81f8-de38adb08ba9.png)

Making it impossible to edit it.  The text field can only be expanded `up and down`, but not to the sides, making it impossible to edit the text.

**Comment by jaegeral** [comment]
Stories are not migrated yet, so I am going to close this issue
