### ISSUE TITLE
Add attributes to sketches

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1376]
Attributes need to be key/value pairs in the DB schema.

This could be used to denote SIEM/SEM/ticketing system ticket numbers, references to case notes, or something else that is relevant to the investigation/sketch.

This means that we need to add:

- [ ] Change the DB schema, add a class called `Attribute`
- [ ] Change the sketch schema to add a 1:many relationship, `attributes`
- [ ] Add an API to add/remove/edit attributes in a sketch
- [ ] Add support for the new API call into the API client.

Then finally this needs to be added to the UI

**Comment by berggren** [comment]
This has been done.
