### ISSUE TITLE
Add the ability to make data ingested outside of the API to be available in Timesketch

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1377]
One use-case is ingesting log data into Elastic via different mechanism than Timesketch itself. However there are limited ways ATM to make that data available in TS.

There needs to be made some changes to the API and maybe add another API call to make it possible to add a SearchIndex, and set the status of that SearchIndex to be `ready` so that it can be added to a timeline/sketch.

**Comment by ptitdoc** [comment]
That would be great. I had to tweak the DB manually in the past in order to do that.

One problem is having to reindex the Elastic index in order to fullfill Timesketch requirements (having datetime, description, and timestamp_desc fields).

**Comment by ptitdoc** [comment]
Just for reference, here is my code to do that (in order to add the feature to tsctl):
```
class ListIndexes(Command):
	def run(self):
		indexes = SearchIndex.query.all()
		for index in indexes:
			print (index.id, index.name, index.index_name, index.user_id,index.get_status.status)


class AddSearchIndex(Command):
	"""Create a new Timesketch searchindex."""
	option_list = (
		Option('--name', '-n', dest='name', required=True),
		Option('--index', '-i', dest='index', required=True),
		Option('--user', '-u', dest='username', required=True), )

	# pylint: disable=arguments-differ, method-hidden
	def run(self, name, index, username):
		"""Create the SearchIndex."""
		es = ElasticsearchDataStore(
			host=current_app.config['ELASTIC_HOST'],
			port=current_app.config['ELASTIC_PORT'])
		user = User.query.filter_by(username=username).first()
		if not user:
			sys.stderr.write('User does not exist\n')
			sys.exit(1)
		if not es.client.indices.exists(index=index):
			sys.stderr.write('Index does not exist in the datastore\n')
			sys.exit(1)
		if SearchIndex.query.filter_by(name=name, index_name=index).first():
			sys.stderr.write(
				'Index with this name already exist in Timesketch\n')
			sys.exit(1)
		searchindex = SearchIndex(
			name=name, description=name, user=user, index_name=index)
		db_session.add(searchindex)
		db_session.commit()
		searchindex.grant_permission('read',user=user)
		sys.stdout.write('Search index {0:s} created\n'.format(name))
```

**Comment by kiddinn** [comment]
Added a draft PR that needs to be tested before being sent for a review.

What this does is that in the API client youc an call

``` 
client.get_or_create_searchindex(es_index_name=ES_INDEX, status='ready')
```

Given that ES_INDEX is an already existing index within Elastic with. data that can be ready by TS and then creates a searchindex for it, and sets the status to your choice.

There is no check for whether or not the data contains the correct information as TS expects, so use at your own risk...

**Comment by kiddinn** [comment]
I never got any response back about whether or not this worked.

I will most likely need to retract that PR or at least modify that considerably, given the new changes to how TS works with uploaded data.

If this is really needed, I can add a way in the API client to tie this together. However the data needs to follow some guidelines, so maybe some checks need to be made.

1. The data needs to have the `__ts_timeline_id` field set, and that need to point to the ID of the timeline object, so that would have to be created in TS and then the data/documents in the ES index changed (this could potentially be done by the REST API)
2. The data needs to have the `datetime`, `message`, etc, fields set to them... this could also be done by the REST API that would check the mappings of the index prior to doing anything to make sure it `looks OK`.

The flow would then be:
1. Some tool uploads/ingests the data into ES
2. The API Client is called to add the data to a timeline, to a sketch (so it would belong to the sketch object)
3. The REST API will check if the index is `legit`, as in contains the needed data. If so it would create a Timeline object, then add the `__ts_timeline_id` field to every document in the index and then return the timeline data to the API client.

**Comment by kiddinn** [comment]
But given how I have not yet received a response about this still being needed, I'm inclined to just close this.

otherwise I will have to scrap the other PR and then start again, with the changed circumstances of how data is now uploaded to a sketch.
