### ISSUE TITLE
API_Client sketch.explore max_entries=5 does not limit the returned entries.

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1410]
```
data = sketch.explore('1.2.3.4 AND NOT timestamp_desc:all_packets.csv', as_pandas=True,return_fields='datetime,message,timestamp_desc',max_entries=5)
```

Expected output: 5 entries.

Received output:
````
data.info()
RangeIndex: 19 entries, 0 to 18
````

(basically all entries)

**Comment by kiddinn** [comment]
If you read the API doc:

```
             max_entries (int): Optional integer denoting a best effort to limit
                 the output size to the number of events. Events are read in,
                 10k at a time so there may be more events in the answer back
                 than this number denotes, this is a best effort.
```

So the number is a *best effort* and is really limiting the entries 10k at a time, so if your result set had 18k records and you set the limit to 10k, you would only get back 10k.

**Comment by kiddinn** [comment]
So this is ATM WAI, we could build a new feature, or change the behavior of this parameter.

This is a limitation on how the API in the backend works, but we could have this enforced stronger in the actual API code.

**Comment by kiddinn** [comment]
If you feel strongly about the behavior of this parameter, please open a new issue, this time as a FR to change the behavior of it, but as of now this is WAI
