### ISSUE TITLE
Create a `sysadmin` guide to Timesketch

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1411]
This means to create a documentation about how to setup and maintain a Timesketch environment. Roughly speaking it would include, how to:

- [x] Setup your production environment.
- [x] Maintain the environment, update the installation
- [x] Upgrade schema changes to the database.
- [x] Common troubleshooting techniques, where the logs are, what to look for, etc
- [x] Sketch maintenance, that is open index limits and archival best practices.
- [x] Other frequent sysadmin tasks.

**Comment by jaegeral** [comment]
Saw no objection, will close it out.
