### ISSUE TITLE
Dummy data set/welcome sketch

### ISSUE THREAD

**Issue by kovakina** [google/timesketch#1415]
It would be nice to have a demo sketch in a standard TS install, both in normal and dev versions.

How I see it:

Timesketch creates  a  "Welcome" sketch during the normal  set up process

The sketch is pre-filled with some dummy/example timeline(s)

This sketch can also be valuable to demonstrate some of the tool's features (analyzers, stories etc)

**Comment by jaegeral** [comment]
Good point, we currently have 
```https://github.com/google/timesketch/blob/master/test_tools/test_events/sigma_events.jsonl````
In the repo, we briefly discussed it and it seems possible to just expand this file with a little more useful data and then add the file and a "welcome" thing for maybe the dev / test docker instance.

So if you have any good mock data that would be cool, would opt we collect the data in that file.

Does that sound good for you?

**Comment by kovakina** [comment]
Yes, that sounds good
The link you posted is broken btw. But yes, let's collect mock data in the file we already have.

I was thinking a timeline of around 500 events. The events can include things relevant to the tool itself

**Comment by jaegeral** [comment]
Updated the link, and agree, more events would be welcome.

**Comment by jaegeral** [comment]
There has not been any activity lately, so I am closing this issue for now.
