### ISSUE TITLE
[20201015-pre Testing] Celery minimum version in requirements.txt (4.4.0) produces error with module vine

### ISSUE THREAD

**Issue by cshanahan** [google/timesketch#1418]
**TS Version**
Timesketch 20201015-pre installed manually using pip3

**OS Version**
Ubuntu 18.04.5

While testing Timesketch v20201015-pre I encountered an error related to celery and vine. I installed Timesketch manually using pip3. The version of celery from requirements.txt is currently set to v4.4.0 (celery==4.4.0). This version produces errors related to vine (No module named vine). I upgraded celery to v5.0.0 and solved the issue. To account for dependency issues, I also had to upgrade WTForms and markdown, also using pip3.

It is unclear yet if the upgraded packages (celery, vine, WTForms, and markdown) will cause issues with the application.

Happy to help test.

**Comment by berggren** [comment]
Hey, sorry for the late response here. WE have moved to a Docker based installation, and that is the only methid supported. Please take a look at https://timesketch.org/getting-started/install.html

Le us know if you encounter any problems.
