### ISSUE TITLE
timeline.delete() doesn't fail if deletion didn't happen

### ISSUE THREAD

**Issue by rgayon** [google/timesketch#1421]
This won't fail:
```
s = sketch.api.get_sketch(7378)
for l in s.list_timelines():
  l.delete()
```
Even if deletion was not successful. For example if a sketch has a label that prevents timelines from being deleted.
In the web UI, we do get a message "Timelines with label [noarchive] cannot be deleted."

**Comment by kiddinn** [comment]
can you elaborate a bit here...

do you ge back a `True` value and the API client also spits out the error that the timeline has a label that prevents it from being deleted? or are you not even getting that value back?

**Comment by kiddinn** [comment]
Trying to reproduce this, I'm not seeing the behavior you are describing.

![Screenshot 2020-12-17 at 16 59 35](https://user-images.githubusercontent.com/8701947/102518494-4529da00-4089-11eb-8a49-fd4009c52883.png)

**Comment by rgayon** [comment]
closing, this was probably fixed with the latest timeline deletion PRs, or I was just being an idiot
