### ISSUE TITLE
Make the Timeline name column optional

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1428]
In the UI, the columns can be modified by adding more  with customize columns. If that is done multiple times, the screen real estate is quite expensive, it is possible to not display ```Message```column.

But the columns ```Datetime```and ```Timeline_name```are fixed. With ```Datetime```It make sense to navigate, with ```Timeline_Name```it would be kind of handy to not display that column, esp if only one Timeline is selected, it is not adding to much value.

**Comment by jaegeral** [comment]
![gh_1428](https://user-images.githubusercontent.com/741037/96872372-d6a71200-1473-11eb-8294-455a8cd685c4.png)

**Comment by berggren** [comment]
Good point - easy to fix. I'll get it done in the next UI sprint :)

**Comment by jaegeral** [comment]
Maybe we can tackle that in the new UI

**Comment by jaegeral** [comment]
This is done in the new UI 🥇
