### ISSUE TITLE
500 Server Error - sqlalchemy/orm/relationships.py:1388

### ISSUE THREAD

**Issue by cybercuffs** [google/timesketch#144]
Getting 500 server error when trying to create a new sketch or upload a plaso file. Latest version of sqlalchemy is installed 1.0.9. 

    ../site-packages/sqlalchemy/orm/relationships.py:1388: SAWarning: Got None for value of column sketch.id; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
    "(but may in a future release)" % column)
    <ip> - - [13/Nov/2015 18:23:55] "POST /sketch/ HTTP/1.1" 500 -

**Comment by berggren** [comment]
Hi,

Thanks for reaching out. Could you enable DEBUG output in the settings and
give me the whole error you get?

**Comment by berggren** [comment]
No response. Closing out. If the problem still exist, please reach out via timesketch-users mailing list:
https://groups.google.com/forum/#!forum/timesketch-users
