### ISSUE TITLE
Analyzers: Add Chrome extensions to feature Extractor

### ISSUE THREAD

**Issue by kovakina** [google/timesketch#1441]
I have a use case where I need a quick way to get info on all the Chrome extensions installed on a machine that has hundreds of Chrome profiles. My thinking is, it could be a good addition to Feature Extractor analyzer, that can be implemented rather quickly.

**Comment by berggren** [comment]
Good idea! - you should be able to get this from chrome:extension_activity:activity_log, and query for extension_id. You can use the tagger analyzer.

**Comment by kovakina** [comment]
My initial idea was using path regexes on filestat as chrome extension paths are very distinct. If I understand it correctly, that could potentially surface the extensions that were not active within the scope of the analyzed timeline. But why not do both?
