### ISSUE TITLE
Sigma analyzer path rules

### ISSUE THREAD

**Issue by lprat** [google/timesketch#1448]
Hi,

I tried to use sigma analyzer in docker e2e version.
I don't found where you give path of sigma rules: https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/sigma_tagger.py#L31

Thanks for help.
Lionel

**Comment by jaegeral** [comment]
Hi Lionel,

can you explain what exactly you get as an error?

The path is set here:
https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/sigma_tagger.py#L178

**Comment by lprat** [comment]
Hi Alexander,

I import "https://github.com/google/timesketch/blob/master/test_tools/test_events/sigma_events.jsonl" in timesketch.
After, i run sigma analyze and no match. I use default signature "https://github.com/google/timesketch/blob/master/data/sigma/rules/lnx_susp_zenmap.yml".

When i runned "sigma" analyze and i before change (https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/sigma_tagger.py#L178) _RULES_PATH value by '/usr/local/src/timesketch/data/sigma/rules/', it's work...

I think that path '../../../data/sigma/rules/' not work on docker version, may be you are in '/tmp' (https://github.com/google/timesketch/blob/master/docker/e2e/docker-entrypoint.sh#L63)...

Thanks
Lionel

**Comment by jaegeral** [comment]
Ah yes, the e2e paths might be a bit different, afair, @berggren was looking into this recently.

**Comment by berggren** [comment]
Thanks for the heads-up. I'll take another look at this.

**Comment by LowcaPromocji** [comment]
Hey, what's the status? As far as I know, in release version of dockerized timesketch sigma rules path is also wrong.

**Comment by jaegeral** [comment]
Yes, there are some items to be done:
Once this PR is in: https://github.com/google/timesketch/pull/1456 make changes to the Sigma Analyzer:

- [ ] make use of rule folder config in the timesketch.conf
- [ ] make use of sigma config path in the timesketch.conf

**Comment by jaegeral** [comment]
Ok both is now fixed with the newest version of the sigma_tagger.
