### ISSUE TITLE
Analyzer field

### ISSUE THREAD

**Issue by lprat** [google/timesketch#1449]
Hi,

I would like to know if the "url" or "domain" field used in the analyzers (ex: https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/safebrowsing.py#L181) is provided by the parser "feature extraction (https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/feature_extraction.py)? Or / and it must already be present in the timeline file ( jsonl, plaso, ...) imported into Timesketch?

Do you think, it's possible to use feature_extraction to extract all "IP address" from all events ('message', 'xml_strings', ...), or the better to do extract IP address before in jsonl or with plaso ( but I don't think it can do that without dev)?

In feature_extraction, if the "store_as" field exists, the value is overwritten? And if the field message contains multiple IPs (for example extract IP), what does it do (create list [])?

Thank,
Lionel

**Comment by berggren** [comment]
Hi @lprat 

> Hi,
> 
> I would like to know if the "url" or "domain" field used in the analyzers (ex: https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/safebrowsing.py#L181) is provided by the parser "feature extraction (https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/feature_extraction.py)? Or / and it must already be present in the timeline file ( jsonl, plaso, ...) imported into Timesketch?

the attribute "url" comes from Plaso, and the "domain" attribute comes from the domain analyzer:
https://github.com/google/timesketch/blob/master/timesketch/lib/analyzers/domain.py

That being said, the safebrwosing analyzer shoud probably mark "domain" as a dependency.

> 
> Do you think, it's possible to use feature_extraction to extract all "IP address" from all events ('message', 'xml_strings', ...), or the better to do extract IP address before in jsonl or with plaso ( but I don't think it can do that without dev)?

You can use the feature extractor for this. It takes a regexp and an attribute and tries to extract it from there.

> 
> In feature_extraction, if the "store_as" field exists, the value is overwritten? And if the field message contains multiple IPs (for example extract IP), what does it do (create list [])?

The attribute will be replaced. It will not store them as a list, but as a string of the matches.

> 
> Thank,
> Lionel

**Comment by kiddinn** [comment]
does this answer all of your questions, can we close this now? Maybe create a FR issue to add some IP extraction in the feature analyzer? We would be happy to take contributions

**Comment by lprat** [comment]
Thanks for your responses! 
I will try to PR for IP extraction.
Thanks
Lionel
