### ISSUE TITLE
Plaso Upload seems broken

### ISSUE THREAD

**Issue by pettai** [google/timesketch#145]
I recently tried to enable PLASO_UPLOAD according to the wiki article
https://github.com/google/timesketch/wiki/UserGuidePlasoUpload

But after selecting a file to upload, typing in a name, and finally pushing the "Upload" button, the WebUI says "Loading..." and just a second later, it says "Error".
And without any helpful output in the log(s) AFAICS...

**Comment by Onager** [comment]
How big is your Plaso file? You may need to increase the worker timeout.

**Comment by berggren** [comment]
@pettai Can you enable DEBUG in settings, then you should be able to see the error in the server logs.

**Comment by pettai** [comment]
@berggren I had, but the server log says nothing of interest...
127.0.0.1 - - [23/Nov/2015 23:10:29] "GET /api/v1/tasks/ HTTP/1.0" 200 -
127.0.0.1 - - [23/Nov/2015 23:10:39] "GET /api/v1/tasks/ HTTP/1.0" 200 -
127.0.0.1 - - [23/Nov/2015 23:10:49] "GET /api/v1/tasks/ HTTP/1.0" 200 -

I think the problem could be that timesketch doesn't find plaso/psort?
PLASO_DATA_LOCATION is undocumented, Could it be that it's needed to be set?

**Comment by pettai** [comment]
Shame on me... 
First problem, my local proxy cut off my upload...
Second problem, the Upload function seems to only accept files named "*something.plaso*", but the message hinting about this only appeared then I tried to upload a tiny plaso file...

So, after fixing the first local issue and renaming all plaso files, it seems to work as expected.
Visible documentation/hint about the second issue would be nice to have in the Upload wiki-page or elsewhere...

(btw. Why do I always have to give the upload a name? Importing via psort output to timesketch defaults to system name, wouldn't that be a sane default if no name was given?)

**Comment by berggren** [comment]
Yeah, fixing documentation for this is wip, but I'll bump the prio on that
for Q1.

The upload feature is still experimental, and there is more work to be
done. I agree that it is not very intuitive with the way validation works
in the form. Can you open a bug for this?

**Comment by pettai** [comment]
https://github.com/google/timesketch/issues/149
Ok?
