### ISSUE TITLE
Variable times for context searches

### ISSUE THREAD

**Issue by andysnowball** [google/timesketch#1470]
In the old UI, it was possible to set a time in seconds for context searches (defaulted to 300s). This was a really useful feature to either expand or reduce the search based on the number of events returned initially. In the new UI, there is no option to change this time, although it looks like there were plans to based on a comment in `timesketch/frontend/src/views/SketchExplore.vue`:

```
// TODO: Make this selectable in the UI
const contextTime = 300
const numContextEvents = 500
```

Having this feature back would be super useful! It would also be good to have a variable number of context events, which appears to be fixed at 500. Thank you for all your hard work on this project.

**Comment by Eunjnnn** [comment]
if it still open can i work on it??

**Comment by Prathamdas3** [comment]
can i work on this issue??

**Comment by berggren** [comment]
We have started the work on this feature. We wanted to rework the experience and take advantage of some new UI elements. This is now work in progress and there is a PR soon to be reviewed.

This is a somewhat involved feature so I opt that folks who have shown interest get started with something a bit lighter as a starter. Take a look at issues tagged with "Good first issue"

**Comment by berggren** [comment]
This has been implemented
