### ISSUE TITLE
Upload enhancements

### ISSUE THREAD

**Issue by pettai** [google/timesketch#149]
Then importing plaso timelines with psort.py, a hostname is usually extracted and giving name to the timeline in timesketch.
Could the Plaso Upload function do the same (if no name is given)? And fallback to generate a unique name (for instance from the uploaded filename/date/time?) if no name could be extracted.
Having to mandatory name is manually causes headache...

And why must the plaso upload file be named .plaso ?
(And if the uploaded file is big, the error message that hints about this wasn't shown...)

**Comment by berggren** [comment]
The idea is to move the upload (rename import) button to the sketch view. This is more intuitive and is what most people expect.

**Comment by berggren** [comment]
The upload have been moved, and a cahnge is pending for defaulting to the filename as timeline name.
