### ISSUE TITLE
Make filter additions "clickable" from the UI 

### ISSUE THREAD

**Issue by pettai** [google/timesketch#152]
Then you explore and pick an event and you expand it (click on "Details"), it would be very powerful to be able to just click on some data, for instance "inode | 205283" and that would be transfered into filter input as "inode:205283" or "AND inode:205283" (or perhaps even "OR inode:205283") if something already was is in filter freetext field ...)

~~As a bonus: the same would also be nice to have for the "Time range", eg. click on the date/time in the "heat map" / "histogram" view, and it would automatically add the same date/time into the "Time range" filter.~~

**Comment by pettai** [comment]
> As a bonus: the same would also be nice to have for the "Time range", eg. click on the date/time in the "heat map" / "histogram" view, and it would automatically add the same date/time into the "Time range" filter.

This has already been implemented

**Comment by berggren** [comment]
This is finally done in the new UI.
