### ISSUE TITLE
[SIGMA] Status of rule coverage

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1532]
This issue is meant to be a tracker which folders from https://github.com/Neo23x0/sigma so far have been tested and verified mappings in Timesketch.

The issue with "unmapped" rules is that users might expect to see results, but because of the lack of mapping, they are not highlighted.

- [x] application (should work natively)
- [X] apt
- [ ] cloud
- [ ] compliance
- [ ] generic
- [ ] linux
  - [ ] auditd
  - [ ] modsecurity
- [ ] network
- [ ] proxy
- [ ] web
- [ ] windows
    - [x] builtin
    - [ ] driver_load (no sample data available)
    - [ ] file_event
    - [ ] image_load
    - [ ] malware
    - [ ] network_connection
    - [ ] other
    - [ ] powershell
    - [ ] process_access
    - [ ] process_creation
    - [ ] registry_event
    - [ ] sysmon

If someone wants to help out, feel free to do.

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/pull/1529 did the windows/builtin

**Comment by SpongeBobCodePants** [comment]
Also noting the following resources for Sigma rules in Timesketch:

- [https://github.com/google/timesketch/blob/master/data/sigma_blocklist.csv](url)
- [https://github.com/google/timesketch/blob/master/test_tools/sigma_verify_rules.py](url)

**Comment by jaegeral** [comment]
Gonna close this issue, the status of the rules is now tracked int he blocklist file. For individual requests, file new bugs.
