### ISSUE TITLE
Check for proper permission on timeline 

### ISSUE THREAD

**Issue by rgayon** [google/timesketch#1543]
In api/v1/resources/timeline.py, remove_timeline_label() checks that the user has permission "delete" on the sketch this timeline is added to:
https://github.com/google/timesketch/blob/b5776d5da1586ea6824e89fd514418a35f4d1908/timesketch/api/v1/resources/timeline.py#L270

This mean a user with "write" pemission on sketch (but not "delete") can add timelines to a sketch  (they need 'write' permissions on the sketch), then add labels to it (currently, no permission check), but not remove the label (which, in turn, might prevent the timeline from being deleted further, if said label is 'noarchive' for example).

**Comment by kiddinn** [comment]
The current behavior is 

a) if you add a timeline to a sketch the labels of the sketch are `transferred` over to the new timeline
b) if you want to add a label to a timeline that's already there you can add it only if you've got write permissions, but you can't remove a label unless you've got delete.

I agree that this is perhaps not ideal, and we should fix it. the question is how...

1. Have write permissions be sufficient
2. Check who added the label, and allow anyone with `write` permissions to remove their own labels, but require `delete` to remove labels added by other users.
3. Reconsider how labels are propagated to newly added timelines. ATM only at the timeline creation, that is if I add a label to a sketch it does not get propagated to the timelines that are already there (should be changed), (sketch.py line 210).... and then the user should also be transferred to the new label of the timeline.

The question remains mostly, should everyone with `write` permissions be allowed to remove/add any labels, or should they be limited to the labels they themselves added (and maybe system user as well, to remove such labels) but be prevented from deleting labels that were added by other users unless they've got `delete` permissions on the sketch.
