### ISSUE TITLE
API addition: Analyzer_run option skip already used analyzers on a sketch.

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1547]
If you have a Sketch with multiple timelines, it can be hard to track which analyzer has already been run on it.

Thus the idea is to have an option in the sketch.analyzer_run() method:
```
bool skip_already_ran_analyzer
```

That by default is set to False, but if set to True it would check something like:
```
status = sketch.get_analyzer_status()
if (complete['timeline_id'] == current_id) and (complete['analyzer'] == desired_analyzer) and complete['status'] == 'DONE':
     logger.debug('We already did that in the past')
     continue
```

This would save CPU cycles and reduce those checks to be done on client side.

**Comment by kiddinn** [comment]
this has already been done, by default the analyzer is not run unless you provide the `ignore_previous` flag
