### ISSUE TITLE
Upcoming licensing changes to Elasticsearch and Kibana

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1560]
In a recent post: https://www.elastic.co/de/blog/licensing-change

Elastic announced to change its licence. This Github issue is to track discussion around how it (might) affect how Timesketch uses and interacts with ElasticSearch.

**Comment by joachimmetz** [comment]
Note that this affects ES 7.11 and beyond

**Comment by jaegeral** [comment]
We switched to OpenSearch in the meantime. Closing this one out
