### ISSUE TITLE
Timelines can't be enabled or disabled individually

### ISSUE THREAD

**Issue by SpongeBobCodePants** [google/timesketch#1570]
**Describe the bug**
When I am in the "Explore" view, the timelines show as "badges" in different colors as expected. However, the number of events listed next to each name is the same. I've calculated it, and what I believe it is displaying is the total number of events of all timelines combined. Also, I cannot enable/disable the timelines individually. I can enable all or disable all. When I click the badge of the first timeline I uploaded it enables or disables everything. Clicking on the badges for the other timelines does nothing.

**To Reproduce**
1) Last night I set up a new VM and followed the instructions on the Timesketch Github page.
2) I created a .plaso file of my drive image using log2timeline.
3) I uploaded the .plaso file in Timesketch by creating a new investigation and then "Upload timeline".

**Expected behavior**
My experience using demo.timesketch.org is that timelines can be enabled/disabled in any combination when searching.

**Screenshots**
Attached (with sensitive info covered). If I click the number of events on any badge but the first one, nothing happens. If I click the number of events on the first badge, every timeline is disabled.
![Screenshot 2021-01-30 123147](https://user-images.githubusercontent.com/70819570/106363565-3c1e6080-62f7-11eb-95d6-3bbc3c5e9b09.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 84

**Additional context**
Everything else works as expected so far. Thank you!

**Comment by kiddinn** [comment]
Was this done with the latest checked in code as of yesterday?

If so, then this is expected, we are revamping how data is ingested, the first phase got checked in yesterday, which involved many backend changes. The UI has not yet been updated to work with the new method, thus filtering based on individual timelines, counts, etc does not work correctly yet. Expect those changes to come later this week. Furthermore changes need to be made into psort to make sure log2timeline data gets correctly ingested, which atm is missing a key part into making this new way work correctly.

**Comment by kiddinn** [comment]
See #1567

**Comment by berggren** [comment]
Hi @SpongeBobCodePants as @kiddinn was saying: We are in the middle of changing how we store data (in order to scale better). To keep backwards compatibility we need to push changes in phases and phase one was done with #1565. We are now working on the UI support but in the mean time the main branch will be a bit unstable. Expect fixes for this in the coming week. Sorry for the inconvenience!

**Comment by SpongeBobCodePants** [comment]
I set up my VM late evening on 01/29 (EST). It's funny, I saw #1567 when I was looking for anyone with a similar issue. I remember thinking that sounds like a lot of work, lol. Anyway, no worries at all. Pretty sure I can work around it with some creative filters for now. Thanks for your help!
