### ISSUE TITLE
Update Upgrading documentation

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1607]
The documentation for Upgrading a Timesketch deployment is out of date.

https://github.com/google/timesketch/blob/master/docs/Upgrading.md

**Comment by rajpratyush** [comment]
Hi @berggren I would like to work on this issue. Can I?

**Comment by kiddinn** [comment]
I assigned it to you @rajpratyush ,

**Comment by rajpratyush** [comment]
@kiddinn just wanna know one thing do I have to figure out what's the existing way to upgrade the timesketch deployment or are there any specific laid out instruction which I need to just update.

**Comment by jaegeral** [comment]
> @kiddinn just wanna know one thing do I have to figure out what's the existing way to upgrade the timesketch deployment or are there any specific laid out instruction which I need to just update.

I think the best way would be to have an Timesketch instance and then try to upgrade based on the current documentation, see if it works or you find something missing.

**Comment by rajpratyush** [comment]
Okay i will start workong on it then

**Comment by jaegeral** [comment]
As far as I am concerned, this is now updated in the meantime, so I will close it, if there are specific things missing or broken in the update / upgrade documentation, we should track them in dedicated issues instead of "upgrade docu needs update".
