### ISSUE TITLE
Analyzer history associated with wrong timeline

### ISSUE THREAD

**Issue by SpongeBobCodePants** [google/timesketch#1619]
**Describe the bug**
When I run an Analyzer on one timeline, the progress status (and history) indicate the Analyzer was run on a different timeline. The issue seems to only affect the status window and history. As far as I can tell, the analyzer is actually running on the correct timeline but reported incorrectly.

**To Reproduce**
My test case has six timelines. These are six different .plaso files from six different hosts that were uploaded into Timesketch using the web interface. When I go to the Analyzer tab, select any Analyzer (e.g., phishy domains), and select a timeline (let's say "timeline 6"), and run the Analyzer...the status indicator states the Analyzer is running on "timeline 1". Once the Analyzer is complete, the history is also associated with the incorrect timeline. However, timeline 6 does have tags for "phishy domains", so I believe this is only a cosmetic issue.

**Expected behavior**
I expect that Analyzer status and history to be associated with the timeline I ran the Analyzer against.

**Screenshots**
The screenshot shows the results of when I ran the Analyzer against, DRIVE_2, DRIVE_3, AND DRIVE_4. The analyzer was not run against DRIVE_1. The differing results seem to indicate the analyzer was run against the correct timelines, though.
![timesketch](https://user-images.githubusercontent.com/70819570/108085383-45236780-7043-11eb-8df8-e60d7b216497.png)

**Desktop (please complete the following information):**
 Ubuntu 20.04
 Firefox 85.0.1
 *I installed this Timesketch instance on February 11, 2021 using the docker instructions. I understand there are some updates happening, so this may get fixed in the next release. I just wanted to make sure it's on the radar.

**Comment by berggren** [comment]
Hey @SpongeBobCodePants thanks for your detailed bug report. This is indeed a bug in the presentation only in the UI. Good news, we fixed it yesterday :)

See #1613 for details.

**Comment by berggren** [comment]
If you pull the latest docker image this will be fixed.

**Comment by berggren** [comment]
Closing this bug out, let us know if you have any other questions.

**Comment by SpongeBobCodePants** [comment]
Thank you. Is this the correct way to update?
`cd /opt/timesketch
sudo docker-compose down
sudo docker-compose pull timesketch-web
sudo docker-compose pull timesketch-worker
sudo docker-compose pull elasticsearch
sudo docker-compose pull postgres
sudo docker-compose pull redis
sudo docker-compose pull nginx
sudo docker-compose up -d`

**Comment by berggren** [comment]
yeah, that correct. You can do it with less downtime as well:

```
cd /opt/timesketch
sudo docker-compose pull
sudo docker-compose down
sudo docker-compose up -d
```

**Comment by SpongeBobCodePants** [comment]
Perfect. Thank you.
