### ISSUE TITLE
Re-introduce search templates

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1620]
This will require few changes:

- [x] Port over the search templates to the new UI
- [x] Add support into the search object in the API client
- [ ] Add ability to save searches as templates in UI
- [x] Add ability to save searches as templates in API client (add a parameter to the saved search object to save as a template)
- [ ] Add ability to load YAML/text file in `tsctl` to upload saved templates
- [ ] Add ability to export search templates into a YAML/text file in UI
- [ ] Add ability to export search templates into a YAML/text file in API client (`ts_client.export_search_templates()` or something like that)

**Comment by kiddinn** [comment]
#1643 will add the support into the API client

**Comment by berggren** [comment]
This has been implemented
