### ISSUE TITLE
"Top x values" for all available fields / columns

### ISSUE THREAD

**Issue by andersnese** [google/timesketch#1629]
**Is your feature request related to a problem? Please describe.**
It is challenging to find output from analyzers without knowing the naming convection used when the analyzer is tagging relevant events. It also an easier to quickly get an an overview with events in a timeline if you can easily show top X values of a given column / field. 

**Describe the solution you'd like**
Provide a list of unique tags + number of occurrences of a given tag. 
A more generic solution / feature would be to provide the possibility to view "Top x values" for all available fields. Kibana provides this way of exploring an index.

**Comment by jaegeral** [comment]
> Provide a list of unique tags + number of occurrences of a given tag.
This is now implemented in the new Search field but might need more exposure.

**Comment by NightAcrobat777** [comment]
It looks like this has been solved, I see the unique tags and their occurrences displayed on Timesketch. This issue should be closed.
