### ISSUE TITLE
"Customize Columns" seems broken

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#1630]
**Describe the bug**
It is possible to select columns via the "Customize Columns" button, and the correct column gets added, but it is empty.

**Screenshots**
![Greendale](https://user-images.githubusercontent.com/4984680/108550593-9fbafe80-72a3-11eb-8421-ab94ebae69a0.png)

**Comment by kiddinn** [comment]
I noticed this as well, but refreshing it makes it appear, or adding another one, something about not loading it up, @berggren can you look into this?

**Comment by berggren** [comment]
Ack, will take a look.

**Comment by itsmvd** [comment]
Taking a look. UI is not sending the most recent fields to the API.

**Comment by jaegeral** [comment]
@itsmvd any update from your side? is this still a thing?

**Comment by itsmvd** [comment]
Yes this is still a bug. I synced up on this with @berggren some time ago and he was going to look into this further (bug seemed rather odd). Assigning to Johan.

**Comment by berggren** [comment]
Sorry for the delay on this one. I can reproduce and will see if we can find a fix asap.

**Comment by jaegeral** [comment]
This is old UI, in new UI this is fine. Closing it out
