### ISSUE TITLE
User does not have write access controls on sketch with shared public access

### ISSUE THREAD

**Issue by KhurumAzam** [google/timesketch#1648]
**Describe the bug**
Our team discovered the bug when providing access to the team using the share "public - All users of the system can access this sketch". 

We'd identified that the team cannot make comments within the explore tab, which outputted "User does not have write access controls on sketch."

We'd fixed the issue with selecting "private - only you and selected users/group can access this sketch" and selected the user to access the sketch and fixed the access controls in the sketch to make comments.

**To Reproduce**
1. Click Share and select "public - All users of the system can access this sketch"
2. Login using another user and access the sketch with public access
3.  Go to the explore tab
4.  Click on a message
5. Type a message in the comment and post
6. Returns "User does not have write access controls on sketch"
7. Login back as owner of sketch and go to share tab
8. Select as "private - only you and selected users/group can access this sketch" and choose the access for each user (ideally everyone)
9. Login back as another user
10. Go to sketch with private access
11. Go to Explore
12. Click on any message and type a command and post

**Expected behavior**
User is able to post a comment within the explore tab when owner provides public access to the sketch.

It should not return a "User does not have write access controls on sketch".

**Screenshots**

![image](https://user-images.githubusercontent.com/76566157/109312361-f6c95200-7814-11eb-95fe-1fbb2c7d8cfb.png)

![image](https://user-images.githubusercontent.com/76566157/109332759-90502e00-782c-11eb-90e9-91ed0f0da850.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 
 - Browser: Chrome

**Comment by kiddinn** [comment]
I think this issue could be in more than one place.... the question is also how to interpret `public`, whether that means a read or write access.

there are several functions that are currently only available when the user has explicit write access to a sketch, which this would affect.... the `public` access so far has been a read-only access.

**Comment by kiddinn** [comment]
what we've got now in the check permissions are:
```
        public_ace = self.is_public$                                                                                                                                                                             
        if public_ace and permission == 'read':$                                                                                                                                                                 
            return public_ace$     
```

That is if the sketch is marked as public we grant `read` access to that sketch, not write access. And many operations are dependent on write access, adding a comment being one, since that is modifying the sketch, hence the need to request write access.

The question is mainly whether we need to expand a bit on the public access, that is to define better what public means, to give the owner a choice of granting public `read` or `write` access.

**Comment by kiddinn** [comment]
That is we can add a different function, that is have two sets of public permission, one that grants only read, and another one that grants read/write permissions.

**Comment by kiddinn** [comment]
OK, so after looking more closely at this and discussing it with @berggren we decided that we want to keep the functionality for public access the same, that is to deem this WAI.

However, this is not very clear in the UI, so we'll make some UI changes to make it clear that public access only means read access, and then to make some UI changes to hide options that are not possible for you, with only read access.

**Comment by KhurumAzam** [comment]
@kiddinn Thanks! I've let my team know of this and looking for future changes in the UI some time :)
