### ISSUE TITLE
API-Client:run_analyzer unexpected keyword argument 'ignore_previous'

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1654]
Not sure if I am using it wrong, but the following is not how I expected the client to work:

On a fresh sketch running the following command

```sketch.run_analyzer(timeline_name='sigma_events.jsonl', analyzer_name='sigma')```

If I re-run, I get (correctly):
```ERROR:timesketch_api.timeline:Analyzer sigma has already been run on the timeline, use "ignore_previous=True" to overwrite``` 

If I add:
```sketch.run_analyzer(timeline_name='sigma_events.jsonl', analyzer_name='sigma', ignore_previous=True)``` 

I get 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-629ac8a66722> in <module>
----> 1 result = sketch.run_analyzer(timeline_name='sigma_events.jsonl', analyzer_name='sigma', ignore_previous=True)

TypeError: run_analyzer() got an unexpected keyword argument 'ignore_previous'```

**Comment by kiddinn** [comment]
`sketch.run_analyzer` should give a warning that it's about to be deprecated, if not I'll add that in.

The right way to run the analyzer is to use the timeline object and use the `timeline.run_analyzer` , which accepts the `ignore_previous` parameter.

**Comment by kiddinn** [comment]
ok, the deprecation warnings have been added... and for the future, use the `timeline.run_analyzer` or `timeline.run_analyzers` function
