### ISSUE TITLE
Support for Elasticsearch 2.x

### ISSUE THREAD

**Issue by berggren** [google/timesketch#166]
Timesketch is not compatible with Elasticsearch 2.x. We need to fix this.

**Comment by marcurdy** [comment]
Thanks for the reply!

**Comment by maurermj08** [comment]
The mapping has changed in Elasticsearch 2.x. The mapping can be fixed in the Plaso output file timesketch_out.py by changing:

`    _document_mapping = {
        self._doc_type: {
            u'_timestamp': {
                u'enabled': True,
                u'path': u'datetime',
                u'format': u'date_time_no_millis'
            },
            u'properties': {u'timesketch_label': {u'type': u'nested'}}
        }
    }`

to:

`    _document_mapping = {
        self._doc_type: {
            u'properties': {
                u'datetime': {
                    u'type': u'date',
                    u'format': u'date_time_no_millis'
                },
            u'timesketch_label': {u'type': u'nested'}
            }
        }
    }
`

I can successfully import a timeline with this new mapping. However, there are likely other issues that will appear as a result of upgrading to Elasticsearch 2.x.

**Comment by berggren** [comment]
@maurermj08 thanks!

I have done some testing and we can actually skip the _timestamp mapping all together. That will make us ES 2.x compatible. Old indexes will still work. I have a pull request for this ready for fixing in Timesketch and will send a fix for the Plaso output plugin.

If you are using ES 2.x you need to update elasticsearch.yml and add:
script.inline: true
script.indexed: true

**Comment by marcurdy** [comment]
I pulled down a git clone to get a few extra fixes (tagging) and updated
elastic.py by hand.  Confirmed works put into elastic.py.

    mapping = {
        self._doc_type: {
                u'properties': {
                u'datetime': {
                u'type': u'date',
                u'format': u'date_time_no_millis'},
        }}
    }

Thanks Johan!

**Comment by berggren** [comment]
ES mapping that brakes 2.x support is now removed from Timesketch. Plaso still needs to remove the mapping on its output module though.

Tracking Plaso bug in: https://github.com/log2timeline/plaso/issues/607

**Comment by marcurdy** [comment]
Thanks
