### ISSUE TITLE
unable to import plaso file using timesketch_importer

### ISSUE THREAD

**Issue by jacurutu1984** [google/timesketch#1677]
**Describe the bug**
I can import plaso file in timesketch using the UI but when i try to do it with timesketch_importer i got the message "RuntimeError: Error uploading data chunk: 0/10. Status code: 400 - BAD REQUEST {"message": "Unable to write data with error: [Errno 21] Is a directory: '/usr/share/timesketch/upload/'."}"
**To Reproduce**
timesketch_importer --sketch_id 1 --host http://plaso-System-Product-Name upload/64Bits/$file

Expected behavior
I expected my timeline to import into timesketch 

Screenshots

Desktop (please complete the following information):

    OS: Ubuntu 20.04.2 LTS
    Browser Firefox
    Version 85.0
plaso - log2timeline version 20210213
docker-compose version 1.25.0, build unknown

Additional context
The directory exist in the docker :  docker-compose.yml have "./upload:/usr/share/timesketch/upload/"
 101713614 4,0K drwxr-xr-x  7 plaso root  4,0K Mär 10 20:25 upload

**Comment by kiddinn** [comment]
hi

what version do you have of Timesketch? That is are you using the latest release, or tracking from head?

This got fixed in: https://github.com/google/timesketch/pull/1625

Did that not work for you? Can you try updating your TS installation and see if it works now?

**Comment by jacurutu1984** [comment]
thanks for the help. I'm not familiar with docker. I do "docker-compose pull" for upgrading (because your doc is not up to date https://github.com/google/timesketch/blob/master/docs/Upgrading.md). Is that correct? 
How can i know my timesketch version?
The importer show me : 
API Client Version: 20210205
Importer Client Version: 20210215

Now when try to upload a file with timesketch_importer, i have another error message :"RuntimeError: Error uploading data chunk: 6/7. Status code: 400 - BAD REQUEST {"message": "Unable to save file correctly, inconsistent file size (90738688 but should have been 719884288)"}"

**Comment by kiddinn** [comment]
the upgrade documentation has been updated now, can you update and test again?

**Comment by kiddinn** [comment]
but also update the importer client and the API client using pip then, since the importer client now does retries on failed chunks.

**Comment by jacurutu1984** [comment]
Thanks a lot, i just update as you said and now it's working. 

Sorry for wasting your time

**Comment by kiddinn** [comment]
no problem, glad it works now
