### ISSUE TITLE
Document CSV import feature

### ISSUE THREAD

**Issue by berggren** [google/timesketch#168]
To import a CSV file it need to have a minimal set of column namns:
- message
- timestamp
- datetime
- timestamp_desc

Document this in the wiki.

**Comment by hiddenillusion** [comment]
It'd also be useful to add info. related to [`tsctl`](https://github.com/google/timesketch/blob/84e5ca617d125e522ad99eced73008d6c8809b4d/tsctl#L348) syntax as found within the [UserGuideTimelineFromJsonFile](https://github.com/google/timesketch/wiki/UserGuideTimelineFromJsonFile) page.

e.g.:
`$ tsctl csv2ts --name my_timeline --file timeline.csv`

**Comment by berggren** [comment]
This is being tracked in #176
