### ISSUE TITLE
API Client: Move RC and token file to a folder to be able to use volume mounts in notebook container

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1682]
**Is your feature request related to a problem? Please describe.**
One of the issues with the notebook container is that credentials are stored locally inside the container, which then will get removed once the container is upgraded.

In order to have the credentials to be persistent then they need to moved away from ~/.FILE to ~/.FOLDER/FILE

Then it would be possible to map up that folder as a volume in the TS container and not needing to copy credentials over for the notebook container.

(also need to make sure permissions work)

**Comment by berggren** [comment]
Closing this for now. The notebook is looking for a new owner. We can reopen this in the future if needed.
