### ISSUE TITLE
In Explore tab, alphabetical order in saved search queries list

### ISSUE THREAD

**Issue by n0tmyproblem** [google/timesketch#1684]
**Is your feature request related to a problem? Please describe.**
When there are more than 10 saved queries, it is difficult to easily identify the one you are interested in. 

**Describe the solution you'd like**
Default sort the list of views alphabetically asc.

**Describe alternatives you've considered**
Any.

**Additional context**
![image](https://user-images.githubusercontent.com/80429728/110922837-7c262980-8320-11eb-8aac-afaa0563bb57.png)
Color explanation:
- Green: the first letter of each row, in no easily identifiable order.

**Comment by kiddinn** [comment]
this can be done in the resource section, I'll add this in
