### ISSUE TITLE
Suggest indenting the tips on the required fields for CSV/JSON

### ISSUE THREAD

**Issue by honorthecode** [google/timesketch#1693]
The https://timesketch.org/learn/create-timeline-from-json-csv/ documentation listed the required fields for CSV/JSON in a bulleted list but the list has no indentation/levels to distinguish between the required fields and the tips:
-     message
-     String with an informative message of the event
-     datetime
-     ISO8601 format
-     Ex: 2015-07-24T19:01:01+00:00
-     timestamp_desc
-     String explaining what type of timestamp it is. E.g file created
-     Ex: "Time created"

Suggesting adding indentation to avoid confusion:
-     message
       -     String with an informative message of the event
-     datetime
       -     ISO8601 format
       -     Ex: 2015-07-24T19:01:01+00:00
-     timestamp_desc
       -     String explaining what type of timestamp it is. E.g file created
       -     Ex: "Time created"

**Comment by berggren** [comment]
Thanks, this looks to be an issue of how the markdown is rendered on the site. GH markdown indent just fine. I'll take a look at reformat this.
