### ISSUE TITLE
Investigate Removing labels

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1694]
Now that we only allow an index to be used in a single sketch we can consider removing the labels, and only use the tag attribute.

Historically the labels was used as a per-sketch scoped label, i.e. a label in sketch-1 was not visible in sketch-2 if the same index was used.

**Comment by jaegeral** [comment]
I assume this will be a rather large code change that affects the whole Timesketch stack, so I added a lot of labels and moved it to Next year, but we can always do it earlier.
