### ISSUE TITLE
Time filter content not parsed correctly when updating

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#1699]
**Describe the bug**
When editing a time filter, the existing date isn't parsed correctly. The original date has to be typed again

**To Reproduce**
1. Go to the explore view with a loaded timeline
2. Add a time filter with a + / - selector
3. Save time filter
4. Click on existing time filter to update
5. Watch as the date is not parsed correctly and "overflows" into the + / - fields

**Expected behavior**
I expect the and "delta" to be exactly as specified

**Screenshots**
![image](https://user-images.githubusercontent.com/1257972/111775502-22d67100-88b1-11eb-8241-81cfd96141a1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 89.0.4389.82

**Comment by jaegeral** [comment]
@binglot could you have a look this

**Comment by binglot** [comment]
Hey Alex! Thanks for flagging this up, I resolved the bug a month ago or so, let me link it up to this bug.
