### ISSUE TITLE
Protocol error when creating elasticsearch index 

### ISSUE THREAD

**Issue by asmirazali** [google/timesketch#1703]
Here is my setup: 
On docker:
timesketch-worker
timesketch-web
nginx (configured to use my own SSL cert)
redis

on DBaaS:
Elasticsearch (Has it's own certificate which has been imported into /etc/ssl/certs)
Postgres (Has it's own certificate which has been imported into /etc/ssl/certs)

So far, setup is fine. Able to create a sketch, and moved to other pages. Previously I had SSL errors connecting to ES, but that has been fixed now. 

Here's my timesketch.conf
--------------------------------
ELASTIC_HOST = 'xxxx.private.databases.appdomain.cloud'
ELASTIC_PORT = 'xxx'
ELASTIC_USER = 'admin'
ELASTIC_PASSWORD = 'xxxx'
ELASTIC_SSL = '/etc/ssl/certs/c92a5016-d56a-11e9-baa1-56da0ec946bd'
ELASTIC_VERIFY_CERTS = True
----------------------

Problem comes when I tried to upload via web or importer. 
root@us-vpc-dallas-timesketch-uploader:~# timesketch_importer xxxx
[2021-03-21 16:10:03,157] timesketch_importer.importer_frontend/INFO Creating a client.
[2021-03-21 16:10:03,689] timesketch_importer.importer_frontend/INFO Client created.
[2021-03-21 16:10:03,689] timesketch_importer.importer_frontend/INFO Saving TS config.
[2021-03-21 16:10:03,690] timesketch_importer.importer_frontend/INFO Uploading file.
[2021-03-21 16:10:03,694] timesketch_importer.importer_frontend/INFO About to upload file.
[2021-03-21 16:10:27,871] timesketch_importer.importer_frontend/INFO File upload completed.
Checking file upload status: ..[FAIL]
Unable to index timeline, reason: 2021-03-21 16:10:29,732 [INFO] (MainProcess) PID:24 <data_location> Determined data location: /usr/share/plaso
2021-03-21 16:10:30,249 [INFO] (MainProcess) PID:24 <elastic_ts> Timeline identifier: 11
**Unable to create Elasticsearch index with error: ConnectionError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))**

Which app is creating the ES Index? This is because of ELASTIC_SSL error. I think it is not being passed to the app trying to create the ES index.

**Comment by asmirazali** [comment]
Seems like the command for psort is short of 'elastic_username", password as well. 

Command '['psort.py', '-o', 'elastic_ts', '/data/783f032d88b943fe854ba9945ddef9ab', '--server', 'xxxx.private.databases.appdomain.cloud', '--port', 'xxx', '--status_view', 'none', '--index_name', 'c4b4e49b00f5494180613a1d13a8dcb9', '--elastic_mappings', '/etc/timesketch/plaso.mappings', '--timeline_identifier', '12']'

It seems like the argument elastic_user is missing.

**Comment by asmirazali** [comment]
I don't know whether this is relevant, I have looked at the tasks.py and it is missing  ELASTIC_USER, ELASTIC_PASSWORD, ELASTIC_SSL. Can we add them in the tasks.py? My ES is connected using username, password and SSL as well. 

elastic_server = current_app.config.get('ELASTIC_HOST')
    if not elastic_server:
        raise RuntimeError(
            'Unable to connect to Elastic, no server set, unable to '
            'process plaso file.')
    elastic_port = current_app.config.get('ELASTIC_PORT')
    if not elastic_port:
        raise RuntimeError(
            'Unable to connect to Elastic, no port set, unable to '
            'process plaso file.')
    es = ElasticsearchDataStore(
        host=elastic_server, port=elastic_port)

**Comment by kiddinn** [comment]
so if you look at the 
```
es = ElasticDataStore(....)
```

Command in the tasks.py it actually takes care of user/pass/ssl information there. Inisde the lib/datastores/elastic.py that is read in, so not needed in the tasks.

But I added the SSL option as well to psort.

**Comment by asmirazali** [comment]
Ah right. Just saw it. So I guess it's just the psort command
