### ISSUE TITLE
Timesketch doesn't respect elasticsearch auth config

### ISSUE THREAD

**Issue by Kamforka** [google/timesketch#1709]
**Describe the bug**
The elasticsearch authentication related configuration values are being ignored and therefore the queries result in an `AuthenticationException`.

**To Reproduce**
1. Specify the elasticsearch auth fields in `timesketch.conf`: `ELASTIC_USER`, `ELASTIC_PASSWORD`
2. Try to create a new sketch or check an existing one, an `Internal Server Error` error message will pop up on the screen. Then in the logs the following exception will be reported: 
```bash
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'missing authentication credentials for REST request [/_search?size=0]')
```

**Expected behavior**
Expected a successful authentication against the elasticsearch instance.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 20210224

**Additional context**
I've tested the elasticsearch side with a kibana instance. The security plugin that is being utilized is `xpack`.

```
  elasticsearch:
    environment:
      - TAKE_FILE_OWNERSHIP=1
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=<my-es-password>
```

**Comment by kiddinn** [comment]
is this an issue with uploading files or just making queries in general?

**Comment by Kamforka** [comment]
I've checked the related code in `timesketc/lib/datastores/elastic.py` and in the `ElasticsearchDataStore.__init__()` method I found the below snippet:

```python
        self.user = current_app.config.get('ELASTIC_USER', 'user')
        self.password = current_app.config.get('ELASTIC_PASSWORD', 'pass')
        self.ssl = current_app.config.get('ELASTIC_SSL', False)
        self.verify = current_app.config.get('ELASTIC_VERIFY_CERTS', True)

        if self.ssl:
            self.client = Elasticsearch([{'host': host, 'port': port}],
                                        http_auth=(self.user, self.password),
                                        use_ssl=self.ssl,
                                        verify_certs=self.verify)
        else:
            self.client = Elasticsearch([{'host': host, 'port': port}])
```

In my case the `ELASTIC_SSL` variable is `False` since I do not expose my elasticsearch instance to the public, however I have an additional Kibana instance configured in the same docker network which is exposed and therefore requires the cluster to be password protected. So in this case requiring SSL is incorrect however changing the above to this might make more sense:

```python
        self.user = current_app.config.get('ELASTIC_USER', None)
        self.password = current_app.config.get('ELASTIC_PASSWORD', None)
        self.ssl = current_app.config.get('ELASTIC_SSL', False)
        self.verify = current_app.config.get('ELASTIC_VERIFY_CERTS', True)

        if self.user and self.password:
            self.client = Elasticsearch([{'host': host, 'port': port}],
                                        http_auth=(self.user, self.password),
                                        use_ssl=self.ssl,
                                        verify_certs=self.verify)
        else:
            self.client = Elasticsearch([{'host': host, 'port': port}])
```

Additional checks could also be made to verify that both the `user` and the `password` settings are provided, but this adds the benefit to onboard an authenticated elasticsearch instance without SSL required.

**Comment by Kamforka** [comment]
@kiddinn it basically doesn't work, no queries, no upload, nothing that is related to elasticsearch.
However I monkeypatched my local version with the suggested snippet above and it works for me just fine, tell me if you are okay with the solution so that I can raise a PR.

**Comment by kiddinn** [comment]
does this work: https://github.com/google/timesketch/pull/1710

**Comment by kiddinn** [comment]
this is a draft PR that I just set up, will add few more things to it before pushing it for a review, but that should patch this up so that the queries will work in your case.
