### ISSUE TITLE
timeline does not show in timesketch

### ISSUE THREAD

**Issue by chadgough** [google/timesketch#171]
Running a new install of Ubuntu 14.04 and Plaso 1.4.  Installed per the docs and left elastic search config as defaults, added groovy line.  The timeline shows briefly in timesketch as "pending" and then disappears.

$ psort.py -o timesketch my_dump.plaso 
[INFO] Index: f104b67893c94fa4877f2b7010290110
[INFO] Timeline name: 
Missing parameter timeline_name for output module: my_timeline
[INFO] Index: f104b67893c94fa4877f2b7010290110
[INFO] Timeline name: my_timeline

[INFO] Starting new HTTP connection (1): 127.0.0.1
No handlers could be found for logger "elasticsearch.trace"
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'f104b67893c94fa4877f2b701...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
[INFO] Adding events to Timesketch..
[INFO] 1000 events added
[INFO] 2000 events added
[INFO] 3000 events added

**Comment by berggren** [comment]
If you create a new sketch, are you able to add the timeline? The timeline seems to be added just fine, so it should turn up in the list when you press the button "Add new timeline".

Let me know

**Comment by chadgough** [comment]
Thanks.  For some reason, a reboot/restart of timesketch allowed it to show up and work properly.  I'm sure it was a user problem on my end.

**Comment by berggren** [comment]
Good to hear. Let me know if you encounter any other problems.
I will close this issue for now.
