### ISSUE TITLE
Infinite spinning search when error 400 is returned

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#1715]
**Describe the bug**
Search for `*Chrome/Default*` in a timeline, spinner spins forever, but an error 400 is returned by the API. (it contains an error message embedded in some HTML)

**To Reproduce**
Upload a timeline (I can provide info if needed). Search for `*Chrome/Default*`.

**Expected behavior**
Ideally, I'd like results that match the query, or at least a visible and human-readable error message.

**Comment by kiddinn** [comment]
this is not an issue in the API client, the error is relayed to the user, this is a UI issue, assigning it to @berggren

**Comment by itsmvd** [comment]
First part of this fix was merged with https://github.com/google/timesketch/pull/1765. Will look into this further.

**Comment by itsmvd** [comment]
This bug is fixed, the error is now returned to the user. A next FR will be to improve error logging in the UI, but this bug can be closed.
