### ISSUE TITLE
docker pull the new branch, css not applied

### ISSUE THREAD

**Issue by asmirazali** [google/timesketch#1721]
**Describe the bug**
After docker pull the new updates, CSS is not applied. 

**To Reproduce**
docker-compose down
docker-compose pull
docker-compose up -d

**Expected behavior**
It seems like CSS is broken. 

**Screenshots**
Previous: 
![image](https://user-images.githubusercontent.com/71688327/112434914-063dab80-8d7f-11eb-8577-5a5bd22e94b9.png)
Now: 
![image](https://user-images.githubusercontent.com/71688327/112435059-35ecb380-8d7f-11eb-9db9-55b0564ea2c8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by berggren** [comment]
This is part of an ongoing UI refresh where we are fixing some inconsistencies and usability issues.
Is there anything else than the look&feel you see is broken?

**Comment by asmirazali** [comment]
So far, nothing is broken. Since this is an ongoing UI refresh, we can close this.
