### ISSUE TITLE
Documentation link are broken

### ISSUE THREAD

**Issue by toshiro92** [google/timesketch#1742]
**Describe the bug**
The link to the JSON and CSV format explanation present into the web interface is no more available. The below link returns a 404 error:
https://github.com/google/timesketch/blob/master/docs/Users-Guide.md#adding-timelines

**To Reproduce**
1. Go to the homepage of a current case
2. Click on the "documentation" link below the "Upload Timeline" section
3. The link will redirect to a 404 error

**Expected behavior**
The page is available

**Desktop (please complete the following information):**
All

**Additional context**
The broken link is also available into the following pages:

- timesketch/frontend/src/views/SketchManageTimelines.vue
- timesketch/frontend/src/views/SketchOverview.vue
- timesketch/frontend/dist/js/chunk-common.a1241482.js.map
- timesketch/frontend/dist/js/chunk-common.a1241482.js

**Comment by toshiro92** [comment]
I can do a Pull Request for the change, however the question would be: Which link would be suitable for the replacement?

**Comment by kiddinn** [comment]
This is because the documentation pages have changed, they are now located on https://timesketch.org -> please go there and verify that all links work.
