### ISSUE TITLE
Ability to delete timelines

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#175]
Currently, the only options available for handling timelines once they're inserted to Timesketch is the ability to change their title, description, color or add it/them to a sketch. It'd be useful to have the ability to delete a timeline via the interface.

**Comment by n3x77** [comment]
I would appreciate it. Because renaming and changing the color makes it very hard to keep track of the other sketches. Also deletion by hand is very tricky ;-)

**Comment by berggren** [comment]
Cool, let's bump this up the prio list.

**Comment by berggren** [comment]
This is done.
