### ISSUE TITLE
Sigma analyzer result is too verbose

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1750]
**Is your feature request related to a problem? Please describe.**
When you run the sigma analyzer it returns an overview of actions that have occurred. ATM it contains few things:

+ It lists up all sigma rules and how many hits there were for each one of them
+ It ends with `problematic rules...`

The issue is that when you've got many rules, this will easily get very cluttered... and if there are no problematic rules it seems like there shouldn't be a statement of problematic rules.

**Describe the solution you'd like**

1. First of all, if there are no problematic rules, the resulting text should not contain that part of the sentence.
2. What if you've got 200 rules? This text will become unruly at that point.. the first and easiest solution is to at least not provide sigma rules in the list that have ZERO hits, only include those that actually have hits.
3. The question is also what if there are 200 rules that have a hit? Then what... then the output will also be cluttered, is that an acceptable clutter or do we want to have a `maximum` length here, or adjust to say `rules with more than 100 hits: ....` or something like that to limit the number of rules that are in the ouptut, in the case where there are more than X sigma rules that have hits...

**Comment by jaegeral** [comment]
Was also fixed with https://github.com/google/timesketch/pull/1960 It will only show you the total amout of hits
