### ISSUE TITLE
Detection date of elastic on jsonl/csv

### ISSUE THREAD

**Issue by lprat** [google/timesketch#1752]
**Is your feature request related to a problem? Please describe.**
When upload jsonl, some field have date information, but the date format can be different on same field. If elsatic have 'detection_date = true" on index (it's default config) then upload timeline generate error:
```
[2021-04-29 11:07:53,471] timesketch.elasticsearch/ERROR Unable to 
upload document: u5BQHXkBHBT8NHjyT4RB to index 
1619694388.0804214spyre_pole_p3 - [400] <mapper_parsing_exception> 
failed to parse field [real_time] of type [date] in document with id 
'u5BQHXkBHBT8NHjyT4RB'. Preview of field's value: '2020-07-07 
15:49:51.7636847 +0200 CEST' [illegal_argument_exception/failed to parse 
date field [2020-07-07 15:49:51.7636847 +0200 CEST] with format 
[strict_date_optional_time||epoch_millis]]
```
The problem can be same on field change type. Example: field X have value "bla" and other line (jsonl) have value 2. 

**Describe the solution you'd like**
My solution is create generic.mappings for jsonl index create. You can specify mappings for your case.

**Describe alternatives you've considered**
It's may be interesting to add option on API upload to choose 'mappings' exclusively for your timeline upload.

**Additional context**
I PR my proposal (generic.mappings).

Thanks
Lionel

**Comment by jaegeral** [comment]
Hey @lprat can this one here be closed seeing you have a merged PR?

**Comment by lprat** [comment]
Thanks for merge!
