### ISSUE TITLE
Document expected formats & additional columns needed in custom timeline import

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#176]
Speaking as someone who's importing custom timelines, I think it'd also be a good idea to mention the following on the wiki:
- format of expected [`datetime`](https://github.com/log2timeline/plaso/blob/b510330cc4760a1353fbaff802c9870d80fbc0c7/plaso/output/timesketch_out.py#L84) (e.g. - 2016-01-01T01:01:01+00:00) as I've encountered rows not being found otherwise
- any other hidden gems to include such as:
  - [`data_type`](https://github.com/google/timesketch/pull/133) so aggregation filtering can be leveraged
  - [`tag`](https://github.com/google/timesketch/pull/140) so these can be displayed in the UI

Since these apply to CSV, JSON and unknown future file formats, I thought this would be better on its own page vs. each of these import feature pages.

**Comment by berggren** [comment]
Yeah, the docs are in great need of updating. There is another issue to track this, but I'll close that one in favour of this one. Thanks!

**Comment by berggren** [comment]
Updated the wiki.
