### ISSUE TITLE
Sigma field mapping overlap

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1760]
Some fieldnames that are referenced in Sigma e.g. ```Image``` in a sysmon event would be used in the sigma mapping as 👍 
```Image:xml_string``` because this is where the value is located. However, if a different Data type uses the same field name but woul dneed a different mapping, it would be screwed.

One solution would be to introduce something like:
```Image: foobarhackymagic``` in the mapping file and then in the actual implementation do a:
```search_query.replace('foobarhackymagic:','')``` so it would technically search in all fields. This would aof course not be very elegant and would be rather expensive as every field would be searched.

**Comment by binglot** [comment]
@jaegeral - does PR #2169 close this issue?

**Comment by jaegeral** [comment]
yes it does
