### ISSUE TITLE
Break up Tags added by Sigma analyzer

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1762]
Right now the Sigma analyzer adds two types of Tags to an event:
- sigma_$FILENAME
- Tags provided by the Sigma rule itself

Depending on the rule, this can clutter the Events list quite a bit.

To clean it up, the suggestion is:
- Add the Filename as an attribute (list of strings) to the matching event as ```sigma_ts_filename:$FILENAME```
- Add all tags provided by sigma that match ```attack.*``` to a new attribute (list of strings) called ```ttp_ts:attack.foobar```
- rest of the tags (if any) would go to the normal ```tags```attribute.

**Comment by tomchop** [comment]
I think this is a good idea, however I would either:

* Pick a more generic prefix than `attack.*`, as some matching TTPs won't always match those in the ATT&CK framework (I assume this what the `attack` is about)
* Alternatively, make the list of prefixes that add tags to attributes easy to extend (e.g. if I want to add another prefix such as `yeti.*` or `misp.*`

**Comment by jaegeral** [comment]
yes, it will be easily extendable, right now as far as I can tell, the Sigma rules only have attack.* in them. But extending them is a good idea, I will add that.
