### ISSUE TITLE
Ability to aggregate/filter on attributes

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#177]
I think it'd be useful to have the same type of querying stats/ability for the required column **timestamp_desc** as there currently is for the column [**data_type**](https://github.com/google/timesketch/pull/133) when you toggle `Filters`.

This feature would be easier to work with when an analyst wants to only show certain timestamps (and much cleaner than possibly having a long query expression they'd have to write within `Search`).

**Comment by berggren** [comment]
Yes, this makes a lot of sense and I have already plans for this :) We don't need to limit ourselfs to any specific attribute, but we could add a dropdown selector in the UI where you can choose which attribute you would like to aggregate on.

I'll change the title of this issue and start tracking it here.

**Comment by berggren** [comment]
This has been implemented as part of the new UI
