### ISSUE TITLE
Bulk select/deselect items within `data_type` filtering

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#178]
Right now a user has to manually check each box next to said `data_type` they want to include/exclude for filtering. This is useful, but if there are a large amount of items here it'd be convenient to be able to bulk select/deselect check boxes.

**Comment by berggren** [comment]
Good point! I'll start looking into this after the upcoming release.

**Comment by berggren** [comment]
Closing this one as we are rewriting the aggregation feature all together
