### ISSUE TITLE
Increase the story tab content width size to 100% (UI/UX)

### ISSUE THREAD

**Issue by n0tmyproblem** [google/timesketch#1783]
**Is your feature request related to a problem? Please describe.**

There are unused right screen white space in story content. Idk why is made. Maybe there is a reason I didn't see in blog posts, issues, documentation or CON-talks on YT.

**Describe the solution you'd like**

Remove the CSS "max-width: 970ch;" attribute in the "markdown-body" class.

**Reference**

https://github.com/google/timesketch/blob/0ab609426b1c128c63eaff42b5ef83ab3ca6803d/timesketch/frontend/src/views/StoryContent.vue#L269

**Example with the proposed change**

![image](https://user-images.githubusercontent.com/80429728/118971952-4c268280-b970-11eb-8489-7132b845f83a.png)

**Comment by berggren** [comment]
Hi, thanks for the report. We used to have this set to 100% width but changed this a while back to make the text easier to read (line length). But maybe we should make this optional, and have a toggle to choose? WDYT?

**Comment by n0tmyproblem** [comment]
Yep, maybe a Button --> modal with simple check boxes and selects to customize sketch

![image](https://user-images.githubusercontent.com/80429728/119832192-409e0300-befe-11eb-8a53-442829914336.png)

It will require to add new text field to "story" table (Postgresql).

![image](https://user-images.githubusercontent.com/80429728/119832905-eb162600-befe-11eb-8d5a-c1478737d894.png)

Maybe a new field "width" and the close values [''narrow', 'full'].

**Comment by tyjlowe** [comment]
@jaegeral Hi Jaegeral! I was checking out this issue just to see how the front end works for this codebase... how do we reflect updates made to the Vue frontend on the development server? I have not been able to figure out how to see changes. Thanks!

**Comment by jaegeral** [comment]
> @jaegeral Hi Jaegeral! I was checking out this issue just to see how the front end works for this codebase... how do we reflect updates made to the Vue frontend on the development server? I have not been able to figure out how to see changes. Thanks!

Hey, you might want to look at: https://timesketch.org/developers/frontend-development/ that covers how to see your updates in your dev server environment.

**Comment by tyjlowe** [comment]
> > @jaegeral Hi Jaegeral! I was checking out this issue just to see how the front end works for this codebase... how do we reflect updates made to the Vue frontend on the development server? I have not been able to figure out how to see changes. Thanks!
> 
> Hey, you might want to look at: https://timesketch.org/developers/frontend-development/ that covers how to see your updates in your dev server environment.

@jaegeral Sorry but one more follow-up. I assume that the first command "docker-compose exec timesketch yarn install --cwd=/usr/local/src/timesketch/timesketch/frontend" should be run from the directory docker/dev, however, it gives me this error when I attempt to docker-compose (note that the timesketch dev server is running at this point).

![image](https://user-images.githubusercontent.com/59340807/144547659-50c3fa34-88af-423f-8270-79c82bcdcc94.png)

I'm wondering if I am the only person with this problem, and if not, which file I need to go to to fix this. Thanks!

**Comment by berggren** [comment]
Closing this out as stories has been ported over to the new UI
