### ISSUE TITLE
Display saved searches datetime milliseconds in story contents (UI/UX)

### ISSUE THREAD

**Issue by n0tmyproblem** [google/timesketch#1785]
**Is your feature request related to a problem? Please describe.**
When many actions are invvoked at the same second, there aren't a fast way to review the milliseconds in the folded events.

**Use case**
Example, with `milliseconds != 0` with many events at the same displayed datetime:

![image](https://user-images.githubusercontent.com/80429728/119174182-90954980-ba68-11eb-8fe9-fdbda02f1bd6.png)

**Describe the solution you'd like**
Get the milliseconds switch inside the saved search content, to know when display it in explorer/story tab.

**Describe alternatives you've considered**
Always show milliseconds in story contents. Maybe a simple solution? Idk yet!

It could be cool to have the option. Thanks,
**TMP**

**Comment by berggren** [comment]
Good catch! We should consider making this default, and definitely add the option to choose.

We will add this to our work log.
