### ISSUE TITLE
Export all items (not only the first 500)

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#179]
Pull https://github.com/google/timesketch/pull/139 added the ability to export (from #84 ), but it's limited to the current view (which is currently 500 events). I can see the hesitation to export _all_ items in a timeline but if a user stars an event, I see that as fitting into another category. They would likely want that data exported - but if I have 3k items starred, I don't want to have to page through them 500 at a time by using the timestamp filtering then merge each individual spreadsheet locally to reconstruct my starred items from my Timesketch timeline.

I know this is feasible, and able to be limited to items that are starred/of interest vs. everything in the timeline - was the determination made that over X amount of items to export produces some unexpected behavior/slowness etc. ?

**Comment by berggren** [comment]
Good idea! This should be relatively easy to do. I'm also working on more general labeling feature so you can create your own label, apart from just stars. This feature should be generic enough to be implement for that.

The reason for the current export limitation to the current view was that it was the easiest way of implement it without changing the backend code. It is planned to fix this in the next iteration of the export feature.

Let's track the work in this issue. I will edit the title a bit.
Thanks!

**Comment by hiddenillusion** [comment]
If this hasn't been implemented, a quick workaround so only the users' current view is still returned in the UI but during exporting to a CSV, all events within the current query are exported instead of just those in the `LIMIT_RESULTS` & current page:
- [timesketch/lib/datastores/elastic.py](https://github.com/hiddenillusion/timesketch/commit/cf86800de9c144d005f250c60bdd44d319fecabe)
- [timesketch/ui/views/sketch.py](https://github.com/hiddenillusion/timesketch/commit/4a003593f55618fba2e0a6214d8c40943fe35087)

**Comment by berggren** [comment]
The export function will now export up to 10k events. The reason for this limit is elastic will be sad and eat memory if you try to export millions of events, also the elastic settings will stop you anyways. If we want to export more events we have to move to the scrolling api instead. Let's do that at a later time.

The export button will now be disabled if the total event count > 10k
