### ISSUE TITLE
Increate CSRF time or option to update it without page reload (UI/UX)

### ISSUE THREAD

**Issue by n0tmyproblem** [google/timesketch#1794]
**Is your feature request related to a problem? Please describe.**
If I am researching with multiple browser tabs with some queries, views, agregations, multiple stories... When the CSRF token expires, I need to reload the entire tab and I could delete or remove a no saved search, because I am testing and understand the context or whatever I freeze in a tab.

**Describe the solution you'd like**
Increase to 6h the CSRF token, idk if this can be a high security risk.

**Describe alternatives you've considered**
Some solution like https://github.com/google/timesketch/pull/1040 could be interesting. I am using the last release build (2021 Feb) and I didn't see this option.

**Additional context**
Any

Thanks,
NMP :)

**Comment by berggren** [comment]
Hey! This is already possible, but not documented (we will fix that). In /etc/timesketch/timesketch.conf you can add:

WTF_CSRF_TIME_LIMIT = 1234 # seconds or "None" to never expire.

The default is 3600s.
