### ISSUE TITLE
Search only within starred events

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#180]
The ability to [view all starred items](https://github.com/google/timesketch/blob/9fa8dbfb45606a6b4c53e3176cddbc754467b12a/timesketch/ui/static/components/explore/explore-search-directive.js#L101) is useful, but your only option for searching within that specific subset of events is `ctrl +f` and hoping it's within the 500 events you're viewing.

Once a user's timeline view is on all their starred items, if they perform a query it applies the query to the entire timeline vs. just the starred items. It'd be useful to be able to query for something just within starred events.

**Comment by berggren** [comment]
Yeah, this is a known limitation. Should be fairly simple to fix, maybe with a button letting you navigate away from the starred view.

I'll use this issue to track it.

**Comment by hiddenillusion** [comment]
for anyone else needing to do this, an interim solution can be to use [__ts_star](https://github.com/google/timesketch/blob/84e5ca617d125e522ad99eced73008d6c8809b4d/timesketch/lib/datastores/elastic.py#L95) within the query box of the Explore view.

e.g. - `__ts_star AND *10.0.0.1*` only shows entries starred and mentioning 10.0.0.1

**Comment by berggren** [comment]
This has been implemented as part of the new UI.
