### ISSUE TITLE
Select fieldnames for exported CSV

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#181]
The [fieldnames](https://github.com/google/timesketch/blob/master/timesketch/ui/views/sketch.py#L191) are currently preselected for a user when one wishes to export their current view to a CSV file. While some of them are universally useful (`tag`, `datetime`, `timestamp_desc`, `message`), ~~others may not be to everyone (`timestamp`, `timesketch_label` ...).~~ others within the events may also be useful to include.

I _think_ it'd be too much overhead & possibly an overwhelming amount for CSV columns if Timesketch iterated all available columns (fieldnames) within each of the timelines of a sketch and allowed a user to check off which they wanted to include in their exported CSV - but - maybe there could be some consensus on the most common and useful that one could choose from?

e.g. - having `computer_name`, `filename`, `username` & *`_hash` would be other ideal items to be able to include

**Comment by hiddenillusion** [comment]
revised - looks like `timestamp` and `timesketch_label` are currently required for exporting

**Comment by kiddinn** [comment]
This is quite an old issue/feature request.

You can now select extra fields you want to include in a view that is stored, and then a view can be exported with the sketch export.

But we still dont' have a way to selectively export fields, except through the API client that supports this fully... in the API client you can both issue a search using a view object or do an arbitrary search via the API client, get the results back as python pandas and then save them as a CSV. In the `explore` function you can decide which columns you want to include. This is an `easy` way of achieving this, can be done in an ipython notebook/jupyter/jupyterlab/colab or just in a quick python script.
