### ISSUE TITLE
UI: Text color is same as background in dropdown menus in dark mode

### ISSUE THREAD

**Issue by rgayon** [google/timesketch#1810]
**Describe the bug**
UI: Text color is same as background in dropdown menus in dark mode

**To Reproduce**
1. Turn on Dark mode
2. Click on a dropdown menu
3. Can't read text

**Expected behavior**
Text shows against the dark background. In the screenshot, the other option is "  Filtered Terms Aggregation"        

**Screenshots**
https://i.imgur.com/Lx7KrXA.png

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser  chrome]
 - Version 91

**Additional context**

**Comment by berggren** [comment]
Ack,  We will take a look at this and also overall dark mode colors to make sure all elements are shown as expected.

Thanks for the report!

**Comment by Donovoi** [comment]
![image](https://user-images.githubusercontent.com/24791115/180364778-c2ed7749-ebf0-46bf-a1ff-d0a190797bb9.png)
![image](https://user-images.githubusercontent.com/24791115/180364856-ef5fa745-5def-42a8-8ba2-562369daeb33.png)
![image](https://user-images.githubusercontent.com/24791115/180364893-bea43eee-c8eb-47ac-a543-b24558049597.png)

**Comment by jaegeral** [comment]
This is old UI, going to close it out.
