### ISSUE TITLE
Can't post comments

### ISSUE THREAD

**Issue by andrewkrug** [google/timesketch#183]
Getting the following stack trace when attempting comment posts.  

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 533, in post
    current_user.id, u'__ts_comment', toggle=False)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 239, in set_label
    body=script)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 460, in update
    doc_type, id, '_update'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: <unprintable RequestError object>

Yes I have enabled groovy scripting on ES 1.7.2
script.groovy.sandbox.enabled: true
http.cors.enabled: true

**Comment by berggren** [comment]
Hi Andrew,

I don't see the actual elastic error in your traceback, but this looks like the index you are working on don;t have the right mapping. How did you create the index?

**Comment by andrewkrug** [comment]
I'm using the timesketch from the latest build of SANS SiFT workstation.  I
just followed the tutorial on the site for getting going.  Is there a step
I could have missed?

On Mon, May 30, 2016 at 1:35 AM, Johan Berggren <notifications@github.com>
wrote:

> Hi Andrew,
>
> I don't see the actual elastic error in your traceback, but this looks
> like the index you are working on don;t have the right mapping. How did you
> create the index?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/timesketch/issues/183#issuecomment-222441837>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACYve4Uocbet6nwkuhvVFk_-_ttnAZqHks5qGqE2gaJpZM4Ik27d>
> .
>



-- 
Andrew J.Krug
541-708-1002

**Comment by BannersSecret** [comment]
@andrewkrug did you manage to work this out? I am able to post comments (although I get an internal server error), but I'm unable to star events.

**Comment by berggren** [comment]
@andrewkrug ok, could you post the command you used to create the timeline? Are you using the output module in Plaso? e.g:
$ psort.py -o timesketch ..

**Comment by andrewkrug** [comment]
I think this was an issue in my installation.  I pulled from a fork of timesketch the docker-compose project.  ( which is slick btw ) +1 vote for getting that merged into your project.  Everything seems to work.  Now I'm troubleshooting an issue that I believe is from using plaso / log2timeline v1.4 and the celery upload jobs.

**Comment by berggren** [comment]
Ok, cool. Let me know how it goes. I'm in the process of writing new,
better installation docs. Would it be ok if I asked you to proof read them
later?

**Comment by andrewkrug** [comment]
Of course.  Feel free to hit me at my personal e-mail andrewkrug@gmail.com

On Tue, Jul 5, 2016 at 11:33 AM, Johan Berggren <notifications@github.com>
wrote:

> Ok, cool. Let me know how it goes. I'm in the process of writing new,
> better installation docs. Would it be ok if I asked you to proof read them
> later?
>
> On Tue, Jul 5, 2016 at 7:30 PM Andrew J Krug <notifications@github.com>
> wrote:
>
> > I think this was an issue in my installation. I pulled from a fork of
> > timesketch the docker-compose project. ( which is slick btw ) +1 vote for
> > getting that merged into your project. Everything seems to work. Now I'm
> > troubleshooting an issue that I believe is from using plaso /
> log2timeline
> > v1.4 and the celery upload jobs.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/google/timesketch/issues/183#issuecomment-230546199
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AATTylnqW3hhwr9MzIzDlNzBsLCNS-qdks5qSpTSgaJpZM4Ik27d
> >
>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/timesketch/issues/183#issuecomment-230563438>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACYve4TxSVh36C3dPoPRdJ7OQiPrYUnZks5qSqOMgaJpZM4Ik27d>
> .
>



-- 
Andrew J.Krug
541-708-1002

**Comment by andrewkrug** [comment]
Can you confirm is timesketch suppose to work with plaso 1.4 or do we need
to freeze at 1.3?

On Tue, Jul 5, 2016 at 11:34 AM, Andrew Krug <andrewkrug@gmail.com> wrote:

> Of course.  Feel free to hit me at my personal e-mail andrewkrug@gmail.com
>
> On Tue, Jul 5, 2016 at 11:33 AM, Johan Berggren <notifications@github.com>
> wrote:
>
>> Ok, cool. Let me know how it goes. I'm in the process of writing new,
>> better installation docs. Would it be ok if I asked you to proof read them
>> later?
>>
>> On Tue, Jul 5, 2016 at 7:30 PM Andrew J Krug <notifications@github.com>
>> wrote:
>>
>> > I think this was an issue in my installation. I pulled from a fork of
>> > timesketch the docker-compose project. ( which is slick btw ) +1 vote
>> for
>> > getting that merged into your project. Everything seems to work. Now I'm
>> > troubleshooting an issue that I believe is from using plaso /
>> log2timeline
>> > v1.4 and the celery upload jobs.
>> >
>> > —
>> > You are receiving this because you commented.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/google/timesketch/issues/183#issuecomment-230546199
>> >,
>> > or mute the thread
>> > <
>> https://github.com/notifications/unsubscribe/AATTylnqW3hhwr9MzIzDlNzBsLCNS-qdks5qSpTSgaJpZM4Ik27d
>> >
>>
>> > .
>> >
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/google/timesketch/issues/183#issuecomment-230563438>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ACYve4TxSVh36C3dPoPRdJ7OQiPrYUnZks5qSqOMgaJpZM4Ik27d>
>> .
>>
>
>
>
> --
> Andrew J.Krug
> 541-708-1002
>
>


-- 
Andrew J.Krug
541-708-1002

**Comment by berggren** [comment]
It should work just fine with 1.4. Could you send me the traceback you get from the celery worker?

**Comment by berggren** [comment]
@andrewkrug any updates on this?
