### ISSUE TITLE
Time Filter Removal behavior 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1832]
**Describe the bug**
In case there was a time filter in place and multiple exclusion\inclusion filters and it was attempted to remove the time filter. all exclusion\inclusion filters will be removed before the actual time filter removal.

**To Reproduce**
1. Create a time filter.
2. create multiple exclusion\inclusion filters.
3. try removing the time filter.

**Expected behavior**
For the time filter to be deleted without affecting existing exclusion\inclusion filters.

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
TimeSketch Version: 20210602

**Comment by binglot** [comment]
Thanks for reporting the issue @rushattac ! It turned out to be a small bug, I've submitted the fix.
