### ISSUE TITLE
Unable to toggle star

### ISSUE THREAD

**Issue by dootyfree** [google/timesketch#1860]
toggle star not working, new install

error:  TypeError: Cannot read property 'id' of undefined
    at Object.saveEventAnnotation (RestApiClient.js:158)
    at o.toggleStar (Explore.vue:999)
    at ne (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.Jr.a._wrapper (vue.runtime.esm.js:6917)

**Comment by berggren** [comment]
Thanks for reporting this, and good find! This is indeed a bug with the new search history. If there is no prior search history for the sketch, and you enter the explore view in a certain way this bug happens. I will make sure I can repro this on my side and create a fix.

**Comment by dootyfree** [comment]
Many thanks for looking into this!  Would you know how to bypass for now?

**Comment by berggren** [comment]
Yes, in the new sketch and when you are in the Explore tab, just do a full reload of the page.
