### ISSUE TITLE
exclusion\inclusion filter behavior

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1867]
**Describe the bug**
if a certain attribute was filtered on using the inclusion filter then that same attribute was excluded the inclusion filter stays and removing it results in canceling the exclusion filter.

**To Reproduce**
1. select an attribute with an inclusion filter.
2. select the same attribute with exclusion filter.
3. remove the inclusion filter.

**Expected behavior**
the exclusion filter should still be active after removing the inclusion filter. A better solution would be the same attribute can't have an inclusion and exclusion filter at the same time and if exclusion is selected the inclusion filter is automatically removed. 

**Screenshots**
Both filters selected
![both_encloude_excloude](https://user-images.githubusercontent.com/57255503/124365188-0e936580-dc4f-11eb-9d3b-507843f52585.png)
after removing the inclusion filter the exclusion filter is automatically canceled .
![after_incloude_reomval](https://user-images.githubusercontent.com/57255503/124365208-25d25300-dc4f-11eb-9db6-c6130f29109d.png)

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
timesketch version: 20210602

**Comment by berggren** [comment]
This bug was recently fixed. Closing this issue out.
