### ISSUE TITLE
select multiple toggle star not working

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1868]
**Describe the bug**
Selecting multiple events and clicking on the toggle star button is not functioning.

**To Reproduce**
1. Click on select multiple.
2. Click on toggle star.

**Expected behavior**
Events selected gets stared.

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Comment by jaegeral** [comment]
This is already known: https://github.com/google/timesketch/issues/1860
