### ISSUE TITLE
Internal Server Error on `sketch.generate_timeline_from_es_index`

### ISSUE THREAD

**Issue by gaelmuller** [google/timesketch#1878]
**Describe the bug**

The `sketch.generate_timeline_from_es_index` API Client method call sometimes fails with an Internal Server Error.

It is because the `update_by_query` ES request done by the API may timeout if there are lots of events to update.

**Comment by jaegeral** [comment]
Can you share the stacktrace for the issue please and if possible the code you calling the method?

**Comment by gaelmuller** [comment]
I don't have the stack trace anymore but I've created https://github.com/google/timesketch/pull/1879 to fix this issue
