### ISSUE TITLE
"My recent activity" shouldn't display clickable links to deleted sketches

### ISSUE THREAD

**Issue by binglot** [google/timesketch#1880]
**Describe the bug**
The main page for Timesketch lists all the sketches and the section "My recent activity" shows recently visited sketches, even if they were deleted, which I think it should not be the case as clicking on those sketches leads to "an invalid URL" message.

**To Reproduce**
1. Go to a sketch that already exists
2. Delete the sketch
3. Go to the "My recent activity" section in the main Timesketch web page
4. Click on the deleted sketch and see an error

**Expected behavior**
I think either the links should be indicated as deleted (e.g. crossed out, not clickable and hover-over shows a tooltip that says the sketch was deleted) or it should not list the deleted sketches.

**Comment by jaegeral** [comment]
This was old UI startpage.
