### ISSUE TITLE
repeated attributes value 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1894]
**Describe the bug**
attribute values displayed in the event details list are repeated.

**To Reproduce**
1. Import data into timesketch
2. Explore a timeline. 
3. click on and event.
4. See repeated values

**Expected behavior**
the values should not be repeated.

**Screenshots**
![timesketch_repeted](https://user-images.githubusercontent.com/57255503/128874543-84e4ac4d-a636-4ce3-ad19-9b075cac9e53.PNG)

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
Timesketch version: 20210602

**Comment by berggren** [comment]
Good catch! This was introduced in PR #1857 . I'll assign this to @tomchop to take a look
