### ISSUE TITLE
Copy icons issues

### ISSUE THREAD

**Issue by berggren** [google/timesketch#1895]
1. The copy icons while on the explore page are not consistent (different colors)

![Screenshot 2021-08-11 at 11 10 22](https://user-images.githubusercontent.com/316362/129003733-fc26cdb3-e5e5-48b3-bc58-802524046b41.png)

Can we make these icons appear on hover instead of always showing them?

2. The `copy message string` icon does not work. It will only expand the event, not copy the content of the message string. Also, do we need this one? You get the copy icon when the event is exapanded.

![Screenshot 2021-08-11 at 11 15 41](https://user-images.githubusercontent.com/316362/129003957-4ad5a206-c154-462d-9f06-2a3e247ec754.png)

**Comment by jaegeral** [comment]
Yes we can get rid of the second copy icon, and fixing the colors should be trivial, will do that next week
