### ISSUE TITLE
Sort timeline list in explore view

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#190]
If I have several timelines added to a sketch, they're currently listed in horizontal blocks based on when they were selected to be added to said timeline. It'd be useful to have the ability to sort these timelines (when they appear in the Explore view after clicking 'Filters') by name and/or date added to timeline.

**Comment by berggren** [comment]
Huh, yeah makes sense. Lets do it!

**Comment by berggren** [comment]
Closing in favour of #822
