### ISSUE TITLE
Unittests fail because Unable to locate package python3-mans-to-es

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1911]
```E: Unable to locate package python3-mans-to-es
Error: Process completed with exit code 100.

```
https://github.com/google/timesketch/blob/cb62b592ad36e33f54b9a3399b147827ddcfe329/.github/workflows/unit-tests.yml#L59

Need to check if we still need that package.

**Comment by joachimmetz** [comment]
I think it can be removed, If I recall correctly, @kiddinn removed the code using it after running to some issues with it

**Comment by kiddinn** [comment]
We can remove it
