### ISSUE TITLE
Add "Domain" as intel type

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1919]
https://github.com/google/timesketch/blob/97ba07e11c53a11b115beb88e9588c8591bb4f46/timesketch/frontend/src/components/Common/TsIOCMenu.vue#L67

Imho a very common intel type should be "domain" in there.

**Comment by jaegeral** [comment]
@itsmvd / @tomchop what do you think about this?

**Comment by tomchop** [comment]
You're looking at an old version of the codebase: https://github.com/google/timesketch/blob/master/timesketch/frontend/src/components/Common/TsIOCMenu.vue#L69 loads the IOCs from https://github.com/google/timesketch/blob/master/timesketch/frontend/src/utils/tagMetadata.js
