### ISSUE TITLE
Python client API support for collaboration settings

### ISSUE THREAD

**Issue by RandomRhythm** [google/timesketch#1929]
**Is your feature request related to a problem? Please describe.**
Need to be able to automate modifying collaboration settings via the Python client API.

**Describe the solution you'd like**
Expose code in the Python client API to interface with sketch collaboration settings.

**Describe alternatives you've considered**
Automate with Selenium?

**Additional context**
Collaboration settings for a sketch are isPublic, addUser, addGroup, removeUser, and removeGroup.

**Comment by berggren** [comment]
Hi! this is already possible using the API client. Using the sketch object from the sketch API you can set the ACL with the `add_to_acl` function:

https://github.com/google/timesketch/blob/master/api_client/python/timesketch_api_client/sketch.py#L474

Closing this issue out, but feel free to reopen if you have any questions.
