### ISSUE TITLE
Show number of hits per timeline

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#193]
The Charts within the Explorer view are great for a quick high level overview of the events a query returned. If I have multiple timelines enabled and perform a query, it'd be useful to have a chart indicating how many results were found in each of those timelines (or those which results were found in).

Since a hostname/IP address won't always be available within the events of a timeline, this would be a good way of quickly seeing how much activity a specific system had (or activity found on with a query) if each system had its own timeline uploaded.

**Comment by berggren** [comment]
Great idea. I have been thinking about adding this as a label on each timeline in the filter view. We can also do a fancy chart :)

**Comment by berggren** [comment]
This has finally been implemented :)
