### ISSUE TITLE
Absent check for mandatory fields

### ISSUE THREAD

**Issue by ghost** [google/timesketch#195]
When filling timesketch with 
tsctl csv2ts --name name --index name --file file.csv
or
tsctl json2ts --name name --index name --file file.json

Timesketch needs some fields to be present at json/csv file to parse data correctly and correctly push them to elasticsearch. If datetime field is absent, above commands will succesfully finish and add bad mapping in elasticsearch. It causes not very informative error at every use of search. 
Please add test for input data format.

**Comment by berggren** [comment]
Thanks for raising this. Will use this issue to track.

**Comment by csash** [comment]
I'll buy this one. Should be pretty easy to do. Just validate that the mandatory fields (timestamp, datetime, timestamp_desc, message) are present and timestamp is in microseconds? Anything else you want done?

**Comment by berggren** [comment]
This is done
