### ISSUE TITLE
Expand "Data Types" overview counts

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#1978]
**Is your feature request related to a problem? Please describe.**
I really like the "Data Types" summary view with the count of each record. However, it only shows the top 10 data types, and it took me a while to realize those weren't the only data types in the sketch. Just showing the top ones is fine, but the problem was I didn't realize there were more than that.

**Describe the solution you'd like**
Somehow indicate that it's the top 10 data types (either change the title to something like "Top Data Types", or add at the bottom something like "+ 6 more data types". Basically some indicator that this isn't **all** the data types in the sketch.

![image](https://user-images.githubusercontent.com/4984680/137220983-8a7d5b21-7706-4a34-b70d-fa50ea7e7fce.png)

**Comment by jaegeral** [comment]
I will add a "bug" label here because there is no obv reason to the user that only 10 results are displayed.

**Comment by binglot** [comment]
@berggren - this has been resolved already, right?

**Comment by binglot** [comment]
Johan confirmed the bug is still there, I'm picking this up. I'll change the default limit for aggregation from 10 to 1,000 entries.
