### ISSUE TITLE
Analyzer logs\Analyzer done UI elements have too many entries 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1990]
**Describe the bug**
After #1960 the tagger analyzer and feature extractor display an entire for every celery worker process based on the number of defined tags\features. which floods the UI for the analyzer logs and analyzer done.

**To Reproduce**
1. pull latest timesketch
2. define x number of tags\features 
3. run the tagger or feature extractor analyzer.

**Expected behavior**
Regardless of the number of workers only a single entre is shown. maybe a status of workers done or still running could be added.

**Comment by jkppr** [comment]
In the v2 UI the results of multi analyzers (e.g. tagger) are shown in a table with pagination etc. So this should make it easier to understand what was tagged and what not. Also all tags are now part of the "Tag" section in the left panel after the analyzer was executed.
