### ISSUE TITLE
Only top10 results is shown for tags/label list in search dropdown

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2003]

**Comment by obsidianforensics** [comment]
Probably related issue: https://github.com/google/timesketch/issues/1978

**Comment by jaegeral** [comment]
![Screenshot 2022-08-22 at 22 18 59](https://user-images.githubusercontent.com/741037/186011397-a082508b-9fcf-4870-b59f-a59421715c0c.png)

Just confirmed this is no longer an issue, TS shows 11 and more now.
