### ISSUE TITLE
Some components are incompatible with node 10.

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#2023]
**Describe the bug**
Yarn install fails on a fresh ubuntu 20.04 install, or even a Docker container

**To Reproduce**
Steps to reproduce the behavior: https://github.com/google/timesketch/runs/4167754674?check_suite_focus=true

**Potential solution**
Upgrade to node 12 in the dockerfile: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04

**Additional context**
This seems to happen on a fresh install when doing `yarn run` or `yarn install`

**Comment by berggren** [comment]
We are now running on Node 14 as default.
