### ISSUE TITLE
Import Google Sheets / Auto-import from Google Drive

### ISSUE THREAD

**Issue by adric-work** [google/timesketch#2024]
**Is your feature request related to a problem? Please describe.**
My team likes to share logs via Google Sheets.

**Describe the solution you'd like**
* Add an option in the UI to import a sheet from Google Sheets.
* Add an option to automatically import or update all sheets from a drive folder

**Describe alternatives you've considered**
Downloading sheets and uploading them to Timesketch manually

**Additional context**
In addition to system/technical logs we would also like to include timeline events that we consider significant to investigations that we collect manually.  e.g. references to in-person communications, HR events, travel, news stories, social media posts, CVE dates, internal all-hands announcements

**Comment by jaegeral** [comment]
Hey,

there are multiple elements to this feature request.

-Add an option in the UI to import a sheet from Google sheets:

That is a feature we will most likely not implement, the design choice was to keep the amount of formats / sources as low as possible and offer a flexible way to extend it via the API client and other tools out there, e.g. https://github.com/log2timeline/dftimewolf.

-Add an option to automatically import or update all sheets from a drive folder
Here again would refer to the API client and potentially a colab which integrates well with Google Drive and Timesketch API. You could load a Sheet or multiple sheets from Google Drive into a pandas dataframe and then use the API client to import it to Timesketch.

- Add manual events:
There is a feature request open to add it to the UI: https://github.com/google/timesketch/issues/1940 in the meantime I recommend to use: https://github.com/google/timesketch/blob/master/notebooks/add_a_single_event_to_a_sketch.ipynb

**Comment by jaegeral** [comment]
Seeing there is now effort in DFTimewolf to implement it there, I will close the issue / request in Timesketch, feel free to re-open if you have additional points for it.
