### ISSUE TITLE
Support for custom CSV/JSONL schemas

### ISSUE THREAD

**Issue by adric-work** [google/timesketch#2025]
**Is your feature request related to a problem? Please describe.**
I have to alter my log headers to include the datetime, timestamp_desc, and message fields

**Describe the solution you'd like**
I'd love to be able to:
* Create and edit custom schemas in the UI
*  Select a custom schema to apply to a CSV/JSONL file when I upload it

**Describe alternatives you've considered**
Manually or automatically modifying my logs

**Additional context**
Please :)

**Comment by jaegeral** [comment]
Can you explain what headers your CSV currently have? When you say you have to alter, does that mean you would like to upload CSV files without those required fields (very likely impossible to implement) or a UI that would help you to rename a column from a csv that was:

```
datetime, timestamp_desc, message123
```

to
```
datetime, timestamp_desc, message
```
?

**Comment by jaegeral** [comment]
@adric-work you might like: https://github.com/google/timesketch/pull/2261 and https://github.com/google/timesketch/pull/2287
I assume that fixed your feature request and closing out the issue.
