### ISSUE TITLE
Customized columns are not populated

### ISSUE THREAD

**Issue by cudeso** [google/timesketch#2034]
**Describe the bug**
When you add additional columns in the explore view the columns are not filled with the data of entries.

**To Reproduce**
1. Done via https://demo.timesketch.org/sketch/6/explore  (but similar behavior on latest Docker instance)
2. Explore
3. Add a column for which you're sure there is data (fe. IMP)
4. Column remains empty

**Expected behavior**
Columns to be filled with the data

**Screenshots**
![2021-11-17 10_02_39-Szechuan Sauce - Challenge](https://user-images.githubusercontent.com/256028/142170068-30f1669d-89d5-48f6-acca-799dc9dbc029.png)
![2021-11-17 10_03_35-Szechuan Sauce - Challenge](https://user-images.githubusercontent.com/256028/142170066-1112b8ae-03ef-4ece-9471-82371ef5979d.png)
![2021-11-17 10_04_17-Szechuan Sauce - Challenge](https://user-images.githubusercontent.com/256028/142170062-252fe5ec-6ceb-4880-81bf-4ea89b92cbdd.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version  https://demo.timesketch.org/ ; but also latest Docker versions

**Comment by itsmvd** [comment]
This is likely related to https://github.com/google/timesketch/issues/1630

@cudeso if you refresh the page or add another column the column should be populated
@berggren could you PTAL this issue / 1630?

**Comment by cudeso** [comment]
> This is likely related to #1630
> 
> @cudeso if you refresh the page or add another column the column should be populated @berggren could you PTAL this issue / 1630?

Indeed; adding another column or selecting fe. the next page in the results populates the columns.

**Comment by berggren** [comment]
Yeah, this is a bug in the custom columns implementation. This has been fixed in the port to the new UI that is upcoming (in the next few weeks.

Will close this out as we don't have time to fix this in the old and soon to be deprecated UI.
