### ISSUE TITLE
Issue with graph generation

### ISSUE THREAD

**Issue by joshuank-fr** [google/timesketch#2044]
**Describe the bug**
I am desperately trying to generate the winlogin graph. I have a note "Gaph generated for timineline" but nothing is displayed. 

**To Reproduce**
1. Go to Graph
2. Click on Windows logins

**Expected behavior**
Generate winlogins graph as show here in demo (https://demo.timesketch.org/sketch/6/graph/explore?plugin=winlogins)

![image](https://user-images.githubusercontent.com/56877912/142832583-b4ba0bb3-1dd7-4df9-a626-b3677b08d08a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/56877912/142831776-fed5a3ff-53fb-4c8e-b437-b3f957682e82.png)

**Desktop (please complete the following information):**
 - OS: NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
 - Browser [chrome]
 - Version [Version 96.0.4664.45 (official Buid) 64-bit]

**Additional context**
N/A

**Comment by csash** [comment]
The Windows logon/logoff events analyzer needs to be run to tag events as being logon/logoff events before this graph will show you any data. Have you already run this analyzer? If you have, do you get results when you search for `tag:logon-event`?

**Comment by berggren** [comment]
As @csash mentioned - The logon/logoff analyzer need to run before to tag the relevant events. We have noted this as an improvement when we port over the graph to the new and upcoming UI.

Closing this out for now, but feel free to reopen as necessary
