### ISSUE TITLE
UI: Change the behavior of "Toggle Star" button

### ISSUE THREAD

**Issue by binglot** [google/timesketch#2048]
**Is your feature request related to a problem? Please describe.**
At the moment if I want to star all the entries on the page, then I'll tick the box at the bottom and click "Toggle Star", which for entries that were already "starred" will result in them becoming "unstarred". I'd like the behavior to be "all in" or "all out" rather than "toggle".

![image](https://user-images.githubusercontent.com/1036124/143530952-5899c804-f3cf-4d19-8983-6f261eb0e8a2.png)

**Comment by binglot** [comment]
WIP - I got the starring/unstarring behavior working but the view doesn't refresh. Need to find out how to force it and then the job will be done.

**Comment by jaegeral** [comment]
IMHO that is a good idea.
