### ISSUE TITLE
Timefilters Disappear When Selecting a Data Type or Tag

### ISSUE THREAD

**Issue by hkhalifa** [google/timesketch#2058]
**Describe the bug**
When you have a Timefilter set and then you want to filter on a "Data Type" or a "Tag" within this time filer, the Timefilter just gets deleted. 

**To Reproduce**
1. Go to Explorer page
2. Add a Timefilter
3. From the search bar select a "Data Type" or a "Tag"
4. Timefilter is gone.

**Expected behavior**
Timefilter should still be active when choosing any of the filters from the search bar.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by jaegeral** [comment]
That was old UI, gonna close it out in favour of the new material design
