### ISSUE TITLE
Error when using psort.py to load timeline into timesketch

### ISSUE THREAD

**Issue by incident-responder-x** [google/timesketch#206]
I can see that the timesketch output module is enabled in psort but I see the attached error when attempting to load the timeline into timesketch using psort.

I followed the installation instructions wiki, installed postgresql and elasticsearch, and can connect to timesketch and login ok. How do I resolve this error please. Thanks for your help!
[error.txt](https://github.com/google/timesketch/files/448083/error.txt)

**Comment by Onager** [comment]
What versions of Plaso and Timesketch are you using? How did you install them?

**Comment by bowleg** [comment]
I am getting the same error using Plaso 1.4.0 and Timesketch 2016.7 release on ubuntu server 14.04.5 LTS following the wiki installation guides.

**Comment by berggren** [comment]
Plaso have had some pretty large changes lately, in particular the storage format has changed and psort does not have backwords compatibility with older plaso files created with v1.4.

In order to be compatible with elasticsearch > 1.x we there was a fix in the timesketch output module that dropped the mapping for _timestamp.

What this means is that you need to use Plaso version 1.54RC2 (or HEAD) for now to pick up the changes. Sorry for the inconvinience, I will update the wiki with this information.

**Comment by incident-responder-x** [comment]
I have python-plaso 1.4.0 installed. I installed it using command, "sudo apt-get install python-plaso"

```
sansforensics@siftworkstation:~$ apt list --installed python-plaso
Listing... Done
python-plaso/trusty,now 1.4.0-1ppa1~trusty all [installed]
```

I installed timesketch by using command, "sudo pip install timesketch". I am using timesketch==2016.7

Thanks for your reply berggren. I will try using Plaso version 1.54RC2 (or HEAD).

**Comment by bowleg** [comment]
I can only find Plaso 1.5.0 RC2 source code on there git. There is no mention of Plaso version 1.54RC2 (or HEAD).

**Comment by Onager** [comment]
Plaso 1.5.0 RC2 is fine, I believe berggren made a small typo.

**Comment by incident-responder-x** [comment]
Can you let me know if the documentation is updated to install timesketch
and the dependencies so it works? ​I'm trying to get a timelining tool in
working order for investigations at work. Thanks

**Comment by berggren** [comment]
Hey @incident-responder-x 

I have updated the documentation on how to get Plaso to work with the latest Timesketch:
https://github.com/google/timesketch/wiki/UserGuidePlasoUpload

The gist is that you should use the latest development version of Plaso until Plaso 1.5.0 is released. You do this by using the dev track of the Plaso PPA repository. This is explained in the link above.

Let me know if you encounter any problems.

**Comment by incident-responder-x** [comment]
Thanks. I installed the latest dev version of plaso but was having issues
installing some of the dependencies. I gave up trying eventually but I will
try and return to it soon and give it another shot. Thanks again

**Comment by berggren** [comment]
Plaso 1.5 is now released. Closing this.
