### ISSUE TITLE
Explore search: __ts_star / __ts_comment

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2061]
It would be good to be able to search in the explore bar for:

```
__ts_comment:*foo*
```

As well as:

```
__ts_star
```

Context: https://twitter.com/stuhlonsky/status/1465948466014785536

**Comment by jaegeral** [comment]
This could be done by just adding a small addition to the `sketch.explore` function if one of the two strings are found to add it to the query n a proper manner, so maybe no change to the UI is really needed.

That said, it will most likely only be in Q3 when we get to this.

**Comment by berggren** [comment]
Star and Labels are implemented as nested docs in todays implementation. @jkppr has added these as chip filters so this functionality can be used with those chips + query.

Implemented in: #2886
