### ISSUE TITLE
CSV with wrong extension is not stopped on UI side

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2064]
https://github.com/google/timesketch/blob/fce0f54e20d9385b264f2401079dbeb5ad773a38/timesketch/frontend/src/components/Common/UploadForm.vue#L124

Uploading a foobar.txt file that has CSV content would still get uploaded and errored out on the backend side, even if the Client JS should error out already.

```Request URL: https://timesketch/api/v1/upload/
Request Method: POST
Status Code: 500 ```

**Comment by jaegeral** [comment]
In the upload error log it will look like:

```
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 235, in _upload_and_index
    pipeline = tasks.build_index_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 252, in build_index_pipeline
    index_task_class = _get_index_task_class(file_extension)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 221, in _get_index_task_class
    raise KeyError('No task that supports {0:s}'.format(file_extension))
KeyError: 'No task that supports txt'
```

**Comment by rojanDinc** [comment]
Hi, what is the expected outcome when uploading files that contains csv formatted data but the filename is different?

**Comment by jaegeral** [comment]
> Hi, what is the expected outcome when uploading files that contains csv formatted data but the filename is different?

The expected outcome is that it should fail. And it does fail at the moment, which is okay, the only thing we should improve is the point where it iwll fail (client side in JS vs on the backend) to give the user a quicker feedback.

**Comment by rishav-karanjit** [comment]
Hey, I want to work on it. Can I be assigned to this issue? 

@rojanDinc are you planning to work on this issue?

**Comment by jaegeral** [comment]
> Hey, I want to work on it. Can I be assigned to this issue?
> 
> @rojanDinc are you planning to work on this issue?

Sure thing, happy coding, reach out if you are stuck with anything (best on slack) or if you found the corresponding region in code feel free to update the issue here so it is visible to others what you are working on.

**Comment by rishav-karanjit** [comment]
Thank you for assigning me @jaegeral

**Comment by rishav-karanjit** [comment]
Hello @jaegeral, I am wondering how does the file goes to backend? When we upload file of wrong extension submit button does not appear.

**Comment by jaegeral** [comment]
> Hello @jaegeral, I am wondering how does the file goes to backend? When we upload file of wrong extension submit button does not appear.

https://github.com/google/timesketch/blob/fce0f54e20d9385b264f2401079dbeb5ad773a38/timesketch/frontend/src/components/Common/UploadForm.vue#L115 this is the method in the JS file that triggers the upload function in the API client and uploads it to the worker.

**Comment by rishav-karanjit** [comment]
Hello @jaegeral, I have opened a pull request for this issue yesterday. Please let me know if any further changes are required.

**Comment by rishav-karanjit** [comment]
@jaegeral, do you have an update on my PR?

**Comment by rishav-karanjit** [comment]
Also, please discard my [last commit ](https://github.com/google/timesketch/pull/2147/commits/3bb2f27142477b85016e35b54897fb741f9cf2c8). I don't know why so many files appear to be changed in this commit. 

Please just look into my [second last commit](https://github.com/google/timesketch/pull/2147/commits/2a771fa053ee65446facd91018f40be4c05100c1)
