### ISSUE TITLE
Aggregation view improve

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2076]
**Is your feature request related to a problem? Please describe.**
I would like to choose in term "table" result:
  - number of result to display by page
  - possible to filter term by regexp
  - order term aggregation by ASC or DESC from elastic

![image](https://user-images.githubusercontent.com/1132448/145024163-01c7dea1-5147-4cc5-a817-b48dc5d4f571.png)

On filtered aggregation 'table", I would like:
  - to pre filter result from regexp to keep only group (from regexp)
    - exemple:  message contains several information including FS PATH, and you want just get FS PATH information (without use FEATURE analyzer):
![image](https://user-images.githubusercontent.com/1132448/145026809-34408213-e377-4ee7-82c1-60bc6ea7fdb6.png)

  - To get information on first, last date to exist this term and duration between first and last event:
![image](https://user-images.githubusercontent.com/1132448/145025749-9276e822-f9dc-4d07-9b45-650cd5d36b70.png)

**Describe the solution you'd like**
PR.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/1132448/145024163-01c7dea1-5147-4cc5-a817-b48dc5d4f571.png)
![image](https://user-images.githubusercontent.com/1132448/145026809-34408213-e377-4ee7-82c1-60bc6ea7fdb6.png)
![image](https://user-images.githubusercontent.com/1132448/145025749-9276e822-f9dc-4d07-9b45-650cd5d36b70.png)

**Comment by jaegeral** [comment]
Hi @lprat sorry for the (very) long delay on this PR. The old UI that this PR is on is deprecated in favour of a new, refreshed UI using material design. We will not be merging any new features to the old UI.
