### ISSUE TITLE
docker-compose up failing due to elasticsearch reference

### ISSUE THREAD

**Issue by lo0pback** [google/timesketch#2088]
@berggren I'm getting an error when running docker-compose up:

```
WARNING: The ELASTIC_VERSION variable is not set. Defaulting to a blank string.
ERROR: no such image: docker.elastic.co/elasticsearch/elasticsearch-oss:: invalid reference format
```

This seems to be caused by line 26 in docker-compose.yml:
`image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION}`

Perhaps the elasticsearch container (lines 25-32) should be removed entirely? 

I also noticed that deploy_timesketch.sh was not updated like deploy_timesketch.ps1 was. It is still referencing the old elasticsearch directories and settings.

_Originally posted by @lo0pback in https://github.com/google/timesketch/issues/2084#issuecomment-998884495_

**Comment by berggren** [comment]
Hey @lo0pback , thanks for the bug report. Your analysis it correct, and I have a fix for this, pending review: #2089
