### ISSUE TITLE
Aggregate similar events

### ISSUE THREAD

**Issue by berggren** [google/timesketch#209]
It would be nice if the UI aggregated similar lines (e.g. if different MAC times for the same file are changed at the same time, show that as part of one line.

**Comment by hiddenillusion** [comment]
Agreed on its usefulness - I currently perform this type of action on any non-Plaso created data prior to sending it to Timesketch to help reduce overall entries/data. As a long term idea, would this serve more useful within something like psort?

**Comment by berggren** [comment]
I agree that this would be useful in psort. Closest neighbor clustering for example. This limits us to Plaso data though, and I would like to support CSV uploaded, non-plaso data as well.

**Comment by hiddenillusion** [comment]
Might be useful to have defined standards for fields that way Plaso & non-Plaso data can be compared (correctly/normalized) together. E.g., the name to use for the 'data_type' and the format it's value(s) should be in.

**Comment by berggren** [comment]
This is being tracked in #220 . Closing this one.
