### ISSUE TITLE
Support: No one event in timeline explore page

### ISSUE THREAD

**Issue by AlexBurkh** [google/timesketch#2092]
Hi, i`ve installed Timesketch on my debian 11 server, create case and upload timeline from web UI (.plaso file (without psort operation with it)).
After indexing there are about 5 millions of events (img1).
# img1
![img1](https://user-images.githubusercontent.com/92160404/147459208-0224bb7e-12f2-4dc0-900c-a1768e6546bf.png)

But when i start explore my timeline there is endless "searching" and no events in event table (img2). 
# img2
![img2](https://user-images.githubusercontent.com/92160404/147455680-7af8780f-7a61-4355-97cd-d55252c2d921.png)

Other operations like running analyzers fine (img3).
# img3
![img3](https://user-images.githubusercontent.com/92160404/147455388-8ba73729-3e2f-4b14-a21c-1311d4473f45.png)

With the use of a time filter, the situation is similar. Please help

OS: Debian 5.10.84-1 (2021-12-08) x86_64

**Comment by jaegeral** [comment]
Can you please search for * or anything else you expect to be in there?

**Comment by AlexBurkh** [comment]
Yes, thanks. I guess i must read more documentation ...
