### ISSUE TITLE
Support: Creating TimeSketches via Python

### ISSUE THREAD

**Issue by KhurumAzam** [google/timesketch#2098]
I'm checking the docs and I'm able to upload data on an existing Timesketch.

My Python program is created to upload new data using a brand new sketch. Is there a way to create a sketch via Python?

**Comment by jaegeral** [comment]
Hey, we have a full fledged api client for python:
https://timesketch.org/developers/api-client/

How do you try to upload data and where does it fail?

**Comment by jaegeral** [comment]
@KhurumAzam not sure if you saw my response.

**Comment by KhurumAzam** [comment]
@jaegeral , looked at the notes, is there a way to create a sketch using Python?

When uploading via CSV via Python, it requires a sketch to be created first.

**Comment by jaegeral** [comment]
Yes, see https://github.com/google/timesketch/blob/master/cli_client/python/timesketch_cli_client/commands/sketch.py#L58 as an example code, it is part of the API client.

**Comment by KhurumAzam** [comment]
Thanks @jaegeral , I'll add this into my program and reopen this ticket if there's any further questions. Thank you!
