### ISSUE TITLE
Constant intelligence view and manually add new IOC

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2115]
**Is your feature request related to a problem? Please describe.**
I would like to add new IOC in the inteligence view without that IOC coming from an event in the timeline.

**Describe the solution you'd like**
The Intelligence view is not constant (just appears when you add the first IOC), you must display all the time even when there is no IOC to leave the possibility of adding a new IOC manually.

Thank you

**Comment by jaegeral** [comment]
![add_indcator](https://user-images.githubusercontent.com/741037/228260081-5e81a999-8dc1-40f5-9878-fc74706850e6.png)

That is now possible in the new UI, the indicator menu is visible all the time.
