### ISSUE TITLE
psort MemoryError: when uploading a Plaso file

### ISSUE THREAD

**Issue by johanlundberg92** [google/timesketch#2124]
```
2022-01-25 19:49:00,670 [INFO] (MainProcess) PID:136 <data_location> Determined data location: /usr/share/plaso
2022-01-25 19:49:01,027 [INFO] (MainProcess) PID:136 <elastic_ts> Timeline identifier: 1
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 491, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 359, in _ExportEvents
    self._ExportEvent(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 253, in _ExportEvent
    self._FlushExportBuffer(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 411, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 123, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 84, in WriteEvent
    self.WriteEventBody(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 476, in WriteEventBody
    self._InsertEvent(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 332, in _InsertEvent
    self._FlushEvents()
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 240, in _FlushEvents
    self._client.bulk(**bulk_arguments)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/__init__.py", line 444, in bulk
    return self.transport.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 350, in perform_request
    method, params, body, ignore, timeout = self._resolve_request_args(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 433, in _resolve_request_args
    body = body.encode("utf-8", "surrogatepass")
MemoryError
```

**Comment by pydvlpr** [comment]
Where are these error messages from, web frontend or cli-importer?

The error messages are from the elastic search backend, which stores the uploaded data. 
Depending on how much data you import, the more memory you will need.

Have you set the values of
OPENSEARCH_MEM_USE_GB in config.env according to your system.
Also the SUM_WSGI_WORKERS value should be  adjusted.

**Comment by joachimmetz** [comment]
Looking at the trace back this is more likely due to psort its process memory limit. It is 4GiB by default but can be set with `--process-memory-limit`. You can add it to the importer task https://github.com/google/timesketch/blob/430912b791bad2ca35e21c66fdf9a6b931817aef/timesketch/lib/tasks.py#L600

One potential root cause for this is that unnecessary extra modules being loaded into memory also see https://github.com/log2timeline/plaso/issues/4029

**Comment by johanlundberg92** [comment]
> Looking at the trace back this is more likely due to psort its process memory limit. It is 4GiB by default but can be set with `--process-memory-limit`. You can add it to the importer task
> 
> https://github.com/google/timesketch/blob/430912b791bad2ca35e21c66fdf9a6b931817aef/timesketch/lib/tasks.py#L600
> 
> One potential root cause for this is that unnecessary extra modules being loaded into memory also see [log2timeline/plaso#4029](https://github.com/log2timeline/plaso/issues/4029)

I am using the web for uploading the plaso and it is 8gb so sounds like it could be an issue, could you please provide me with a more detailed description on how I adjust it? Sorry doesn’t have much experience with this…

**Comment by johanlundberg92** [comment]
> Where are these error messages from, web frontend or cli-importer?
> 
> The error messages are from the elastic search backend, which stores the uploaded data. Depending on how much data you import, the more memory you will need.
> 
> Have you set the values of OPENSEARCH_MEM_USE_GB in config.env according to your system. Also the SUM_WSGI_WORKERS value should be adjusted.

Where do I find this config file? Sorry I don’t have much experience with this…

**Comment by pydvlpr** [comment]
The file is inside the installation directory, usually /opt/timesketch.

Within you'll find a description to each setting telling you the optimum setup depending on your system

OPENSEARCH_MEM_USE_GB should be half your RAM but max 32 GB

SUM_WSGI_WORKERS should be number of CPU cores +1

**Comment by johanlundberg92** [comment]
> 

The RAM setting there was already at 31GB and I have adjusted the SUM_WSGI_WORKERS according to the rule.

I am wondering if the psort memory limit has something to do with it but don't know how to adjust it...

**Comment by joachimmetz** [comment]
You can add `--process-memory-limit <value>` to the line of code I pointed you to earlier, but to this with care since the limit is there for a reason.

**Comment by johanlundberg92** [comment]
> You can add `--process-memory-limit <value>` to the line of code I pointed you to earlier, but to this with care since the limit is there for a reason.

I find these files inside the timesketch-web container, you happen to know which it its?
```
root@489201053e8a:/# find . -name tasks.py
./usr/lib/python3/dist-packages/plaso/containers/tasks.py
./usr/lib/python3/dist-packages/opensearchpy/client/tasks.py
./usr/lib/python3/dist-packages/opensearchpy/_async/client/tasks.py
./usr/lib/python3/dist-packages/elasticsearch/client/tasks.py
./usr/lib/python3/dist-packages/elasticsearch/_async/client/tasks.py
./usr/lib/python3.8/asyncio/tasks.py
./usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py
./usr/local/lib/python3.8/dist-packages/opensearchpy/client/tasks.py
./usr/local/lib/python3.8/dist-packages/opensearchpy/_async/client/tasks.py
./usr/local/lib/python3.8/dist-packages/celery/worker/consumer/tasks.py
./usr/local/lib/python3.8/dist-packages/celery/contrib/testing/tasks.py
```

**Comment by joachimmetz** [comment]
The file I pointed you to is part of timesketch so `./usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py`

**Comment by joachimmetz** [comment]
What did you change the limit to? The more details you can provide the easier it is to point you in the right direction.

You'll need to determine what is eating up the memory on your installation (also see: https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html#high-memory-usage)

Could you also indicate how you installed timesketch and which versions you are using

**Comment by johanlundberg92** [comment]
```
root@ebbddc15762f:/usr/local/lib/python3.8/dist-packages/timesketch/lib# grep 'memory_limit' tasks.py
        '--index_name', index_name, '--process_memory_limit', ''68719476736
```

**Comment by joachimmetz** [comment]
0 should disable psort enforcing a limit, but the MemoryError can still happen if the process runs out of available memory. 

> Is it okay to change the value while the container is running or do I need to map the file to the host/volume and have it load it right from the start? 

the value needs to be changed before you run the import task, not 100% sure if celery needs to be restarted for it to pick up the changes

**Comment by johanlundberg92** [comment]
Still same error, tried a new deployment of timesketch but still same error, it works if I psort it first an outputs it to CSV (which ironically gets even larger in size) but I loose alot of the fields then like event_identifier for WinEVTX etc... so a lot of sigma rules doesnt work...

**Comment by joachimmetz** [comment]
@johanlundberg92 can you:

* add the `-d` option to psort and provide debug logs, that might indicate what is not working on your installation
* also is this `''68719476736` correct ? or did you mean `'68719476736'` ?

Also see https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html#quick-list for more things you could check

**Comment by johanlundberg92** [comment]
```''``` was a typo yes, will this work you think?
```
cmd.extend(['--process_memory_limit', '0')
cmd.extend(['-d'])
cmd.extend(['--logfile','/var/log/timesketch/custom_log.log'])
```
Fetching the logs from the mapped path of /var/log/timesketch of the host.

**Comment by joachimmetz** [comment]
> will this work you think?

at first glance I see no issues. Know that if you change `/var/log/timesketch/custom_log.log` to `/var/log/timesketch/custom_log.log.gz` psort should use gzip compressed logging

**Comment by johanlundberg92** [comment]
Thanks, I changed to .gz.
Running again now, takes some time before it errors out.

**Comment by johanlundberg92** [comment]
Looks like same error but it did not provide any log file.... (I corrected the square bracket that was missing at the end of the first cmd.extend)

```
2022-02-01 12:36:35,119 [INFO] (MainProcess) PID:137 <data_location> Determined data location: /usr/share/plaso
2022-02-01 12:36:35,434 [INFO] (MainProcess) PID:137 <elastic_ts> Timeline identifier: 15
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 491, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 359, in _ExportEvents
    self._ExportEvent(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 253, in _ExportEvent
    self._FlushExportBuffer(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 411, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 123, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 84, in WriteEvent
    self.WriteEventBody(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 476, in WriteEventBody
    self._InsertEvent(event, event_data, event_data_stream, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 332, in _InsertEvent
    self._FlushEvents()
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 240, in _FlushEvents
    self._client.bulk(**bulk_arguments)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/__init__.py", line 444, in bulk
    return self.transport.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 350, in perform_request
    method, params, body, ignore, timeout = self._resolve_request_args(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 433, in _resolve_request_args
    body = body.encode("utf-8", "surrogatepass")
MemoryError
```

```
root@6125675fbe69:/usr/local/lib/python3.8/dist-packages/timesketch/lib# ls /var/log/timesketch/
worker.log  wsgi_error.log
```

**Comment by joachimmetz** [comment]
I'll have a look when time permits if I see if I can make the changes to get psort logging working. That might hint at why it looks like the psort parameters don't seem to have effect on your configuration.

**Comment by johanlundberg92** [comment]
Did some further investigation and found this:

`4026532168  354194 /usr/bin/python3 /usr/bin/psort.py -o elastic_ts /usr/share/timesketch/upload/a560cff6ea9e4bf2867438bf72df5829 --server opensearch --port 9200 --status_view none --index_name 0a4a55b03d174eeb9d382d914da00ace --elastic_mappings /etc/timesketch/plaso.mappings --timeline_identifier 18`

That namespace:
`4026532168 pid        67 349500 root             /bin/bash /docker-entrypoint.sh timesketch-worker`

This while time I have been changing the tasks.py file on the timesketch-web container, was that incorrect? Because it seems like any changes I make to that file doesn't have any effect.

@jaegeral 
My images:
```
REPOSITORY                                                TAG             IMAGE ID       CREATED         SIZE
us-docker.pkg.dev/osdfir-registry/timesketch/timesketch   latest          26bdba91ca89   12 days ago     616MB
opensearchproject/opensearch                              1.2.2           33d5e431025d   6 weeks ago     836MB
gcr.io/k8s-minikube/kicbase                               v0.0.28         e2a6c047bedd   4 months ago    1.08GB
redis                                                     6.0.8-alpine    8835e6aeca99   15 months ago   31.1MB
postgres                                                  13.0-alpine     700e581c202e   15 months ago   159MB
nginx                                                     1.19.3-alpine   4efb29ff172a   15 months ago   21.8MB
```

**Comment by joachimmetz** [comment]
> This while time I have been changing the tasks.py file on the timesketch-web container, was that incorrect? 

If psort ran on timesketch-worker, then changing code in timesketch-web has little effect on psort. I opt to try to make the same changes in timesketch-worker. Not sure why Plaso would be installed on timesketch-web as well then @berggren might know

**Comment by johanlundberg92** [comment]
Seeing this now after editing the tasks.py on the timesketch-worker... will get back with results.

```
4026532169 /usr/bin/python3 /usr/bin/psort.py -o elastic_ts /usr/share/timesketch/upload/5bd050c1c65a409193c897240452ce9c --server opensearch --port 9200 --status_view none --index_name 8ca89ffc2f164b07adcd2521f92c7650 --elastic_mappings /etc/timesketch/plaso.mappings --timeline_identifier 22 --process_memory_limit 0 -d --logfile /var/log/timesketch/custom_log.log.gz

4026532169 pid        67 364316 root             /bin/bash /docker-entrypoint.sh timesketch-worker
```

**Comment by johanlundberg92** [comment]
I think it worked actually, verifying with a second plaso that where struggling.....

**Comment by johanlundberg92** [comment]
Timesketch actually says 0 events instead now but no errors......... so maybe it didn't work...

**Comment by johanlundberg92** [comment]
It seems to actually work now, I made a new investigation and started fresh. So changing ```--process_memory_limit <value>``` solved the issue.

**Comment by joachimmetz** [comment]
@johanlundberg92 any indication which python module is causing the base memory usage to be high?

**Comment by johanlundberg92** [comment]
Unfortunately no... the log ended up being several gigs so I did not go that through when it all worked eventually.

**Comment by joachimmetz** [comment]
I was more referring to a slightly different check. Per https://github.com/log2timeline/plaso/issues/4029 we noticed that opensearch extra modules have a large memory fingerprint. You can check this by:

* start a Python process
* run `pmap PID`, where PID is the process ID of the Python process
* import opensearch
* and run `pmap PID` again to see how much memory it consumes

In the issue I linked, numpy was consuming a lot of memory
