### ISSUE TITLE
timesketch_importer dont quit when timeline error to upload in opensearch

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2126]
**Describe the bug**
When you upload your timeline by tool timesketch_importer.py, if an error occurs during upload in opensearch, UI timesketch display error on UI (when you click on "info") but the script timesketch_importer.py stay running and never quit (the information of occured error never sent to script).

**To Reproduce**
1. use script  timesketch_importer.py to upload with timeline make error on opensearch
2. When error display on UI "info" check tour script  timesketch_importer.py 
3.  timesketch_importer.py always running

**Expected behavior**
The information of occured error in process to upload in opensearch never sent to script timesketch_importer.py to stop running.
Last error see: MemoryError
![image](https://user-images.githubusercontent.com/1132448/151695137-9a9e14c7-c721-4479-ac94-6ede99c4c46d.png)

**Desktop (please complete the following information):**
- opensearch version 1.2.2
 - Version of timesketch: docker 
```us-docker.pkg.dev/osdfir-registry/timesketch/timesketch   latest            56ee7fb4c917   2 weeks ago     607MB```
 - Version of script: https://github.com/google/timesketch/blob/master/importer_client/python/tools/timesketch_importer.py

**Additional context**

**Comment by jaegeral** [comment]
Hm I am not 100 % sure how we can handle this...

**Comment by berggren** [comment]
This is the background worker crashing because psort ran out of memory. Difficult to catch this as doesn't have a connection to the caller (import client in this case).

We have added a state check for the celery task, so it should surface there. 

I'll close this out for now - feel free to re-open.
