### ISSUE TITLE
Intelligence tab not showing and cannot add intelligence

### ISSUE THREAD

**Issue by johanlundberg92** [google/timesketch#2129]
As the topic says the intelligence tab is not showing and I cannot add anything to intelligence either, the "Add to intelligence is not clickable"
Running latest version.

![image](https://user-images.githubusercontent.com/16693982/152294924-e5b76d5b-9676-448d-a85c-7b340e37185b.png)

![image](https://user-images.githubusercontent.com/16693982/152294797-add3d0c4-8389-4fb3-9590-6eceb965ae77.png)

**Comment by johanlundberg92** [comment]
Yes it is. If I navigate manually to the intelligence page via /intelligence, it is empty, but expecting that since add to intelligence doesn't work...

**Comment by tomchop** [comment]
`Add to intelligence` is not meant to be clickable, but an indicator of what that dialogue box is for. You should use the blue `Add` button to add intelligence to the sketch. 

In the latest master branch, the intelligence tab is always visible - can you tell us what version of Timesketch you're using?

**Comment by jaegeral** [comment]
closing it out, we are moving away from the old UI and there was no update on the issue for over a year.
