### ISSUE TITLE
UI: Intelligence tab needs a "search all" button for the IOCs

### ISSUE THREAD

**Issue by binglot** [google/timesketch#2143]
**Is your feature request related to a problem? Please describe.**
When there are multiple IOCs in the Intelligence tab, I don't have an easy way to search for all of them in the Explore tab.

**Describe the solution you'd like**
A button at the top of the page that takes me to the Explore tab with a pre-populated search query that has an "OR" statement with all the IOCs from the Intelligence tab.

**Describe alternatives you've considered**
A tag or a label for all entries that march the IOCs?

**Additional context**
N/A

**Comment by binglot** [comment]
@tomchop - any progress on this? 😉

**Comment by tomchop** [comment]
Soon! I was working on the preview PR first :)
