### ISSUE TITLE
Introduce a break-glass feature that allow users in privileged group to  access ACLed sketches

### ISSUE THREAD

**Issue by sa3eed3ed** [google/timesketch#2157]
in some cases the analyst who created the sketch is OOO or maybe in a different time zone, while some other analyst need to access the sketch. Having a privileged group who can break-glass will help in such cases

**Comment by jaegeral** [comment]
Would that be fine if it would be the admins who can share a sketch with a specific group or user?

**Comment by berggren** [comment]
Good point. Good news is that it is available as an admin action on the server. How this is used/implemented is up to the deployment though. I'll close this out as WAI, but feel free to re-open if you think that this should be implemented in the UI layer as well.
