### ISSUE TITLE
Make running analyzers via client library a non-blocking server-side job

### ISSUE THREAD

**Issue by sa3eed3ed** [google/timesketch#2158]
make running analyzers, via client library, a non-blocking server-side job? Instead of waiting for all anayzers to finish before the Timesketch upload job finishes. This makes client code run for long time when uploading large number of timelines (i.e. hundreds) and the wait time is big mainly for analyzers

**Comment by jaegeral** [comment]
This sounds like a future, larger rewrite of things effort...

**Comment by berggren** [comment]
Analyzers are already implemented as non-blocking. They run in a distributed queue on the server,  separate from the web serving frontend. 

It is up to the caller (user of the api client) to block or not. Closing as WAI.
