### ISSUE TITLE
Need to migration `node-sass` to `dart-sass`

### ISSUE THREAD

**Issue by digitalisx** [google/timesketch#2173]
**Describe the bug**
Hello, everyone in the community! 🙂
We can see that `node-sass` is used as `DevDependencies` at the frontend of Timesketch.

https://github.com/google/timesketch/blob/172b2cac2e05efa30c26909365bdfb1083d25f64/timesketch/frontend/package.json#L53

However, it is recommended that the module is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and that the community be migrated to [dart-sass](https://sass-lang.com/dart-sass).
These modules rely on older `Python2` and related modules.
This may not be a problem for immediate use, but can increase the complexity of using software in environments that no longer support `Python2` by default.
These issues will reduce the motivation of users, developers, and contributors alike.

**To Reproduce**
This issue can occur when installing components inside the `frontend` folder.

```shell
> yarn install
```

```
error /Users/donghyunkim/timesketch/timesketch/frontend/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/donghyunkim/timesketch/timesketch/frontend/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/donghyunkim/timesketch/timesketch/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/donghyunkim/timesketch/timesketch/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.14.2 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
```

**Expected behavior**
Simplify installation for users and developers with diverse and up-to-date environments

If community maintainers don't have time to patch, please assign the issue to me :)

**Comment by jaegeral** [comment]
@digitalisx  if you want to work on it to migrate, feel free to open a PR.

**Comment by digitalisx** [comment]
All right @berggren, I didn't have enough time to work on this.
I think it will be enough if this is resolved in the course of the project. :)
