### ISSUE TITLE
Make starred events more apparent

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#218]
Right now a starred event just has the yellow star applied to it - if one's focused on the event message or just scrolling down the list of events, a starred event isn't always obvious. 
 
One idea that I found which greatly increased their visibility was simply adding [logic](https://github.com/hiddenillusion/timesketch/blob/6dc1df9126fca36418cfe8fd74de74921407f434/timesketch/ui/static/components/explore/explore-event.html#L35) to the [explore events page](https://github.com/google/timesketch/blob/master/timesketch/ui/static/components/explore/explore-event.html#L27) to highlight the text within the event summary if said event is starred.

**Comment by berggren** [comment]
Good idea! I ficed this is PR 222
