### ISSUE TITLE
CLI client --limit doens't work with --saved-search

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2187]
**Describe the bug**
When running the CLI client and searching the --limit flag doesn't work.

**To Reproduce**
1. timesketch search --saved-search 1234 --limit 5

**Expected behavior**
The output should be limited to 5 entries.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by berggren** [comment]
@jonathan-greig FYI, let me know if you wanna pick up some of the CLI client maintanance

**Comment by jaegeral** [comment]
I will take this.

**Comment by jaegeral** [comment]
Attempts to reproduce:

```
timesketch saved-searches list
4 500
2 foobar
```

The saved search 4 has a search that has 540 results.

**Comment by jaegeral** [comment]
After fix:

```
timesketch search --limit 5 | wc -l
9
```
Which is fine
