### ISSUE TITLE
Internal Service Error when parsing invalid dates

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#219]
Right now if you give an invalid date to the filter, it will give an "Internal Service Error" rather than a more intuitive error that references having an invalid date (e.g.  2016-08-24T010:50:00 vs 2016-08-24T10:50:00 with an extra '0' in the hour).

**Comment by pettai** [comment]
Some sort of input validation and highlighting the field with wrong formatted input would be better approach

**Comment by berggren** [comment]
Timefilters are now much more flexible. Closing this issue as the new system addresses it.
