### ISSUE TITLE
Sigma Overview page 2.0

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2204]
Stuff that people would like to see on the Sigma overview page:

- [ ] aggregation which rules matched how often
- [ ] Sort table of rules after matches
- [ ] create a view to filter after OS / product etc That means a user could filter on all Windows rules, all Linux Rules or see all syslog rules.

**Comment by tomchop** [comment]
> aggregation which rules matched how often

From a UX perspective, I would just plainly say "which rules have hits in our sketch"

> create a view to filter after os / product

Not sure what you mean by this, can you elaborate?

**Comment by jaegeral** [comment]
<img width="1549" alt="screenshot_1" src="https://user-images.githubusercontent.com/741037/171936568-720b06f9-ff62-4590-b287-ec3988956ebb.png">

**Comment by jaegeral** [comment]
Will close this issue as we are tracking several of those efforts in different places like aggregations.
