### ISSUE TITLE
Surface XSRF token errors

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#221]
There is no visible error when there are XSRF token errors from hiding/starring events, and the UI still seems to perform actions as if there were no problems.  It's not until you try an action that actually switches the page that you see the warning message about invalid tokens, and then coming back you can see all the work you've done on the timeline in the meantime was lost.

This can happen if you load a page, leave and come back a while later (not sure how long the tokens are good for, but it's happened to me twice now) and start working on the timeline without re-loading the page.

Maybe an easy shorter term workaround would be to pop up a message to re-load the page if it's been idle for too long.  Or maybe there's a way to refresh the tokens every once in a while?

**Comment by berggren** [comment]
This has been fixed in the new ui.
