### ISSUE TITLE
sigma_rule_status.csv appears to be missing in containers after contrib/deploy_timesketch.sh install script

### ISSUE THREAD

**Issue by wirsiing** [google/timesketch#2223]
**Describe the bug**
After installing timesketch via the Script and starting the docker-containers a 404 error is raised after every request. 

**To Reproduce**
1. Execute the script
2. Open the website
3. Create a new investigation

**Expected behavior**
An investigation is created without the 404 error.

**Screenshots**
Error Message:

<img width="536" alt="grafik" src="https://user-images.githubusercontent.com/14091816/174285704-53d846e6-56da-4bfe-bb2e-f48edce45a04.png">

<img width="812" alt="grafik" src="https://user-images.githubusercontent.com/14091816/174285889-ae8601e1-f855-4cef-b7f1-7b2c48dbc909.png">

**Desktop (please complete the following information):**
- Ubuntu 20.04.4 LTS Kernel: Linux 5.4.0-117-generic Architecture: x86-64
- Browser: Firefox

**Additional context**
To fix it I downloaded sigma_rule_status.csv from this git and manually added it to the etc/timesketch/ folder. After this everything worked as expected. I assume it is for some reason not copied by default anymore but I do not understand the structure of the project well enough to know for certain.

**Comment by wirsiing** [comment]
Hi,

you need to add the following line to deploy_timesketch.sh in row 92 then it should work:
curl -s $GITHUB_BASE_URL/data/sigma_rule_status.csv > timesketch/etc/timesketch/sigma_rule_status.csv

Alternatively you can also download it from 
   https://raw.githubusercontent.com/google/timesketch/master/data/sigma_rule_status.csv

I will create a pull-request once I have more time.

Let me know whether this fixed your issue.

**Comment by jaegeral** [comment]
Thx for the bug report and for triaging, yes that is very much possible. The scripts in /contrib are not the recommended and maintained way of doing things but scripts / helpers / things that might help.
