### ISSUE TITLE
OpenSearch Error: No reason given [Unknown Type/Unkown Detailed Reason]

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#2234]
**Is your feature request related to a problem? Please describe.**
I'm importing data via the importer library, using a notebook (because that's what I do), so essentially

1. open up a notebook
2. create a dataframe using whatever method of my choosing
3. use the importer library to import to TS
4. look at logs....

What do I see:

```
[2022-06-27 12:27:39,435] timesketch.opensearch/ERROR Unable to upload document: rjEhpYEBYiH8dwDwt7sR to index 7217ecc82dba4569ad653f54406472ef - [201] <Unknown Type> No reason given [Unknown Type/Unkown Detailed Reason]

```
I see quite a few of these logs, and they are not that helpful... the best error messages are typically the ones that are unknown, but still, would be helpful to get a bit more detail here.

Then if I tail the opensearch container logs, then I see:

```
[2022-06-27T12:07:02,399][DEPRECATION][o.o.d.r.a.d.RestGetAction] [79304b87aff8] [types removal] Specifying types in document get requests is deprecated, use the /{index}/_doc/{id} endpoint instead.
```

So there is some updating that needs to happen here , probably somewhere in the import logic, that is using a now depracated thing in opensearch.

**Describe the solution you'd like**
Probably a better error report when things are not working as expected in the OpenSearch indexing process.

**Additional context**
Reach out to me if you've got further questions.

**Comment by jaegeral** [comment]
Did that happen with all the data you tried?

**Comment by Zawadidone** [comment]
I have had the same issue when uploading JSONL files produces by `psort.py` to Timesketch, but this does not occure when uploading Plaso files.

**Comment by jaegeral** [comment]
Hm this issue is a year old and so far the only report, I am opting to close it out, if we have multiple reports we can go in it again and try to repro / fix it.

My normal answer would be to "use colab" but well :-)

It seems the colab version of "unknown server error"
