### ISSUE TITLE
Submission of a CSV file with malformed headers creates infinite loop of HTTP requests

### ISSUE THREAD

**Issue by marcobrotto** [google/timesketch#2255]
**Bug Description**
The submission of a CSV with missing mandatory headers fals on the server side. However, even if the clients are notified with an error, they will try to retrieve the timeline using the HTTP requests `/api/v1/sketch/sketch_ID` and `/api/v1/sketch/sketch_ID/timeline/timeline_ID`. These requests are sent until the uploaded CSV file is manually deleted. 

**To Reproduce**
1. Go to Timesketch (TS) UI and submit a CSV file that is not compliant with TS specifications (e.g., missing headers).
2. Refresh the page and verify on the info tab of the submission that you have received the error: `Missing fields in CSV header: datetime,timestamp_desc`
3. Open the network tab on your window and verify that your Browser is sending HTTP requests to retrieve the non-created-timeline, thus it will send indefinitely HTTP requests. 

**Expected behavior**
When a CSV file is sent to the Server and some constraints are missed (e.g., mandatory headers are not present), then the Server should return an error that prevents the client to retrieve a non-existing resources

**Screenshots**
The image below shows the error message that the clients receive when they submit a CSV with wrong headers.
 
![errorMessageTS](https://user-images.githubusercontent.com/108743205/179936232-3091bc7e-52b0-4132-a499-3890f8f0728d.png)

The image below shows the HTTP requests after that the user  submits the CSV and after he receives the error message. In a correct scenario, i.e., when the CSV is correctly formatted, these HTTP requests are used to check the status of the uploading of the CSV file into Opensearch.

![infiniteHTTPReq](https://user-images.githubusercontent.com/108743205/179937085-97ef7602-dcda-4e3a-958a-334b43484724.png)

**Additional context**
UI_2237 should partially solve this problem since CSV files with missing mandatory headers can not be uploaded using the UI.

**Comment by Nexidian** [comment]
@marcobrotto There is a PR merged that addresses this issue. Can this be closed?
