### ISSUE TITLE
Get link to a single event

### ISSUE THREAD

**Issue by anttitikkanen** [google/timesketch#2270]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to get a link to a single event, which can be embedded into external documentation. 

**Describe the solution you'd like**
A "Get Link" button on the event row, which copies a link to the event to the clipboard. When you access the link, you end up on the Explore page that shows only the single event. 

The link could likely use the Opensearch internal docid, as an implementation detail?

**Describe alternatives you've considered**
You can apparently do this also with existing functionality, creating a search that returns the particular event, saving that search, and using the link to the saved search. This is a bit cumbersome.

**Additional context**

**Comment by anttitikkanen** [comment]
I'm happy to implement this if we agree on design.

**Comment by jaegeral** [comment]
Hey Antti, yes I think a link that points to the event id is the best way, I cannot think about any other potential alternative, I would love to see that feature, if you want to give it a try, feel free 👍

**Comment by berggren** [comment]
Hey @anttitikkanen  - this is a great idea. We actually had this feature a couple of years back, but it never made it in the migration of the UI :) But the good news is that this is already possible using URL params. Example:

```
http://127.0.0.1:5000/sketch/3/explore?q=_id%3A%22<opensearch _ID>%22&timeline=<TIMELINE ID>
```

That will give you the explore view with just that single event. So a simple button in the UI next to the event will do the trick!

Here is the old PR for this as reference:
https://github.com/google/timesketch/pull/502

All this being said - I suggest we implement this in the new UI that we are working on. I'm happy to guide you to that and get your environment setup for development. It's not too much work, but then you will be ready for future UI dev work. Let me know.

**Comment by anttitikkanen** [comment]
Ack @berggren ! Happy to add it to the new UI. I've not looked at the state of the new UI yet -- is it close to being on par with old UI? Otherwise I can add this to both, as it seems like such a small tweak.

**Comment by jaegeral** [comment]
```
getEventLink: function () {
  // Set the sketch ID
  var sketchId = this.$store.state.sketch.id;

  // Set the event ID
  var eventId = this.event._id;

  // Set the timeline ID
  var timelineId = this.event._source.__ts_timeline_id;

  // Create the link to the event
  var link = this.$router.resolve({
    name: 'explore',
    params: {
      sketchId: sketchId,
      query: '_id:"' + eventId + '"',
      timeline: timelineId
    }
  });

  // Return the link
  return link;
}

```

Might do the trick
