### ISSUE TITLE
Issue indexing plaso files after uploading

### ISSUE THREAD

**Issue by zpaul-r7** [google/timesketch#2274]
**Describe the bug**
When uploading a plaso file to timesketch via timesketch-importer or through the GUI, we receive the error: 

```
usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE]
                [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u]
                [--status_view TYPE] [--slice DATE_TIME]
                [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                [--language LANGUAGE_TAG] [--dynamic_time]
                [--output_time_zone TIME_ZONE] [-o FORMAT] [-w OUTPUT_FILE]
                [--profilers PROFILERS_LIST] [--profiling_directory DIRECTORY]
                [--profiling_sample_rate SAMPLE_RATE]
                [PATH] [FILTER]
psort.py: error: unrecognized arguments: --server opensearch --port 9200 --index_name 5a96c741d01b401abe20514183df1645 --elastic_mappings /etc/timesketch/plaso.mappings --timeline_identifier 10

```
**To Reproduce**
1. Create plaso file
2. upload via GUI OR timesketch-importer.py
3. failure happens immediately after upload

**Expected behavior**
Once uploaded the plaso file should index properly.

**Screenshots**
![Screen Shot 2022-08-12 at 11 56 28 AM](https://user-images.githubusercontent.com/55293833/184425321-565605e9-e2dc-48ab-b22c-3ebe09ec213d.png)

**Server:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**Comment by jonathan-greig** [comment]
Think this is also causing a e2e tests to fail on PRs [example](https://github.com/google/timesketch/runs/7833775426?check_suite_focus=true).
