### ISSUE TITLE
Support: Run Database outside of docker environment

### ISSUE THREAD

**Issue by HolzmanoLagrene** [google/timesketch#2303]
Hi there

I would love to use an existing _Elasticsearch_  instead of the _OpenSearch_ database. My problem however is, that the database is mapped via ssh tunnel to `localhost:9208` and i just cant get `docker-compose` to handle that:

I tried these two options and both do not work:

- I do not specify any networks in docker-compose: The containers talk to each other but the worker cannot reach localhost.
- I tell the worker to run in the hosts network (`network-mode: host`) and it reaches localhost. As a result it does not reach the other containers anymore.

Does someone know how to deal with this or already has a running docker-compose file?  

Thanks for your help

**Comment by jeffc-s1** [comment]
I'm running with a opensearch cluster outside of my docker environment. All that was necessary in the dockerfile was to comment out the opensearch services declaration, and add my connection info in the timesketch.conf. I am running the most recent docker-compose file however, I know there were a few changes in the last couple months.
