### ISSUE TITLE
Unable to delete aggregation

### ISSUE THREAD

**Issue by Xboarder56** [google/timesketch#2345]
**Describe the bug**
After uploading plaso dumps into timesketch and running 2 aggregators on them (browser and domain) I'm unable to delete any aggregations. I confirmed this as well in a second VM.

**To Reproduce**
1. Import plaso dumps created from Kape data.
2. Add a story and fill in a saved search
3. Run an aggregation and attempt to delete it.

**Expected behavior**
The aggregation would be deleted. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome/Safari (tried both)
 - Version: 105.0.5195.125 (Official Build) (x86_64)

**Comment by jaegeral** [comment]
This is for the old UI, which will be soon deprecated, gonna close the issue for that reason
