### ISSUE TITLE
Update Docker configurations to use Ubuntu 22.04

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#2359]
Plaso switched to Ubuntu 22.04 per https://osdfir.blogspot.com/2022/08/plaso-20220724-released.html. TimeSketch docker configuration still seems to use Ubuntu 20.04 https://github.com/google/timesketch/blob/master/docker/release/build/Dockerfile-latest#L2

Please update

**Comment by joachimmetz** [comment]
@berggren @jaegeral FYI

**Comment by berggren** [comment]
This is done, ref: #2372
