### ISSUE TITLE
Dynamic message field

### ISSUE THREAD

**Issue by Zawadidone** [google/timesketch#2362]
**Is your feature request related to a problem? Please describe.**
When importing data parsed by other tools then Plaso these events don't include the field message with most important fields of the event. 

**Describe the solution you'd like**
I would like to have a feature in Timesketch that dynamically shows all fields in the message field in the frontend without the timesketch [mandatory fields](https://timesketch.org/guides/user/import-from-json-csv/) like message and timestamp_desc as the field message.

For example when viewing documents in Kibana the document fields contains all available fields:

![image](https://user-images.githubusercontent.com/21525407/194843215-70a023d2-32ef-4e06-85e7-f4a6c7032bab.png)

It would be nice if Timesketch could support this by enabling a parameter or special field named message_dynamic for example.

**Describe alternatives you've considered**
Using Logstash to do this before ingesting data to Timesketch/Opensearch/Elastic. But this requires the usage of a message field that contains fields and data that are already part of the document. From a data usage perspective the message field is not needed.

**Comment by berggren** [comment]
Hey @Zawadidone  - this is a good idea. We are developing a new feature that we call `dynamic fields` that will give you the ability to choose whatever field to show in the output. One other feature that just landed for the upcoming new UI is a import helper that will map eny field from a CSV to the message field. We will update the documentation with this as soon as time permits.

**Comment by Zawadidone** [comment]
@berggren is this a feature where I can contribute to? I am not a frontend guy, but if adjustment to Python code is needed I can help.

**Comment by Zawadidone** [comment]
@jaegeral how will this feature be implemented? I have added a few suggestions below.

## 1
As shown in the image (https://user-images.githubusercontent.com/21525407/194843215-70a023d2-32ef-4e06-85e7-f4a6c7032bab.png) the `datetime` field and the full `document` without fields that start with an underscore and the default Timesketch fields like `timestamp`, `timestamp_desc` and `message` will be shown

## 2
The `datetime` field and the full `document` without fields that start with an underscore and the default Timesketch fields like `timestamp`, `timestamp_desc` and `message` will be shown, and additional fields can be selected to be shown in between `timestamp` and the full document.

## 3
@berggren suggested the following `One other feature that just landed for the upcoming new UI is a import helper that will map eny field from a CSV to the message field.`. This solves the issue but creates another issue. The contents of every document is added to a new field (`message`), because of this the size of an Opensearch index will be as twice as big depending on the compressing. In my opion the frontend should combine the necessary fields when shown to the user  by using the data that is already stored in Opensearch.
