### ISSUE TITLE
Unable to load the timesketch API Client

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#2388]
**Describe the bug**
In a notebook container run the command: 

```
from  timesketch_api_client import client
```

This can also be done in a python script, something simple...

**To Reproduce**
1. Write a simple python script, ipython or a notebook
2. Import the Timesketch API Client
3. Prepare to be amazed
4. Experience the disappointment by witnessing an error

**Expected behavior**
I expected the client to be loaded and everyone to be happy...

what happened instead is:

```
ImportError: cannot import name 'external_account_authorized_user' from 'google.auth' (.../lib/python3.8/site-packages/google/auth/__init__.py)
```
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kiddinn** [comment]
This is most likely due to deprecated OOB Oauth FLow

**Comment by jleaniz** [comment]
Hey @kiddinn, which version of the google auth library is installed in your testing environment where you encountered the error?

**Comment by kiddinn** [comment]
no, sorry, this is not TS... I looked closer at this, this is due to a bug in Google OAUTH lib, let me close this, and fix versions we use there
