### ISSUE TITLE
Pagination error with frontend-ng while importing data

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2390]
**Describe the bug**
Hard to explain, that is why I made a video it seem to only happen when there is still a file being imported in the background, causing data to be added to the index while not being full represented in the pagination

**To Reproduce**
See video

**Expected behavior**
Pagination that works :-)

**Screenshots**

**Additional context**
File in question is: https://github.com/jaegeral/timesketch-test-data/releases/download/main/all_packets.csv

https://user-images.githubusercontent.com/741037/197235799-02f32472-f7ce-4f32-8a9a-a25d015cca9f.mov

**Comment by berggren** [comment]
I can't reproduce this. Are there any specific steps taken here that is not shown?
Did you upload a timeline while you were searching maybe?

**Comment by jaegeral** [comment]
I am not sure if I ran into it again since filing the issue, so I am closing it out.
