### ISSUE TITLE
Analyzer can be run on timelines that have not finished importing

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2393]
It is possible to select Timelines to run analyzers while they are still importing. There should be:

a) no possibility to do that in the UI
b) a check in the analyzer code that checks for the status of a timeline before running it

**Comment by jkppr** [comment]
This should not be possible from the UI anymore.

**Comment by jkppr** [comment]
Small update on this issue:
If analyzers are triggered via API during or shortly after the import of a Timeline it still happens that they will be shown as never ending analyzers in the new UI. They will not create any errors anymore and the spinner will timeout after a few minutes.

I'll take a look at the API next, to verify analyzers are only run on timelines that are actually ready.
