### ISSUE TITLE
Frontend-ng "Untag an event" / Remove a Tag from an event

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2396]
If you tag an event e.g. with `suspicious` or `bad`or `good` you might have tagged the wrong event so you want to remove that tag, which is currently not possible.

This is a known issue and will be fixed in Q2, as this requires a new API endpoint, we did not want to introduce it as a new feature right before we make the big switch.

Expected solution:
Have a way to remove a tag from an event.

- [x] Add functionality to API https://github.com/google/timesketch/pull/2689
- [x] Add functionality to Python API client
- [x] Add to cli client
- [x] Add to Web UI

**Comment by jaegeral** [comment]
This is blocked by https://github.com/google/timesketch/issues/2605

**Comment by jkppr** [comment]
Frontend should be ready in my branch: https://github.com/jkppr/timesketch/tree/2396_ui_untag_events

I will review the backend PR in #2605 and then create a PR for the frontend when the backend is merged.

**Comment by jkppr** [comment]
Draft PR: #2694 ready for review. Could be merged as soon as the backend is implemented and the PR adjusted.

**Comment by jaegeral** [comment]
Done
