### ISSUE TITLE
After initial login, the web UI is blank (just a white page)

### ISSUE THREAD

**Issue by Mufassa4n6** [google/timesketch#2411]
**Describe the bug**
I setup timesketch using the instructions per https://timesketch.org/guides/admin/install/. However, after I log into the web interface I am only presented with a blank screen. I have setup and used timesketch several other times. 

**To Reproduce**
1. Install Timesketch
2. Create user
3. Go to logon page (servername:80)
4. Login
5. Blank screen appears
6. If I try https I get connection refused.

**Expected behavior**
I was expecting the usual screen to come up where I can create my cases and stories

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.4 LTS
 - Chrome - From a Windows 11 machine. I alto tried edge and Firefox

**Ngnix Config**

events {
    worker_connections 768;
}

http {
    server {
        listen 80;
        listen [::]:80;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /v2/ {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://timesketch-web-v2:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

**Docker ps output**

CONTAINER ID   IMAGE                                                            COMMAND                  CREATED             STATUS          PORTS
       NAMES
0d69aabea4f5   opensearchproject/opensearch:1.2.2                               "./opensearch-docker…"   About an hour ago   Up 23 minutes   9200/tcp, 9300/tcp, 9600/tcp, 9650/tcp
       opensearch
236acbc8850a   nginx:1.19.3-alpine                                              "/docker-entrypoint.…"   About an hour ago   Up 23 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx
6954cd6d0cec   redis:6.0.8-alpine                                               "docker-entrypoint.s…"   About an hour ago   Up 23 minutes   6379/tcp
       redis
a0085ef1a0a4   postgres:13.0-alpine                                             "docker-entrypoint.s…"   About an hour ago   Up 23 minutes   5432/tcp
       postgres
177b81d2170e   us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest   "/docker-entrypoint.…"   About an hour ago   Up 23 minutes
       timesketch-worker
61bc87d20d34   us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest   "/docker-entrypoint.…"   About an hour ago   Up 23 minutes
       timesketch-web-v2
948dfba63162   us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest   "/docker-entrypoint.…"   About an hour ago   Up 23 minutes
       timesketch-web

**Comment by jknyght9** [comment]
Similar issue to #2410

**Comment by jaegeral** [comment]
Closing in favour of #2410
