### ISSUE TITLE
Install Plaso Instructions Update

### ISSUE THREAD

**Issue by jessemillar** [google/timesketch#242]
The [Timesketch wiki page for Plaso](https://github.com/google/timesketch/wiki/UserGuidePlasoUpload) makes a comment about how certain installation steps "will go away as soon as Plaso 1.5.0 is released." We should probably update that wiki page now since we're on [Plaso 1.5.1](https://github.com/log2timeline/plaso/releases/tag/1.5.1).

**Comment by berggren** [comment]
Good point! I'll update asap.

**Comment by berggren** [comment]
Documen updated.
