### ISSUE TITLE
Install.md: link to admin-cli/ invalid (404)

### ISSUE THREAD

**Issue by mdrenger** [google/timesketch#2424]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md
2. Click on 'here' under Set up users
3. See 404

**Expected behavior**
links to admin-cli.md

**Comment by jaegeral** [comment]
Not an issue, as the links are made to work on Timesketch.org: https://timesketch.org/guides/admin/admin-cli/
