### ISSUE TITLE
MISP and Hashlookup analyzers

### ISSUE THREAD

**Issue by DavidCruciani** [google/timesketch#2428]
**New Analyzers**
Adding of MISP and Hashlookup analyzers. 

**Goal**
- MISP:
    - Search for attributes that match timesketch event and return the associated MISP event url.
- Hashlookup:
    - Identified legitimate file from timesketch events' hashes.

**Comment by joachimmetz** [comment]
@DavidCruciani thanks for the PR unfortunately both projects use the AGPL license. Also see https://opensource.google/documentation/reference/using/agpl-policy

**Comment by adulau** [comment]
@joachimmetz Indeed, the code contributed by @DavidCruciani is not under the AGPL license and under the license of the timesketch project.

To summarise:

- The code contribution in question is not licensed under AGPL, but rather the license of this project.
- The CLA has been signed. I can also confirm that @DavidCruciani has a clause in his working contract for signing CLAs under his work as an employee of CIRCL.  
- For the end to end test, CIRCL provides hashlookup as an open service and we are happy to give you access to a MISP server for testing. No requirement shall be made for Google to install any AGPL code for the testing.

In the scope of the end-to-end test, we are happy to set up a MISP that will be re-imaged daily on a AWS and give you permanent access to it.

**Comment by joachimmetz** [comment]
@adulau thanks for the additional context. I understand that the contributions are not under the AGPL license. We've asked for additional guidance seeing the previously linked policy and controversy around the license.
