### ISSUE TITLE
Issue using tsctl

### ISSUE THREAD

**Issue by jamdunnDFW** [google/timesketch#243]
I'm getting the following error when trying to install timesketch using the instructions from the wiki (https://github.com/google/timesketch/wiki/Installation). I'm attempting to install on Ubuntu 14.04.

Anyone run into this issue before?

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 34, in <module>
    from timesketch import create_app
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 26, in <module>
    from timesketch.api.v1.resources import AggregationResource
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 39, in <module>
    from flask_login import current_app
ImportError: cannot import name current_app

**Comment by MajinLogan** [comment]
I have had the exact same issue when I attempt to add a user.

**Comment by csash** [comment]
Flask-Login did some refactoring between v0.3.2 and v0.4.0 that changed where this import lives. As a temporary workaround, installing Flask-Login v0.3.2 instead will fix this issue. 

I think all the current_app imports can just be changed to importing from flask instead of flask_login though.
