### ISSUE TITLE
Move the XML prettify function into context links?

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2449]
At the moment the xml prettify feature is a separate function in the [EventDetail.vue](https://github.com/google/timesketch/blob/master/timesketch/frontend-ng/src/components/Explore/EventDetail.vue). With the introduction of Context Links in #2439 it might be worth to check if it makes sense to integrate the prettify feature into the context link sub-menu.

**Comment by jkppr** [comment]
Idea: Change the `mdi-open-in-new` icon for context links to something more general like e.g. `mdi-vector-link` and then include features like the prettify function, or future unfurl and intelligence integrations into the submenu. Here each item gets the appropriate icon, e.g. `mdi-open-in-new` for context_links and the `mdi-xml` for the prettifier etc.

**Comment by jaegeral** [comment]
This has been implemented, so we can close the issue, thx @jkppr
