### ISSUE TITLE
Integrate "send to intelligence" with context links.

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2453]
Related to #2439 .

In the old UI we had a feature to mark parts of an EventDetail value and when clicked again a submenu opens that allows us to add the marked part to be added to the Intelligence tab. 

![4XeVo4qh26BnBRj](https://user-images.githubusercontent.com/99879757/206188719-0183798e-c349-4981-a17e-5238b0457ce9.png)

This feature is not available in the new v2 UI yet. We should research on how to integrate this function with the context link submenu, to send specific IoC to the intelligence tab.

**Comment by jaegeral** [comment]
This still seems relevant, I am adding it for Q2 to get feature match.
