### ISSUE TITLE
Display plaso version in Timesketch importer

### ISSUE THREAD

**Issue by jnimmo** [google/timesketch#2457]
**Is your feature request related to a problem? Please describe.**
I've been struggling to find a supported version of Plaso, keep running into import issues. 

**Describe the solution you'd like**
- Display the current Timesketch version somewhere on the import screen so users can see which version they should install. 

- Alternatively, ensuring the documentation is clear and up to date with the correct Plaso version
- For bonus points, exposing the current version via an unauthenticated API call would be awesome (for example /info/plaso) so we can obtain the current plaso version number through automation and install the correct version

**Comment by jaegeral** [comment]
This has been implemented with: https://github.com/google/timesketch/pull/2631
