### ISSUE TITLE
Unable to publish Timesketch on a non-standard port

### ISSUE THREAD

**Issue by jnimmo** [google/timesketch#2458]
**Describe the bug**
When presenting Timesketch on a non-standard port (through NAT port forwarding or editing the Docker file to publish a different port), any requests to Timesketch result in the browser redirecting back to the default port. This is due to the nginx $host environment variable not including the port number.

**To Reproduce**
1. Edit the docker-compose.yml file to expose Timesketch on port 8080 ("8080:80")
2. docker-compose up
3. Browse to localhost:8080
4. The browser redirects to https://localhost/login?next=%2F

GET http://localhost:9080/
302 Redirect > http://localhost/login/?next=%2F

**Expected behavior**
The redirection should include the non-standard port
i.e. http://localhost:9080/login?next=%2F

**To Fix**
Edit nginx.conf to update "proxy_set_header Host $host" to "proxy_set_header Host $http_host"
$http_host includes the port number when connecting to a non-standard port.

**Additional context**
For more information about this problem with other applications, see https://serverfault.com/a/916736

**Comment by jaegeral** [comment]
As this is covered in the doc now instead of code, I am going to close here, thank you for raising this issue.

https://timesketch.org/guides/admin/install/
