### ISSUE TITLE
missing installed-files.txt ?

### ISSUE THREAD

**Issue by juju4** [google/timesketch#246]
can't list files owned by timesketch

```
# pip show -f timesketch

---
Name: timesketch
Version: 2016.7
Location: /usr/local/lib/python2.7/dist-packages
Requires: Flask-RESTful, Flask-Migrate, Flask-Login, Flask-script, blinker, Flask, Flask-SQLAlchemy, redis, Flask-WTF, celery, SQLAlchemy, Flask-Bcrypt, elasticsearch
Files:
Cannot locate installed-files.txt
```

**Comment by berggren** [comment]
Are you using virtualenv? This happens for me when I have it installed in virtualenv, ut it seems to work when I'm installing it on the system.

**Comment by juju4** [comment]
No virtualenv, ansible role tested in lxc container or travis/docker (https://travis-ci.org/juju4/ansible-timesketch)
https://github.com/juju4/ansible-timesketch/blob/master/tasks/main.yml#L38
checked nok on trusty
checked ok on xenial

have few more checks to do in my role that I will push later

**Comment by berggren** [comment]
I can't reproduce this. Please re-open if this is still an issue.
