### ISSUE TITLE
import jsonl error if have not 3 lines

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2467]
**Describe the bug**
If your file.jsonl must have 3 lines min else you receive a error

**To Reproduce**
sample:
```
{"message": "A message","timestamp": 123456789,"datetime": "2015-07-24T19:01:01+00:00","timestamp_desc": "Write time","extra_field_1": "foo"}
{"message": "Another message","timestamp": 123456790,"datetime": "2015-07-24T19:01:02+00:00","timestamp_desc": "Write time","extra_field_1": "bar"}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1132448/208158678-3e34ee03-371a-4976-bacd-8efbb9a8614e.png)

If you add one line more, you dont have error and you can upload jsonl.

**Additional context**
Timesketch docker version: "us-docker.pkg.dev/osdfir-registry/timesketch/timesketch   latest            915624b6d4e0   27 hours ago    737MB"

**Comment by FazlOmar9** [comment]
Hey! If this is still relevant, I'd like to work on this. Could you please give me the details for this?

**Comment by jasochen7** [comment]
Hello, I'm interested in working on this issue and am really passionate about the timesketch project. How can I get started in addressing this issue?

**Comment by jaegeral** [comment]
Hey @FazlOmar9 and @jasochen7  I am not sure about your ask here, where do you struggle to get started?

**Comment by jasochen7** [comment]
Just to clarify the error; are there any requirements that follow beyond the immediate description of the task? I.e. are there any reliability thresholds or other criteria that a solution must meet?
