### ISSUE TITLE
How to clear failed Celery tasks? (plaso upload feature)

### ISSUE THREAD

**Issue by tt1379** [google/timesketch#250]
Hi

Forgive the stupid question; I made an error when configuring the [upload feature](https://github.com/google/timesketch/wiki/UserGuidePlasoUpload). I've fixed that now, but I can't seem to clear the error from the web interface? 

Is there an easy way to do this?

![plaso_error](https://cloud.githubusercontent.com/assets/13198524/19974299/ea32660e-a1df-11e6-91f9-47d6069a45f4.png)
Thanks!

**Comment by berggren** [comment]
Hi, no, unfortunately not at the moment. I'm about to refactor and change the whole upload UX after this release and will revisit this then.

In the meantime you can test to purge the Celery queue:
# celeryctl purge

**Comment by tt1379** [comment]
Ok, thanks for your help.
