### ISSUE TITLE
Inconsistencies in the Aggregation section of the Timesketch API

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#2503]
Some inconsistencies in the TS Python API when interacting with aggregation. This was something that I found when calling [list_aggregations](https://github.com/google/timesketch/blob/1cef69b041c488878f062ce9e515313aa05f96cd/api_client/python/timesketch_api_client/sketch.py#L545), and was confused as to why the `.name` attribute of the returning objects was not the one returned by the API (`"sketches/{self.id}/aggregation/"`). It seems the `name` and `description` of the Aggregation object are extracted from `resource_data`, which is populated by [from_saved](https://github.com/google/timesketch/blob/1cef69b041c488878f062ce9e515313aa05f96cd/api_client/python/timesketch_api_client/aggregation.py#L136).

So this goes like this:

1. list_aggregations, query to `sketches/{self.id}/aggregation`
2. At this point, I'd expect the funciton to return these results, but it goes on
3. `from_saved` is called for each aggregation (which I expected loaded pre-cached results from a database), calling another API endpoint, presumably to get fresh aggreagtor data. This is the data containing the right name and description for the aggregation.
4. `from_saved` calls `_run_aggregator` (which runs the aggregation once more?) and stores the result in the resource_data attribute of the `self` object. (maybe erroneously, instead of doing this with the results of the previous API call?)
5. When `list_aggregations` returns, the objects it returns are a list of results of _run_aggregator, which don't contain the expected data.

**Comment by sydp** [comment]
Having looked at the code a bit more today, it seems there are two "names" for an aggregation.  The first being the name defined by the user (and the expected value when calling the ```.name``` attribute) and the second being the aggregator name, drawn from the ```NAME``` class attribute of BaseAggregator implementations.  

To avoid confusion, I'll update the python API aggregation resource to have two attributes:
* ```name``` - the "expected" name value defined by the user
* ```aggregator_name``` (NEW) - the aggregator name
