### ISSUE TITLE
Starring timeline entries does not work

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#252]
Hi all,

after installing a new timesketch instance from the current master branch, starring does not work anymore. 
I've attached the error message thrown while using the star button.

Cheers,
Sven
[error_ts_issue.txt](https://github.com/google/timesketch/files/578521/error_ts_issue.txt)

**Comment by berggren** [comment]
Hi, this is because we moved away from dynamic scripting in ES to server side scripting instead. The documentation will be updated for the release, but here is what you need to do:

copy contrib/*.groovy /etc/elasticsearch/scripts/ and restart elasticsearch. This should fix the problem.

**Comment by n3x77** [comment]
Thx @berggren ; Works fine!

Bye!
