### ISSUE TITLE
GOOGLE_OIDC_ALGORITHM leads to None variable

### ISSUE THREAD

**Issue by Zawadidone** [google/timesketch#2522]
**Describe the bug**
Using the config variable `GOOGLE_OIDC_ALGORITHM=None` leads to no alogrithm value set. Besides that I could not find a reason why this variable is used in a function that is made for the `GOOGLE_IAP_*` variables.

**To Reproduce**
1. Start Timesketch on GCP with the variables `GOOGLE_IAP_*` set 
2. Open the Timesketch URL
3. Login on the IAP
4. See logs `timesketch.app/ERROR JWT validation error: The specified alg value is not allowed`

**Expected behavior**
1. Start Timesketch on GCP with the variables `GOOGLE_IAP_*` set 
2. Open the Timesketch URL
3. Login on the IAP
4. Succesfull login to Timesketch

**Comment by berggren** [comment]
Following up here, I'll take a look today and will update this bug

**Comment by Zawadidone** [comment]
Note that in a fork of Timesketch I made this adjustment (https://github.com/hnhdev/timesketch/commit/63fa7737b38ce0a15913fd67dcaa8f14a822b14c) which works with a working GCP IAP.
