### ISSUE TITLE
Implement Docker tags to identify Timesketch versions

### ISSUE THREAD

**Issue by jnimmo** [google/timesketch#2524]
**Is your feature request related to a problem? Please describe.**
There seems to be no easy way to tell what commit/tag the Timesketch docker image was built from which makes it difficult to know what version of the code you're using.

**Describe the solution you'd like**
Docker tags should be included in the build process to allow installing a specific version.
Tags should be built for releases, Github commit SHAs (edge)

i.e. 
- latest
- 20210224
- edge
- sha-a14f758

**Additional context**

**Comment by berggren** [comment]
This has been implemented. All releases now have a tagged docker image.
