### ISSUE TITLE
Sort Saved Views alphabetically

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#253]
Hi, 

after saving a few views in timesketch, it may be very usefull to sort the dropdown of the saved views alphabetically. So when using a naming convention for different types of views it might be better easier to use. 

In the current master from github it seems that by using multiple filters for one sketch, sometimes the order of the saved views is changing.

Bye,
Sven

**Comment by berggren** [comment]
Good idea! I'll add it to the roadmap.

**Comment by berggren** [comment]
This has now been fixed.
