### ISSUE TITLE
Not able to switch timeline pages after tagging an entry

### ISSUE THREAD

**Issue by bluefox6** [google/timesketch#2530]
Hello everybody,

**Describe the bug**
After tagging an entry in my timeline (1) I can't move to the next or previous page anymore (2). If I click on the "<" or ">" button nothing happens  So I have to refresh the page in my browser that this works again. 
![Screenshot from 2023-02-02 09-27-29](https://user-images.githubusercontent.com/124274695/216354342-e864aeac-be84-48d2-83da-667c678fa24d.png)

Furthermore, after tagging an entry I see an error message pop up if I inspect the page with DevTools.
![Screenshot from 2023-02-02 09-46-57](https://user-images.githubusercontent.com/124274695/216358164-c55f0671-dba3-4660-80c2-14c378450ea4.png)

**To Reproduce**
- I'm hosting timesketch with docker as described here: [https://timesketch.org/guides/admin/install/](url)

**Expected behavior**
I expect the tagging to have no effect on switching to the previous or next page.

**Desktop**
 - OS: Ubuntu 22.04.1 LTS
 - Browser : Mozilla Firefox (109.0.1 (64-bit))

Thanks for your help and best
bluefox6

**Comment by jaegeral** [comment]
As this is still the old UI; I am gonna close this issue as obsolete.
