### ISSUE TITLE
Add the ability to filter on analyser (added) tags under filter options

### ISSUE THREAD

**Issue by pettai** [google/timesketch#255]
Under filter option "Choose which data types to query" where you can filter on various data types,
it would also be useful to add the possibility to filter on analyser tags.

For instance, I'd like a simple way of hiding all the nsrl_present tagged events. So an "tag:nsrl_present" data type with a check button would be nice...

**Comment by berggren** [comment]
I'm planning on adding a more flexible filtering option here, basically you can sure to filter out any attribute available.

In the mean time you can use "AND NOT tag:nsrl_present" for example to filter out those events.

**Comment by pettai** [comment]
Ok thx!

**Comment by berggren** [comment]
Closing this out as the functionality is present in the query string. We will track the new filter addition an another bug.
