### ISSUE TITLE
UI feedback: Add deselect other timelines on menu

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2555]
**Describe the solution you'd like**
When clicking the timeline we should add an option to deselect all other timelines.

**Comment by jaegeral** [comment]
yes, while I think it is important, it is not a blocker for the migration, so adding it to Q2.

**Comment by gstgrace** [comment]
I'm working on this.

**Comment by jkppr** [comment]
@gstgrace here are some issues that you might be interested in working on as an alternative:
* #2693 
* #2813 
* #2802
