### ISSUE TITLE
psycopg2.ProgrammingError) column view.query_dsl does not exist

### ISSUE THREAD

**Issue by jasonblanks** [google/timesketch#257]
Was trying to upgrade to the current version of timesketch, believe I was on the last version.   Just did a pip install timesketch -U.

Is there a guide to upgrading?

ProgrammingError: (psycopg2.ProgrammingError) column view.query_dsl does not exist LINE 1: ...y_string, view.query_filter AS view_query_filter, view.query... ^ 

[SQL: 'SELECT view.id AS view_id, view.created_at AS view_created_at, view.updated_at AS view_updated_at, view.name AS view_name, view.query_string AS view_query_string, view.query_filter AS view_query_filter, view.query_dsl AS view_query_dsl, view.user_id AS view_user_id, view.sketch_id AS view_sketch_id, view.searchtemplate_id AS view_searchtemplate_id \nFROM view \nWHERE %(param_1)s = view.user_id AND view.name = %(name_1)s ORDER BY view.updated_at DESC \n LIMIT %(param_2)s'] [parameters: {'name_1': u'', 'param_1': 1, 'param_2': 1}]

**Comment by jasonblanks** [comment]
just an update deleted existing postgres db wiped ES starting fresh and appears to be working fine.  Just hoping for direction on upgrades just don't want to have to delete all investigation data on future updates.

**Comment by berggren** [comment]
Sorry for the inconvenience here. You need to migrate to the new database schema and I see that the documentation for that is missing. This is something that I will fix asap. tl;dr - backup your database first (!), run tsctl db upgrade from the timesketch src dir.

I will write the docs for this.

**Comment by jasonblanks** [comment]
Awesome! Adding to personal notes.

**Comment by berggren** [comment]
Hey, I have added some documentation for upgrading Timesketch. Let me know if you still have problems.
