### ISSUE TITLE
UI feedback: Having Timelines in the left Panel

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2574]
**Describe the solution you'd like**
With large amounts of Timelines, it might be useful to have the Timelines listed on the left int he leftbar as a searchable table where you can select / un-select Timelines.

That would also enable Searching for e.g. certain parts of a hostname that is in the timeline name and bulk enable / disable all found timelines.

This feature could be seen as an addition to the existing Timeline selector in the main panel of the explore view.

**Screenshots**
![Timeline left panel](https://user-images.githubusercontent.com/741037/219331580-7ddb7134-5c58-495b-97f9-30e144b18f65.png)

**Comment by jkppr** [comment]
This will be tackled in the Timeline Management project: https://github.com/google/timesketch/projects/20

**Comment by jkppr** [comment]
Timelines are available in the left panel by now.
