### ISSUE TITLE
column view.query_dsl does not exist

### ISSUE THREAD

**Issue by owllie90** [google/timesketch#258]
Hi,

I ran tsctl runserver -h 0.0.0.0 -p 5000 and able to see the login page.

but once i login, it showed me internal error 500,

And it prompted "ProgrammingError: (psycopg2.ProgrammingError) column view.query_dsl does not exist

Kindly advise.

Thanks

**Comment by berggren** [comment]
Hi, sorry for the delay. See the documentation on upgrading:
https://github.com/google/timesketch/wiki/Upgrading
