### ISSUE TITLE
UI feedback: Error Details text color same as background color

### ISSUE THREAD

**Issue by Aevyz** [google/timesketch#2588]
Heyho, small UI bug I found. 

# Reproduction

1. Enable Dark Mode
1. Generate a plaso file that is unsupported 
2. Create a new investigation
3. Upload the plaso file via the Web Interface
4. Click on more details regarding the error
5. Error field in dark mode is white

# Screenshots
Light mode
![image](https://user-images.githubusercontent.com/17731961/222177885-5f24ac4d-dc9f-4f7b-bbda-0e82bd914ddc.png)
Dark Mode (Problem here)
![image](https://user-images.githubusercontent.com/17731961/222177798-e3affbef-1abe-44c0-bf30-85d0fdf44216.png)

**Comment by Aevyz** [comment]
Related to #1810

**Comment by jaegeral** [comment]
This is old UI, going to close it out.
