### ISSUE TITLE
UserGuideTimelineFromFile wiki page - update to use microsecond timestamps

### ISSUE THREAD

**Issue by csash** [google/timesketch#259]
At the moment, the timestamp field actually needs to be a microsecond timestamp. Some of the math (for instance, to compute start/end times for context queries) expects microsecond timestamps. Also, if there's a mix of timestamp formats, a number of other things go wrong, like the overall display of events on the explore tab and computation of time between events.

**Comment by berggren** [comment]
Thanks, good point! The code for importing CSV files need more work. First priority is to add validation of the input so we can catch these kind of things at import time. See #195.

**Comment by berggren** [comment]
Done.
