### ISSUE TITLE
Problems opening a .plaso container with "Format version : 20160715" with plaso 1.5.1

### ISSUE THREAD

**Issue by acecilia** [google/timesketch#260]
Hello:

I got a .plaso container that I need to read. I installed the last version 1.5.1 in my Mac with ElCapitan. When running psort.py I am getting nothing (also the output file is empty):
![captura de pantalla 2017-01-14 a las 13 22 15](https://cloud.githubusercontent.com/assets/7938671/21954810/91005612-da5c-11e6-99e4-a345be664bfb.png)

After reading https://github.com/google/timesketch/issues/256 I realized that it could be the reason. I checked the .plaso container with pinfo.py and I got:
![captura de pantalla 2017-01-14 a las 13 20 33](https://cloud.githubusercontent.com/assets/7938671/21954815/c99a834e-da5c-11e6-9e5a-6169b9904048.png)
I saw that the formatVersion date shown there is from the moment when plaso was in it's 1.4 version, so probably the .plaso container is created with plaso 1.4. I downloaded plaso 1.4. Because I did not see any uninstallation guide or information about how to remove plaso, I run the install.sh of plaso 1.4 straight. Now I am stuck with an error when running any log2time python scripts:
![captura de pantalla 2017-01-14 a las 13 26 41](https://cloud.githubusercontent.com/assets/7938671/21954827/1f2ee8a4-da5d-11e6-9bf2-d01bfd6ff5d1.png)
I totally run out of ideas at this point (I run install.sh of plaso 1.5.1 again, but now I am getting the same error above).

**Comment by acecilia** [comment]
I am not interested in the solution anymore (finally found the needed information by other means). Closing, thanks!

**Comment by joachimmetz** [comment]
acecilia@ plaso installation uses the macOS package manager; and yes it is not as user friendly as package mangers of other operating systems, but the solution is to deinstall plaso. I'll make a note to add a remove.sh.
