### ISSUE TITLE
[frontend-ng] timestamp_desc missing from list of mandatory headers in upload form

### ISSUE THREAD

**Issue by csash** [google/timesketch#2630]
**Describe the bug**
timestamp_desc is a mandatory header for a CSV/JSON upload but is missing from the list of mandatory headers in UploadForm.vue. If a user uploads a file without a timestamp_desc field, they will not have the opportunity to map the field in the UI. 

Offending code:

https://github.com/google/timesketch/blob/feae441954926ea5db65fc5c78b607db7eaab0b7/timesketch/frontend-ng/src/components/UploadForm.vue#L182-L185

**To Reproduce**
1. Upload a CSV file without a timestamp_desc field
2. You won't be prompted to map the field
3. The file will upload successfully but fail processing because of the missing timestamp_desc header

**Expected behavior**
The user has the opportunity to map the timestamp_desc header like the other mandatory headers in the upload form

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by csash** [comment]
Disregard. Apparently I can't read...

**Comment by ravensics** [comment]
I am facing the same issue. How did you resolve this?
