### ISSUE TITLE
UI feedback: Align elements in the left panel

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2659]
**Describe the solution you'd like**
The left + symbols in the left panel for Stories and TI are a bit more left than the centered ones which align with the numbers.

**Screenshots**
![leftPanelpolish](https://user-images.githubusercontent.com/99879757/229834251-74d37ab2-1808-4e32-8ab9-cc5bc40f4c0b.png)

**Comment by sosa-e** [comment]
Hello, I am new to open source and would like to work on this
