### ISSUE TITLE
UI: Display an active analysis counter

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2675]
At the moment we have only a loading circle displayed left to the analyzer results counter and a loading circle for each timeline that is still loading.
It would be great if:
* The loading circle on the "Analyzer Results" shows a counter of left active sessions.
* Each Analyzer also shows a loading circle if there is a matching active session (including a counter for the number of timelines processed with this analyzer at the moment)

**Comment by Annoraaq** [comment]
There is still one part unresolved (the second bullet point)
