### ISSUE TITLE
UI: Analyzer Result searches on the wrong field

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2676]
**Describe the bug**
When there are more than 10 different analyzers run, the Analyzer Result section in the left panel will display a search bar for better navigation. However, the search is based on the `analyzer_name` key and not on the `analyzer_display_name` value which is the value visible to the user.

**To Reproduce**
1. Run > 10 different analyzers, including the `Windows logon/logoff events` analyzer
2. When the search bar shows up, search for `Windows` 
3. This will not result in `Windows logon/logoff events` showing up, since the analyzer_name is `login`.
4. Search for `login` and `Windows logon/logoff events` will show up.

**Expected behavior**
1. The search should be based on the display_name that is visible to the user.
2. (optional) It would be great if the search would also work for timeline names.

**Comment by jkppr** [comment]
@Annoraaq thanks for fixing the search so it does work on the display_name for now. Are you going to look into the optional part of searching for timeline names as well? Or shall we just close it out and keep it like this for now?

**Comment by Annoraaq** [comment]
@jkppr I will look into the optional part, too.
