### ISSUE TITLE
[UI] Tags error with non plaso data

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2680]
**Describe the bug**
Timelines that are not imported/processed via plaso don't have a tags attribute by default. When trying to add a tag in the new UI (e.g. quick tags) to such an event, it will throw an error since the attribute does not exists yet in the event.

**To Reproduce**
1. Import data that is not generated by plaso.
2. Try to add a tag there.
3. See error

**Expected behavior**
With the new UI we changed the way tags work from database (ex labels) & attributes (tags) to attributes in the event only. The expected behaviour is, for the tagging feature to add an `tag` attribute if it does not exist yet.

**Comment by jaegeral** [comment]
I tested it with timesketch-cli, and there it works:

```
events annotate --timeline-id 10 --event-id AsdDj4cBkeTGnypecZyo --tag doesthatwork_janisch
{'meta': {'comments': []}, 'objects': {'__ts_timeline_id': 10, 'datetime': '2015-07-24T19:01:03+00:00', 'extra_field_1': 'baz', 'message': 'Yet more messages', 'tag': ['doesthatwork_janisch'], 'timestamp': 123456791, 'timestamp_desc': 'Write time'}}
```

So this should only need a fix in the UI
