### ISSUE TITLE
UI feedback: Add tooltips to all the new icons

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2693]
**Describe the solution you'd like**
With the switch to the new UI, there are plenty of new icons for many different actions. Many actions still miss tooltips if they have no description next to it.

Icons I found that need a tooltip (incomplete list):
- [ ] Trigger search (search bar magnifying glass)
- [ ] Tooltip on the timeline chip for truncated timeline names
- [ ] Save search action
- [ ] Time chart icon
- [ ] select columns icon
- [ ] more settings icon
- [ ] star event
- [ ] tag event
- [ ] action menu
- [ ] Copy icon in the event details
- [ ] Aggregation icon in the event details
- [ ] Icons in the graph view
- [ ] Tooltip of truncated data in the Threat Intelligence table (left panel)
- [ ] Tooltip for the + icons in the left panel
- [ ] Tooltip for the manage icons in the left panel
- [ ] Icons in the Threat Intelligence feature

**Comment by jkppr** [comment]
@Fryyyyy since you mentioned running into this today, are you missing any other tooltip not listed above?

**Comment by Fryyyyy** [comment]
Those cover the ones I encountered

**Comment by gstgrace** [comment]
I'm working on this.

**Comment by bryankhor07** [comment]
I'm working on this.

**Comment by jkppr** [comment]
@bryankhor07 are you still working on PR #2952?
