### ISSUE TITLE
error during sigma rule import

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2720]
**Describe the bug**
When importing a sigma rule that has a `:` in the description the python backend crashes.
Example for such a rule: https://github.com/google/timesketch/blob/master/data/sigma/rules/win_suspicious_keywords.yml

**To Reproduce**
1. Copy the rule from https://github.com/google/timesketch/blob/master/data/sigma/rules/win_suspicious_keywords.yml
2. Try to import the rule via the `tsctl` tool or UI
3. There will be an error in the frontend and a traceback in the backend logs.

**Expected behavior**
iirc `:` are not prohibited in the sigma rule description. So this should either fail with an useful information for the analyst or not fail at all.

**Comment by jaegeral** [comment]
Uh good catch, I need to wait for the e2e tests to finish before merging.

Thanks for the fix

**Comment by jkppr** [comment]
Thanks for the fix!

@jaegeral probably your rule validation in the editor should check for this as well and highlight it appropriately instead of crashing.
