### ISSUE TITLE
Support DFIQ

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2781]
Support the upcoming DFIQ format to create Investigative Scenarios.

**Comment by thinrope** [comment]
A paragraph explaining how to import/setup https://github.com/google/dfiq/ into /etc/timesketch properly will be great here!
Is simply copying `data/*` into `/etc/timesketch/dfiq/` enough?

**Comment by jaegeral** [comment]
That will come soon (think weeks) with plenty of documentation, what it is, how to use it etc etc.
