### ISSUE TITLE
Timesketch_importer duplicates jsonl events (imports twice)

### ISSUE THREAD

**Issue by boingomw** [google/timesketch#2796]
**Describe the bug**
timesketch_importer runs twice when executed on json_line files, resulting in double events.

**To Reproduce**
1. Create a sample timeline:  
log2timeline.py --storage_file example.plaso /usr/bin
2. verify how many lines are in the file:  
pinfo.py example.plaso
3. import into timesketch: 
timesketch_importer --host http://127.0.0.1:81 -u examiner -p xxxxxx --sketch_id 19 example.plaso
4. verify in gui you have 1 import and the correct # of events
5. convert the plaso to json_line (normally, this is done for a reason, like slicing or something):
psort.py -o json_line -w example.jsonl example.plaso
6. get a word count to verify the # of messages hasn't changed:
wc example.jsonl
6. Import this into timesketch:
timesketch_importer --host http://127.0.0.1:81 -u examiner -p xxxxx--sketch_id 19 example.jsonl
7. Check Gui:
[example-jsonl](http://lava.im-lab.local:81/legacy/sketch/19/explore?timeline=39)
14.1K events (2 imports: details)
[example](http://lava.im-lab.local:81/legacy/sketch/19/explore?timeline=38)
7K events (imported with CLI importer tool)

**Expected behavior**
Expected it to not double import

**Screenshots**
![image](https://github.com/google/timesketch/assets/17418298/40891587-c5af-4bdc-9fa1-905278f3a68d)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 22

latest docker install, as of 6/15/2023

**Comment by S-Nicholas** [comment]
Same issue as https://github.com/google/timesketch/issues/2334

**Comment by berggren** [comment]
@boingomw I see that you have 2 imports reported. This indicates that you ran the importer twice with the same timeline name. That will put the events in the same timeline.

Can you confirm that this isn't the case? I can't reproduce this issue on my end.

**Comment by boingomw** [comment]
I did run it twice.  once for the .json file and once for the .plaso file.  The issue is that the files both had the same amount of lines in them, but when I imported the json file, it ended up having 2x the number of events.

so when you do the process above you end up with 7k for the .json and 7k for the .plaso file?

**Comment by arisjr** [comment]
I can confirm here that timesketch_importer is also creating doubled sources for JSONL imports, doubling the events on searches. The same does not apply to web imports, that seems to import correctly. 

If you need a sample jsonl, I can supply. 

Regards,

**Comment by boingomw** [comment]
Maybe it's volume related and 5 isn't enough lines to trigger

**Comment by arisjr** [comment]
[sample.zip](https://github.com/google/timesketch/files/12718675/sample.zip)

@jaegeral , try this. password: sample123
It has 484 events, but doubles up on importing. 

Regards

**Comment by arisjr** [comment]
@jaegeral I just realized that you're using timesketch cli instead of timesketch-import-client (timesketch_importer). Is there any difference on the approaches?

**Comment by jaegeral** [comment]
Hm indeed, it is importing them twice.

**Comment by jaegeral** [comment]
fwiw, I am still working on this, it seems my e2e tests in https://github.com/google/timesketch/pull/2976 does not trigger it.

**Comment by mari0d** [comment]
Still seeing this bug in the latest version of TS.  Looking at the code this [flush call](https://github.com/google/timesketch/blob/master/importer_client/python/tools/timesketch_importer.py#L144) isn't needed since the stream [close method](https://github.com/google/timesketch/blob/master/importer_client/python/timesketch_import_client/importer.py#L711-L726) calls flush. We are seeing duplicates because `flush()` is called twice (and the `_data_lines` buffer isn't cleared directly by `flush()` which makes the method name a bit misleading).
