### ISSUE TITLE
Support emojis in new UI

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2802]
When running the default feature extraction there are rules like [gmail_accounts](https://github.com/google/timesketch/blob/master/data/features.yaml#L74) which are adding an emoji to the event. However, this seems not to work in the new UI yet.

**Old UI:** 
![image](https://github.com/google/timesketch/assets/99879757/8e29a8a4-51f7-4596-b43a-e159ad6439cb)

**New UI:**
![image](https://github.com/google/timesketch/assets/99879757/3d563b10-f3b5-4588-9e64-02d73bf1b16c)

**Comment by NightAcrobat777** [comment]
@jkppr I can help with this issue.

**Comment by jkppr** [comment]
@NightAcrobat777 thanks for your help. Please feel free to send an early draft PR my way for feedback.
