### ISSUE TITLE
Add functionality to preserve story

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#282]
To preserve the story long term, have a way to export it e.g. to PDF

**Comment by csash** [comment]
Can we extend this to include comments and stars/tags too? That's needed to meet record retention and discovery requirements in some contexts.

**Comment by joachimmetz** [comment]
@csash can you elaborate on these "record retention and discovery requirements"

we have no ideas what these are for your use cases

**Comment by csash** [comment]
Sure. The details for my use case are jurisdiction-specific, but the general requirement is similar across many jurisdictions.

In criminal proceedings in the U.S., the prosecution has an obligation to provide certain information, including exculpatory material, material that may aid in one's defense, and prior statements of witnesses (including forensic examiners) the defense. This is known as "discovery." If Timesketch gets used during a forensic exam, the stories, comments and stars/labels applied are potentially things that will need to be provided, at a minimum, to a prosecutor to review, and potentially to the defense. 

U.S. federal law requires federal agencies to preserve their records -- a record is basically anything providing "evidence of the organization, functions, policies, decisions, procedures, operations, or other activities of the Government" or having "informational value," which could include Timesketch stories, comments, and stars/labels -- for extended periods of time, sometimes in excess of 20 years. These are "retention requirements."

A single action that would export all this -- stories, comments, stars/tags, and the associated events for sketch -- in both human-friendly (PDF) and machine-friendly (JSON) formats for preservation would make it super easy to comply with both of those legal requirements.

**Comment by kiddinn** [comment]
This has already been implemented. A sketch can now be `exported` and an export will generate a single ZIP file that contains all "changes" to the sketch, tjhat is all events that have been tagged, commented on, all views, aggregations and stories. These are all exported with meta data files, csv and for some also as a html
