### ISSUE TITLE
UI feedback: Saved Searches / Views ID

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2836]
From user feedback:
* To get the saved search ID a user has to click the three dots next to the saved search and copy the link there and then get the ID from the link.
* It would be prefered to make this task more easy, e.g. by adding a copy link or ID icon on hover.
* Have a option to only copy the ID and not the full URL.

**Comment by berggren** [comment]
Maybe move the copy ID to the three dot menu, and make the hover-copy copy the URL?
