### ISSUE TITLE
install helper script

### ISSUE THREAD

**Issue by johnncennaa** [google/timesketch#2868]
HI,

I am trying to install timesketch for some testing. However, the URL provided for the helper script doesn't seem to exist.

Any next recommended steps?

Thanks

**Comment by jaegeral** [comment]
Hi @johnncennaa, can you explain a little more, in particular

* which helper script did you use?
* which URL does not exist?

Also did you check https://timesketch.org/guides/admin/troubleshooting/?

Cheers

**Comment by johnncennaa** [comment]
For sure.

I am just following the installation instructions at https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md

On step number 2 (download helper script) "curl -s -O https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh", I am getting a 404 error.

**Comment by jaegeral** [comment]
hm can you try to run `curl -s -O https://google.com` as the shell script is clearly available: https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh ?

**Comment by jaegeral** [comment]
Just tried it myself, and it was downloaded without any issue.

```
md5sum deploy_timesketch.sh
eac6d6798ff66c91a84a81bd94965d5d  deploy_timesketch.sh
```

**Comment by johnncennaa** [comment]
ok i got it solved. i probably have some dependencies that caused issues with curl.

i used wget and worked no problem. md5 hash matches. good to go. thanks for the quick response!

**Comment by jaegeral** [comment]
Cool
