### ISSUE TITLE
Add timeline management features to the cli client

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2877]
On the timesketch slack channel, we recently ran into a problem where it would have been useful to delete timelines via the CLI client.

Feature Request:
Add support for timeline management features like 
- [x] renaming
- [x] deleting
- [x] changing color to the cli client.

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/pull/3158 also

**Comment by jaegeral** [comment]
All done here
