### ISSUE TITLE
Export/import search templates

### ISSUE THREAD

**Issue by ryanwes21** [google/timesketch#292]
Request to add the ability to export/import search templates both for backup purposes and to share with other Timesketch users.

**Comment by berggren** [comment]
This is a great idea. thanks for filing this, will look into it.

**Comment by aarontp** [comment]
It would also be really nice to have a set of checked in search templates that can be community edited and installed by default in Timesketch.  Maybe that exists somewhere in Timesketch already, but I couldn't seem to find it.

**Comment by aarontp** [comment]
I wonder if it would be worth having an import mechanism for data from the ForensicsArtifacts repository as well?  Maybe that's too granular though.

**Comment by tomchop** [comment]
Happy to start working on this (at least a first PR with an API endpoint to CRUD SearchTemplates)

**Comment by aguilajesus** [comment]
I'm picking this up again, I'm going to push the API code first.

**Comment by kiddinn** [comment]
@aguilajesus are you still working on this?

**Comment by jaegeral** [comment]
> I'm picking this up again, I'm going to push the API code first.

Friendly ping @aguilajesus
