### ISSUE TITLE
UI bug: long timeline names in analyzer results

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2925]
The analyzer results do not truncate the timeline names resulting in an overflow of the left bar:

![image](https://github.com/google/timesketch/assets/99879757/7917c22f-e15c-44d2-a53a-3944e9852235)

**Comment by NightAcrobat777** [comment]
@jkppr are you still currently working on this? I want to give it a try if you want the help.

**Comment by jkppr** [comment]
@NightAcrobat777 thanks for your interest in fixing this issue. However, I had the fix already done locally and not yet pushed the PR, sorry.

Maybe I can interest you in working on any of those issues instead:
* #2899 
* #2813 
* #2802
