### ISSUE TITLE
Ability to add new events into an existing timeline?

### ISSUE THREAD

**Issue by xlong88** [google/timesketch#293]
I am wondering whether it is possible to append new events into an existing timeline.

**Comment by csash** [comment]
If you're talking about importing another Plaso/CSV/JSON file into an existing timeline, that works. Just use the same timeline name and Elasticsearch index name.

If you're talking about manually adding events to a timeline via the UI, that's not possible yet. See #71.

**Comment by xlong88** [comment]
Importing another file into an existing timeline, just resulting in multiple 
(different) timelines with the same name (see the attached figure). Is there any way to merge the new importing timeline into an existing one (resulting in a single timeline, not two with the same name)?

![screenshot from 2017-03-07 17-42-22](https://cloud.githubusercontent.com/assets/6059626/23681666/e1fcfa3c-035d-11e7-8225-811f6f7d138d.png)

**Comment by pettai** [comment]
> @csash Just use the same timeline name and Elasticsearch index name.

Not with running $ psort -o timesketch ... (AFAIK) 

Can you elaborate on how you manage to do it?

**Comment by xlong88** [comment]
Sorry, I forgot to add index name. It worked after adding index name. 
Thanks!
