### ISSUE TITLE
bug Error message: ERROR: Unable to determine path to custom formatter definitions: /etc/timesketch/plaso_formatters.yaml

### ISSUE THREAD

**Issue by sebdraven** [google/timesketch#2931]
Hi !

after a fresh install with docker I've this error when I put a plaso file with the Web UI

![image](https://github.com/google/timesketch/assets/1478484/023a0a6a-2077-438f-973a-9453c0ad88bf)

**Comment by sebdraven** [comment]
I've found a workarround

```
sudo docker cp plaso_formatters.yaml timesketch-worker:/etc/timesketch/
```

**Comment by jkppr** [comment]
#2933 should fix this for good.
