### ISSUE TITLE
filter chip content cannot be copied

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2950]
When filtering results using chips, the content of a chip cannot be copied. This might be use-full for documenting investigation steps. However, especially when excluding something per filter, the only place to copy the value from is the "NOT filter chip" but this is not possible. 

See demo below:
![chipbug](https://github.com/google/timesketch/assets/99879757/f7426bd4-443d-4eaf-ad79-de1608b00eaa)

Sidenote: The filterchip can also be clicked, without any action happening. This should also be fixed.

**Comment by JohannesLks** [comment]
Hello! I would like to approach this issue. Could you assign it to me?

**Comment by jkppr** [comment]
How is it going @JohannesLks ? Do you think you can make this feature work until our next planned release 2023-12-06?

**Comment by JohannesLks** [comment]
Yes i think so. So far, i added a copy button in the time filter chips and its Woking! :) I just need to implement the copy function to other chips. I am a bit unsure about the testing process, are threre any test scripts to run before i open a PR? Because im just working at the frontend.

**Comment by JohannesLks** [comment]
@jkppr how can i add in the UI a filterchip if its not a timefilter?

**Comment by jkppr** [comment]
I would say the minimum requirement is: The text can be marked and copied from a filter chip (like default text copy & paste). There is no special need for a copy icon in the first iteration. But if you already have it implemented, feel free to submit it with the review and we'll test if it benefits the UX.

> @jkppr how can i add in the UI a filterchip if its not a timefilter?

Option A: Click a Tag from the list in the left panel (should add a tag filter chip).
Option B: Open any event and in the event details click the filter icon that appears when hovering over an event attribute.

For the PR: 
* There are no special tests you need to run. When the PR is submitted, GitHub will run some workers & tests and inform you about any linter / test errors. You can take care of those with another commit then. (Or you check the GitHub worker config and run the tests locally before submitting, works as well)
* Please ensure to only commit the files you have changed code in. No `yarn.lock`, no frontend build files like `index.html` or `login.html`. We will build a new UI with the next release then.
