### ISSUE TITLE
Add CRNG to deploy_windows.ps1 script for generating random keys/passwords

### ISSUE THREAD

**Issue by coloradosarge** [google/timesketch#2986]
**Is your feature request related to a problem? Please describe.**
Get-Random is not a cryptographically secure RNG.  Get-SecureRandom is not supported in PS versions earlier than 7.0.  Update the deploy_timesketch.ps1 script to use a cryptographically secure RNG.

**Describe the solution you'd like**
Update the deploy_timesketch.ps1 to use a crypographically secure RNG.  Update to use Get-SecureRandom when PS 7.0 is commonly supported.

Example
# Function to get Cryptopgraphically random alphanumeric characters
$CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
$rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
Function Get-RandomString {
    Param($length)
    $KEY = ""
    for($i = 0; $i -lt $length; $i++)
    {
        [byte[]] $byte = 1
        $rng.GetBytes($byte)
        $KEY = $KEY + $CHARS[[int]$byte[0]%62]
    }
    $KEY
}
...
$POSTGRES_PASSWORD=Get-RandomString -length 32
...
$SECRET_KEY=Get-RandomString -length 32

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jkppr** [comment]
Hi @coloradosarge,
thanks for submitting your feature request. Given you have already an idea on how to solve this, want to submit a pull request with the changes to this issue and #2985 ?

Thanks

**Comment by coloradosarge** [comment]
Hello @jkppr 
I can do this but it is going to be a week or two before I can get to it as I'm traveling.

Thank you

**Comment by jkppr** [comment]
Should work, I would not consider these changes to be urgent. Looking forward to your PR and thank you.

**Comment by coloradosarge** [comment]
Hello #jkppr.  Pull request has been submitted with included fixes.  Should be no issues with PR as long as the signed Contributor License went through.  I received errors when I submitted the CL info.

**Comment by jkppr** [comment]
Thanks for the PR. I'll review it before the release. Looks like the CLA worked as well.
