### ISSUE TITLE
Error after indexing a timeline

### ISSUE THREAD

**Issue by sebdraven** [google/timesketch#3007]
When I want to search in Timeskecth I've an error 500 and in my log I've this

`SQL: SELECT searchhistory.created_at AS searchhistory_created_at, searchhistory.updated_at AS searchhistory_updated_at, searchhistory.id AS searchhistory_id, searchhistory.parent_id AS searchhistory_parent_id, searchhistory.sketch_id AS searchhistory_sketch_id, searchhistory.user_id AS searchhistory_user_id, searchhistory.scenario_id AS searchhistory_scenario_id, searchhistory.facet_id AS searchhistory_facet_id, searchhistory.question_id AS searchhistory_question_id, searchhistory.approach_id AS searchhistory_approach_id, searchhistory.description AS searchhistory_description, searchhistory.query_string AS searchhistory_query_string, searchhistory.query_filter AS searchhistory_query_filter, searchhistory.query_dsl AS searchhistory_query_dsl, searchhistory.query_result_count AS searchhistory_query_result_count, searchhistory.query_time AS searchhistory_query_time 
FROM searchhistory 
WHERE %(param_1)s = searchhistory.user_id AND %(param_2)s = searchhistory.sketch_id ORDER BY searchhistory.id DESC 
 LIMIT %(param_3)s]
[parameters: {'param_1': 1, 'param_2': 1, 'param_3': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-12-15 12:28:41,073] timesketch.app/ERROR Exception on /api/v1/sketches/1/searchhistory/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column searchhistory.scenario_id does not exist
LINE 1: ..., searchhistory.user_id AS searchhistory_user_id, searchhist...`

![image](https://github.com/google/timesketch/assets/1478484/c56b0256-8493-4935-84a2-8633fcf93f81)

And I've no result

**Comment by jkppr** [comment]
Hi @sebdraven 
to help you with this issue I need some more information.

* Have you checked the troubleshooting section https://timesketch.org/guides/admin/troubleshooting/ ?
* What version of Timesketch are you running?
* Have you recently updated your Timesketch instance? What what version did you run before?
* Are all containers running in a good state?
* Is the database available to your timesketch container?

**Comment by sebdraven** [comment]
Hi ! 

I've fixed the problem,

This error appears when I've updated my Timesketch instance and I've no seen your note about the upgrade of the database schema :) 

You can close the issue ! And sorry, before to open an issue, I'll read before the different release note !

Thanks !

**Comment by jkppr** [comment]
Glad it works now :)
