### ISSUE TITLE
Finding the version of a plaso file that is supported with timesketch

### ISSUE THREAD

**Issue by 6adir123** [google/timesketch#3011]
Hi, I would like to request an easy way to find which versions of plaso files does a timesketch version support

**Comment by jkppr** [comment]
Hi, Timesketch has a `tsctl info` command. If you run Timesketch in docker, you need to execute this command inside the container. See https://timesketch.org/guides/admin/admin-cli/#info for more details.

**Comment by jkppr** [comment]
Closing. Please feel free to re-open if the answer above does not solve your problem.
