### ISSUE TITLE
Is there a way to return to sketch list from inside a sketch?

### ISSUE THREAD

**Issue by hasamba** [google/timesketch#3034]
other than reconstruct the url? am im missing something?

**Comment by jkppr** [comment]
If you mean the overview of all sketches? You can just click the Timesketch logo on the top left.
![image](https://github.com/google/timesketch/assets/99879757/167aa1ab-a129-4875-9cea-a2d8829a9a2c)

Let me know if you think any other method would be more user-friendly.

**Comment by hasamba** [comment]
thanks!
i had a feeling im missing something,
maybe a "back to sketch list" button under the sketch menu (the 3 dots) would be more helpful
