### ISSUE TITLE
for every search getting "sorry, there was a problem"

### ISSUE THREAD

**Issue by hasamba** [google/timesketch#3067]
*** Update: just found out that it's working ok in the legacy UI, the problem is only at the new UI ***

searching for * shows all records,
selecting a search from "saved searches" show results,
searching for something specific like *.exe gives attached error
![chrome_k6xJnl1963](https://github.com/google/timesketch/assets/7392290/842f1cf4-8da4-4e5a-b07c-c4916adb7dd5)

console show error 500
![chrome_9jXRyoKH3v](https://github.com/google/timesketch/assets/7392290/53c98733-edb4-4495-af6f-4970a4773fcc)

something wrong with my configuration?
thanks

**Comment by jkppr** [comment]
Can you share some more details about your setup and configuration please?
* Is this a fresh installation? 
* Did you do any recent version upgrades?
* How many timelines and what size do you have in this sketch?
* Does it happen with all sketches?
* There should be an error/exception logged in `timesketch/logs/wsgi_error.log` when you encounter this error. What does it say?
