### ISSUE TITLE
Timesketch missing entries if Disabled key is present and the value is a string

### ISSUE THREAD

**Issue by puffyCid** [google/timesketch#3087]
**Describe the bug**
Timesketch does not show all entries when uploading JSONL data if the Disbaled key is present and the value is a string.
When uploading macOS launchdaemon data i noticed that Timesketch wont display entries if the Disabled key is present and the value is a string.

**To Reproduce**
Attempt to upload the follow examples:
```
{"datetime":"1601-01-01T00:00:00.000Z","timestamp_desc":"N/A","message":"/System/Library/LaunchDaemons/com.apple.containermanagerd.system.plist","data_type":"macos:plist:launchd:entry","artifact":"Launchd","ProcessType":"Adaptive","Disabled":"eyIjVGhlbiI6dHJ1ZSwiI0lmRmVhdHVyZUZsYWdEaXNhYmxlZCI6ImNvbnRhaW5lcm1hbmFnZXJkL3VzZXJfc3lzdGVtX3NwbGl0In0=","MachServices":"eyJjb20uYXBwbGUuY29udGFpbmVybWFuYWdlcmQiOnRydWUsImNvbS5hcHBsZS5jb250YWluZXJtYW5hZ2VyZC5zeXN0ZW0iOnRydWV9","EnableTransactions":true,"ProgramArguments":["/usr/libexec/containermanagerd_system","--runmode=privileged","--user-container-mode=current","--bundle-container-mode=global","--bundle-container-owner=_appinstalld","--system-container-mode=none"],"EnablePressuredExit":true,"Label":"com.apple.containermanagerd.system"}
{"datetime":"1601-01-01T00:00:00.000Z","timestamp_desc":"N/A","message":"/System/Library/LaunchDaemons/com.apple.containermanagerd.plist","data_type":"macos:plist:launchd:entry","artifact":"Launchd","ProcessType":"Adaptive","Disabled":"eyIjVGhlbiI6dHJ1ZSwiI0lmRmVhdHVyZUZsYWdFbmFibGVkIjoiY29udGFpbmVybWFuYWdlcmQvdXNlcl9zeXN0ZW1fc3BsaXQifQ==","MachServices":"eyJjb20uYXBwbGUuY29udGFpbmVybWFuYWdlcmQiOnRydWV9","EnableTransactions":true,"ProgramArguments":["/usr/libexec/containermanagerd","--runmode=privileged","--user-container-mode=current","--bundle-container-mode=global","--bundle-container-owner=_appinstalld","--system-container-mode=none"],"EnablePressuredExit":true,"Label":"com.apple.containermanagerd"}
```
No entries will show up in Timesketch.  
If you remove or rename the Disabled key, the entries will show up. If u change the value to true/false the data will show up

**Expected behavior**
Show the entries regardless of Disabled key value or show a warning when uploading?

**Desktop (please complete the following information):**
 - Version 20240328

**Additional context**
I tried to search previous issues and the website to see if this is expected behavior or identified before. But could not find anything

Let me know if additional info is required or if the JSONL format is incorrect. Thanks!

**Comment by jkppr** [comment]
Hi @puffyCid thanks for raising this issue.
I tried to reproduce it with the jsonl data you have provided using the upload via web-ui and timesketch_importer script. Both times it did work with no issues using the latest version of Timesketch.

Could you please try again if the issue persists and share detailed steps on how you upload the data?

Thanks

**Comment by jkppr** [comment]
Not reproducible. Please re-open with the requested information if the issue still exists.
