### ISSUE TITLE
Run selected/analyzers from "timesketch importer"

### ISSUE THREAD

**Issue by hasamba** [google/timesketch#3096]
im using a script that creates a plaso file from kape output and upload the output file to timesketch,
it would be very helpful if there will be an argument for timesketch_importer that will auto run selected or all analyzers/tagger after uploads and indexing finishes.

thanks

**Comment by jkppr** [comment]
Hi @hasamba
We are using dftimewolf for this use-case and its `TimesketchExporter` module supports triggering Analyzers on the uploaded timelines. For example with the [upload_ts](https://github.com/log2timeline/dftimewolf/blob/main/data/recipes/upload_ts.json) recipe.

Adding this feature to the timesketch_importer is not on the road map for now, but something that sounds like a great opportunity for a community contribution. I'm happy to review the PR if anyone wants to take a stab.

**Comment by wiredinhp** [comment]
@hasamba @jkppr Hi there ! I am a new contributor to this repository and would love to contribute by solving this issue. Could you please assign this issue to me ?

**Comment by jkppr** [comment]
Hi @wiredinhp thanks for offering to implement this feature request. I have assigned you the issue.
* Please find the getting started guide here: https://timesketch.org/developers/getting-started/
* Feel free to submit a draft PR early to gather some review feedback.

**Comment by jkppr** [comment]
@wiredinhp How is it going with this issue? Are you still working on it?

**Comment by wiredinhp** [comment]
@jkppr Hi ! Actually I am working on this issue and I would try to finish it in 3-4 days. My apologies I got paused in between due to some reasons and not informed. Am still working on it and if have some issue I would contact you here 👍 . Thanks for your support 👍

**Comment by abroglesc** [comment]
@wiredinhp Do you happen to have an update on this? We are facing this same issue and deciding whether we should invoke the analyzers via API call or wait for this fix now.

**Comment by YiChiCanCode** [comment]
@jkppr Could you assign me to resolve this issue please? Thanks!

**Comment by jkppr** [comment]
Reassigning this issue due to inactivity.
