### ISSUE TITLE
Check for new indexes when rendering the 'timelines' page

### ISSUE THREAD

**Issue by maestretti** [google/timesketch#317]
When rendering the timelines tab/page that allows linking Elasticsearch indexes to human readable timeline names, automatically pull a list of existing indexes from the ES cluster and display them with the option to add/name them. 

Provide a preview button / popup of the first 5 entries that would be created if a given index were mapped.

Filter for indexes that have a date field.

**Comment by berggren** [comment]
Do you mean indices that have not yet been ingested into Timesketch, e.g. indices that was added to Elasticsearch by some other means?

**Comment by maestretti** [comment]
Exactly. There might be multiple systems adding events to ES directly rather than through the Timesketch API. This would further decouple collection and processing from analysis. In my case using Lambda functions to parse forensics artifacts and generate events into ES. Then later view them with Timesketch. 

I could also imagine a use where you wanted to add a new Timesketch frontend to an existing ES cluster and re-link indices.

**Comment by berggren** [comment]
Closing this issue seeing it is not part of the design at this moment, and is better handled by the new import_client.
