### ISSUE TITLE
Support Elasticsearch metadata to automatically link indexes and timesketches

### ISSUE THREAD

**Issue by maestretti** [google/timesketch#318]
Elasticsearch has some support for [index metadata](https://github.com/elastic/elasticsearch/issues/1649). This could be used to specify timeline names and other characteristics as an alternate to storing them in SQL. That would allow multiple Timesketch front ends to share more context via a common ES cluster, and might lead to eliminating the requirement for managing a SQL instance as well (separate issue). This could also be used by other systems populating ES directly (Plaso, others) to setup timelines without interacting with the Timesketch server.

**Comment by berggren** [comment]
Researching this a bit. Index metadata doesn't really exist in ES, just type metadata. The dependency on SQL is more that just the index names. The ACL system, and sketches etc are implemented as SQL models seeing that this is highly relational data.
