### ISSUE TITLE
Add --skip-create-user option to enable non-interactive deployments

### ISSUE THREAD

**Issue by raihalea** [google/timesketch#3193]
**Is your feature request related to a problem? Please describe.**
The script prompts for user input to confirm whether to create a user or not, which blocks the automation process.

**Describe the solution you'd like**
To solve this, I propose adding a `--skip-create-user` option to the script. This option will allow the script to skip the user creation prompt and proceed with the deployment without any manual interaction.

**Describe alternatives you've considered**
Adding a `--skip-create-user` option provides a flexible solution for both manual and automated deployments.

**Comment by jkppr** [comment]
Thanks for raising the issue and also submitting a PR to fix it! 👍
