### ISSUE TITLE
Support multiple Elasticsearch backends

### ISSUE THREAD

**Issue by maestretti** [google/timesketch#320]
Add support for multiple Elasticsearch clusters from a single Timesketch front end. This would allow the inclusion of data from other ES sources without copying / replicating it into a dedicated ES cluster. The example provided in [issue 315](https://github.com/google/timesketch/issues/315) would be relevant here - using an ES cluster that ingests other log formats.

**Comment by berggren** [comment]
This should work with the new "Cross Cluster Search" in ES 5.x. Looks promising but I haven't tested it. In theory you just need to configure your cluster to federate with the other cluster and then just prepend the cluster alias to the indices in your search. This would mean that the only thing you need to do is name the index_name in Timesketch like: cluster_alias:indexname and then it "should just work".

We need to test this :)

**Comment by berggren** [comment]
This is the link: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html

**Comment by berggren** [comment]
This is supported with native ES features. Closing out.
