### ISSUE TITLE
Dynamic tagging in tagger analyzer

### ISSUE THREAD

**Issue by silver-eva** [google/timesketch#3206]
**Describe the bug**
If we run the Tagger analyzer on a timeline, dynamic tags that should be derived from event attributes are split into single-letter values instead of strings.

**To Reproduce**
1. update 'tags.yaml' file with the tagger rule
```Yaml
test_tagger:
  query_string: '_exists_:<any_string_attribute>'
  tags: ['$<any_string_attribute>']
  modifiers: []
```
2. Go to Ur 'test' sketch
3. Click on 'add timeline'. I'm uploading a CSV file, and it`s importing fine.
4. Open the left sidebar, scroll down to 'Analyzer Results' and press '+' (plus) 
5. Select the timeline and run the 'Tagger' analyzer
6. On the left sidebar scroll up to the 'Search' tab
7. Every tagged event now has split strings (that represent event attribute values specified in the tagger rule) inside the tag list

**Expected behavior**
If I set an attribute with a single-line value as a dynamic tag, I want the tag to consist of a line from the attribute value and not be split into a character list. 

Only when we set `modifiers` in the tagger rule to `split` we can get the expected behavior.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - Browser: Firefox
 - Version: 131.0

**Additional context**
In my case event has attributes:
```
rule: TestLNK 
provider:  Windows Shortcut
```
if any/all of these attributes pass as dynamic tags:`['$rule', '$provider']`
attribute `tag` which was created by the `Tagger` analyzer filled up by a list of single-character values such as: `['o', 'c', ' ', 'i', 's', 'W', 'd', 'w', 'n', 't', 'u', 'S', 'h', 'r']`

**Comment by jkppr** [comment]
Thanks for raising this issue. I successfully reproduced the issue on my setup. 
* Test timeline: Plaso parsed Browser History
* Tagger config:
```
test_tagger:
  query_string: '_exists_:domain'
  tags: ['$domain']
```
* Result:
![Image](https://github.com/user-attachments/assets/2f7e45e9-226f-4bc8-99da-d28f55365057)

**Comment by silver-eva** [comment]
To pass over this bug we can just set `modifiers` in the Tagger config to `['split']` but not `['upper']` or `[]`.

I [find](https://github.com/google/timesketch/blob/c0c8d9a2c73cafdc491fd7101f84e8daf472a1c5/timesketch/lib/analyzers/tagger.py#L132) that if no `modifiers` are set the event attribute value, that is a string, checks with Iterable, and it is. Then `dynamic_tag_values`, a list, extend by string, an iterable. That is why tags are splitting.

**Comment by jkppr** [comment]
Thanks, the issue will be fixed in the next release.

You can just replace your `tagger.py` with the fixed version and restart your deployment (at least the celery workers) and then it should work again as expected.
