### ISSUE TITLE
Visualizer fields, no data available

### ISSUE THREAD

**Issue by judgedread540** [google/timesketch#3208]
**Describe the bug**
I've tried with several different timelines and I don't get any fields to choose from, meaning I can't use the visualizations at all, I was using the feature with the previous release but after the UI change and introduction of the fields api method, nothing returns. API response is empty and before I ran out of time I tested that the data types list also returns empty.  result_obj.values is an empty list, https://github.com/google/timesketch/blob/4d6e1e67ddcdfd37e21ba1b81a4b7f24884ef346/timesketch/api/v1/resources/timeline.py#L599

**API response:**
`{
  "objects": []
}`

**To Reproduce**
Upload some timeline to a sketch, open the visualizations page, select timeline and query and then attempt to select a field.

**Expected behavior**
UI displays a list of the fields that are present in the specified timeline.

**Platform**
Noticed initially with OSDFIR k8s setup and then tested locally with the docker compose dev setup. Specifically release 20241009.

**Comment by jkppr** [comment]
Hi @judgedread540 thanks for raising this issue.

Does your timeline data contain a `data_type` field?

**Comment by judgedread540** [comment]
> Hi [@judgedread540](https://github.com/judgedread540) thanks for raising this issue.
> 
> Does your timeline data contain a `data_type` field?
> 
> Can you provide some example data where this happens to you?

😅 The data did not contain the data_type field, works just as before after including it. Totally missed that it was needed.

**Comment by jkppr** [comment]
Glad it works now. The `data_type` is not yet a mandatory field, but it is used by many features in Timesketch, so maybe its time to change it to mandatory. Let's see for the next release.
