### ISSUE TITLE
Error Uploading file Timesketch docker-compose

### ISSUE THREAD

**Issue by Pitbully7** [google/timesketch#330]
I recieve an an internal server error on the GUI and this is the terminal messages.  I used docker-compose based off https://hub.docker.com/r/jessemillar/timesketch/

postgres_1       | LOG:  database system was shut down at 2017-06-09 14:42:13 UTC
timesketch_1     | TIMESKETCH_USER set to default: admin
postgres_1       | LOG:  MultiXact member wraparound protections are now enabled
timesketch_1     | TIMESKETCH_PASSWORD set randomly to: jB8MOHnAXElg5u4+jfzpvzFqvALjOeXUTPvCJ3PaDbE=
postgres_1       | LOG:  database system is ready to accept connections
postgres_1       | LOG:  autovacuum launcher started
elasticsearch_1  | [2017-06-09 14:42:19,284][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elasticsearch_1  | [2017-06-09 14:42:19,469][INFO ][node                     ] [Arno Stark] version[2.4.5], pid[1], build[c849dd1/2017-04-24T16:18:17Z]
elasticsearch_1  | [2017-06-09 14:42:19,469][INFO ][node                     ] [Arno Stark] initializing ...
elasticsearch_1  | [2017-06-09 14:42:20,108][INFO ][plugins                  ] [Arno Stark] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | [2017-06-09 14:42:20,175][INFO ][env                      ] [Arno Stark] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda2)]], net usable_space [35.4gb], net total_space [171.1gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2017-06-09 14:42:20,175][INFO ][env                      ] [Arno Stark] heap size [989.8mb], compressed ordinary object pointers [true]
timesketch_1     | User admin created/updated
timesketch_1     |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
elasticsearch_1  | [2017-06-09 14:42:21,895][INFO ][node                     ] [Arno Stark] initialized
elasticsearch_1  | [2017-06-09 14:42:21,895][INFO ][node                     ] [Arno Stark] starting ...
elasticsearch_1  | [2017-06-09 14:42:22,043][INFO ][transport                ] [Arno Stark] publish_address {172.17.0.3:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2017-06-09 14:42:22,047][INFO ][discovery                ] [Arno Stark] elasticsearch/dZw8rFwpSs6TxO_UFnyZfg
elasticsearch_1  | [2017-06-09 14:42:25,165][INFO ][cluster.service          ] [Arno Stark] new_master {Arno Stark}{dZw8rFwpSs6TxO_UFnyZfg}{172.17.0.3}{172.17.0.3:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1  | [2017-06-09 14:42:25,256][INFO ][http                     ] [Arno Stark] publish_address {172.17.0.3:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2017-06-09 14:42:25,256][INFO ][node                     ] [Arno Stark] started
elasticsearch_1  | [2017-06-09 14:42:25,277][INFO ][gateway                  ] [Arno Stark] recovered [0] indices into cluster_state
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:48:31] "GET / HTTP/1.1" 302 -
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:48:32] "GET /login/?next=%2F HTTP/1.1" 200 -
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:48:32] "GET /static/css/timesketch.css HTTP/1.1" 404 -
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:49:05] "POST /login/?next=%2F HTTP/1.1" 302 -
timesketch_1     | /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "sketch_accesscontrolentry.group_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
timesketch_1     |   'strategies for improved performance.' % expr)
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:49:06] "GET / HTTP/1.1" 200 -
timesketch_1     | /usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py:1423: SAWarning: Got None for value of column sketch.id; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
timesketch_1     |   "(but may in a future release)" % column)
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:49:10] "POST /sketch/ HTTP/1.1" 302 -
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:49:10] "GET /sketch/10/ HTTP/1.1" 200 -
timesketch_1     | [2017-06-09 14:49:40,746] ERROR in app: Exception on /api/v1/upload/ [POST]
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
timesketch_1     |     rv = self.dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
timesketch_1     |     return self.view_functions[rule.endpoint](**req.view_args)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
timesketch_1     |     resp = resource(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
timesketch_1     |     return self.dispatch_request(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
timesketch_1     |     resp = meth(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
timesketch_1     |     return func(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 943, in post
timesketch_1     |     message=form.errors[u'file'][0],
timesketch_1     | KeyError: u'file'
timesketch_1     | 172.17.0.1 - - [09/Jun/2017 14:49:40] "POST /api/v1/upload/ HTTP/1.1" 500 -

**Comment by berggren** [comment]
Thanks for your report!
The upload feature is not yet supported in the docker deployment. I have updated the docs to reflect this.

We need Redis and Celery containers to make this happen, PRs welcome :)

**Comment by ilyaglow** [comment]
Hey there, I just made it to work. You can check it on my [upload timeline feature](https://github.com/ilyaglow/timesketch/tree/upload-timeline-feature) branch.

**Comment by Pitbully7** [comment]
I just tested it and it works great!  Thanks!

**Comment by berggren** [comment]
Thanks @ilyaglow ! Can you rebase from master?

**Comment by berggren** [comment]
Never mind, lets use this issue to track this: #361 
Closing this one.
