### ISSUE TITLE
Internal server error - Plaso Upload

### ISSUE THREAD

**Issue by fredbird1012** [google/timesketch#334]
When uploading a plaso file to timesketch, I am receiving an internal server error.  I have installed all the dependencies and TimeSketch on a Ubuntu 14.04LTS virtual machine.  Everything built fine without issues.  Redis, Elasticsearch, Celery, and Timesketch start up without any problems.  I receive the internal server error every time a .plaso file is uploaded with the entry below.

File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 920, in post
    status_code=HTTP_STATUS_CODE_BAD_REQUEST)
ApiHTTPError

**Comment by udgover** [comment]
Hi,

I freshly installed Ubuntu Server 16.04.3 and followed exactly the following documentation:

- Timesketch : https://github.com/google/timesketch/blob/master/docs/Installation.md
- Plaso : https://github.com/google/timesketch/blob/master/docs/EnablePlasoUpload.md

And I get the same traceback as @fredbird1012:

~$ tsctl runserver -h 0.0.0.0 -p 5000
 \* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.0.2.2 - - [20/Dec/2017 11:41:44] "GET / HTTP/1.1" 302 -
10.0.2.2 - - [20/Dec/2017 11:41:49] "GET /login/?next=%2F HTTP/1.1" 200 -
10.0.2.2 - - [20/Dec/2017 11:41:49] "GET /static/css/timesketch.css HTTP/1.1" 404 -
10.0.2.2 - - [20/Dec/2017 11:41:49] "GET /favicon.ico HTTP/1.1" 404 -
10.0.2.2 - - [20/Dec/2017 11:42:01] "POST /login/?next=%2F HTTP/1.1" 302 -
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "sketch_accesscontrolentry.group_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)
10.0.2.2 - - [20/Dec/2017 11:42:01] "GET / HTTP/1.1" 200 -
/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py:1424: SAWarning: Got None for value of column sketch.id; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
  "(but may in a future release)" % column)
10.0.2.2 - - [20/Dec/2017 11:42:15] "POST /sketch/ HTTP/1.1" 302 -
10.0.2.2 - - [20/Dec/2017 11:42:15] "GET /sketch/4/ HTTP/1.1" 200 -
[2017-12-20 11:42:29,358] ERROR in app: Exception on /api/v1/upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 971, in post
    status_code=HTTP_STATUS_CODE_BAD_REQUEST)
ApiHTTPError
10.0.2.2 - - [20/Dec/2017 11:42:29] "POST /api/v1/upload/ HTTP/1.1" 500 -`

This is the complete log from starting the server, authenticating, creating a new sketch and trying to upload a plaso dump.

**Comment by adamjnichols** [comment]
Can you please verify that you have upload toggled to "enabled" in /etc/timesketch.conf, and that you've configured a directory that the process has permissions to write to?

I suspect this won't completely solve your issue, but let's please start there.

**Comment by TinoKautschkeCSNC** [comment]
I had the same issue. In my case, the internal server error disappeared by renaming the extension of the plaso file to "blabla**.plaso**".

**Comment by kiddinn** [comment]
is this still an issue? or has this been resolved by now?

**Comment by berggren** [comment]
correct, filename needs to be .plaso or .jsonl. Closing this issue.
