### ISSUE TITLE
tsctl to support TSV files

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#337]
`tsctl` currently supports reading CSV files, however, often times its easier/less likely data gets broken by using _tab_ delimited files.

This is trivial to implement, e.g - :
1.  add the option `tsv2ts` to [`shell_manager`](https://github.com/hiddenillusion/timesketch/blob/master/tsctl#L424)
2. in `CreateTimelineFromCsv()`have an option for _delimiter_ and if `tsv2ts` was provided, change the CSV [`reader`](https://github.com/hiddenillusion/timesketch/blob/master/tsctl#L412) delimiter to a tab.

**Comment by berggren** [comment]
Great idea, this should be simple enough. Do you have time to code this up? Let me know otherwise and I'll take a look asap.

**Comment by hiddenillusion** [comment]
ack, will submit a PR
