### ISSUE TITLE
Ability to rearrange/change columns within the Explore view

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#338]
When viewing timeline data within the `Explore` view, it'd be useful to be able to:

1. rearrange the columns

This is useful in instances where a user might want/prefer the order in which the columns are present to be different (e.g. - 1st column star, 2nd column datetime, 2rd column datetime attrib etc.)

2. change which columns are present

For certain data, a user may only want to focus on data within certain columns. The ability to remove/hide the remaining columns would provide additional screen space and increase ones ability to focus on what they feel is important.

I can see a few potential ways to implement:
- ability to create custom view templates
- configuration/selecting within the users settings
- dynamic w/ JS ? (drag & move etc.)

**Comment by berggren** [comment]
This has been implemented as part of the new UI
