### ISSUE TITLE
Enriching of timeline data after being uploaded

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#340]
One can currently (1) use the _analysis_ argument of `psort` for some tagging/enrichment or (2) add  include their own info. in the _tag_ field of a timeline row but either way, this is static once the timeline is uploaded to Timesketch.

It'd be useful to have the ability to continuously enrich data once it's uploaded to Timesketch.

1. One way might be to have something like a cron job pulling/reading a DB and applying the criteria within it to the timeline data.

2. On-demand. e.g, Right clicking on details within timeline data (e.g. - Domain Name) would load details related to said data type. In this instance, it'd be useful to pull data from resources like YETI, MISP, PassiveTotal etc. to include relevant stuff like first/last seen, pDNS etc. Since some of this data may be updated after it's uploaded to Timesketch, having this pull/API lookup can be beneficial.

Note - having it pulled dynamically on request would mean it wouldn't be query-able, unless each time a user performed this enrichment the retrieved content was saved/appended/linked to the event/unique data & only updated if it changed.

**Comment by berggren** [comment]
Oh, and Ramses talked about having both 1 and 2 :)

**Comment by geekscrapy** [comment]
I'd like to see MISP lookup and possibly integration into TheHive Cortex (or generally TheHive eco system)

**Comment by berggren** [comment]
This has been implemented as part of the new analysis framework. You can write a MISP analyzer for example and run it on individual timelines.
