### ISSUE TITLE
Macros in search query

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#341]
Add the possibility to use macros for common filters, or use existing search templates as macros. e.g. `registry_persistence(rundll32.exe)` would have `registry_persistence()` expand into a filter for all values of registry that are known to be used as peristence mechanisms.

Another example of this would be `execution(at.exe)` which could look in prefetch files, windows event logs, etc.

**Comment by kovakina** [comment]
I'm potentially interested in working on this. Maybe have something like a drop down list of templates, with an entry field.

**Comment by berggren** [comment]
This has been implemented as part of user supplied parameter support in search templates.
