### ISSUE TITLE
Correlate multiple events

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#342]
Implement a correlation system between events. Some examples:

* Show me all the registry changes 1 minute before and after a file was downloaded by a browser
* Show me all services that have changed to point to a file that was created in the last N days.
* Tell me if any files referenced in ASEPs (services, scheduled tasks, etc.) are not signed (ala Sysinternal Autoruns)
* Commands launched in sequence: `tasklist` followed by `net view` followed by `net localgroup administrators`

**Comment by hiddenillusion** [comment]
@tomchop what are your thoughts for the last bullet point? Just leveraging process auditing/sysmon for Win event logs etc. or also trying some additional approaches such as $SI/$FN data, Prefetch data, (possible) ShimCache order etc.

**Comment by tomchop** [comment]
Yes, I was thinking of EID:4688 + prefetch files, but any other source that logs execution works.

**Comment by berggren** [comment]
All the bullet points here is doable with vanilla elasticsearch queries, no?
The "are not signed" part is something that needs to be pulled in via context processing. @hiddenillusion mentioned this in #340

**Comment by berggren** [comment]
Updating this old issue. With the modern TS this could be achieved with a combination of analyzers and Sigma rules. 

@tomchop WDYT? Something you wanna work on?

**Comment by berggren** [comment]
This is also related to #220  - I'll close this one in favour of that. Please re-open if any implementation will go into this.
