### ISSUE TITLE
ES datastore fails to import events if text within an event is a ceratin type

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#351]
The [deocoding](https://github.com/google/timesketch/blob/master/timesketch/lib/datastores/elastic.py#L390) within `import_event()` for the ES datastore doesn't handle embedded lists/dicts etc. as a value in `event`.  This may be by design but figured I'd bring it up as some timelines I have are configured this way and failed to upload in recent TS versions as a result.

If it's not by design, it'd be trivial to automatically check the value's type and iterate if it's not a str or int and then decode.

Traceback:
```
Traceback (most recent call last):
...
  File "tsctl", line 319, in run
    flush_interval, index_name, event_type, event)
  File ".../timesketch/timesketch/lib/datastores/elastic.py", line 390, in import_event
    k.decode(u'utf8'): v.decode(u'utf8') for k, v in event.items()
  File ".../timesketch/timesketch/lib/datastores/elastic.py", line 390, in <dictcomp>
    k.decode(u'utf8'): v.decode(u'utf8') for k, v in event.items()
AttributeError: 'list' object has no attribute 'decode'
```

**Comment by berggren** [comment]
This works in recent versions of TS. Please reopen of the issue persist.
