### ISSUE TITLE
API to support retrieving details for Timeline(s) without associating a Sketch

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#353]
The current API only allows one to get details for a Timeline if it's included within a Sketch. 

One can iterate through all available sketches/single sketch via one of the Sketch resources and get details on a timeline that way, however, if a timeline is uploaded and not included within a Sketch then you won't be able to get such details/see it.

It'd be useful to have the ability to list all (ACL pending) timelines within Timesketch, regardless if they're included in a Sketch (e.g., Timelines + Available timelines as seen in the UI).

This could also open up the possibility to leverage something like [`CountEventsResource `](https://github.com/google/timesketch/blob/master/timesketch/api/v1/resources.py#L1107) on individual timelines instead of only via a Sketch.

**Comment by berggren** [comment]
Great idea, and I have actually already planned for it :) Just waiting for the code review for the initial API client code. Will implement after that.

**Comment by berggren** [comment]
I have implemented this now. You can list all timelines regardless of sketch. You can also create new indices in Elasticsearch and mapping them in Timesketch. This should make @csash happy :)

@hiddenillusion Can you review the code here? When you are done, just add a "LGTM" as a comment to the PR. Let me know if you don't have time.

PR: https://github.com/google/timesketch/pull/376

**Comment by hiddenillusion** [comment]
ack - will have a look
