### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by ilyaglow** [google/timesketch#361]
Recently I became an active user of [dockerized Timesketch](https://github.com/ilyaglow/docker-timesketch) and happy to contribute my work here.

As a follow up on #329 I'll try to briefly list things that doesn't work or may be improved in docker version here at the moment:

## Not working

* Timesketch fails to start at first invocation of `docker-compose up`. 
_Why_: postgres container take some time initializing and is not available at the very same moment timesketch is connecting to it

* Upload plaso timelines from inside the container using `psort` doesn't work 
_Why_: typo in the `ELASTIC_ADDRESS` env value

* Upload timelines from web interface doesn't work 
_Why_: there are no celery workers started

* Starring and commenting events do not work 
_Why_: `contrib` dir with scripts is not mounted to elasticsearch's container

## Need improvements

* Elasticsearch image should be 5.x due to newest changes #350 

* Neo4j container should be added for the new graph feature #349 

* Unnecessary services ports exposure which is security concern because there are hardcoded creds (postgres) or no auth at all (elasticsearch). It is a user's responsibility IMO to make databases accessible from the external net.

* Unnecessary links statements should be removed to make compose file a bit cleaner

**Comment by berggren** [comment]
Thanks @ilyaglow for your work here. Let's use this Issue to track these things. Let's fix these issues.

Question: Do we really want to provide postgresql as a container? It is not good to have databases as containers for many reasons and I'm afraid that we encourage users to deploy a system where data loss can be real. What do you think?

**Comment by ilyaglow** [comment]
Maybe this is subjective, but I have not faced any issues running database as a container in production for a while like many other users, so I don't feel any harm here.

Data loss can be prevented if you mount `pgdata` to an external location. Needless to say, folks who use dockerized apps should know what they're doing, but we may force them to use volumes to address this and add `volumes` to the postgres container or make a recommendation in the docker readme.

**Comment by adamjnichols** [comment]
#520
