### ISSUE TITLE
REMOTE_USER SSO not working

### ISSUE THREAD

**Issue by Red5d** [google/timesketch#370]
I'm trying to get SSO working in timesketch using the REMOTE_USER method. I have nginx set up as a reverse proxy to authenticate the user and pass a REMOTE_USER value back to the timesketch backend using configs from here: https://github.com/Siecje/nginx-auth-proxy

I've confirmed that nginx is working correctly and authenticates the user and sets a REMOTE_USER value. However, when the request goes to timesketch, it just redirects to the login page.

How is SSO supposed to work in timesketch? I've set "SSO_ENABLED = True" and "SSO_USER_ENV_VARIABLE = u'REMOTE_USER'" is set in /etc/timesketch.conf

**Comment by Red5d** [comment]
Solved by changing "environ" to "headers" on line 68 of https://github.com/google/timesketch/blob/master/timesketch/ui/views/user.py

The Nginx auth proxy is sending the REMOTE_USER value via headers.

**Comment by ptitdoc** [comment]
This issue should probably be reopened.
