### ISSUE TITLE
Ability to view custom information for the message field when exploring a timeline

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#371]
It would be extremely helpful to have the ability to create custom `message` formats (maybe a config file which the UI references for each `parser`/`data_type` to build this field? We can further discuss) Currently, the offline data parser is responsible for placing this data in a `message` field and the timesketch UI renders that within the explore view.

This added functionality would allow people to display different pieces of information within a parsed event and become less distracted by only focusing on what information they deem important for said event.

e.g., here's an example of a truncated `message` from the demo site:

>... [4624 / 0x1210] Record Number: 120 Event Level: 0 Source Name: Microsoft-Windows-Security-Auditing Computer Name: GREENDALEGOLD Message string: An account was successfully logged on.\n\nSubject:\n\tSecurity ID:\t\tS-1-5-18\n\tAccount Name:\t\tWIN-LK5OF8CDD94$\n\tAccount Domain:\t\tWORKGROUP\n\tLogon ID:\t\t0x00000000000003e7\n\nLogon Type:\t\t\t2\n\nNew Logon:\n\tSecurity ID:\t\tS-1-5-21-1539974973-2753941131-3212641383-1000\n\tAccount Name:\t\tgold_administrator\n\tAccount Domain:\t\tGREENDALEG

There's a lot being displayed in this example - one might feel it's easier to read if their custom format for `message` displayed: 

```
source_machine_ip (source_computer_name) source_domain\source_user_name -> target_machine_ip (target_machine_name) target_domain\target_user_name
```

Since anything queried will still match on any of the fields within said event, one doesn't have to worry about missing something (unless said query only targets specific fields of course).

Current work arounds include creating custom `message` fields prior to uploading to timesketch and/or slicing via the API.

**Comment by morallo** [comment]
A more generic approach to this (but maybe more complex) could be to implement some result display customization: let the analyst choose what fields he want's displayed.

This way you can build your own table with the desired fields, as long as they are parsed in the timeline generation phase (plaso).

**Comment by berggren** [comment]
This has been implemented as a human_readable attribute. If this is present then that will be shows in the UI instead (with the option to show the original message field of course).

currently this is exposed for auto analyzers.
