### ISSUE TITLE
Possible timeline picker enhancements

### ISSUE THREAD

**Issue by csash** [google/timesketch#374]
These are a few of my random thoughts on possible enhancements to the timeline picker page. If these seem sane to other people, I'll work on making them happen.

- I think ordering the sections Timelines, Import timeline, Available timelines would be a little more logical (what you have already, followed by your options to add stuff, instead of the current option to add, followed by what you have, followed by option to add. Maybe that's just a personal preference?
- Does the edit page need to exist? If we displayed the timeline meta (index name, original timeline name, added by, added date) in the edit modal and had the edit button on the timelines page open the modal, would that do the trick and save you two clicks when editing timeline info?
- The CSV file mandatory field documentation should be included in Timesketch; Internet links aren't useful for folks running in offline enclaves
- The Available timelines list needs a search function; it gets kind of unwieldy when you've got 100+ timelines
- Deleted timelines should re-appear in the Available timelines list without requiring a page refresh
- Would it make sense to replace the checkboxes and "Add to sketch" button with per-timeline add buttons? You'd save a click, plus you wouldn't have to scroll all the way down to the button at the bottom when you have a ton of timelines.

**Comment by berggren** [comment]
Hey @csash 

These are all really good ideas, and I have been thinking in the same direction. Can you please make individual Issues so we can track them before next release?

Also, I would love for you to send PRs :)

Thanks for contributing!

**Comment by csash** [comment]
Split into separate issues, so closing this one. PRs are definitely on my todo list.
