### ISSUE TITLE
API should warn if ES index_name already exists when creating a new timeline

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#377]
Using [`create_timeline()`](https://github.com/google/timesketch/pull/376/files#diff-cfc277cad8b430c4868c66b63ef6ded2R181), from #376, to manually create a timeline works as expected, if the `index_name` provided doesn't already exist within ES.

However, when a duplicate is used, there's no indication/warning. The only way to currently tell is to list all the timelines afterwards, and realize it was never created (the original will exist, the attempted new one silently fails).

One possible work around is to do a quick check (e.g.) -
```
def es_index_exists(self, index_name):
    response = self.fetch_resource_data(u'timelines/')
    for index in response[u'objects'][0]:
        if index_name == index.get(u'index_name'):
            return True
    return False
```

and then verify before creation:

```
def create_timeline(self, timeline_name, index_name=None, public=False):
...
    if not index_name:
        index_name = uuid4().hex

    if self.es_index_exists(index_name):
        <raise/return duplicate error>
```

**Comment by berggren** [comment]
Good point. I have fixed this. When a duplicate is found the server will respond with a HTTP 409 (conflict) and the client code will catch this and raise an error.

**Comment by berggren** [comment]
After thinking about this some more I believe that this is actually working as intended. We are confusing searchindex with timeline here and it was a mistake to call it create_timeline(), it should be named create_searchindex().

A timeline is always bound to a Sketch. A SearchIndex can be referenced in many timelines. This being said, I will change the name of the methods to make this clear.
