### ISSUE TITLE
Adding a view to a story does not work on Firefox

### ISSUE THREAD

**Issue by franekp** [google/timesketch#388]
Some UI bug prevents the "Choose View" drop-down from opening when using Firefox.

**Comment by deralexxx** [comment]
![Choose View drop down](https://user-images.githubusercontent.com/741037/62699660-5a482080-b9e0-11e9-979a-8b9f01ec3fa6.png)

As far as I can tell this is no longer a bug. Tested on FireFox 68.0.1 (64-Bit) on https://demo.timesketch.org/sketch/285/explore/view/2876/

**Comment by berggren** [comment]
This has been fixed as part of the new UI
