### ISSUE TITLE
Rename SearchIndex* API resources to reflect new name

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#391]
renaming of timeline->searchindex re: #377 needs to be reflected in the initial `__init__.py` for [SearchIndexListResource](https://github.com/google/timesketch/blob/master/timesketch/__init__.py#L151) and [SearchIndexResource](https://github.com/google/timesketch/blob/master/timesketch/__init__.py#L152) or code depending on that route to exist will 404 e.g. - [`list_searchindices()`](https://github.com/google/timesketch/blob/377-raise-error-on-conflict/api_client/python/timesketch_api_client/client.py#L202)

**Comment by berggren** [comment]
This has been fixed.
