### ISSUE TITLE
run_linter.sh could be a bit more granular

### ISSUE THREAD

**Issue by franekp** [google/timesketch#393]
Currently, it runs pylint on every .py file present in the directory structure. It makes an assumption that there are no other .py files than that of timesketch. For example, creating a virtualenv inside project dir makes the linting script unusable.

**Comment by franekp** [comment]
particularly, it really ***should*** ignore stuff in node_modules

**Comment by Androbin** [comment]
* `node_modules` was excluded by 6d407bc4ad8ce35bd916e6c8c22a1ccd0a6c6da0.
* `run_linter.sh` was replaced in b5d875a66fc541f58d9462ab851caca719e4ba23
* `run_tests.py` does not exclude `node_modules`
* `.pylintrc` should take care of that
