### ISSUE TITLE
Timeline picker: Remove edit page and move timeline info & edit options to single modal dialog

### ISSUE THREAD

**Issue by csash** [google/timesketch#397]
Splitting #374 into separate issues.

Does the edit page need to exist? If we displayed the timeline meta (index name, original timeline name, added by, added date) in the edit modal and had the edit button on the timelines page open the modal, would that do the trick and save you two clicks when editing timeline info?

**Comment by berggren** [comment]
I agree, the edit page is pretty horrible and it takes too many clicks to get there. Modal sounds good, I'll make sure to implement this.

**Comment by berggren** [comment]
This has been implemented as part of the new UI
