### ISSUE TITLE
Make import file documentation available in Timesketch (not via internet)

### ISSUE THREAD

**Issue by csash** [google/timesketch#398]
Splitting #374 into separate issues.

The CSV file mandatory field documentation should be included in Timesketch; Internet links aren't useful for folks running in offline enclaves.

**Comment by berggren** [comment]
Great idea! Should be easy enough.

**Comment by kiddinn** [comment]
This is also now "built" into the timesketch importer. That is if you use the timesketch importer it will check to see whether the CSV file is missing fields and ask the user to fill them in.
