### ISSUE TITLE
Add search function to Available Timelines list

### ISSUE THREAD

**Issue by csash** [google/timesketch#399]
Splitting #374 into separate issues.

The Available timelines list needs a search function; it gets kind of unwieldy when you've got 100+ timelines

**Comment by berggren** [comment]
Yep, I agree. We actually had this feature in the beginning :) Let's add it again.

**Comment by tirtharajghosh** [comment]
I'd like to claim this issue. Could you please assign it to me?

**Comment by kiddinn** [comment]
Sure, I can assign it you

**Comment by rajpratyush** [comment]
@kiddinn I would like to work on this issue. Can you guide me ?

**Comment by kiddinn** [comment]
Since this is a front-end search window for timelines in the ui, I ask for @berggren  to provide guidance

**Comment by berggren** [comment]
Hi @rajpratyush thanks for reaching out. We have recently change how we are managing timelines in the UI, and also in the backend. You cannot add timelines to multiple sketches any more. We will close this issue out.

Let us know if you find anything else to contribute to.
