### ISSUE TITLE
Timeline picker: Add to sketch buttons instead of checkboxes

### ISSUE THREAD

**Issue by csash** [google/timesketch#400]
Splitting #374 into separate issues.

Would it make sense to replace the checkboxes and "Add to sketch" button with per-timeline add buttons? You'd save a click, plus you wouldn't have to scroll all the way down to the button at the bottom when you have a ton of timelines.

**Comment by berggren** [comment]
This is a great idea. I'm currently thinking of how to better represent and build UX around the timeline adding feature. I'll start experimenting and will update this issue.

**Comment by berggren** [comment]
This has been fixed in the new UI.
