### ISSUE TITLE
Timeline picker: Deleted timelines should return to available timelines list

### ISSUE THREAD

**Issue by csash** [google/timesketch#401]
Splitting #374 into separate issues.

Deleted timelines should re-appear in the Available timelines list without requiring a page refresh

**Comment by berggren** [comment]
Good catch, yeah the angular component need to be updated.

**Comment by gaelmuller** [comment]
I think this is now working as expected with the new UI.

**Comment by berggren** [comment]
This has been implemented as part of the new UI
