### ISSUE TITLE
Create saved views automatically from starred and commented events

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#419]
It would be nice to be able to auto-generate a Story from all of the events that have been starred or commented on.

**Comment by pettai** [comment]
+1 
(why not make them go in automatically then you create the story? or was that what you meant?)

**Comment by aarontp** [comment]
I was thinking about something like a "Generate a Story" button either next to the "Write a story" button, and/or possibly somewhere in the story edit page so that you could insert the auto-generated section into an existing story.

**Comment by berggren** [comment]
I think aut-creating a view makes most sense for this. Out of that, we can create stories if the user chooses. I'll change the title of this FR

**Comment by berggren** [comment]
This has been done, and is currently in review. Both starred and commented events will be surfaced as quick links in the new search dropdown menu.

https://github.com/google/timesketch/pull/1838
