### ISSUE TITLE
Timeline mouseover tip in explore view

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#420]
When working with many different timelines it would be nice to have a way to determine which timeline you are looking at without having to correlate the colors.  Just having a mouseover tip when hovering over the colored timestamp would be useful.

**Comment by berggren** [comment]
The timeline name is on the right side. Isn't that enough?

**Comment by aarontp** [comment]
Yeah....  Really not sure how I missed that!   Longer names do seem to get truncated, so maybe I was only seeing the first part of the truncated name that was similar to other timelines.  Just out of curiosity why do the timestamps get the timeline color instead of the actual timeline column?

I'll close this then.  A super "nice to have" would still be to have a tooltip above the timeline name to distinguish when they get truncated, but I'm sure there are lots of other better things to spend time on for now.
