### ISSUE TITLE
Document advanced search queries

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#421]
It would be nice to have some documentation on search operators and what are some of the common fields to search on (e.g. data_type, event_identifier, etc.).  Also probably want to mention partial word matches requires globbing characters, etc.

**Comment by berggren** [comment]
Yeah, this has been on the radar for a long time. About the attributes to filter on that is just the Plaso schema. I agree, we need to document this.

Any takers? :)

**Comment by pettai** [comment]
one part this could be to include it as search templates.
I'd like to volunteer, but I would need some input on the topic

**Comment by n3x77** [comment]
My team will also support this with few search queries we typically use in
ir cases.

Should we create a pull request for the documentation ?

Cheers
Sven
pettai <notifications@github.com> schrieb am Fr. 15. Sep. 2017 um 19:55:

**Comment by kovakina** [comment]
From my (first) experience with search queries, I think, together with more detailed documentation, the following could potentially smooth the learning curve:
- When viewing an example query, highlight and have a small annotation of each syntax element, operator, etc on rollover, and a more detailed  explanation of that element on click.
- Auto-completing elements and element suggestions, like in any spreadsheet software.

I could work on mocking it up and prototyping

**Comment by kovakina** [comment]
Initial search guide is almost ready
https://github.com/kovakina/timesketch/blob/master/docs/SearchQueryGuide.md

**Comment by adamjnichols** [comment]
This is *so* awesome.

**Comment by jaegeral** [comment]
Seeing @kovakina work and the recent addition to the default search window, I will close this one out, if there are new specific requests on what needs to be documented, we can open a new more specific issue to track it.
