### ISSUE TITLE
timesketch (20170721) - source filter (by data_type) is missing from GUI

### ISSUE THREAD

**Issue by pettai** [google/timesketch#428]
The lastest stable timesketch release (20170721) no longer shows the source filter (by data_type) in the GUI.

![missing-source-filter](https://user-images.githubusercontent.com/3317462/30344073-1c7608f2-9800-11e7-88e2-c39d92c4c212.png)

**Comment by rough007** [comment]
I'm having the same issue.  I've been troubleshooting to see if there was something wrong but I've not found any errors in the logs.  This is one of the most useful filters!

**Comment by berggren** [comment]
We removed this feature from the latest release as it was a bit confusing when switching back and forth between saved searches and normal queries. We are looking into building a better UX for this feature in the near future.

**Comment by pettai** [comment]
Ok, I see the point.
(In which commit was it removed btw. ? )

**Comment by berggren** [comment]
abd3bf03f7e2f7623ba17d40ea6d2409892d6305

:)

**Comment by JamesHabben** [comment]
Is there a way to use the advanced query to replicate this in a manual way?

I've tried following this suggestion and I only get 'Internal Server Error' back.
https://stackoverflow.com/questions/14466274/query-all-unique-values-of-a-field-with-elasticsearch/26647301#26647301

**Comment by kiddinn** [comment]
this is trying to use the aggregation functionality of ES, which is not yet built into TS, it is coming soon though.

What are you trying to accomplish? Seeing all available data_type attributes in the timeline? Or just trying to filter on some of them?

**Comment by JamesHabben** [comment]
Part of it trying to filter on types. I know how to do that.

Another part is exploring TS. I’m fairly new user and I don’t know all the data types.

On Jan 23, 2019, at 02:52, Kristinn <notifications@github.com<mailto:notifications@github.com>> wrote:


this is trying to use the aggregation functionality of ES, which is not yet built into TS, it is coming soon though.

What are you trying to accomplish? Seeing all available data_type attributes in the timeline? Or just trying to filter on some of them?
