### ISSUE TITLE
Vagrant install issue

### ISSUE THREAD

**Issue by adrastee** [google/timesketch#442]
Hello,
Using Vagrant wiki install docs, I've done :

$ cd timesketch/vagrant
$ vagrant up
.. wait until the installation process is complete
$ vagrant ssh
$ tsctl runserver -h 0.0.0.0 **<-- error : "tsctl: command not found"**

Thanks for your help.

**Comment by franekp** [comment]
We need some more information:
 - the commit hash of version that was used
 - output of the `vagrant up` command you did
 - output of `pip show timesketch` inside vagrant
 - output of `echo $PATH` inside vagrant

A fix you can try:
```console
vagrant ssh
pip install -e /usr/local/src/timesketch/
```

**Comment by adrastee** [comment]
I finally did a fresh install and all is ok now. Thanks.
