### ISSUE TITLE
Support importing of psort.py JSON lines output

### ISSUE THREAD

**Issue by morallo** [google/timesketch#476]
To overcome the memory exhaustion issue when importing large JSON files, it could be possible to use the [`json_line`](https://github.com/log2timeline/plaso/blob/150cf208c5a3d5e8346317c3cc46c5be01e2e21c/plaso/output/json_line.py) Plaso output format to import into Timesketch.

This way it should be imported line-by-line, like a CSV, without the limitations of CSV format (static columns).

Reference: http://jsonlines.org/examples/

**Comment by adamjnichols** [comment]
#511

**Comment by adamjnichols** [comment]
Merged.
