### ISSUE TITLE
Make invalid query message appear/more prominent

### ISSUE THREAD

**Issue by Onager** [google/timesketch#498]
At present, the only indication in a query is a very small "internal error" box at the top of the page, and this is easy to overlook.

**Comment by geekscrapy** [comment]
+1 for this, a red banner bar would be better. I've often overlooked these errors

**Comment by kiddinn** [comment]
#1001 is partially addressing this concern, that is at least providing better error messages from the API. However the actual error messages also need to be made more prominent in the UI, which is another step that needs to be done

**Comment by kiddinn** [comment]
This is also more or less the same as #682

**Comment by kiddinn** [comment]
I will close this issue and track the issue in #682 instead of having multiple tickets open
