### ISSUE TITLE
Create User guides

### ISSUE THREAD

**Issue by zappeee** [google/timesketch#505]
Some more guides on how to use Timesketch would be appreciated.

**Comment by berggren** [comment]
Yeah, this is really needed, I agree :) We are working on a user guide. @aguilajesus for awareness.

**Comment by deralexxx** [comment]
@zappeee  anything else then already in https://github.com/google/timesketch/blob/master/docs/Users-Guide.md that you would like to have covered?

**Comment by zappeee** [comment]
Yes, I was think more about the UI

**Comment by jaegeral** [comment]
Actually I think this is duplicate to https://github.com/google/timesketch/issues/1204 which also has some examples already.

Will close this issue here as duplicate.
