### ISSUE TITLE
SearchTemplate API

### ISSUE THREAD

**Issue by tomchop** [google/timesketch#508]
It seems SearchTemplate manipulation as it currently exists in the API is very much bound to View creation (e.g. https://github.com/google/timesketch/blob/master/timesketch/api/v1/resources.py#L367). Would it be useful to add an extra API resource for CRUD'ing system-wide SearchTemplates?

**Comment by aguilajesus** [comment]
what's your use case, tom? we could use SearchTemplates API for #292 through the UI.

**Comment by tomchop** [comment]
I'd want systems to be able to regularly push or update SearchTemplates.

**Comment by berggren** [comment]
Thanks Tom. Closing this one in favor of #292
