### ISSUE TITLE
Timesketch & Elasticsearch 6.1??

### ISSUE THREAD

**Issue by NetwarSystem** [google/timesketch#512]
I installed Timesketch on a system with Elasticsearch 5.6.5 - this was a local VM, had no serious issues getting it going.

Tonight I decided to Timesketch on a system running Wazuh, which recently upgraded to Elastic 6.1. The install feels pretty similar, but at the end of the run I have a service on port 5000 that doesn't respond. Are there any caveats to making it go on 6.1?

An adjunct question - we often tunnel services over ssh and I found that Timesketch seems to dislike this. Does anyone else do it this way, or are we required to run nginx+ssl to keep it safe?

**Comment by NetwarSystem** [comment]
Not sure what the issue was, but local install on 6.1.1 is working.

**Comment by berggren** [comment]
Hi,

ES 6.x should work just fine, as long as your indices was created with 5.x.
Regarding tunneling over SSH. What exact problems are you seeing? There
should not be any problems with this. Timesketch only needs 443 from the
client.

/jbn
