### ISSUE TITLE
Use icons instead of names for Plaso timestamp descriptions

### ISSUE THREAD

**Issue by Onager** [google/timesketch#516]
The idea is to make things a bit more compact and readable in the timeline view. I'm happy to work on a PR for this.

**Comment by berggren** [comment]
Great idea! Would this be different icons for different timestamp sources? I guess so. This means we need to map each source type to a specific icon name.

**Comment by adamjnichols** [comment]
Could this be done upstream in Plaso with a change to include an icon with the ForensicArtifacts lib?

**Comment by rgayon** [comment]
Consider using emojis instead of binary files

**Comment by berggren** [comment]
@adamjnichols I don't think we should dictate what icon should be used in the artifact lib.
@Onager Any progress on this one?

**Comment by Onager** [comment]
No progress as yet, and I agree that this should live in Timesketch, not Plaso or Artifacts.

**Comment by berggren** [comment]
generic emoji support has been implemented and can be used to express timestamp descriptions if wanted. Currently exposed for analyzers.
