### ISSUE TITLE
Upload and process plaso storage files

### ISSUE THREAD

**Issue by berggren** [google/timesketch#52]

**Comment by dnice77** [comment]
Just curious, I have both Plaso and timesketch installed but when I run psort.py -o list no timesketch output option...did I overlook something?

**Comment by berggren** [comment]
@dnice77 What version of Plaso are you running?

**Comment by dnice77** [comment]
The latest so 1.2

**Comment by berggren** [comment]
I see! So, you need to run the development version of plaso in order to use the new Timesketch feature at the moment. See the following link for more information:
https://github.com/google/timesketch/wiki/UserGuideAddTimelines

**Comment by berggren** [comment]
This is done.
