### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by deralexxx** [google/timesketch#522]
Hey there, I am currently collecting various Security related APIs for https://github.com/deralexxx/security-apis/

As I can see, timesketch has a nice API (https://github.com/google/timesketch/tree/master/timesketch/api/v1) but I am unable to find any documentation for it, so either it is very good hidden or not available, would appreciate it if you can point me to a doc that I can refer to.

Thank you very much

**Comment by adamjnichols** [comment]
I'm not sure that the Timesketch API is a true RESTful API similar to those that you're collecting.  The API for TS is a bit more tightly coupled to the client, and not meant as much for the sort of use that would be documented in this way.  Do you have a specific use case in mind?

**Comment by berggren** [comment]
What Adam said, the API is meant for internal implementation for the Web frontend. This doesn't mean that it can be used for whatever you want though. Documentation for it, seeing it has not been a end-user API, hasn't been done yet.

The preferred way of interacting with the API is with the official python client that wraps the REST API.

```
pip install timeksketch-api-client
```

**Comment by deralexxx** [comment]
hm yes that makes sense, I thought it would be somehow possible to send logline entries from everywhere like:
```

curl -H "Content-Type: application/json" -X POST -d '{
  "message": "A message","timestamp": 123456789,"datetime": "2015-07-24T19:01:01+00:00","timestamp_desc": "Write time","extra_field_1": "foo","extra_field_2": "bar",
 }' http://timesketch/api/addEntry

```

The reason why I would actually love to use timesketch is that while not using log2timeline / plaso is a "add one entry with an web ui"

But I maybe should start a dedicated issue for that to see how that could be an use-case.

**Comment by berggren** [comment]
Aha, ok yes that is another use case and we have another issue open for this feature request (#71 ). This could be implemented as a manual index per sketch, and then append to that via the UI.

Hopefully we can start the implementation on that soon.

**Comment by berggren** [comment]
Closing this one as we are tracking this feature in #71
