### ISSUE TITLE
Install failure on Ubuntu 16.0.4.3 LTS

### ISSUE THREAD

**Issue by NetwarSystem** [google/timesketch#528]
Having beat the bare Timesketch install process half to death, I took a look at pull requests and noticed "Docker is for deployment". I'm not a Docker user, but I've got some folks who want to play with Timesketch, so I found some install instructions.

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

And this seemed easy enough, soul caveat is that my Ubuntu boxes are running under a Xen based cloud provider.

The following commands
apt install docker-ce docker-compose
git clone https://github.com/google/timesketch.git
cd timesketch/docker
docker-compose up

Produces this error:

root@cathouse:~/timesketch/docker# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I get the idea that maybe if I pull this branch of Timesketch, it'll run, but my git-fu is not strong. Is there some specific incantation to get this branch? I'm reading on git now, but if I ran into this, others may as well.

https://github.com/google/timesketch/tree/ajn-docker-tweaks

**Comment by berggren** [comment]
I don't recommend docker right now, it need more testing before stable. Did you get Vagrant to work for you? If you follow the exact same steps as in the bootstrap.sh script in the vagrant directory on a fresh Ubuntu box everything should just work for you. Have you tried this approach?

I will test the installation instructions tomorrow on a fresh installation of Ubuntu. I will let you know.

**Comment by adamjnichols** [comment]
To berggren's point, Docker is being revised but there is a PR coming that will make this quite a bit better.  If you want to use the branch you've mentioned, you'll have more success.

The issue you're having, is due to the way you're installing docker.  We don't know anything about what repos are defined on that system, or what packages you're getting with those apt commands.  This is why the [Docker instructions](https://github.com/google/timesketch/tree/ajn-docker-tweaks/docker) specifically state to install from the official directions to ensure you are configuring the official repositories and getting the latest and greatest.

**Comment by NetwarSystem** [comment]
Even when the Docker setup is working, that doesn't fit either of my environments.

I have four machines in an Elasticsearch cluster, ports 9200/9300 already claimed.

Wazuh is a standalone box but same deal, ports 9200/9300 already claimed.

So I am chasing this method so I can stick up a public demo system, mark off this task, and wait for a stable release I can use more broadly.

If the Digital Ocean instructions are used to install Docker, then do this to get latest for Timesketch, looks like it'll behave.

git clone https://github.com/google/timesketch.git
cd timesketch
git checkout origin/ajn-docker-tweaks
docker-compose up

This seems very positive ...

https://gist.github.com/NetwarSystem/11e50126134405efb66f033433a2e1fc

The comment problem in the bare install is resolved here, the only complaint I have so far as that the system 'clocks' forever while importing a single line CSV file. It only stops when one tries to make use of that file's content in a Sketch.

Did this on a local Lubuntu VM, was smooth. I have a small VPS that's just getting recycled, will see if I can get a public demo up and going this morning ...

**Comment by NetwarSystem** [comment]
I made Docker work - I think we can just gas this thread.
