### ISSUE TITLE
Vagrant install is broken due to polkit

### ISSUE THREAD

**Issue by adamjnichols** [google/timesketch#531]
Celery doesn't want to enable/start due to polkit policy issues.

**Comment by berggren** [comment]
Can you add the error you get when starting celery?

**Comment by adamjnichols** [comment]
Thinking about closing this, based on some of the things I've found.  Polkit isn't the issue as much as some of the permissions changes that removed the ubuntu user as the default for canonical cloud images earlier this month.  The polkit thing was just a symptom.

At any rate, I believe we fixed it with a merge some time ago, will dig that out, link, and close.

**Comment by adamjnichols** [comment]
Should be corrected with last pagination [commit](https://github.com/google/timesketch/compare/ajn-paginate-the-things#diff-3a627674bc62724e5f508803f8ac3e2b)
