### ISSUE TITLE
Replace test.plaso zip format file with new sqlite format

### ISSUE THREAD

**Issue by adamjnichols** [google/timesketch#536]
A [commit](https://github.com/log2timeline/plaso/commit/3b681c9abb7fa8664c054e29457091b645ded0e7) to the plaso project on 2 Jan 18 removed support for zip-based files, rendering our test file useless.

**Comment by berggren** [comment]
Good catch, let's create one with Plaso 20171231. The test file is System.evtx from the Plaso test_data dir.

**Comment by berggren** [comment]
^-- this file:
https://github.com/log2timeline/plaso/blob/master/test_data/System.evtx
