### ISSUE TITLE
Some minor UI improvements

### ISSUE THREAD

**Issue by kovakina** [google/timesketch#544]
Listing here all the things I'd like to add/change to the UI:

1. Rearrange the index page, include extra text about what is happening on the page, for example : "Choose a sketch from the list below or create a new one"
2. Put sketch name into each of its' pages header
3. More hovers! Make hovering explanations to UI icons.
4. put a "edit sharing settings" button next to "Shared with" list.

Maybe some more minor changes

**Comment by adamjnichols** [comment]
- Refactor controls/button clusters
- Make current working sketch more apparent

**Comment by kovakina** [comment]
Great ideas.What would you change in button clusters?

**Comment by adamjnichols** [comment]
Let's talk offline.  There are a lot of UI things planned in the near term.

**Comment by kovakina** [comment]
+ add links to help files into the UI, once help files are ready

**Comment by berggren** [comment]
"Currently no way to delete/modify Views (this requires discussion)" <- this works indeed, but I agree we need to think more of the UX here.

**Comment by berggren** [comment]
Let's split these into 3 separate issues:
1. Refactor controls/button clusters
2. Make current working sketch more apparent
4. Filter card doesn't handle lots of timelines

**Comment by berggren** [comment]
@kovakina do you want to pick this up again, now with the new UI ready?

**Comment by berggren** [comment]
Closing as obsolete. This was for the old UI.
