### ISSUE TITLE
Rollback/cleanup on error conditions

### ISSUE THREAD

**Issue by adamjnichols** [google/timesketch#550]
The database can reach a cluttered state over time when failures are encountered.  We should prevent this.

**Comment by berggren** [comment]
Do you have any more information around this? Log output? I haven't seen this in any of my deployments.

**Comment by berggren** [comment]
A bunch of work has been done to make this more stable. Now every celery worker will get its own SQL connection and session for example. Closing this one, but feel free to re-open if there is any problems left.
