### ISSUE TITLE
Advised needed for installing Timesketch on Alpine Linux

### ISSUE THREAD

**Issue by dustyhorizon** [google/timesketch#554]
Hello,

I am trying to get Timesketch working on Alpine Linux in a docker container but there seems to be issues with pycypher (libcypher-parser) where the builds are not working properly. 

Managed to get one of the builds working which gave me pycypher 0.6.1 and had to manually update the requirements file so it is used instead of trying to get 0.5.9.

Enabled graph supports and everything else and tried to process an image but it does not show up in graph view. Could it be that I am using a different version of pycypher?

Any help would be appreciated.

**Comment by adamjnichols** [comment]
Hi there -- there is some pretty complex transpilation that occurs for cypher that so far as I know has a hard requirement for 0.5.9, which is likely why you run into this issue.  Do you have any server-side output or other info you can provide?

Failing that, I would remove 0.6.1 and replace it with 0.5.9, which can be found [here](https://pypi.python.org/pypi/pycypher/0.5.9).

**Comment by dustyhorizon** [comment]
I am having issues which branch was used to build pycypher listed on pypi. On Alpine I am unable to install pycypher via pip which is why I require to build them myself.

**Comment by berggren** [comment]
Hi, the python bindings for libcypher is currently being integrated into the libcypher project. In the meantime you can build using the instructions here:
https://github.com/franekp/libcypher-parser/blob/pycypher-wip/pycypher/doc/DeveloperGuide.md

**Comment by adamjnichols** [comment]
Please let us know if you still require assistance here, else we'll assume you've solved the issue and close.  Thanks!

**Comment by berggren** [comment]
Closing this due to 1.5y of silence :)
