### ISSUE TITLE
Stars and Annotations do not work

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#557]
Hi,

I'am using the current timesketch version from the github master branch on Ubuntu 16.04.
I've setup Celery, Plaso and Timesketch and everything works fine.

After the successful import of a Plaso File into timesketch, I am not able to set stars on the timeline.
I already tried it with the tsctl development server and gunicorn.

When a star or comment is set the following backtrace occurs:
[traceback.txt](https://github.com/google/timesketch/files/1799549/traceback.txt)

 I am using the following elasticsearch version with the elasticsearch5 pip package.
``` "number" : "5.6.8",
    "build_hash" : "688ecce",
    "build_date" : "2018-02-16T16:46:30.010Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"```

Thanks for your help,
Cheers
Sven

**Comment by berggren** [comment]
This is probably because you need the elastic scripts loaded:

```cp timesketch/contrib/*.groovy /etc/elasticsearch/scripts/```

and then restart elasticsearch.

**Comment by berggren** [comment]
^-- Installation instructions need updating. I will fix asap.

**Comment by n3x77** [comment]
Hi Johan,

Thx for the very quick reply. I thought elastic 5 needs the painless
scripts.

I will give it a try with the groovy ones.
Johan Berggren <notifications@github.com> schrieb am Sa. 10. März 2018 um
19:37:

**Comment by berggren** [comment]
groovy still works, will update to painless in the next release. Let me knows how it goes!

**Comment by n3x77** [comment]
Hi Johan,

after switching from Painless to Groovy the following setup works:
* Timesketch from Github Master
* Elasticsearch 5.6.8
* Groovy Scripts
* Celery

Thanks for your help!

I've just requested the CLA.

If you like, I could provide an ansible role for the deployment.

Cheers,
Sven

**Comment by berggren** [comment]
Would love to see the ansible role :)
