### ISSUE TITLE
Ability to label events after import

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#558]
It'd be great to be able to manually tag events once uploaded

**Comment by berggren** [comment]
Yeah, this has been a long standing request. I'll make it a priority. The code is there in the backend, it just need to be implemented in the frontend.

**Comment by garanews** [comment]
any news on this?

**Comment by jaegeral** [comment]
nope, still open.

**Comment by kiddinn** [comment]
this is being worked on ATM

**Comment by berggren** [comment]
So, tags can be done by analyzers. for manually added, it is labels. Changing the title to reflect this.

**Comment by berggren** [comment]
Closing i favour of #580
