### ISSUE TITLE
Pivot from graph view

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#563]
I don't seem to be able to pivot from the graph view at the moment. Is this correct?

Really like to use the graph for a bit of discovery work, and to highlight other events of interest - or at least be able to star events

**Comment by berggren** [comment]
Yes, the interactive pivoting is limited at the moment. Could you explain some use-cases you would like to see implemented?

**Comment by geekscrapy** [comment]
Disclosure, I still need to actually figure out how to insert graph data (not familiar with neo4j at all! Any docs re creation of this data?). What I've been playing with is the old demo site and limited exposure with the docker build.

Usecase 1, show all events for discovering new connections.

Usecase 2: Looking at dumping lots of network communications between systems and asking questions of it, using graphing. So to be able to pivot on that data would allow me to find adjacent logs of interest in the timeline view (e.g. host based logs).

As a priority, I'd at least allow staring events.

**Comment by berggren** [comment]
Ok, interesting. Do you want to star nodes in the graph?

**Comment by berggren** [comment]
Ok, interesting. Do you want to star nodes in the graph?

**Comment by geekscrapy** [comment]
I wouldn't want to star nodes, but the events behind them (from the table view from with the graph). You could then search for these starred events in the timeline viewand see what else happened around them. This would allow for a pivot of sorts, all be it, a clunky way to do it

**Comment by berggren** [comment]
@geekscrapy Sorry for the delayed answer here. We are working on making the graph feature more accessable and also easier to build new models using the new analyzer framework.

**Comment by berggren** [comment]
I'm closing this one, but will incorporate this into the new graph framework.
