### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#564]
Quick one! Where can you manage users from?

Using the docker-compose instance.

TIA!

**Comment by berggren** [comment]
The current way of manage users are from the CLI tool tsctl.

```$ tsctl add_user --name foo```

you should be able to run that within your docker container as well.
We are thinking of adding this functionality into the UI as well.

**Comment by geekscrapy** [comment]
Ok thanks - would be great to have this in the gui of course, but appreciate that maybe part of a much larger admin piece!

**Comment by geekscrapy** [comment]
FYI happy to close this if it's already on the roadmap

**Comment by berggren** [comment]
I'll keep it open for now so we can track it here. I might merge it later.

**Comment by deralexxx** [comment]
Would be good to add that to a seperate wiki page for user guides like "administration". Could not find a readme.md for it or I would already have added it.

**Comment by berggren** [comment]
Yeah, we need a general administration/deployment page. @deralexxx feel free to start one under docs/ if you have some cycles over :)

**Comment by berggren** [comment]
Closing out since the support question was answered. User management is being tracked in other issues.
