### ISSUE TITLE
How to create graph

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#566]
Is there any documentation regarding input of data to generate the neo4j graphs?

Are they created upon event ingest? I'm mainly using the csv import feature

**Comment by berggren** [comment]
There is no good documentation at the moment for the graph feature. We are working on it though. The nodes and edges are created here:
https://github.com/google/timesketch/blob/master/timesketch/lib/experimental

I'm currently refactoring that code though, to make it easier to write new transforms.

**Comment by geekscrapy** [comment]
Ok thanks

**Comment by 82d28a** [comment]
Any directions creating graphs from within timesketch app? I set GRAPH_BACKEND_ENABLED = True and made the appropriate changes to that section.  When I select for example interactive logons, I enter username and host, I get the perpetual wait.

**Comment by berggren** [comment]
@82d28a There is no way to do this withi the UI at the moment. With the addition of the new analyzers and the work on the new UI we are updating this feature to be more user friendly and useful. Stay tuned for updates in the near future.

**Comment by berggren** [comment]
Closing this one, as the graph framework is being rewritten.
