### ISSUE TITLE
Scoped search when in saved view context

### ISSUE THREAD

**Issue by geekscrapy** [google/timesketch#570]
A couple of thoughts, some are linked:

1. Add events to an existing Saved view - is this currently possible?

2. Graphically, I believe that when you are viewing a Saved view, the active tab/menu item should be Views and not Explore - the option to "Click here to go back to explore view." is misleading, as you are effectively already there (with some invisible filters applied to make it a saved view)

3. The active view should have its title at the top of the page, not under the search bar? This would make it more obvious what data you are looking at, and the fact that it is a limited view of the data.

4. If a search is conducted from within a Saved view, limit the results to those events included in that Saved view - don't allow other data to become part of the view. If you want to explore the data globally, that is what the "Click here to go back to explore view." button is for. I believe this is currently a bug as the description "You are exploring in the context of a saved view." makes the user believe search results will be limited to results within the Saved view.

5. When switching back to the Explore view with "Click here to go back to explore view.", activate the previous Saved view in the drop-down box. This is a visual clue that not all events are shown. Without it, the user is left guessing what filters are applied as it's not always obvious what timelines are activated. To do this, another drop-down item will probably have to be created to allow deselection of the view.

</thoughts>

**Comment by kiddinn** [comment]
ok, this is an old issue, let's start to look at it.

1. Add an individual event manually? No that's not possible, a view consists of a search query, if the event does not come up during the search query, the query needs to be adjusted or the event.

2. This should be changed in the new ui

3. New UI is different

4. This is not the case today, an interesting idea that we've discussed before. This is of course possible in the API client and using jupyter/colab notebooks. But having this inside the UI would also make sense, we just have to make sure to have some visual indications that a new search query is only querying the results from the saved view and not the entire dataset. @berggren WDYT?

**Comment by berggren** [comment]
Yeah, so most of these have been fixed in the new UI, or changed behaviour. For #4, this is something we have been looking at. It is a bit tricky to get right, but is a good idea.

I'll change the title of this issue to reflect that we are going to do here.

**Comment by berggren** [comment]
Closing this issue as the UI has been rewritten and we are handling saved searches diffrently now. The "search within context" is gone.
