### ISSUE TITLE
Timelines not shown when imported with psort.py

### ISSUE THREAD

**Issue by n3x77** [google/timesketch#571]
Hi,

when importing plaso storage containers that have been created with the plaso version 20180127 
using port.py the Timelines are not shown in the Overview View and Timeline VIew in Timesketch (See attached pictures)
![bildschirmfoto 2018-03-22 um 16 26 14](https://user-images.githubusercontent.com/20700780/37781198-89c558b4-2df0-11e8-8d24-1981b7cd19d5.png)
![bildschirmfoto 2018-03-22 um 16 26 33](https://user-images.githubusercontent.com/20700780/37781199-89e61fb8-2df0-11e8-9cdd-561434d3aa63.png)

If I am using the HTTP upload function the timelines are shown correctly.

Cheers,
Sven

**Comment by adamjnichols** [comment]
HI there!  Can you please provide a bit more information?  It's not clear to me how you're using psort, what args you're giving it, or whether or not your expectations are correct.

Thanks!

**Comment by n3x77** [comment]
Hi, 
so we usually use psort.py from the command line of the timesketch system, with the following arguments:
`psort.py -o timesketch --flush_interval 1000 --name <TIMELINENAME> <PLAOFILE>`.
Afterwards we're adding the Timeline in the web ui.

All timelines that were added directly using psort are not shown in the Timelines Tab.

If we use the http upload function of the timesketch web ui, the timelines are shown in the timelines tab.

Unfortunately it is not clear for me why this happens, because the upload function also uses psort.py insight.

Sorry for the delay, i didn't receive any notification on this issue.

Cheers,
Sven

**Comment by adamjnichols** [comment]
Do you have any verbose output from the psort that fails?  Additionally, why have you chosen to provide a flush_interval?

**Comment by berggren** [comment]
This is because Plaso (psort.py) doesn't update the status of the timeline when done. There is a fix for this in recent Master for Timesketch. Have you tried the latest?
