### ISSUE TITLE
Groovy removed from Elasticsearch 6

### ISSUE THREAD

**Issue by r3dham** [google/timesketch#575]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_scripting_changes.html

As TimeSketch is still using Groovy, annotation and stars don't work on Elasticsearch 6. 
Could you update the script to Painless?

**Comment by mari0d** [comment]
@r3dham I'm working on a PR for this. I have TimeSketch working cleanly with ES 6.x at https://github.com/mari0d/timesketch/tree/mari0d/painless and we are using that fork internally, but it currently isn't fully compatible with ES 5.x. Once I have the ES 5.x support back in I will open the PR (may need some handholding).

**Comment by mari0d** [comment]
@berggren is it worth me taking the time to do a PR for the work above? Not sure how far along you are with it; just noticed that you mentioned in issue 557 that you had the work queued up.

**Comment by berggren** [comment]
@mari0d Sorry for the delay. We already have painless scripts ready in the repository. We just need to update the documentation and make some minor changes to the loading.

Example:
https://github.com/google/timesketch/blob/master/contrib/add_label.painless

I will make this a priority to have Timesketch be ES 6.x ready by default.

**Comment by adamjnichols** [comment]
Looks like the ‘file’ key is now ‘source’, but that change has not been made in the fork you mention.

**Comment by r3dham** [comment]
While I modified the source codes “file” key to “source” or “id”, it still doesn’t work

**Comment by r3dham** [comment]
@berggren From version 6, Elasticsearch removed file scripts itself.(https://github.com/elastic/elasticsearch/pull/24627)
It means that coping painless scripts into the scripts directory doesn't work. 

We need to use "Stored Script" with "id" parameter. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#modules-scripting-stored-scripts

Or embedded painless scripts with "source" parameter.

**Comment by berggren** [comment]
Yeah, thanks for the heads-up. We will need to figure out a clean migration to 6.x without brake all 5.x users. Will take a look asap.

**Comment by ptitdoc** [comment]
Please note that the commit attempt above only support Elasticsearch 6 using embedded painless scripts as suggested by @r3dham.
I currently use it as a workaround because I cannot install Elasticsearch 5.X.

**Comment by ptitdoc** [comment]
Side note: Elasticsearch version can probably retrieved from self.client.info(). How about using scripts embedded in code with a selection based on Elasticsearch version ?

I also noted that the histogram is only showing a single bar using this commit. I don't know yet if the commit is the cause.

**Comment by ptitdoc** [comment]
Also elasticsearch 6 now apparently requises specifying path:timesketch_label in nested querie. This is required for star or hidden queries.
However I managed to make star queries work several times before fixing this. I really dont understand why.
