### ISSUE TITLE
TimeSketch on Docker failed at step 14

### ISSUE THREAD

**Issue by TWFpa2Vs** [google/timesketch#578]
Hi guys,

Im trying to run TimeSketch within docker on my MacBook pro but it is giving an error on step 3 and is failing on step 14.

> [3/4] Linking dependencies...
> warning "@angular/compiler-cli > tsickle@0.23.6" has incorrect peer dependency "typescript@2.3.4".
> warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
> warning " > codelyzer@3.2.0" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
> warning " > karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".

> Step 14/20 : RUN pip install /tmp/timesketch/
>  ---> Running in ad2fc29903d6
> Processing /tmp/timesketch
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-XI28Ek/setup.py", line 27, in <module>
>         from pip.req import parse_requirements
>     ImportError: No module named req
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-XI28Ek/
> ERROR: Service 'timesketch' failed to build: The command '/bin/sh -c pip install /tmp/timesketch/' returned a non-zero code: 1

docker version: Version 18.03.0-ce-mac60 (23751
MacOS version: 10.13.4 (17E199)

**Comment by TWFpa2Vs** [comment]
Thanks for pointing that out, i have tried vagrant also but could not get that to work. will try again in a few days.

**Comment by berggren** [comment]
Ok, let me know what problems you run into and I'll try to fix it.

**Comment by adamjnichols** [comment]
Hey there -- this is not an issue with docker, but appears to be an issue that has resulted from the release of PIP 10.  I've submitted PR #583 to address this.  After it's merged (or if you'd like to clone the ajn-pip10 branch) you should have no issues running Docker.

**Comment by berggren** [comment]
Fix merged, thanks Adam!
