### ISSUE TITLE
Manually adding labels

### ISSUE THREAD

**Issue by berggren** [google/timesketch#580]
We need a way to manually add labels to events.

**Comment by jaegeral** [comment]
In the same way it should also be possible to remove labels.

**Comment by kiddinn** [comment]
this is already possible in the REST API, and the API client has support for this. This request is for adding this into the UI.

**Comment by kiddinn** [comment]
> In the same way it should also be possible to remove labels.

But are you supposed to be able to remove any labels? Or just those that were manually added? Can we remove labels that an analyzer has programmatically added?

**Comment by jaegeral** [comment]
> But are you supposed to be able to remove any labels? Or just those that were manually added? Can we remove labels that an analyzer has programmatically added?

This is a good question. I guess it would be pointless if we would allow removing an automatically added label and then do not implement a "protection" for the same label to be added again. But this would also mean if someone deleted an analyzer added label by accident, how to recover that.

Overall I think I would also be fine to start with "no function to delete Tags" for now and we see how the feature is used and if there is actually huge demand to remove a tag.

**Comment by jaegeral** [comment]
This feature has been added to TS in the meantime so this issue can be closed. WRT to removing labels, @kiddinn did mention some good points, so if there is a need to discuss removing labels from an event, we could track that in a seperate issue
