### ISSUE TITLE
Graph creation framework

### ISSUE THREAD

**Issue by berggren** [google/timesketch#582]
Creating edges and nodes should be simple and automated when adding data to a sketch.

**Comment by berggren** [comment]
This is a very interesting idea! The forst iteration will be a framework on the backend that will make it easy to code this up when inporting new data. Having this from the UI is something that could potentially be very powerful. At least for simple modelling like your example.

**Comment by geekscrapy** [comment]
Agreed

For an extra example of things I'd be looking at in particular: model events from Sysmon, parent child process relationships and network events etc.

**Comment by garanews** [comment]
This can be useful for event logs:  https://github.com/JPCERTCC/LogonTracer
Do you have any news for automatic creation of edges and nodes?
Thanks

**Comment by berggren** [comment]
The graph feature was recently updated (rewritten). We have a new plugin system for creating graphs. I will open a new issue to document the development process of new graphs.
