### ISSUE TITLE
have a stand-alone timesketch storage (or equiv) module

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#589]
have a stand-alone timesketch storage (or equiv) module that plaso can use without timesketch front-end dependencies

**Comment by joachimmetz** [comment]
Currently plaso imports flask as well: https://github.com/log2timeline/plaso/blob/master/plaso/output/timesketch_out.py#L10

```
try:
  from flask import current_app
  import timesketch
  from timesketch.models import db_session
  from timesketch.models.sketch import SearchIndex
  from timesketch.models.user import User
except ImportError:
  timesketch = None
```

**Comment by berggren** [comment]
The Timesketch output module is meant to be used on a machine where Timesketch is installed and configured. The use of "current_app" is to pick up configuration for the elasticsearch server configured for Timesketch.

This module is not designed to output to a remote Timesketch server per se. It can be done, but most people should use it on their Timesketch server itself.

If you want to export a Plaso file to a remote Timesketch server the user need to use the upload API which is out of scope for Plaso.

That being said, we should add a check to make sure that the local Timesketch installation is configured and ready to use.

**Comment by joachimmetz** [comment]
Per conversation this is something to consider long term. The immediate use case would be testing plaso-timesketch integration without having to install all dependencies, but additional use-cases could be other things that want to talk to the timesketch database.

**Comment by berggren** [comment]
Closing this one. The solution here is to drop the dependency on Timesketch on Plaso and just have a generic ES output module.

https://github.com/log2timeline/plaso/issues/2560
