### ISSUE TITLE
Error while "docker-compose up"

### ISSUE THREAD

**Issue by adrastee** [google/timesketch#591]
Hi,

I am trying to install Timesketck Docker following https://github.com/google/timesketch/tree/master/docker
on Windows 10 x64

At the last stage "docker-compose up" the error is:

> docker-compose up

> Creating docker_neo4j_1 ...
> Creating docker_postgres_1      ... error
> Creating docker_elasticsearch_1 ...
> Creating docker_redis_1         ...
> Creating docker_elasticsearch_1 ... error
> ERROR: for docker_postgres_1  Cannot create container for service postgres: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\postgresql\\\\data:/var/lib/postgresql/data"\nis not a valid Windows path'
> 
> Creating docker_neo4j_1         ... error
> Creating docker_redis_1         ... error
> 
> ERROR: for docker_redis_1  Cannot create container for service redis: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\redis:/data"\nis not a valid Windows path'
> 
> ERROR: for docker_neo4j_1  Cannot create container for service neo4j: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\neo4j\\\\data:/var/lib/neo4j/data"\nis not a valid Windows path'
> 
> ERROR: for postgres  Cannot create container for service postgres: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\postgresql\\\\data:/var/lib/postgresql/data"\nis not a valid Windows path'
> 
> ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\elasticsearch:/usr/share/elasticsearch/data/elasticsearch"\nis not a valid Windows path'
> 
> ERROR: for redis  Cannot create container for service redis: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\redis:/data"\nis not a valid Windows path'
> 
> ERROR: for neo4j  Cannot create container for service neo4j: b'Mount denied:\nThe source path "\\\\var\\\\lib\\\\neo4j\\\\data:/var/lib/neo4j/data"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.

Reading the last lines of the help page:
> (...)
> redis: /var/lib/redis
> These locations on the host filesystem

These path are unix path ; I understand your Docker does not work on Windows ?

**Comment by adrastee** [comment]
Could you please confirm me that Timesketch via Docker works on Windows 10 (or not?)
Thanks.

**Comment by adamjnichols** [comment]
Sorry, we do not currently support any of the container-based installs on Windows.

**Comment by berggren** [comment]
Correct, we do not support Windows 10 as host system at this time. I have updated the docs to reflect this. Thanks for raising this!

@adrastee - If you get it to work I would be more than happy to work on a PR with you :)
