### ISSUE TITLE
CSV Upload "Missing fields in CSV header: [u'message']"

### ISSUE THREAD

**Issue by deralexxx** [google/timesketch#596]
Pulled the latest version of timesketch today in a vagrant, ran it, tried to upload a csv which looks like the following:
```
message,timestamp,datetime,timestamp_desc,Date,aaa
A message,1331698658276340,2015-07-24T19:01:01+00:00,Write time,foo,baraaaa
```

Gives me the following error:
`
                        Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/tasks.py", line 143, in run_csv_jsonl
    for event in read_and_validate(source_file_path, delimiter):
  File "/usr/local/src/timesketch/timesketch/lib/utils.py", line 61, in read_and_validate_csv
    u'Missing fields in CSV header: {0:s}'.format(missing_fields))
RuntimeError: Missing fields in CSV header: [u'message']
`

However, as far as I can tell, the header is set in the right way.

I stumbled across the error while trying to import a way larger csv with way more columns that failed for some reason and trying to shrink the file down I ended up with the mentioned bug above.

Ideally a preview of the csv would be handy to see what was parsed or what was the error.

**Comment by deralexxx** [comment]
I named the file "testtest.csv" also tried "test-test.csv"

**Comment by deralexxx** [comment]
Ok investigated the def read_and_validate_csv(path, delimiter) method in /usr/local/src/timesketch/timesketch/lib/utils.py a bit and I think this needs some more love in regards to parsing and value errors to not simply crash, I hope I can give a PR for that, however I did not spot the difference between uploading via web and command line.

**Comment by berggren** [comment]
Can you run diff against the two files? I'm curious what the difference is. Maybe newlines?

**Comment by deralexxx** [comment]
There you go: <img width="778" alt="issue" src="https://user-images.githubusercontent.com/741037/39995529-c0a9b266-577c-11e8-9445-7cffddc7146b.png">
It was a non printable char.

**Comment by berggren** [comment]
Good to hear, problem solved. :)
