### ISSUE TITLE
Show surrounding context for events 

### ISSUE THREAD

**Issue by mmaisel** [google/timesketch#60]
This would be similar to the -A and -B flags for grep/ack. A user might have an indicator and want to match nearby events to identify related activity.

I manually adjust the time filter to and use a wildcard search to achieve this effect. Maybe I'm missing how to do this in the ES or Lucene DSL?

**Comment by berggren** [comment]
Hi,

Yeah, this is something that would be super valuable. My thinking is that this is a kind of "zoom" feature, where you can zoom in on a event and get +-time and all events surrounding it to get context. Then zoom out again to get back to the timeline.

Thanks for the great idea! I'll put it on the roadmap.

**Comment by berggren** [comment]
This is done.
