### ISSUE TITLE
Delete user / groups

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#600]
During Documentation creation I realised there is at the moment no method to delete users / groups

Lacking insights, I was not sure if deleting a user might crash other concepts like tags, comments etc. 

At least having an issue for people to see, there is at the moment no such think like deleting users.

Workaround if you want to block access for a user is setting his password to a value that he does not know.

**Comment by berggren** [comment]
In the User model we have a boolean attribute called "active", and the indented use is to deactivate a user. We should make it possible to inactivate a user via tsctl.

**Comment by deralexxx** [comment]
I will give that one a try to implement.

**Comment by deralexxx** [comment]
- [ ] introduce disable_user to tsctl
- [ ] implement disable_user
- [ ] add information to user_guide how to disable user and why not deleting user

**Comment by kiddinn** [comment]
This is still not possible in tsctl. Do you want to add it @jaegeral ??

**Comment by jaegeral** [comment]
I think it would still be a useful feature, yes

**Comment by jaegeral** [comment]
freeing this Feature request for now as I had no time to work on it for a while if someone wants to pick it up.

**Comment by LeoAndTheTree** [comment]
Hello! We are a group of undergraduate students from Carnegie Mellon University working on a software engineering class project. We have been tasked with contributing to an open-source project, and we are very interested in this one! We want to take a look at this issue and implement this feature. Please let us know if there is anything else you can let us know about this feature. Thanks!
[https://github.com/dyou3968](url)
[https://github.com/joshjzhou](url)
[https://github.com/tyjlowe](url)
[https://github.com/LeoAndTheTree](url)

**Comment by jaegeral** [comment]
Hey @LeoAndTheTree I think there should be plenty of info already in this Issue, let me know if you have any further question and thank you for picking it up.
