### ISSUE TITLE
[HELP] Importing winevtx events - missing events and parsing errors

### ISSUE THREAD

**Issue by arisjr** [google/timesketch#602]
Hello.

I'm just starting to use timesketch. 

I'm importing a PLASO file and I'm concerned that some important events, like TerminalServices login and others, are missing on the processed TIMESKETCH timeline. Also, I noticed that the EVTX events strings parsing is very poor, and in a worst case it removes its contents. 

If I export to a XLSX format using the same PSORT tool, I can correctly read the EVTX TerminalServices events and its contents.

I need a help to see If this is a psort.py problem or a timesketch problem. 

I'm using the release 20180127 as asked on the timesketch page. 
Using timesketch in a docker container installation, as instructed in timesketch page.

**Comment by arisjr** [comment]
No answer from developers so far. Timesketch a nice tool, but without this correction, it will be difficult to use. I consider EVTX an important source of evidence.

**Comment by kiddinn** [comment]
sorry for the lack of answers here... but do you happen to have an example timeline that we can use for testing purposes?

timesketch uses the message field from plaso and displays that, is this something that should rather be added upstream, that is to fix the actual message string?

**Comment by arisjr** [comment]
As you may know, I already solved my case with a spreadsheet. But I just checked and I still have the plaso file. It has 2.5Gb. 

If you may, I would prefer to continue this conversation in privet to exchange data.

Regards,

**Comment by kiddinn** [comment]
yes, please reach out to me out of band, so that I can debug this... kiddi at kiddaland dot net

**Comment by berggren** [comment]
Closing this as the last response was a year ago
