### ISSUE TITLE
docker:  Permissions issue on causing services to restart

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [google/timesketch#607]
### docker:  Permissions issue on causing services to restart
- Docker build runs without errors, docker pulls down the addtional images as needed.  
- I had to change the docker-compose to v 2 as the install in RHEL 7 uses this version.  
- Remove 'links' as its deprecated and added a networks to each of the services and a networks to the config
- changed the volumes to run and store in dockers volumes 
> my compose file is listed below the errors

- all containers appear to be up and running except _elasticsearch_ do to permissions issue (see below).
- timesketch looks to have an issue pushing the default admin password (see below as well)
- permissions appear to be on the actual container.  first time i have seen this with docker so not sure what the issues is.  

__errors:__
- elasticsearch:
```chown: changing ownership of '/usr/share/elasticsearch/data/elasticsearch': Permission denied```
- timesketch:
 - the issue here is retrieiving the password to login ( i believe)
```
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter password: Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 600, in <module>
    shell_manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/bin/tsctl", line 85, in run
    password = self.get_password_from_prompt()
  File "/usr/local/bin/tsctl", line 74, in get_password_from_prompt
    first_password = prompt_pass(u'Enter password')
  File "/usr/local/lib/python2.7/dist-packages/flask_script/cli.py", line 35, in prompt_pass
    rv = getpass.getpass(prompt)
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
```

__docker-compose.yml__
```
version: '2'
services:
  timesketch:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8090:80"
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - NEO4J_ADDRESS=neo4j
      - NEO4J_PORT=7474
      - TIMESKETCH_USER=${TIMESKETCH_USER}
      - TIMESKETCH_PASSWORD=${TIMESKETCH_PASSWORD}
    restart: always
    networks:
      - tsnet

  elasticsearch:
    # uncomment the following lines to control JVM memory utilization
    # in smaller deployments with minimal resources

    #environment:
    #  - ES_JAVA_OPTS= -Xms1g -Xmx1g # 1G min/1G max
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - escontrib:/usr/share/elasticsearch/config/scripts/
      - esdata:/usr/share/elasticsearch/data/elasticsearch
    networks:
      - tsnet

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tsnet

  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - tsnet

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    restart: always
    volumes:
      - neo:/var/lib/neo4j/data
    networks:
      - tsnet

networks:
    tsnet:
      driver: bridge

volumes:
    esdata:
    escontrib:
    pgdata:
    redis:
    neo:
```

on a side note, and this may be ingorance to the tool, but the compose file is expose all the different services externally via port mapping "hostport:containerport".  would we want to do this? or just the timesketch application?

**Comment by lostInSpaceSomewhere** [comment]
I was able to get the permission issue fixed by changing the volumes on elastic to:
``` - esdata:/usr/share/elasticsearch/data``` which is where the data will sit

I do have an issue with the output of the password tho.  Is there a way for me to set a default admin password??  or another way to retrieve that password?

im trying to get it via 
``` docker logs <containerID>```

do i need to ```docker exec -it <dockerid> /bin/bash``` and search any logs there?

**Comment by berggren** [comment]
There was a recent change to how docker compose is setup, it now exposes new environment vatriables:
      - TIMESKETCH_USER=${TIMESKETCH_USER}
      - TIMESKETCH_PASSWORD=${TIMESKETCH_PASSWORD}

This way, you can control the password being set for the initial user.

**Comment by lostInSpaceSomewhere** [comment]
does this mean i can remove the following text from the docker-entrypoint.sh:
```
# Set up web credentials
  if [ -z ${TIMESKETCH_USER+x} ]; then
    TIMESKETCH_USER="admin"
    echo "TIMESKETCH_USER set to default: ${TIMESKETCH_USER}";
  fi
  if [ -z ${TIMESKETCH_PASSWORD+x} ]; then
    TIMESKETCH_PASSWORD="$(openssl rand -base64 32)"
    echo "TIMESKETCH_PASSWORD set randomly to: ${TIMESKETCH_PASSWORD}";
  fi
```

**Comment by berggren** [comment]
This should have been fixed in the new Docker. Please reopen if the issue still persist
