### ISSUE TITLE
Stories: saved views selector not working properly with Firefox 

### ISSUE THREAD

**Issue by ptitdoc** [google/timesketch#615]
Testing master branch. 

Inspecting the page shows that the select widget is properly populated. 
The selector cannot be opened as clicking on it highlight the whole select widget instead of opening it.

**Comment by ptitdoc** [comment]
The is working as expexted with chromium.

**Comment by kiddinn** [comment]
this should work now, closing this.

Re-open if this is not the case, but the UI and tjhe stories have been completely rewritten from scratch.
