### ISSUE TITLE
Master branch, bundle.css/bundle.js missing?

### ISSUE THREAD

**Issue by cbboggs** [google/timesketch#616]
Working from a fresh install of the SIFT workstation, followed basic install procedures (SIFT has the pypi packaged version of timesketch installed, but doesn't have postgres or elasticsearch..) and then wanted to try the master branch of Timesketch.   

I did the git clone, ran the pip install . --upgrade from the cloned repo, and then ran the tsctl db upgrade (wasn't sure that was necessary since it's a brand new empty db, however it did throw some errors).

It seems to be working OK, however the webserver is trying to load static/dist/bundle.css and bundle.js which don't exist, and obviously the web interface looks terrible without them..

Is the master branch currently broken or did I bork this install/upgrade?  I found issue #322 about an upload progress feature, which mentions these two files missing, but it's from 2017 and references a fix from a docker specific branch that doesn't seem to exist any longer.

**Comment by adamjnichols** [comment]
Hi there,

To run the master branch from source, you must build components from scratch, including the front-end yarn bundle that you're currently getting 404 for.  Doc on how to accomplish use of the master source build are here:

https://github.com/google/timesketch/blob/6ac10aaa1d2441a93aa38b2ee9d8db07ab3d2e0b/docs/Developers-Guide.md

**Comment by cbboggs** [comment]
Ah, understood and thanks!
