### ISSUE TITLE
TIMESKETCH_PASSWORD in logfile?

### ISSUE THREAD

**Issue by adrastee** [google/timesketch#620]
Hi,

Following a Docker installation : "Retrieve the randomly generated password from startup logs: TIMESKETCH_PASSWORD set randomly to: xxx"
i did not see anything like this in my shell.
Where can I find the logfile ? Or simply change the password ?

Thank you.

**Comment by adrastee** [comment]
Any help please?

**Comment by berggren** [comment]
Hi, sorry for the delay. You can set your own password by creating the environment variable TIMEKSKETCH_PASSWORD before running docker compose. The docker-compose file will pick this up and use it to setup the user.

If the env variable is missing, the script will generate a random password for you and print it out to the containers stdout.

**Comment by adrastee** [comment]
Great ! Thank you.
