### ISSUE TITLE
Events not displayed - possible pagination issue

### ISSUE THREAD

**Issue by Onager** [google/timesketch#621]
Using Timesketch recently I had two odd occurrences:

1. Paging through a large number of events, page 17 loaded with no events. Moving forward to page 18, events were displayed, then going back to page 17 the events I expected to see were there.
1. No results were displayed at all for some searches, despite the event counter showing a number of results returned from the query. 

I can provide more information privately.

**Comment by berggren** [comment]
Thanks @Onager for the report!
@adamjnichols can you take a look at this? I will try to get a stable repro.

**Comment by adamjnichols** [comment]
Have we had any luck with this?

**Comment by berggren** [comment]
Pagination was rewritten in the new UI, and fixed this. Closing this issue.
