### ISSUE TITLE
how to damonize celery? 

### ISSUE THREAD

**Issue by 696Paul696** [google/timesketch#623]
Hello,

i would like to enable plaso upload and failed to get the celery running as dam$
generally, i am able to run celery working prozesses as damon with own settings$

when i run (as user)
celery -A timesketch.lib.tasks worker --loglevel=info

>  -------------- celery@LAB-TimeSketch v4.1.1 (latentcall)
> ---- **** -----
> --- * ***  * -- Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic 2018-06$
> -- * - **** ---
> - ** ---------- [config]
> - ** ---------- .> app:         timesketch:0x7fc181568510
> - ** ---------- .> transport:   redis://127.0.0.1:6379//
> - ** ---------- .> results:     redis://127.0.0.1:6379/
> - *** --- * --- .> concurrency: 4 (prefork)
> -- ******* ---- .> task events: ON
> --- ***** -----
>  -------------- [queues]
>                 .> celery           exchange=celery(direct) key=celery
> 
> 
> [tasks]
>   . timesketch.lib.tasks.run_csv
>   . timesketch.lib.tasks.run_plaso
> 
> [2018-06-07 18:10:51,230: INFO/MainProcess] Connected to redis://127.0.0.1:6379$
> [2018-06-07 18:10:51,235: INFO/MainProcess] mingle: searching for neighbors
> [2018-06-07 18:10:52,314: INFO/MainProcess] mingle: all alone
> [2018-06-07 18:10:52,329: INFO/MainProcess] celery@LAB-TimeSketch ready.

my config files look like this:

> CELERYD_NODES="celery"
> CELERY_BIN="/usr/local/bin/celery"
> 
> CELERY_APP="timesketch.lib.tasks"
> CELERYD_MULTI="multi"
> 
> CELERYD_OPTS="--time-limit=300 --concurrency=8"
> 
> 
> CELERYD_PID_FILE="/var/run/celery/%n.pid"
> CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
> CELERYD_LOG_LEVEL="INFO"
> 

with this, the celery damon is working. but not with the settings from the commandline, eg Redis server is missing, key is missing and so on.
can someone provide a working version of the damon config file?

when i start with 

> `celery -E -A timesketch.lib.tasks worker --loglevel=info`

from commandline, which config-file is used which contains the redis config and the other stuff?

thank you
Paul

**Comment by berggren** [comment]
Hi,

The config is in /etc/timesketch.conf and is set when the Celery app is initiated by Timesketch.
To run Celery in the background follow the official documentation here: http://docs.celeryproject.org/en/latest/userguide/daemonizing.html

**Comment by sansstudent** [comment]
Hello,
thank you for your answer. i was able to deamonize a celery-worker, but i was not able to damonize the timesketch celery with the timesketch config. 
/etc/systemd/system/celery.service looks like:

```
[Unit]
Description=Celery Service
After=network.target

[Service]
Type=forking
User=celery
Group=celery
EnvironmentFile=/etc/timesketch.conf 
WorkingDirectory=/opt/celery
ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'
ExecStop=/bin/sh -c '${CELERY_BIN} multi stopwait ${CELERYD_NODES} \
  --pidfile=${CELERYD_PID_FILE}'
ExecReload=/bin/sh -c '${CELERY_BIN} multi restart ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'

[Install]
WantedBy=multi-user.target
```

with no luck.

**Comment by DevStudent77495** [comment]
i tried this and failed like the person above. it does not come up with the timesketch config from /etc/timesketch.conf

so, could someone show how this could be done with timesketch config?

**Comment by n3x77** [comment]
Hi,

You need to create the directories where timesketch can create temporary
files. This folder must be accessible and writable by the celery user.

Please check the link above. In this ansible task file the necessary
options in timesketch.conf are setup.



https://github.com/n3x77/ansible_timesketch/blob/master/roles/timesketch_latest/tasks/ubuntu.yml

**Comment by berggren** [comment]
Closing this issue as it is 1.5y old by now. Please reopen if the issue still persist.
