### ISSUE TITLE
Don't create database tables automatically

### ISSUE THREAD

**Issue by berggren** [google/timesketch#637]
When the server is started the database will get initialized and any missing tables will be created. This causes problems when a WSGI server is started with multiple workers. They will race to create the tables.

The fix is to have an explicit call to create_all tables where the admin can create any missing tables or set up the system from scratch.

**Comment by kiddinn** [comment]
@berggren isn't this fixed by now?

**Comment by berggren** [comment]
@kiddinn Not quite. I need to take a look at this again, but is something we probably need to fix.

**Comment by jaegeral** [comment]
Will close this, as it was open almost 5 years :-)
