### ISSUE TITLE
[HELP] Sync data from elasticsearch to neo4j. Can't understand how it works

### ISSUE THREAD

**Issue by OhBonsai** [google/timesketch#638]
Hi ,  I found this awesome project last mouth..  I have readed [thinking-in-graphs-exploring-with-timesketch](https://medium.com/timesketch/thinking-in-graphs-exploring-with-timesketch-84b79aecd8a6)
It's a veryyyy excellent idea. But when I read source code, I can't find the implement of DATA sync between elasticsearch and neo4j.

**My question is where the data sync code is**

**Comment by adamjnichols** [comment]
Hi there.  Please see this snippet for what you're looking for:

https://github.com/google/timesketch/blob/ee21bcfd4cb50d8bd942be2f70e21f44239deb26/timesketch/api/experimental/resources.py#L43

**Comment by OhBonsai** [comment]
Thank you ~

**Comment by garanews** [comment]
Hi, 
so when loading data with "psort -o timesketch" it should populate both ES and Neo4J? Or Neo4J data needs to be inserted with some script?
I started loading a plaso in timesketch but I can see data only under Explore and not under Graphs.
In the timesketch.conf I see Ne04J enabled but db is empty.
Thanks
