### ISSUE TITLE
Kibana/elastisearch 6 incompatible queries

### ISSUE THREAD

**Issue by MariasStory** [google/timesketch#643]
Hi,
we have managed to get timesketch working with elastisearch 6.
The problems are:
1) Unmasking hidden records - there are some issues for this.
2) The **query is not compatible with Kibana/Elasticsearch 6**

The second part is the most annoying.

I don't understand why not make timesketch an extension/patch for Kibana. In particular my problem that I cannot search for specific events within starred events!

Please make the solution compatible with Elasticsearch 6 and solve the annoying problems.

**Comment by MariasStory** [comment]
OK. Let me make clear.
First of all it is a problem with timesketch and advanced queries.
Again, I am using ES 6.
Works:
1) Search for starred events.
2) Search for events with specific query.
Does not work:
1) Search for starred events with query.

For some reason I cannot combine queries for nested fields and normal queries!

Also the nested queries are not working the same way in Kiabana :-(
It might be an ES 6 problem, but I don't understand why there is no simple option to search for starred events in timesketch.
Please check if possible.

**Comment by n3x77** [comment]
As a trick you can Use __ts_star in the timesketch query to search for
starred events.

Does it work in your setup?

**Comment by MariasStory** [comment]
Hi @n3x77, please paste an example of the query.
If I am right it is a part of a nested field.
Any combination of the string isn't working for me ;-(

**Comment by n3x77** [comment]
Hi @MariasStory, 
You just need to enter "__ts_star" in the Query-Field. It is important, that You begin with two underscores. I will add you a picture from my Timesketch Instance also with the DSL-Query.

```__ts_star```

or
```
{
	"query": {
		"bool": {
			"must": [
				{
					"query_string": {
						"query": "__ts_star"
					}
				}
			]
		}
	},
	"size": 40,
	"sort": {
		"datetime": "asc"
	}
}
```

Hope that helps!
<img width="1336" alt="bildschirmfoto 2018-07-09 um 16 48 49" src="https://user-images.githubusercontent.com/20700780/42457639-42ea46d6-8398-11e8-8461-dee607b2f86a.png">
