### ISSUE TITLE
Multi-user setup problem

### ISSUE THREAD

**Issue by MariasStory** [google/timesketch#644]
We have tried to setup multi-user instance and have problems with one users not able to see stars from the other.
Can someone elaborate on the proper multi-user setup and collaboration.

**Comment by berggren** [comment]
Interesting, I'll see if I can reproduce this on my system. Is this for one specif user only of for all users?

**Comment by MariasStory** [comment]
Hi @berggren, we have tried to set a new user. There was no option to use the timeline that was setup by the first one. Only "Create new".

It seems that there are more problems with porting timeskectch to ES6.

Sorry for not properly debugging the problem. I don't have time to do it at the moment.

**Comment by berggren** [comment]
Ok, the new user don't have access to the other users timeline. Try to join the sketch with the new user and try again,

**Comment by berggren** [comment]
Closing due to no response in over a year. Please reopen if necessary
