### ISSUE TITLE
Dokumentation unclear (?)

### ISSUE THREAD

**Issue by DevStudent77495** [google/timesketch#646]
When using this documentation
https://github.com/google/timesketch/wiki/Installation
it says:
Install the latest Elasticsearch 2.x release (5.x is not yet supported):

wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.3/elasticsearch-2.4.3.deb
sudo dpkg -i elasticsearch-2.4.3.deb

when i check this document:
https://github.com/google/timesketch/blob/master/docs/Installation.md
it says
$ sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
$ sudo echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list
$ sudo apt-get update
$ sudo apt-get install elasticsearch

so, whats right ? i believe elastic5 is more accurate?

**Comment by adamjnichols** [comment]
It is, we'll get that fixed right away.  Great catch!

**Comment by DevStudent77495** [comment]
thank you :-D
