### ISSUE TITLE
add more checks to read_and_validate_csv()

### ISSUE THREAD

**Issue by aguilajesus** [google/timesketch#655]
- [x] check if datetime is a valid ISO 8601 string.
- [x] if present, timestamp should be in epoch with microseconds precision.
- [ ] Add unit tests if possible.

reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

**Comment by berggren** [comment]
@aguilajesus What is still needed here?

**Comment by kiddinn** [comment]
these tests have now been moved to the importer, which will now do these checks before you upload the files.
