### ISSUE TITLE
add ability to export all fields into a csv file

### ISSUE THREAD

**Issue by aguilajesus** [google/timesketch#657]
it would be nice to export events with its extra fields, other than the defaults (timestamp, message, timestamp_desc, datetime)

**Comment by andysnowball** [comment]
Agree, this would be an incredibly useful feature. This is one of the areas I struggle with in Timesketch - it's great for analysing Plaso timelines but getting the data back out again for reporting purposes is a little tricky!

**Comment by aguilajesus** [comment]
of the top of my head I am thinking in two options:

- append empty fields in all timelines
- return a zip file with multiple csv (one per timeline)

@berggren what do you think ?

**Comment by aguilajesus** [comment]
Merged in #678
