### ISSUE TITLE
[Explore] Unexpected results for "Starred" button

### ISSUE THREAD

**Issue by toryc** [google/timesketch#676]
Clicking the Starred button in the Explore view selects just the starred events. Clicking this button a second time does nothing. It's then confusing to get back to the previous thing that the analyst was looking at. What's expected is that clicking Starred will filter to just the starred events, but then clicking it a second time will restore whatever the analyst was looking at before (probably a filter).

**Comment by berggren** [comment]
this is for the old deprecated UI. this changed in the new UI.
