### ISSUE TITLE
[Explore] Unexpected cursor on timestamp hover

### ISSUE THREAD

**Issue by toryc** [google/timesketch#677]
In the Explore view, when the cursor is hovering over the timestamp of an event, it changes to show a hand that's grabbing the event and a plus sign. This gives me the impression that I should be able to click and move the event somewhere, but AFAICT this is not supported, which is a bit confusing to me as a user.

**Comment by kovakina** [comment]
Looks like it is WAI - clicking on the timestamp will put it into Filter start time. But I agree that this cursor is counter intuitive,  taking a look

**Comment by berggren** [comment]
I agree this was confusing :)
This has been removed in the new UI.
