### ISSUE TITLE
Make error messages more visible

### ISSUE THREAD

**Issue by aarontp** [google/timesketch#682]
Some error messages aren't very visible and users can potentially miss them.  I was trying to figure out why comments weren't being added when I finally noticed a CSRF Token expiration error.  Right now these errors are dark blue on top of a blue banner with grey text.  Can we change the color to something brighter and more noticeable?

Here's a screenshot of my recent error:
![image](https://user-images.githubusercontent.com/2667195/46636307-6a674900-cb0c-11e8-9af1-2ceecf2b0dc0.png)

**Comment by kiddinn** [comment]
Somewhat related: #1001 , to improve the backend. This will cause the error messages (at least those that have to do with API calls) contain more information.

What is left is perhaps other places that produce errors, as well as to make sure the UI makes them more prominent. ATM the error message in the current/old UI only displays part of the error message and it disappears shortly (and is not very obvious)

**Comment by kiddinn** [comment]
Adding a comment on #498 
```
At present, the only indication in a query is a very small "internal error" box at the top of the page, and this is easy to overlook.
```

**Comment by kiddinn** [comment]
The steps that are needed:

- [ ] Change the API to make error messages consistent and contain more information (#1001)
- [ ] Update the UI to make the error message more prominent (and persistent)

**Comment by kiddinn** [comment]
This is a brief view of how this looks like in the current UI with a bit more detailed error messages (still a room for improvements with error messages, but a lot of wiggle room in the UI)

![ts_mynd](https://user-images.githubusercontent.com/8701947/67242563-4f305880-f445-11e9-8075-94d592466d37.png)

**Comment by kiddinn** [comment]
ok, API and backend side done, let's move this to @berggren for the UI/UX aspect

**Comment by berggren** [comment]
This has been done in the new UI.
