### ISSUE TITLE
Docker - ERROR: manifest for elasticsearch:latest not found

### ISSUE THREAD

**Issue by weichea** [google/timesketch#688]
Error when running docker-compose 

Pulling elasticsearch (elasticsearch:)...
ERROR: manifest for elasticsearch:latest not found

**Comment by fmurer** [comment]
I circumvented this issue with changing the docker-compose.yml:

`image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2`

Unfortunately, the elasticsearch service then always seems to restart / fail with exit code 78
