### ISSUE TITLE
Cannot use psort.py with timesketch flag

### ISSUE THREAD

**Issue by Splinks** [google/timesketch#69]
Hi,

Everytime I use psort.py -o timesketch I get the following error

plaso/output/interface.py, line 45:
ValueError: Unused keyword arguments: filehandle.

After going into the file and commenting out the kwargs check it can contact my elasticsearch server but it crashes on the following error (it cant set the index aswell as the computer name/hostname):

[INFO] Adding events to timesketch..
Traceback:
for flag description in self.SECURITY_VALUES:
typerror: 'int' object is not iterable.

**Comment by joachimmetz** [comment]
This is likely a plaso issue introduced in the recent output refactor. I'll have a look why filehandle is passed.

**Comment by Splinks** [comment]
The unused keyword arguments is in fact fixed with the latest version (1.2.1_20150417) but the TypeError: 'int' object is not iterable is still not working

**Comment by joachimmetz** [comment]
Which is as to be expected, @berggren will very likely look at it as soon as time permits.

**Comment by berggren** [comment]
Yes, this is in the Plaso message formatter for olecf. I'm working on fixing it.

**Comment by Splinks** [comment]
I've submitted this https://codereview.appspot.com/231780043, the issue was trying to iterate through a dict the wrong way

**Comment by joachimmetz** [comment]
Thanks, however @berggren indicated working on a fix I'll need to sync with him first.

**Comment by joachimmetz** [comment]
Synced with berggren and moving forward with the patch, some small comment. Once those have been changed, the CL is good to go.

**Comment by joachimmetz** [comment]
Thanks, fine in this case but normally we wait for a LGTM (looks good to me) before submit.

**Comment by berggren** [comment]
Thanks @Splinks for fixing! Closing this issue.

**Comment by joachimmetz** [comment]
Something went wrong with the submit I'll fix that manually.
