### ISSUE TITLE
current docker build issues

### ISSUE THREAD

**Issue by aguilajesus** [google/timesketch#694]
- [x] elasticsearch docker image does not have latest tag (afaik) (#688)
- [x] pyyaml package conflicts between plaso and timesketch requirements.  (#664) 
- ~[ ] create a docker image for [plaso](https://hub.docker.com/r/log2timeline/plaso/)~
- [x] create a docker-compose file for development/testing.

**Comment by kovakina** [comment]
Check https://github.com/google/timesketch/pull/718 , it added compose yml for development

**Comment by aguilajesus** [comment]
Thanks kovakina@, closing this for now. Creating a docker image for plaso infeasible until we can run psort outside the frontend server/instance. more of info on #589
