### ISSUE TITLE
Allow overriding the displayed "message" field with a custom one

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#700]
Now that Timesketch has custom analyzers that can add new fields, we should have a new field that when present would be displayed instead of the default message field.

For a simple example, currently a Google search URL is displayed like:

> [Last Visited Time] https://www.google.com/search?q=best+ketchup&ie=utf-8&oe=utf-8&client=firefox-ab (best ketchup - Google Search) [count: 1] Host: www.google.com (URL not typed directly) Transition: TYPED

We could instead use an analyzer to parse this entry into something more human-readable and display that instead in the Timesketch UI, like:

> Search for "best ketchup"

The original, more verbose message would still be available for searching and viewing when the event is expanded. This search example is a trivial one, but this same idea could be much more valuable with more complex analyzers or on events with verbose messages (like #371). 

The new field could be named something like "message_friendly", "event_description", "human_readable", or whatever, and Timesketch would display the contents of that field, if it exists for the event, and if not, just display the original message field.

**Comment by berggren** [comment]
Great idea! Should be pretty straight forward to implement. 2 parts:
1. Backend analyzer code to format the message and update the event.
2. Frontend, extend the event-list component to display the field if it exist.

Also, searching for "best ketchup" should be everyones daily routine. ;)

**Comment by deralexxx** [comment]
Uh I like that a lot. One other Use case could be a extract google maps GPS coordinates and do a reverse address lookup.

**Comment by kiddinn** [comment]
I added a browser search "extraction" like the one that is described in the original FR (#733)

This is just one example of what can be done with extracting meaning from browser history, in this case I add a tag "browser_search" and an attribute which can be searched, as well as changing using the human_readable field to change what is displayed in the UI, adding an emoji for visual "spotting" of the search history and make the search query more visible
