### ISSUE TITLE
Have ACL for timelines

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#706]
Currently as far as I understand the ACL setup you can share entire sketches with individuals and or groups.

That does not affect the timelines within a sketch.

I envision a possibility to also add timelines to the sketch and that they are only visible / usable by the people assigned to the sketch.

Any opinions or roadmaps or is it something that is out of scope for timesketch?

**Comment by berggren** [comment]
this is actually how it works :) If you add a timeline to a shared sketch, then all collaborators can see that timeline and query it, but only in the context of that sketch.
