### ISSUE TITLE
Be able to add events manually

### ISSUE THREAD

**Issue by pstirparo** [google/timesketch#71]
It would be extremely useful if, between two events generated from plaso let's say, one could manually add something that happened like "10:30am the user received a phone call from someone pretending to be XYZ" or whatever other type of event/note with a timestamp.
Thanks.

**Comment by berggren** [comment]
Yes, this would be super useful. This feature can be implemented as a manual timeline added to the sketch and populated by the analysts. Then the timeline can be filtered on etc.

In the UI we could have a control in the events list that creates a form for manual events that prepopulates the timestamp from the event before.

**Comment by geekscrapy** [comment]
+1 for this feature. Drag and drop of csv events would be super useful!

**Comment by adamjnichols** [comment]
This is currently in development, and you are able to fork the ajn-api-timelines branch to play with it if you like.

You have to leave compla— err, feedback though. :)

**Comment by geekscrapy** [comment]
Just tested this - Whilst it works well it adds to another timeline that is not exposed in the Timelines display which I believe it should be.
Also, when the first event is added, it is added to the new timeline which is hidden by default on the Explore view. This could make the user think it has not added successfully.

But overall, a great feature to have!!

Nice to haves:
- A tagging feature in the custom event window

- Make the manually created timeline appear in the Timelines view

- Add ability to add extra fields to the event - not just the one message.

**Comment by geekscrapy** [comment]
FYI, I expected the Cancel button to close the window, instead, it clears the fields. Maybe a reset button would be more intuitive?

**Comment by geekscrapy** [comment]
When trying to add an event manually, the window does not appear if the 'parent' event is set to Hidden

**Comment by geekscrapy** [comment]
More so to do with user feedback and stability but, client side checks should be put in place to check if the required fields have been provided upon submission to limit internal server errors. I did not provide input to any fields and the following error was raised:

`
timesketch_1     | [2018-03-21 22:32:59,199] ERROR in app: Exception on /api/v1/sketches/1/event/create/ [POST]
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
timesketch_1     |     rv = self.dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
timesketch_1     |     return self.view_functions[rule.endpoint](**req.view_args)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
timesketch_1     |     resp = resource(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
timesketch_1     |     return self.dispatch_request(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
timesketch_1     |     resp = meth(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
timesketch_1     |     return func(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 836, in post
timesketch_1     |     status_code=HTTP_STATUS_CODE_BAD_REQUEST)
timesketch_1     | TypeError: __init__() takes exactly 3 arguments (2 given)
`

**Comment by adamjnichols** [comment]
Thanks for your feedback!  I should have mentioned that this is very early, and is nowhere near complete, so much of what you mention will not be in the PR. :)

To answer the question of why the private, sketch-specific timeline -- timelines should be immutable forensic artifacts that can be decorated, but not altered.  This is due to the collaborative nature of the tool, and the potential that a timeline could exist in multiple sketches at once.  Therefore, in addition to potentially trampling evidence, you could alter another user's sketch inadvertently.  As a result, we've opted to make additional sketch entries -- or sketch decorations -- their own timeline.

I've had a few competing priorities of late, and haven't been able to do as much as I'd like here, but should get back to wrapping up that branch and starting others.  Thanks for taking the time to contribute your ideas and feedback!

**Comment by geekscrapy** [comment]
No problem, I'll attempt to look at the source myself and see if I can help with the tool at some point - much code review would be needed though!

Got it, with the own/private timeline - could this be enabled in the filter pane once a manual event is added though? Without it, I didn't think it had added successfully.

**Comment by adamjnichols** [comment]
Yes, the manual event timeline will be auto-enabled.  After this PR, all new sketches will include it by default, with it auto-enabled as well.  The current implementation is designed to be backward-compatible with older sketches.

**Comment by adamjnichols** [comment]
PR #587

**Comment by berggren** [comment]
Done!
