### ISSUE TITLE
Bug: Pagination is not updated when filter out events

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#710]
Having a list of events in a sketch, after filtering out one or more events, the events per page ar not updated.

### Work environment

| Questions                     | Answers
|-------------------------------|--------------------
| Type of issue                 | Bug

### Expected behavior

After filtering out the event, the first event from the next page should be seen on the current page
So the number of displayed should always be the number selected per page, not less.

### Actual behavior

Pagination is not updated, resulting in worst case in a complete empty page.
So number of diplayed elements is < number of elements per page selected

### Steps to reproduce the behavior
Get a list of events, filter out one and see the result

### Logs, screenshots, configuration dump, ...

![pagination error](https://user-images.githubusercontent.com/741037/48555077-6a632180-e8e0-11e8-85dd-a83be08272b0.png)

Not sure if it is related to: https://github.com/google/timesketch/issues/621

**Comment by berggren** [comment]
This is for the old UI. Closing as obsolete.
