### ISSUE TITLE
Official TimeSketch Docker Image on DockerHub

### ISSUE THREAD

**Issue by orlikoski** [google/timesketch#727]
There are many unofficial TimeSketch images currently on DockerHub and it would be nice to have an officially supported version there.

In these days of supply chain attacks and for the reputation of TimeSketch it would be good to have positive control of how those see the product as a pre-built Docker image. Having the GitHub docker documentation point to that image would ensure users know that is it the one made from the pure repo and ensure that they know the others are not officially supported.

![image](https://user-images.githubusercontent.com/9388572/49342811-4c5a2880-f625-11e8-9898-1c2652c7eeb3.png)

**Comment by berggren** [comment]
Yeah, good point! The reason for it not to be published is because we aren't supporting Docker officially. It is mainly used for development.
