### ISSUE TITLE
Add an analyzer for bruteforce-like behavior

### ISSUE THREAD

**Issue by kovakina** [google/timesketch#737]
Analyzer idea:
1 Flags ssh attempts from nonexistent users
2. (Optional)Flags if common generic usernames were used (admin, root, user, test etc)
3. Annotates username/IP address of the login
4. (Optional) some checking if IPs are from a known bad network
5. (Optional) Some sort of analytics around it

**Comment by berggren** [comment]
We have this in the sessionizer analyzers. Closing this one for now.
