### ISSUE TITLE
Make it possible to run similarity scorer on more than one data type/attribute in the same sketch

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#738]
The issue here is that if the similarity scorer is run on data_type X and then again on data_type Y or attribute Z there is no way to differentiate between what data type/attribute the score was run on, making the UI element here not as optimal.

Ideas could include:
+ Have the similarity score attribute reflect the data_type/attribute it was run against, eg: similarity_score_X where X is the name of the data_type/attribute
+ Have the similarity_score a dict with keys as attributes/data_types

The UI would then have to be reworked to have a drop down or something similar so you can choose which key you are keying off in the UI when dimming events.

**Comment by kiddinn** [comment]
This is now completed, the logic has been moved into a separate library, `timesketch.lib.similarity` and is already being used by one more analyzer.

**Comment by kiddinn** [comment]
sorry, this was the wrong issue,

**Comment by jkppr** [comment]
Similarity score seems to be a concept or functionality that is not used in Timesketch for a long time by now. Therefore going to close this issue.
