### ISSUE TITLE
Extract usernames or account email addresses from browser history

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#745]
Create analyzer to extract usernames or account email addresses from popular websites in browser history. 

Example: 
url: https://mail.google.com/mail/u/1
title: Inbox (1) - **example@gmail.com** - Gmail

**Comment by kiddinn** [comment]
This got implemented with the feature extraction analyzer: #785 , inside the features.yaml file: https://github.com/google/timesketch/blob/master/config/features.yaml#L39

I don't want to close this one down in case there are other uses cases you needed for this particular FR than those implemented in the YAML file.

**Comment by kiddinn** [comment]
isn't this done now?

**Comment by obsidianforensics** [comment]
The extraction part is. I want to add a table view of the results, which is waiting on the aggregation feature.

**Comment by kiddinn** [comment]
@obsidianforensics can we close this now, or do you want to add some further aggregations?

**Comment by obsidianforensics** [comment]
Closing sounds good
