### ISSUE TITLE
Add Support for SubPath Hosting

### ISSUE THREAD

**Issue by orlikoski** [google/timesketch#748]
It would be helpful if the coding was done in such a way to support hosting TimeSketch in a subpath such as https://mydomain.com/timesketch. 

This is possible as a Flask app using uWSGI but the static elements with TimeSketch (such as the Logon, Logoff, anything with `static` in the link are called with absolute root pathing all the time). It requires significant workarounds using a reverse proxy to support trying to do this now. Although that solution works 99% of the time it'll never be as good or reliable compared to having it supported in the code base.

Not sure if it helps but here are the configs I'm using to get it to that 99% working.

The uWSGI .ini file: 
https://github.com/orlikoski/Skadi/blob/master/Docker/timesketch/timesketch_config.ini

The Nginx lines:
https://github.com/orlikoski/Skadi/blob/master/Docker/nginx/skadi_default.conf#L23-L41

Also, maybe I'm not doing something in the configs correctly and if that's the case just let me know to go back and keep trying.

Thanks

**Comment by ptitdoc** [comment]
Similar problem here (in addition I'm going from https on nginx to http on gunicorn):
Some additional tips:

* nginx can be configured to use headers that may be or not interpreted by gunicorn/flask/timesketch:
```
            proxy_set_header X-Forwarded-Proto "https";
            proxy_set_header X-Forwarded-Ssl "on";
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Forwarded-For $remote_addres;
```

* an additional headers seems to be standardized and is interresting to solve this problem:

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

https://tools.ietf.org/html/rfc7239

* timesketch provide the `EXTERNAL_HOST_URL` flask app configuration that can be used to force resources to resides in a specific URL (seems to be used for sketches URLs)

* flask_login provides the `FORCE_HOST_FOR_REDIRECTS` to redirect the login page to the proper host, however it does not works for URLs. Only for Host:Port.

* werzeug.redirect is used a lot in timesketch authentication code and also need to rewrite the redirection URLs

* ProxyFix seems to be a solution for these problem but I don't know how to use it in timesketch, and has also apparently a lot of limitations: https://github.com/pallets/werkzeug/issues/1023

* ProxyFix also seems to fix the bug reported here : https://github.com/google/timesketch/issues/1088 as it rewrites some HTTP headers to environ

**Comment by ptitdoc** [comment]
Using gunicorn, it is possible to activate FixProxy by editing the `wsgi.py` code:
```
from werkzeug.middleware.proxy_fix import ProxyFix

application = create_app()
application.wsgi_app = ProxyFix(application.wsgi_app)
```
Of course ProxyFix should only be enabled if there is some configuration setup (such as `USE_PROXY_ENVIRON=True`).

**Comment by ptitdoc** [comment]
ProxyFix then automatically sets the following environ:
```
environ["REMOTE_ADDR"] 
environ["wsgi.url_scheme"]
environ["SERVER_PORT"]
environ["HTTP_HOST"]
environ["SERVER_PORT"]
environ["SCRIPT_NAME"]
```

**Comment by ptitdoc** [comment]
This fix most of the login process for me, except when I click on logout, the URL is not properly constructed (uses http instead of https).

**Comment by ptitdoc** [comment]
This logout link can probably be fixed by replacing
```
frontend/src/components/AppNavbarMain.vue:        <a href="/logout" style="color:#fff;">Logout</a>
```

to 
```
frontend/src/components/AppNavbarMain.vue:        <a href="/logout/" style="color:#fff;">Logout</a>
```
and then rebuilding the frontend.

However, the problem seems more generally related to the fact that 'https://myapp/something' redirects to 'http://myapp/something/'

**Comment by ptitdoc** [comment]
This is apparently due to werkzeug.routing.RequestRedirect exception (HTTP ERROR 308)

This call calls werkzeug.redirect which apparently does not deos properly with the environ set by HTTPFix

**Comment by orlikoski** [comment]
The links on my original post are outdated now.

Here is the timsektch nginx lines now used ([source](https://github.com/orlikoski/Skadi/blob/master/Docker/nginx/conf.d/skadi_default.conf#L50-L69))
 ```
 # TimeSketch
  location /timesketch {
    root         /usr/local/lib/python2.7/dist-packages/timesketch;
    include            uwsgi_params;
    uwsgi_pass         unix:///var/timesketch/timesketch.sock;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    sub_filter 'Logout</a>' 'Logout</a><br>&nbsp;&nbsp;&nbsp;<a target="_blank" style="color:#fff;" href="/">Skadi Portal</a>';
    sub_filter 'Sign in</button>' 'Sign in</button><br><br><a target="_blank" style="color:#fff;" href="/">Skadi Portal</a>';
    sub_filter_once off;
  }
  # TimeSketch subpath fixes
  location ~ "^/(api|lib|models|static|templates|sketch|views|login|logout)/" {
    include         uwsgi_params;
    uwsgi_pass unix:///var/timesketch/timesketch.sock;
    rewrite ^/(.*)$ /timesketch/$1;
  }
```

And here is the uwsgi.conf file ([source](https://github.com/orlikoski/skadi_timesketch/blob/master/uwsgi_config.ini))
```
[uwsgi]
plugin = python3
chdir = /usr/local/lib/python3.6/dist-packages/timesketch
master = true
reaper = true
processes = 4
buffer-size = 65535
enable-threads = true

# Settings to deal with the subdirectory
manage-script-name = true
static_url = /timesketch
mount = /timesketch=timesketch.wsgi:application
socket = /var/timesketch/timesketch.sock
chmod-socket = 777
vacuum = true
die-on-term = true
```

**Comment by berggren** [comment]
@orlikoski @ptitdoc Thanks the for research here. Would love to see this more streamlined as well. Would you have time to work on a fix for this in TS?

**Comment by ptitdoc** [comment]
Hello,
I just updated timesketch to master. I come back to you to see if the fixes are still working.

**Comment by ptitdoc** [comment]
Related when using NGINX for SSO : https://github.com/google/timesketch/issues/1088

**Comment by berggren** [comment]
Hi @ptitdoc lets move this discussion to "discussions" :)
https://github.com/google/timesketch/discussions
