### ISSUE TITLE
Combine and Collapse Events

### ISSUE THREAD

**Issue by heatheradkins** [google/timesketch#77]
I'd like to have a saved view option, where I can highlight several events (e.g., all the events associated with a type 10 login) and annotate them "RDP Login", then have them collapse in the UI into a single line.

**Comment by berggren** [comment]
This can probably be implemented when label (other than star) support is added to the UI. You could label the "RDP login" events and have a knob on the label that says to cluster them together in the output. This would be a very nice feature indeed!

**Comment by berggren** [comment]
This is being tracked in #220
