### ISSUE TITLE
De-dup events

### ISSUE THREAD

**Issue by heatheradkins** [google/timesketch#78]
Sometimes plaso duplicates events. It would be handy if timesketch didn't show duplicate events.

**Comment by berggren** [comment]
Yes, this should be handled by the output module in Plaso. But a feature in Timesketch to de-dup events would be valuable for non plaso timelines in the future.

**Comment by berggren** [comment]
Relevant issue (hiding events in the UI): #54

**Comment by berggren** [comment]
This is being addressed in #54 hiding events in view. Closing this one out.
