### ISSUE TITLE
Consider upgrading to beautifulsoup4

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#788]
While working on packaging BeautifulSoup 3.2.1 for GIFT PPA, a Python 3 build fails on the tests (due to usage of print without parenthesis) consider upgrading to beautifulsoup4 (also seeing that BeautifulSoup 3 is marked as obsolete) 

https://pypi.org/project/BeautifulSoup/

**Comment by kiddinn** [comment]
There is the first step in removing it done in #796 , making it possible to run both in the client.

Once this is checked in, I'll start making changes to the rest of the codebase to just remove v3 in favor of v4, there are few API changes that need to be made in order for this to work.

**Comment by kiddinn** [comment]
This is done now...
