### ISSUE TITLE
Remove Search Templates

### ISSUE THREAD

**Issue by thesilas** [google/timesketch#805]
Is there a way to remove search templates added using the webgui? I have some duplicates in there that I want to cleanup. I tried to export the search templates using 
```
tsctl search_template -e export.yaml
```
Then remove the duplicates in the export and import them again
```
tsctl search_template -i no-more-duplicates.yaml
```
However, the duplicates are still in the database. It seems the import function adds additional templates.

**Comment by berggren** [comment]
Hi, yeah good catch. It is currently not possible to delete search_templates in the UI, and the export/import function doesn't do that either. This is relative easy to add though as all necessary bits are already ready in the backend. I'll use this bug to track that feature.

**Comment by berggren** [comment]
Search templates are being rewritten in the new UI and will incorporate the requests here. Closing this out.
