### ISSUE TITLE
Pivot from interactive charts

### ISSUE THREAD

**Issue by obsidianforensics** [google/timesketch#816]
The chart views are helpful for getting an overview of spikes or dips in record volume. A nice feature would be to easily "pivot" from the graph to table views of the data. 

For example:

1.  Search to limit the records to particular data type
2.  Click 'Charts' -> Histogram to see if any days stand out for a closer look.
3.  I see a spike (or whatever) on a particular day and I want a table view of those records to examine closer.

(3) is possible right now by my modifying the search query. It'd be nice to just be able to click on the interesting part of the graph and get a filtered down table view of the data. 

This looks similar to #216, but I'm not sure what happened there.

**Comment by kiddinn** [comment]
The API client has something "similar" to this, but only when it comes to aggregations.

That is if you do an aggregation search, or run an aggregator, the aggregation object has two options, .chart and .table which will jump between the two.

But having this in the UI will be nice as well.

**Comment by berggren** [comment]
This can be implemented with interactive charts. Will change the title to reflect this and track it here as a FR.

**Comment by berggren** [comment]
This has been implemented in #1836 - interactive histogram.
