### ISSUE TITLE
Split pylint tests

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#830]
different pylint versions are not compatible I opt to move the pylint test out of the default tests like in plaso https://github.com/log2timeline/plaso/blob/master/.travis.yml

@berggren @kiddinn Thoughts?

**Comment by joachimmetz** [comment]
https://github.com/google/timesketch/pull/831

**Comment by berggren** [comment]
This is being addressed in other issues in the overall work on making testing better. Closing this one in favour of that.
