### ISSUE TITLE
Export data in CSV format

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#84]
Once one has a certain view events they feel is report worthy, it'd be convenient to have the ability to export those events out of timesketch in some fashion/format (e.g. - CSV). The main purpose for this in my eyes would be to ease the data ingestion process into various reports vs. copying/pasting certain details from the events properties ... especially if there is a large amount of events starred/commented/in a certain view.

**Comment by berggren** [comment]
Great idea! This should be pretty simple to implement and I'll take a look at it after the upcoming release.
