### ISSUE TITLE
Domain analyzer should not hide the message string

### ISSUE THREAD

**Issue by berggren** [google/timesketch#847]
The domain analyzer adds a human readable that is not that useful in most cases. Consider removing the human readable and add back the original message string.

**Comment by kiddinn** [comment]
I'll do some modifications to the analyzer, I agree with this, I think we can have some sort of threshold... bottom X% or bottom Y# of domains, or a threshold of Z visits lands a new shiny human readable, otherwise not.

**Comment by kiddinn** [comment]
this has already been fixed
