### ISSUE TITLE
plaso files not processed after upload

### ISSUE THREAD

**Issue by steoleary** [google/timesketch#849]
After uploading a plaso file to create a timeline, nothing happens in the UI, the spinner next to the upload name keeps going indefinitely.  All the dependencies are installed and up and running, in the celery log for the worker I see the following message:

```
return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 361, in run_plaso
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I've configured an uploads directory in timesketch.conf that both the user running timesketch and the user running celery can access, I can see the files in the folder after the upload and have verified the celery user can read them too.  I'm not sure what the "No such file or directory" error is referring to.

**Comment by orlikoski** [comment]
I have a suggestion on this. I recently discovered that the newest version of Plaso uses a newer configuration file where it no longer accepts values that start with u'<value name'.

This could by the u'/tmp' value or many others. check that

**Comment by steoleary** [comment]
Sorted this out, turned out to be super simple, the docs state that to enable plaso uploads you should install the following:
`sudo apt-get install python-plaso`

When in fact you need to run:
`sudo apt-get install python-plaso plaso-tools`
