### ISSUE TITLE
list existing users using tsctl

### ISSUE THREAD

**Issue by 82d28a** [google/timesketch#850]
Just reviewing the docs and testing out timesketch, there seems to be no obvious way to list existing users.  using the tsctl cli. Assuming this is a feature request, may I have a quick workaround?

**Comment by berggren** [comment]
Sorry for the delay. This is not yet avaiable in the the tsctl tool, I'll add an issue to track it. In the meantime, you can:

```
tsctl shell
from timesketch.models.user import User
for u in User.query.all():
  print(u.username)
```

**Comment by kiddinn** [comment]
this is already implemented, see: https://github.com/google/timesketch/commit/76b901ddf2c8bdcf1a431bf3f12ca7805b804755
