### ISSUE TITLE
auto-generated requirements.txt file causes pip tests to fail

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#854]
auto-generated requirements.txt file (https://github.com/google/timesketch/pull/790) causes pip tests to fail https://travis-ci.org/google/timesketch/builds/509600198

possibly a new version of a dependency causing a conflict

**Comment by joachimmetz** [comment]
@berggren the issue I mentioned to you yesterday, not urgent IMHO but might be worth a look what is causing this

**Comment by berggren** [comment]
we are no longer generating the requirements.txt file. Closing this as the overall effort on making packaging better is tracked in other issues.
