### ISSUE TITLE
Update pylintrc

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#855]
Update .pylintrc to closer match that of the log2timeline projects

* [x] update .pylintrc file https://github.com/google/timesketch/pull/856
  * fix issue pylint python 3.5.2 versus pip python 3.5.6
* [ ] enable load-plugins=pylint.extensions.docparams
* [ ] do not ignore invalid-name
* [ ] do not ignore no-member

**Comment by berggren** [comment]
Closing this out as the pylintrc has been updated.
