### ISSUE TITLE
Delete a view

### ISSUE THREAD

**Issue by hiddenillusion** [google/timesketch#86]
Once a view is created, I don't see a way that the view can be deleted without deleting the entire sketch.

**Comment by berggren** [comment]
Yes, this is definitely on the agenda. If not before the upcoming release this will be added shortly after that. Also ability to delete timelines and other entities in the system will be added.

**Comment by pettai** [comment]
I was also about to ask about the possibility to delete timelines.
I would be happy if tsctl could get a (admin) command for that.

**Comment by berggren** [comment]
@pettai Do you mean deleteing as in purging the timeline along with the Elastic index? Or do you mean deleting a timeline from a sketch? A timeline can be part of multiple sketches, so purging it might get difficult without breaking potential other sketches.

If the latter, this is much easier to do, and I'm working on that. You will be able to delete the timeline from the current sketch you are working on.

**Comment by pettai** [comment]
@berggren Delete from sketch is a good start. 
But I actually wanted to purge timelines too (but that could be an "admin" operation, only available via tsctl for instance)

(But showing import date and possible other metadata like number of events for the timeline would help to be able to avoid the less useful imported timelines. (For instance, I imported several copies of the same host from different plaso runs (using different versions of plaso) to check if / how much the timeline events would differentiate...)

**Comment by berggren** [comment]
Good idea, makes sense. I'll add the purge option to be implemented.
Regards to getting stats from the timelines, that is a WIP.
