### ISSUE TITLE
Improve UX for finding analyzer results 

### ISSUE THREAD

**Issue by Onager** [google/timesketch#861]
It's difficult to find which tags/analysis results are present in a timeline.

**Comment by berggren** [comment]
Yep, it is almost impossible to figure out what tags are present in a sketch, I agree :) We are working on it using the new aggregation framework. Tracking here: #857

**Comment by jaegeral** [comment]
I wonder if the new Search Hover menu is addressing this issue here, since it lists the tags and the number of events for the tag.
![Screenshot 2021-07-01 at 10 32 06](https://user-images.githubusercontent.com/741037/124092878-9b73ce80-da57-11eb-9234-7b5dc502f06e.png)

WDYT @Onager ?

**Comment by jaegeral** [comment]
As this feature request is a bit vague and we did improve the empty state search bar, I am gonna close this one.

@Onager  if you have strong objections on it, feel free to re-open.
