### ISSUE TITLE
"Next" button behavior is confusing when a search limit is hit

### ISSUE THREAD

**Issue by Onager** [google/timesketch#864]
When a search returns lots of events, a limit is hit on the number of results return. Hitting "Next" to page through gets to the end of the list of these events, but doesn't re-run the query, so it's not possible to page through all results.

**Comment by berggren** [comment]
I don't follow here.. when you hit "next" in the pagination the query is cached on the server with a cursor to where in the result set to return. Is the paginator not working?

**Comment by aarontp** [comment]
I'm seeing something similar, and possibly the same here.  If I'm on the last page of results in the current cached set (e.g. at 10k results from the total of 200k results in the Sketch), the `Next` button is greyed out, which I believe is WAI.  But if I click on the timestamp for one of the last events to set my time range filter to start at that time, and click `Filter` or re-click search (the magnifying glass), it still leaves me at the last page of results and doesn't re-run my query, so I'm stuck at the last page of the initial results.

I'm not sure what the best way to implement this would be, but it would be nice if there was a way to re-query or get a new result set if I click `Next` when I'm on the last page of the current result set.  I guess it could either implicitly re-query to get a new result set, or possibly set the filter start time to the event time of the last event on the page (but I can see how each of those might have their own problems).

**Comment by berggren** [comment]
This has been fixed in recent pagination fixes. Please re-open if issues are still present.
