### ISSUE TITLE
Importing Evtx logs 

### ISSUE THREAD

**Issue by 82d28a** [google/timesketch#865]
Using plaso: psort.py --output_format timesketch , I am able to import plaso files with kitchen sink parsers which includes winevtx type of events. However I am unable to ingest plaso files that only contain winevtx events. I tested one off non winevtx specific plaso files and had no issues importing and viewing them in timesketch. 

There are no errors in the psort output, but there appears to be errors in the standard out of the elastic search. 

BTW I did confirm the winevtx plaso file held events by dumping them to csv.

I get this error per event attempted to be imported:

[2019-04-04T15:24:08,095][DEBUG][o.e.a.b.TransportShardBulkAction] [KhAeCt3] [6ba0c523bd2749588851f0f1a2516b7e][0] failed to execute bulk item (index) index {[6ba0c523bd2749588851f0f1a2516b7e][plaso_event][8q3z6GkBGgNwCVQGOP2o], source[n/a, actual length: [2kb], max length: 2kb]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
.....

Caused by: java.lang.IllegalStateException: No matching token for number_type [BIG_INTEGER]

Thanks

**Comment by arisjr** [comment]
I don’t know, but perhaps it’s a similar issue: https://github.com/google/timesketch/issues/602

**Comment by berggren** [comment]
Hi @82d28a what version of Plaso are you using? And what version of Elasticsearch and Timesketch?

**Comment by joachimmetz** [comment]
Closing in favor or https://github.com/log2timeline/plaso/issues/2450
