### ISSUE TITLE
check compatibility with elasticsearch-py 7

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#871]
elasticsearch-py 7 is released check compatibility

**Comment by berggren** [comment]
Thanks for filing. I'm planning to take a look asap.

**Comment by ptitdoc** [comment]
This line is already failing because Elasticsearch 7 remove the document_type concept. So loading a plaso file will already crash before indexing because the mapping definition is invalid:
https://github.com/log2timeline/plaso/blob/4b2d657ab72d8e44414b1b09dd357200c0f60ab6/plaso/output/timesketch_out.py#L95

Only the following should be kept in the mapping:
```
           'properties': {
                'timesketch_label': {
                    'type': 'nested'
                }
}
```

**Comment by ptitdoc** [comment]
I manage to load the index by removing all _document_type references from there:
https://github.com/log2timeline/plaso/blob/4b2d657ab72d8e44414b1b09dd357200c0f60ab6/plaso/output/shared_elastic.py#L113
https://github.com/log2timeline/plaso/blob/master/plaso/output/shared_elastic.py#L212

But there are then a lot of errors in timesketch queries toward elasticsearch 7:
RequestError: RequestError(400, u'illegal_argument_exception', u'request [/e48e2c40175f4135b0eeaca51e0f2e62/_search] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?')

**Comment by ptitdoc** [comment]
Probably because of 
> Remove deprecated url parameters _source_include and _source_exclude

https://www.elastic.co/guide/en/elasticsearch/reference/7.0/release-notes-7.0.0.html

**Comment by ptitdoc** [comment]
Actually, replacing `_source_include` by `_source_includes` there seems to be sufficient.
https://github.com/google/timesketch/blob/458e7bdeed26d44623d4664bacce9441d0ffe8ba/timesketch/lib/datastores/elastic.py#L316

**Comment by ptitdoc** [comment]
From this point, it seems to works properly. I however did not tested all features yet. Sorry for not proposing a proper pull request, but I'm not sure how to deal with the usage of potentially different elasticsearch versions.

**Comment by joachimmetz** [comment]
@ptitdoc thanks for looking

Related issue: https://github.com/google/timesketch/issues/840

**Comment by berggren** [comment]
this has been fixed. Support for both Es6 and ES7 exist.
