### ISSUE TITLE
Unable get root (neo4j error)

### ISSUE THREAD

**Issue by ghost** [google/timesketch#873]
I get the following error when trying to load the Graph View.

`timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
timesketch_1     |     self.handle_request(listener, req, client, addr)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 191, in handle_request
timesketch_1     |     six.reraise(*sys.exc_info())
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
timesketch_1     |     respiter = self.wsgi(environ, resp.start_response)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
timesketch_1     |     return self.wsgi_app(environ, start_response)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
timesketch_1     |     response = self.handle_exception(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
timesketch_1     |     return original_handler(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
timesketch_1     |     reraise(exc_type, exc_value, tb)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
timesketch_1     |     return self.handle_error(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
timesketch_1     |     response = self.full_dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
timesketch_1     |     rv = self.handle_user_exception(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
timesketch_1     |     return original_handler(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
timesketch_1     |     reraise(exc_type, exc_value, tb)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
timesketch_1     |     return self.handle_error(e)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
timesketch_1     |     rv = self.dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
timesketch_1     |     return self.view_functions[rule.endpoint](**req.view_args)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
timesketch_1     |     resp = resource(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 88, in view
timesketch_1     |     return self.dispatch_request(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
timesketch_1     |     resp = meth(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
timesketch_1     |     return func(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 1652, in post
timesketch_1     |     result = self.graph_datastore.query(
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 240, in graph_datastore
timesketch_1     |     password=current_app.config['NEO4J_PASSWORD'])
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/neo4j.py", line 89, in __init__
timesketch_1     |     password=password)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/client.py", line 83, in __init__
timesketch_1     |     raise NotFoundError(response.status_code, "Unable get root")
timesketch_1     | NotFoundError: Code [404]: Not Found. Nothing matches the given URI.
timesketch_1     | Unable get root
`

This is also reproducible in a python shell.

`from neo4jrestclient.client import GraphDatabase
self.client = GraphDatabase('http://neo4j:7474/db/data/')
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/client.py", line 83, in __init__
    raise NotFoundError(response.status_code, "Unable get root")
neo4jrestclient.exceptions.NotFoundError: Code [404]: Not Found. Nothing matches the given URI.
Unable get root
`

I noticed here (https://stackoverflow.com/questions/24994335/neo4jrestclient-error-unable-to-get-root) that since Neo4j > 2.0 there are no default nodes generated. 

Is there a quick fix for it? Also when connecting to the Neo4J Browser, is see an empty database only.

Thanks in advance,
Michael

**Comment by garanews** [comment]
same issue with python3:``

**Comment by berggren** [comment]
This is due to the experimental status of the graph view. This is being addressed in the new UI that is being developed. We will start creating the graphs using the new analyzer framework.

Let me know if you want to be early testers :)

**Comment by garanews** [comment]
of course! :)

**Comment by berggren** [comment]
Closing this issue as it will be tracked in the new graph implementation that is planned for in the future.
