### ISSUE TITLE
Incorrect routes in frontend

### ISSUE THREAD

**Issue by michaelschratt** [google/timesketch#874]
It seems, that there are old routes used in the frontend. 
```
Request URL: */api/v1/sketches/1/aggregation/
Request Method: POST
Status Code: 404 NOT FOUND
```

**Comment by kiddinn** [comment]
what version of timesketch are you using? and where did you see this occur?

**Comment by kiddinn** [comment]
I assume this might be the culprit that needs to be changed to legacy aggregation: https://github.com/google/timesketch/blob/master/timesketch/ui/api/api.service.ts#L326

**Comment by michaelschratt** [comment]
> what version of timesketch are you using? and where did you see this occur?

It's the most recent version. It occurs in the Explore Tab when clicking on Charts.

**Comment by garanews** [comment]
I have the same behavior: no heatmap/histogram: 404.
It seems that called page is ok (comparing online demo vs local install):
![image](https://user-images.githubusercontent.com/16938405/58017273-1429a200-7b00-11e9-84f0-64de366d9c46.png)
![image](https://user-images.githubusercontent.com/16938405/58017378-5fdc4b80-7b00-11e9-80fe-a9a9615990b2.png)


Just request payload and filter are a bit different:


![image](https://user-images.githubusercontent.com/16938405/58017293-1f7ccd80-7b00-11e9-957e-06b33e825c8c.png)
![image](https://user-images.githubusercontent.com/16938405/58017391-65d22c80-7b00-11e9-86c9-8dc407af0633.png)

**Comment by berggren** [comment]
We need to change the API endpoint to /aggregation/legacy/ and rebuild the bundle. Fix in incoming.

**Comment by berggren** [comment]
This is now fixed.

**Comment by garanews** [comment]
confirmed working:

![immagine](https://user-images.githubusercontent.com/16938405/58472861-81b08080-8147-11e9-98fb-1040e6461674.png)
