### ISSUE TITLE
Importing of JSON timelines fails on large files

### ISSUE THREAD

**Issue by liamjm** [google/timesketch#88]
Likely caused by memory exceeded. On my current machine this fails on files >2GB; succeeds on 1GB files.

**Comment by berggren** [comment]
Yes, this is most likely due to memory exceeded. Because this is JSON file we can't read it line by line, but need to read the whole file in at once.

To ingest large files we need something else, and I plan on adding a CSV reader. See this issue #91 that tracks this effort.
