### ISSUE TITLE
Install Timesketch from scratch: additional info

### ISSUE THREAD

**Issue by garanews** [google/timesketch#880]
Installed following "Install Timesketch from scratch" and I installed separately neo4j, postgresql, elasticsearch on different machines,  some considerations about the guide:

1) add to install redis
2) add to install plaso

Then I'm stuck with "uploading plaso from http".
I see files correctly loaded under temp folder and from gui I see the Timeline added but loading state never ends.
How can I debug it? I set debug= True in config file, but no errors.

Thanks

**Comment by garanews** [comment]
I'm on Ubuntu 18.04.2 LTS
The psort.py didn't find timestetch, had to install it from git source. (doing psort -o list I have seen timesketch disabled) 
Had also to install correct elasticsearch pip package uninstalling the one present in requirements.txt (5.4.0) and installing 6.3.0 (I have ES 6.7.2)
Now from command line I am able to import the plaso file and can see timeline in gui.
Loading plaso from gui I have same issue ( loop never ends).

**Comment by garanews** [comment]
Found the guide https://github.com/google/timesketch/blob/master/docs/EnablePlasoUpload.md  :)
So had to install, configure and run celery and now the upload plaso from http works.

Do you know if there is a way to use multiprocessing with psort? Currently I see psort that uses only 1 CPU and is taking a lot of time to process the plaso file.

**Comment by deralexxx** [comment]
Agree, without running celery imports will appear to be importing forever, in reality, nothing happens.

**Comment by n3x77** [comment]
> Found the guide https://github.com/google/timesketch/blob/master/docs/EnablePlasoUpload.md :)
> So had to install, configure and run celery and now the upload plaso from http works.
> 
> Do you know if there is a way to use multiprocessing with psort? Currently I see psort that uses only 1 CPU and is taking a lot of time to process the plaso file.

As far as I know, there is currently no way than using multiprocessing. You can use some fine tuning with the flush_internal parameter. This parameter sets the number of events that will be imported into elasticsearch in on bulk request.

**Comment by garanews** [comment]
About multiprocesing, I opened an issue on log2timeline https://github.com/log2timeline/plaso/issues/2529
They found useful input :)

**Comment by berggren** [comment]
The install procedure has been moved to docker, and documentation has been updated. Closing this out.
https://github.com/google/timesketch/blob/master/docs/getting-started/install.md
