### ISSUE TITLE
Add dpkg packaging files

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#883]
* [x] add dpkg packing files https://github.com/google/timesketch/pull/882
  * ~~what about frontend and ui files?~~
* [x] timesketch-server add:
  * system configuration file
  * service start/stop scripts
  * script to set up initial configuration

**Comment by joachimmetz** [comment]
Note to self:

* move tools into server package
* add "new ui" (@berggren which directory?)

**Comment by berggren** [comment]
New UI is under:
timesketch/timesketch/frontend/dist/

**Comment by joachimmetz** [comment]
@berggren does the timesketch server requires its own user and group?

Notes on systemd configuration files https://www.shellhacks.com/systemd-service-file-example/

**Comment by joachimmetz** [comment]
@berggren things we discussed

* could you point me to the existing systemd configuration files
* could you move the new UI out of the Python module so this can be added to the data package (and it does not need to be replicated across multiple packages)

**Comment by joachimmetz** [comment]
Note to self https://github.com/google/timesketch/pull/895

**Comment by berggren** [comment]
Does the timesketch server requires its own user and group?
A: No, it runs as the webserver user, usually www-data

Could you point me to the existing systemd configuration files
Added: https://github.com/google/timesketch/pull/895/

I will move the new UI out from the python package asap.

**Comment by joachimmetz** [comment]
@berggren most of the basics have been added to https://github.com/google/timesketch/pull/882.

We'll need to have a closer look to make sure everything is configured and working and regarding the new UI.

**Comment by joachimmetz** [comment]
Changed merged, closing issue. Note that this might require some additional tweaks.
