### ISSUE TITLE
Migrate to official Neo4j Python driver

### ISSUE THREAD

**Issue by garanews** [google/timesketch#884]
In order  to support neo4j >= 3.x what do you think to migrate the driver?

**Comment by berggren** [comment]
Yes, neo4jrestclient is not maintained anymore and we should move to the official python driver instead. I suggest we use: https://neo4j.com/developer/python/#neo4j-python-driver

I'll keep this issue open to track that.

**Comment by berggren** [comment]
Closing out as the old graph code has been deprecated and will be rewritten.
