### ISSUE TITLE
Deleting timelines does not delete data in ES

### ISSUE THREAD

**Issue by garanews** [google/timesketch#885]
Deleting timeline from ui doesn't delete index in ES, is an expected behavior?

**Comment by garanews** [comment]
The tsctl drop_db drop ES indexes but leaves the data in Postgresql so the list of available timelines is still filled with data no more present.

**Comment by berggren** [comment]
This is expected. A timeline can be part of many sketches, so purging from ES is not always possible. If you want to purge the timeline from both ES and SQL you can run ```tsctl purge```

**Comment by garanews** [comment]
what do you think to have these features available from UI?

**Comment by deralexxx** [comment]
I agree with @garanews here, having the ability to delete it in WebGui would be really handy.

**Comment by kiddinn** [comment]
This will be addressed in #1602 

The feature is that we can add a label to the sketch, which would indicate that it should get purged, then X days later the data will be automatically purged, this will give the user the chance to "cancel the purge" if they chance their mind, but still provide the optin of purging data from the GUI/API client.
