### ISSUE TITLE
Importing of JSON timelines creates duplicate timelines with same name.

### ISSUE THREAD

**Issue by liamjm** [google/timesketch#89]
Steps to reproduce
1) command line:
echo '[
  {
    "datetime": "2012-04-12T17:24:38-08:00",
    "timestamp_desc": "Test",
    "timestamp": 1334251478000000,
    "message": "Test message"
  }
]' > test_dupe.json           
tsctl json2ts --name test_dupe --file test_dupe.json
tsctl json2ts --name test_dupe --file test_dupe.json

2) Create new sketch
3) Notice duplicate "test_dupe" timelines on list to select from.
4) Add both
5) Explore, using "*" as filter.
6) notice duplicate results.

**Comment by berggren** [comment]
Yep, this is a bug. It a actually fine to have multiple timelines with the same name at the moment though, but this change makes it that if the same name, index and user is used it will not create another timeline but reuse the current one and add the events to the same elastic index.

E.g:
```
$ tsctl json2ts --name test --file test.json
Timeline name: test
Elasticsearch index: 9ff10eb5f1bc4d3dae37591a21e15653
2 events inserted
```
The second round, when you want to add to the same one you need to provide the elastic index name as well:
```
$ tsctl json2ts --name testus2 --index_name 9ff10eb5f1bc4d3dae37591a21e15653 --file test.json
Timeline name: test
Elasticsearch index: 9ff10eb5f1bc4d3dae37591a21e15653
2 events inserted
```
