### ISSUE TITLE
Create a logo for Timesketch

### ISSUE THREAD

**Issue by toryc** [google/timesketch#916]
Timesketch has been around for a while now, but the only thing that could be considered a logo at this point is the name "timesketch". It would help with recognition, consistency, and some usability if there were a pictorial representation of the tool.

This can be used for favicons, navigation to the homepage, laptop stickers, or various icons.

**Comment by richardbmx** [comment]
@toryc  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project.

[My Portfolio](https://www.behance.net/richardcaseres)
