### ISSUE TITLE
WebUi upload feedback improvement

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#945]
Looking into several issues, there are various cases where upload failed for different reasons.
Uploading files via Webui can fail because of different root causes and I believe we should improve user feedback directly to the WebUI without the need to log into the console logs.

Some examples where UI feedback would be good:

- Celery workers not running
- header fields in csv missing (+display which one is missing)
- import error in a csv line (+tell which line it was)

**Comment by kiddinn** [comment]
100% agree, I'll start working on this.

**Comment by jaegeral** [comment]
I think we can now say we can close this
