### ISSUE TITLE
Searching within starred events does not work

### ISSUE THREAD

**Issue by stuhli** [google/timesketch#946]
Hello,

using our current setup, search queries in combination with starred events `__ts_star` (as workaround described in #180) do not work any more. In prior releases this was possible (unintentionally or not). The "normal" view of starred events works as expected.

We use the latest Timesketch release [20190207](https://github.com/google/timesketch/releases/tag/20190207) in combination with Plaso [plaso-20190331](https://github.com/log2timeline/plaso/releases/tag/20190331).

Is there a way to get this fixed or another solution?
Thank you!

**Comment by kiddinn** [comment]
the API client works at least, you can do a 

```
from timesketch_api_client import client
ts_client = client.TimesketchApi(SERVER_ADDRESS, USER, PASS)
sketch = ts_client.get_sketch(0)
sketch.search_by_label('__ts_star', as_pandas=True)
```

This will at least give you all the starred events using the API client.

But I'll assign this to Johan to take a look at the UI. This may be fixed already in the new UI.

**Comment by kiddinn** [comment]
this should work now in the ui, if not, you can re-open this issue.

**Comment by stuhli** [comment]
Thank you! We will try as soon as possible.
