### ISSUE TITLE
Show overview of query results (eg aggregate by week)

### ISSUE THREAD

**Issue by liamjm** [google/timesketch#95]
It would be great to have an overview of the results, aggregated by time window, so that the user can get a 'big picture view' of the results. A graph that can zoom (ie adjust the filter start & end ranges) of the results would be ideal. eg
https://developers.google.com/chart/interactive/docs/gallery/annotationchart

**Comment by pettai** [comment]
Aggregate by type ("extractor" like filesystem event, registry event, event log, etc.) could also be useful

**Comment by berggren** [comment]
@pettai Yes, good idea! This is the plan, and has always been part of the long term goal of the aggregation and visualization features. My thinking here is that we want to surface this data and make that part of the filter interface.
