### ISSUE TITLE
Run analyzer on already imported timelines

### ISSUE THREAD

**Issue by taishi8117** [google/timesketch#997]
We should have a feature in the UI to support running analyzers on imported timelines.

**Comment by kiddinn** [comment]
This depends on #998, that is having an API to manually run them.

Pushing that in, and then we can add the UI element.

**Comment by kiddinn** [comment]
assigning the issue to @berggren due to the UI element.

The backend is ready, API is in and client supports this right now.

**Comment by berggren** [comment]
UI is ready and in review: #1019
